### ISSUE TITLE
🐛 Connection dies while running `rome check` 

### ISSUE THREAD

**Issue by iaravindreddyp** [rome/tools#1006]
## Environment

```
$ rome check

```

## Steps To Reproduce

1.rome init in a local project
2.rome check
one running lint it is trying to analyze a file in node_modules and it ends saying connection died
![Screenshot 2020-08-09 at 11 22 05 AM](https://user-images.githubusercontent.com/22080780/89725951-0036cc80-da33-11ea-8f48-2f7d04d8b584.png)
 
and also the ignore pattern configuration for lint doesn't seem to work

**Comment by aravind1078** [comment]
it happens even when i fork rome and run `./rome ci`.
![Screenshot 2020-08-09 at 12 59 35 PM](https://user-images.githubusercontent.com/22080780/89727227-3a5a9b00-da40-11ea-83f7-1435cb05d5d0.png)

**Comment by kyle1320** [comment]
If this is happening for you even in the Rome repo it may be a system-dependent issue.

@aravind1078 Please run `rome rage --summary` and paste the output here.

**Comment by aravind1078** [comment]
So yeah when i closed my vscode and tried it worked and it occurred again after running few commands 
@kyle1320  it is occurring intermittently so am not sure i will try to get rage output if it occurs again

**Comment by sebmck** [comment]
Is there anything above where you've taken the screenshots? If you're running the VSCode extension then the CLI could be connecting to the server that's attached there.

**Comment by aravind1078** [comment]
am not sure @sebmck and I did not install the Rome vscode extension. this one seems to be occurring intermittently in my local and mostly it fails in parsing some file in `node_modules` and it just waits for few secs before the connection dies. I will try to get a full screenshot if possible.

**Comment by aravind1078** [comment]
@sebmck here is complete error with latest code 
<img width="953" alt="rome_error" src="https://user-images.githubusercontent.com/22080780/90106447-0e535880-dd65-11ea-9105-5ee90543f9a8.PNG">
<img width="946" alt="romeerr1" src="https://user-images.githubusercontent.com/22080780/90106458-10b5b280-dd65-11ea-9264-5c8819020b5f.PNG">
<img width="889" alt="romeerr2" src="https://user-images.githubusercontent.com/22080780/90106464-11e6df80-dd65-11ea-93cb-5c4d432cb1e8.PNG">

**Comment by matiaschileno** [comment]
I'm having exactly the same issue, `Connection died` after some `Process unexpectedly exit` on `rome check`. This is the output of `rome rage --summary`:
`
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  12.16.3

Platform
  linux x64 5.7.9-1-MANJARO

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 183
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/home/matias/projects/purapalta/purapalta-backend"
    realCwd: "/home/matias/projects/purapalta/purapalta-backend"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 56_037_376
      pid: 75_040
      uptime: 1.10978598
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 56_037_376
        ownedBytes: 0
        ownedFileCount: 0
        pid: 75_040
        uptime: 1.109617216
      }
    ]
  }
`

**Comment by sebmck** [comment]
I don't think this is an issue anymore after #1054 since we are no longer using separate processes for workers. I'll leave this open so we can confirm for the next release.

**Comment by ematipico** [comment]
@iaravindreddyp are you able to test and see if the issue is still present?

**Comment by ematipico** [comment]
Closing due to no responses.
