### ISSUE TITLE
📎 Create script to run in CI to verify the correctness of the commit messages

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1009]
We already have a parser and some log inside `changelog.ts`.

We want to have a script to run in the CI that checks if the commit message follows the `conventional-commit` guidelines/rules.

**Comment by bitpshr** [comment]
This is a great idea. Note that while I think it's smart to provide local tooling to verify commit messages, I also think that we should rely on a well-tested GitHub Action if possible, similar to how we use them for other CI tasks already. I don't think we necessarily have to recreate a conventional-commit verification mechanism.

**Comment by ematipico** [comment]
Is there a GitHub action for that already? If so, we could add it!
