### ISSUE TITLE
💭 Formatter feature request: comment before `else` keyword

### ISSUE THREAD

**Issue by AlchemistCamp** [rome/tools#1024]
One of the most contentious decisions in Prettier and the reason I personally no longer use it for any projects, was its forcing the removal of breaks before else blocks: https://github.com/prettier/prettier/issues/840

To illustrate two issues with this, consider the following code:

```
  // comment for if block
  if (cond1) {
    doFoo(tree, data);
    if (cond2) {
      collect(tree.left, data, depth + 1);
      collect(tree.right, data, depth + 1);
    }
  }
  // comment for else block
  else {
    doBar(data);
  }
```

As it is now, Rome will throw errors suggesting the following format

```
  // comment for if block
  if (cond1) {
    doFoo(tree, data);
    if (cond2) {
      collect(tree.left, data, depth + 1);
      collect(tree.right, data, depth + 1);
    }
  } else {
    // comment for else block
    doBar(data);
  }
```

The problems with eliminating the break before the else are that it now lines up the else block with the wrong conditional and that it eliminates the clearest place for the else block comments.

I don't see much upside in a linter being rigid to this degree, and based on the the discussion on the Prettier issue linked above, many others would agree.

---
Edit: Since the title was changed, I'll reiterate:

**I strongly prefer not removing the break before else, even in cases where there are no comments. The `else` should line up with the `if` it corresponds to, not an inner one.**

**Comment by bitpshr** [comment]
I'm in favor of breaking before `else` statements, I feel that the advantages are objective in terms of comment legibility.

**Comment by milesj** [comment]
What about?

```
  // comment for if block
  if (cond1) {
    doFoo(tree, data);
    if (cond2) {
      collect(tree.left, data, depth + 1);
      collect(tree.right, data, depth + 1);
    }
  // comment for else block
  } else {
    doBar(data);
  }
```

**Comment by bitpshr** [comment]
@milesj that syntax is especially common and admittedly pretty readable, but it's technically semantically-off since the comment for the `else` block is inside the `if` block.

**Comment by ematipico** [comment]
Would this formatting choice applied only in presence of comments or always?

**Comment by milesj** [comment]
@bitpshr Interesting point. I've never thought about it that way, as semantics in relation to comments don't mean anything to me. They describe the following line/block and nothing more.

**Comment by noftaly** [comment]
> What about?
> 
> 
> 
> ```
> 
>   // comment for if block
> 
>   if (cond1) {
> 
>     doFoo(tree, data);
> 
>     if (cond2) {
> 
>       collect(tree.left, data, depth + 1);
> 
>       collect(tree.right, data, depth + 1);
> 
>     }
> 
>   // comment for else block
> 
>   } else {
> 
>     doBar(data);
> 
>   }
> 
> ```

The main downside I see is that if we fold the `if` block, we won't see the comment of the else block anymore, but still the comment of the if block.

I'm also in favor of breaking before else statements 😄

**Comment by AlchemistCamp** [comment]
That's still aligning the else block with cond2, even though it corresponds
to cond1.

**Comment by AlchemistCamp** [comment]
> Thanks for taking the time to file this @AlchemistCamp. I'm also in favor of breaking before `else` statements, I feel that the advantages are objective in terms of comment legibility.

Thanks for taking it under consideration!

**Comment by AlchemistCamp** [comment]
> What about?
> 
> ```
>   // comment for if block
>   if (cond1) {
>     doFoo(tree, data);
>     if (cond2) {
>       collect(tree.left, data, depth + 1);
>       collect(tree.right, data, depth + 1);
>     }
>   // comment for else block
>   } else {
>     doBar(data);
>   }
> ```

This would still have the else block lined up with cond2, instead of cond1.  It's

**Comment by yufizan** [comment]
> > What about?
> > ```
> > 
> >   // comment for if block
> > 
> >   if (cond1) {
> > 
> >     doFoo(tree, data);
> > 
> >     if (cond2) {
> > 
> >       collect(tree.left, data, depth + 1);
> > 
> >       collect(tree.right, data, depth + 1);
> > 
> >     }
> > 
> >   // comment for else block
> > 
> >   } else {
> > 
> >     doBar(data);
> > 
> >   }
> > ```
> 
> The main downside I see is that if we fold the `if` block, we won't see the comment of the else block anymore, but still the comment of the if block.
> 
> I'm also in favor of breaking before else statements 😄

**Comment by richard-lopes-ifood** [comment]
I'd agree with the Prettier decision by moving the comment inside the `else` block because you could have a lot of comment lines (or a larget comment block) - it could hurt the legibility where you could quickly identify if it is about an `if`/`else` statement and not a solely `if`.

```javascript
  // comment for if block
  if (cond1) {
    doFoo(tree, data);
    if (cond2) {
      collect(tree.left, data, depth + 1);
      collect(tree.right, data, depth + 1);
    }
  // what if you 
  // have a lot if
  // comment lines here
  // it's easy to forget this is about
  // an if/else statement.
  // moving the comment lines to the inside of the else
  // statement quickly reveals
  // what is it about.
  } else {
    doBar(data);
  }
```

**Comment by richardaum** [comment]
I'd agree with the Prettier decision by moving the comment inside the `else` block because you could have a lot of comment lines (or a large comment block) - it could hurt the legibility where you could quickly identify if it is about an `if`/`else` statement and not an isolated `if`.

```javascript
  // comment for if block
  if (cond1) {
    doFoo(tree, data);
    if (cond2) {
      collect(tree.left, data, depth + 1);
      collect(tree.right, data, depth + 1);
    }
  }
  // what if you 
  // have a lot of comments lines 
  // here
  // it's easy to forget this is about
  // an if/else statement.
  // moving the comment lines to the inside of the else
  // statement quickly reveals
  // what is it about.
  else {
    doBar(data);
  }
```

**Comment by bitpshr** [comment]
@richardaum most code editors rely on the semantically-correct placement of comments for block folding. For example, if the `if` block in your example above is collapsed, the `else` block comments are also incorrectly collapsed.

I'd argue that Prettier and other tools that do not add new lines before `else` blocks are doing so at the cost of proper alignment, code folding, and comment placement, when the gained legibility is minimal (and highly subjective.)

**Comment by Anoesj** [comment]
I agree with @AlchemistCamp that a break before the `else` keyword makes more sense. `if` and `else` indented identically are visually more cohesive. Also, you can decide where to place the comment yourself. Because personally, when I write this...
```javascript
// comment for if block
if (cond1) {
  // do stuff
}
// comment for else block
else {
  doBar(data);
}
```

...I mean something different than when I'm writing this:
```javascript
// comment for if block
if (cond1) {
  // do stuff
}
else {
  // comment for why I'm using doBar(data)
  doBar(data);
}
```

**Comment by sebmck** [comment]
Ah, that makes sense and makes this change a lot easier. I actually think this would be fairly straight forward to do now. Although I think we would still have issues inserting the comment in the correct place, but that can be resolved also.

The heuristic we would use here when determining if `else` should have a preceding line break, would be if the `alternate` starts on a different line than what the `consequent` ended on.

The changes would need to be made to `internal/formatter/builders/js/statements/JSIfStatement.ts`. You can access the line numbers via `node.loc.start.line` and `node.loc.end.line`. (Note that `node.loc` can also be `undefined` in the case of generated code.)

I am generally in favor of whitespace retention if it has been signaled explicitly by the developer, we can easily detect it, and it isn't a significant maintenance burden to handle. We already do this with newlines between statements, which Prettier also does, so I don't know why this would be such a contentious issue.

**Comment by jamiebuilds** [comment]
Moving to #1507
