### ISSUE TITLE
📎 Clarify Node support as a "frontend"

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1034]
It hasn't been clear to a lot of people that Rome supports writing Node backend code. There isn't anything special we need to do to support it. I think it's still important to emphasis "frontend toolchain" as it emphasises the cohesion that Rome is aiming for and doesn't seem like an unfocused collection of tools and supported languages. There is possibly something we can tweak or further clarify to reduce some of this concern.

**Comment by jamiebuilds** [comment]
I don't think its true that there's nothing special we need to do to support Rome. There are certainly things we could do to make the Node experience better. Especially when we start talking about test runners and platform specific compiling/bundling
