### ISSUE TITLE
🐛 Rome doesnt recognize typescript libs globals, example ReadonlyArray interface

### ISSUE THREAD

**Issue by kno-raziel** [rome/tools#1040]
## Environment

```
$ npx rome rage --summary
Environment Variables
  Object {
    LANG: "en_US.UTF-8"
    PATH: "Z:\\Code\\figma-plugin\\node_modules\\.bin;C:\\Users\\UserProfile\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program
    Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program
    Files\\Git\\usr\\bin;C:\\Users\\UserProfile\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\Sy
    stem32\\OpenSSH;C:\\Program Files\\TortoiseGit\\bin;C:\\Users\\UserProfile\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\NVIDIA
    Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\ProgramData\\chocolatey\\bin;C:\\Program
    Files\\Git\\cmd;C:\\Users\\UserProfile\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\UserProfile\\AppData\\Local\\Programs\\Microsoft VS
    Code\\bin;C:\\Users\\UserProfile\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl"
    TERM: "cygwin"
    TERM_PROGRAM: "Terminus"
  }

User Config
  unset

Rome Version
  10.0.3-beta

Node Version
  14.5.0

Platform
  win32 x64 10.0.19041

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 179
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: false
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "Z:\\Code\\figma-plugin"
    realCwd: "Z:\\Code\\figma-plugin"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 105_086_976
      pid: 11_124
      uptime: 0.769558299
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 105_086_976
        ownedBytes: 0
        ownedFileCount: 0
        pid: 11_124
        uptime: 0.769510899
      }
    ]
  }

```

## Steps To Reproduce

1. create **test.ts file** with the following code
```typescript
let romeTest: ReadonlyArray<string>;
romeTest = ["a", "b", "c"];
console.log(romeTest);
```
2. run **npx rome check**
```
$ rome check

 test.ts:1:14 lint/js/noUndeclaredVariables 
  × The ReadonlyArray variable is undeclared

  > 1 │ let romeTest: ReadonlyArray<string>;
      │               ^^^^^^^^^^^^^
    2 │ romeTest = ["a", "b", "c"];
    3 │ console.log(romeTest);
```

## Expected Results

```
√ No known problems!
```

**Comment by thisizkp** [comment]
Rome by default generates the following config https://romefrontend.dev/#project-configuration. We would have to manually add globals to the config by using the following command https://romefrontend.dev/#lint.globals

So in this use case, the command should be `npx rome config push lint.globals ReadonlyArray`. I don't think this is a bug. It looks like more of an intentional feature.

**Comment by sebmck** [comment]
@thisizkp This issue is to track automatically loading and extracting global names from TypeScript libraries. It would allow these to not even need to be configured.

**Comment by thisizkp** [comment]
My bad. That makes sense 👍, manually configuring and managing all the globals will be hard.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!

**Comment by kno-raziel** [comment]
@jamiebuilds I believe this issue shouldn't closed since is not related to typescript based coded used to build Rome, it was related to the linter functionality using typescript files and global names. Not sure if that have been updated/fixed...
