### ISSUE TITLE
📎 Add `README`s to all `internal` folders

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1062]
This will make it easier for others to understand what a package does and it's responsibilities.

**Comment by mudathirlawal** [comment]
Hello, @sebmck,

I am willing to pick up this task that addresses the concern raised in issue #1062. However, I have difficulty understanding what the various functions of internal folders do. If you could please provide me some guide.

Many thanks.
**Mudathir**

**Comment by sebmck** [comment]
Sorry, I don't think this is a task someone else can take on (some core contributors likely could). If I explain what all the folders do then I've essentially already written the READMEs.
