### ISSUE TITLE
📎 Suppress lint diagnostic for an unknown peer dependency

### ISSUE THREAD

**Issue by EduardoLopes** [rome/tools#1066]
## Discord conversation

*Thursday, August 13, 2020*

**Eduardo Lopes Today at 6:30 PM**
I'm trying rome in a lib that have peer dependencies. Since these dependencies are not installed, the lint shows a resolver/notFound problem
there's any way to deal with that other than suppression?

**Sebastian Today at 6:32 PM**
```
bundler: {
    externals: ["peer-dependency-name"]
}
```
you can add that to your project config
ideally though we should suppress that for an unknown peer dependency and only surface it during bundling, probably

**Comment by ematipico** [comment]
This has been implemented!
