### ISSUE TITLE
💭 Consider changing ts noArrayShorthand rule

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1079]
Right now we require `Array<T>` instead of `T[]` but it usually ends up with extracting the array type into one that just has an `s` on the end.

**Comment by ematipico** [comment]
Is this a lint rule or a diagnostic of the compiler?

And what's the suggested change?

**Comment by sebmck** [comment]
It's the lint rule `js/noShorthandArrayType` (it should actually be in the `ts` namespace). We ban:

```
T[];
```

And instead recommend:

```
Array<T>;
```

The proposed change is flipping it and recommending `T[]` instead of `Array<T>`. The reason I added this rule in the first place was that `Array<T>` is the recommended pattern in Flow, which Rome was previously using.

**Comment by ljharb** [comment]
This is a good change. It looks better, is just as obvious, and is shorter.

**Comment by ematipico** [comment]
I'll work on this one
