### ISSUE TITLE
📎 Gracefully handle failing VSC getUncommittedFiles and getModifiedFiles

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1087]
See #1073 for relevant discussion.

We could do one of three things:

1. What we do now: throw a hard error. But make it more descriptive. We don't even include the method name right now.
2. Log an error, and return an empty array.
3. Log an error, and return something else besides an array when we aren't sure or fail.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
