### ISSUE TITLE
📎 Setup CODEOWNERS

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1089]
Can be used for PR review recommendations and allow people to opt in to parts of the codebase they want to be responsible for or care about.

**Comment by bitpshr** [comment]
Happy to help oversee current and future lint rules and their utilities in `internal/compiler/lint/`.

**Comment by EduardoLopes** [comment]
I'll help oversee the website and related stuff

**Comment by ematipico** [comment]
I'd be happy to take responsibility of the `internal/markdown-parser` and `internal/html-parser`. 
I could also assist @bitpshr with the linter.

**Comment by yassere** [comment]
I'll help review any PRs for `internal/core` because that's where I've mostly been working, but I'll generally still wait for @sebmck to merge them to make sure any core changes match the project's principles.
