### ISSUE TITLE
🐛 Progress bar bleed when running `rome ci`

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1104]
Something wrong with the cursor movement when clearing lines.

<img width="1792" alt="Screen Shot 2020-08-17 at 2 47 22 AM" src="https://user-images.githubusercontent.com/853712/90382788-14cb2400-e034-11ea-8d13-39711c90ac6a.png">

**Comment by ematipico** [comment]
I wonder, is there a way to test these cases? It's not the first time there are this kind of regressions and having some test could prevent them from happening.

**Comment by sebmck** [comment]
Terminal cursor movement is really hard to define and manage. I'm open to suggestions on how we can regression test it. It's notably more difficult as progress bar rendering is not predictable and has a variable "frame rate".

**Comment by ematipico** [comment]
Let's close it, this is fixed!
