### ISSUE TITLE
📎 Add test cases for different cache directories/platforms and make the code more abstract

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1136]
From https://github.com/romefrontend/rome/pull/1126#issuecomment-675890704

> Might be a good idea to eventually make these more abstract and unit test them with different variables but would require a significant amount of boilerplate to do so.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
