### ISSUE TITLE
🐛 Rome does not use tsconfig baseUrl

### ISSUE THREAD

**Issue by pikeas** [rome/tools#1155]
## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    COLORFGBG: "0;15"
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
    TERM_PROGRAM: "iTerm.app"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  12.18.3

Platform
  darwin x64 19.6.0

Terminal Features
  Object {
    background: "light"
    colorDepth: 24
    columns: 197
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/me/code/foo"
    realCwd: "/Users/me/code/foo"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_320_896
      pid: 78_078
      uptime: 0.172710707
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_320_896
        ownedBytes: 0
        ownedFileCount: 0
        pid: 78_078
        uptime: 0.172635536
      }
    ]
  }
```

## Steps To Reproduce

1. tsconfig.json file with `"baseUrl": "."` 
2. A tsx file with an import like `import foo from "styles/Foo.css"`
3. `rome check` throws `resolver/notFound`

## Expected Results

Rome is aware of absolute imports.

**Comment by ematipico** [comment]
We might probably want to support aliases too. What do you think @pikeas ?

```js
import { Button } from '@components/button`
```

**Comment by pikeas** [comment]
@ematipico Absolutely, anything that the Typescript compiler can resolve should be visible to Rome. I'm sure what a sane precedence policy is for tsconfig's include/exclude interacting with Rome's include/exclude.

**Comment by ematipico** [comment]
Great, there's a feature request for the aliases as well: https://github.com/romefrontend/rome/issues/1137

And we plan to enable this feature using the `auto-config`: https://github.com/romefrontend/rome/issues/1112

**Comment by jamiebuilds** [comment]
Merging this into the other linked issues
