### ISSUE TITLE
🐛 formatter breaks with labelled continue statement while running tests

### ISSUE THREAD

**Issue by iaravindreddyp** [rome/tools#1156]
## Environment

```
$ rome rage --summary

```

## Steps To Reproduce

1. add below test in one of the test cases:
`loop: for (let i = 0; i < 5; i++) {
		continue loop;
}`
2.run `./rome test` 
 rome fails to tokenize the labelled continue statement 
![Screenshot 2020-08-28 at 4 08 37 PM](https://user-images.githubusercontent.com/22080780/91552105-e1986700-e948-11ea-91fd-1f589c6124aa.png)

## Expected Results

Rome should continue tokenizing without terminating

**Comment by aravind1078** [comment]
@sebmck @ematipico where should i head if i wanna try and fix this? the ast generated itself is getting undefined in the body but where should i look for the ast generation code...?

**Comment by sasurau4** [comment]
I couldn't reproduce this bug in e41e4e7d8ae619a96f503b8b2488c719d721dba4 (Today's main latest).
I created following `test.test.ts`, ran `./rome test test.ts` and passed the test.
Any other steps to reproduce the bug or already fixed it?

```ts
import {test} from "rome";
test("test", (t) => {
  let str = ""
  loop: for (let i = 0; i<5; i++) {
    if(i === 1) {
     continue loop;
    }
    str += i
  }
  t.is(str, "0234")
})
```

**Comment by ematipico** [comment]
It seems fixed. Feel free to open a new issue if that happens again.
