### ISSUE TITLE
📎 Website should not point to `main`

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1169]
The website should only point to the version that was at the latest release and we can cherry pick into that branch. Otherwise we need to wait for a release before merging documentation updates.

**Comment by richardaum** [comment]
How does the `website` is published to the host? Locally using some sort of CLI?

**Comment by EduardoLopes** [comment]
It uses Netlify continuous deployment

**Comment by sebmck** [comment]
It no longer does. It now points to `latest`.
