### ISSUE TITLE
🐛 Cannnot rome config push dependencies.exceptions.invalidLicenses

### ISSUE THREAD

**Issue by yoshixmk** [rome/tools#1177]
## Environment

```
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  14.4.0

Platform
  darwin x64 19.6.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 168
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "*sorry repository here, https://github.com/yoshixmk/f3*"
    realCwd: "*sorry repository here, https://github.com/yoshixmk/f3*"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 35_885_056
      pid: 67_571
      uptime: 0.688892192
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 35_885_056
        ownedBytes: 0
        ownedFileCount: 0
        pid: 67_571
        uptime: 0.68875429
      }
    ]
  }
```

## Steps To Reproduce
I noticed that `vite` uses deep-freeze@0.0.1 and removed it first.
```shell
$ yarn remove vite
```
then,
```
npx rome config push dependencies.exceptions.invalidLicenses.invalid-license-name "deep-freeze@0.0.1"
```
And an error occurred during the check stage, bellow.
![image](https://user-images.githubusercontent.com/6196702/92185807-ccaf5c80-ee8f-11ea-9f9d-6937bbf4a523.png)
next,  
I have also tried adding the config directly in rome.rjson , but it has been failure.
When I run command, I get an error
```json
dependencies: {
	exceptions: {
		invalidLicenses: {
			"": ["deep-freeze@0.0.1"]
		}
	}
}
```

## Expected Results
No error occurs when add invalidLicenses settings.

**Comment by ematipico** [comment]
Hi @yoshixmk , this feature is not available yet. We have a problem with the documentation where the new changes that are pushed to main are directly published to the main website. (We have an issue to track it)

This feature will be available next release

**Comment by cherihung** [comment]
is the next release with this feature the only way to bypass/address this error?

**Comment by ematipico** [comment]
@cherihung yeah that's the only way.

An invalid license (of the libraries as dependencies of the project) is an error for Rome.

**Comment by ematipico** [comment]
The feature is now enabled!
