### ISSUE TITLE
🐛 Invalid bundling for code with optional chaining

### ISSUE THREAD

**Issue by antonk52** [rome/tools#1199]
## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    COLORFGBG: "7;0"
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
    TERM_PROGRAM: "iTerm.app"
    TMUX: "/private/tmp/tmux-1434521695/default,73535,0"
  }

User Config
  unset

Rome Version
  10.0.4-beta-dev

Node Version
  14.9.0

Platform
  darwin x64 18.7.0

Terminal Features
  Object {
    background: "dark"
    colorDepth: 8
    columns: 173
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    silent: false
    cwd: ___R$project$rome$$internal$path$index_ts$AbsoluteFilePath: /Users/antonk52/Documents/dev/personal/rome
    realCwd: ___R$project$rome$$internal$path$index_ts$AbsoluteFilePath: /Users/antonk52/Documents/dev/personal/rome
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 63_004_672
      pid: 85_382
      uptime: 0.47658209
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 63_004_672
        ownedBytes: 0
        ownedFileCount: 0
        pid: 85_382
        uptime: 0.476475193
      }
    ]
  }
```

## Steps To Reproduce

1. Create a `foo.ts` file with the contents
```ts
export function foo(
	arg:
		| undefined
		| {
				children: Set<string>;
			},
) {
	arg?.children.add('foo')
}
```

2. run `./rome bundle ./foo.ts ./dist`
3. Open `./dist/foo.js` to see the following

```js
(arg == null ? undefined : arg.children).add == null
	? undefined
	: (arg == null ? undefined : arg.children).add("foo");
```

This produces invalid code, which breaks at the runtime. Ie `TypeError: cannot get add of undefined`

## Expected Results

Bundle command should not introduce new ways for code to error out. To be more specific I expected to see something similar to

```js
arg == null ? undefined : arg.children.add("foo")
```

**Comment by antonk52** [comment]
I've looked into how rome handles `optionalChaining` and it looks like there might be some non-intuitive behavior with optional call expressions as well. Below is what I've found. Not sure if this should be extracted into a separate issue.

Any call expression that has `?.` anywhere in the callee is marked as `JSOptionalCallExpression`. Which is okay, however there is no indicator if `?.` is between callee and the parens. This is the reason why we have

```js
// input
a?.b();

// output
(a == null ? undefined : a.b) == null
                ? undefined
                : (a == null ? undefined : a.b)();
```

Here we can see two conditional expressions instead of one. One conditional expression is done by the [optional member transformer](https://github.com/romefrontend/rome/blob/main/internal/compiler/transforms/compile/transpile/optionalChaining.ts#L17-L28) and the other one is by [optional call expression transformer](https://github.com/romefrontend/rome/blob/main/internal/compiler/transforms/compile/transpile/optionalChaining.ts#L30-L38). To illustrate the unwanted behavior we can can comment out the optional member transformer and rerun the bundle command with the same input.

```js
// input
a?.b();

// output
a?.b == null ? undefined : a?.b();
```

This looks excessive since the optional check happens before we do the calling, therefore the conditional expression here is not needed. At the moment I can see two ways of solving this problem:
1. We can add an indicator for `?.` presence prior the calling paren and check in the transform for its presence.
2. Only mark nodes as `JSOptionalCallExpression` when there is `?.` in between callee and parens.

For reference here is. how other compilers parse the same input in [astexplorer](https://astexplorer.net/#/gist/b38691c2ecaf8bb5d6f4dc0ed107d383/f9466bb0c07507cd0b5ef6d018a5ac16f1b5ebab)
- babel and flow have `OptionalCallExpression` with `optional: false` flag.
- acorn and eslint-parser mark it as `CallExpression`, Typescript has `CallExpression` and an optional property `questionDotToken`(not set in our case).

**Comment by ematipico** [comment]
I also noticed that the babel's output is different from our output [here](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=IYfgdARgFAlA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=true&targets=&version=7.11.6&externalPlugins=) (Rome compiler is a fork of babel compiler).

**Comment by antonk52** [comment]
@ematipico if you mean the comparison to `null` and `undefined` than it will be the same if `loose mode` is enabled for babel. However, we still need to fix rome's output replacing the outermost expression with a ternary and I think adding a flag to optional call expressions to see if it is the very the call expression that is optional or an object on which we are calling a method
