### ISSUE TITLE
💭 Bundler & Plugins

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#1208]
Used to track discussion related to the rome bundler and the design of it's plugin system.

**Comment by jer3m01** [comment]
Plugins could be made using callbacks similar to Laravel's middleware https://laravel.com/docs/8.x/middleware#defining-middleware.
```ts
type data = {};
type next = (data: data) => data;
type config = {};

// Example struc
abstract class RomePlugin {
    // Whatever the name of the stages would be
    abstract compile(data: data, next: next, config: config): data;
    abstract bundle(data: data, next: next, config: config): data;
}

class pluginA extends RomePlugin {

    compile(data: data, next: next, config: config): data {
        data.doStuff();
        // Returning `data` instead of `next` would not run the other plugins
        return next(data);
    }

    bundle(data: data, next: next, config: config): data {
        // Using the return value of the closure would run all the other plugins before performing it's actions
        let processedData = next(data);

        processedData.doOtherStuff();

        return processedData;
    }
}

class pluginB extends RomePlugin {
    ...
}

// config plugin list, would run in order for each stage
plugins: [
    pluginB,
    pluginA,
]
```

This would also make the backend implementation fairly easy. *This should in theory be working*
```ts
const config;

// Repeat for each stage
function runCompile() {
    // Internal compiling code
    const internalData = internalFunction();

    let i = 0;
    const next = (data: data): data => {
        if (i >= config.plugins.length) return data;

        const plugin = config.plugins[i++];
        return new plugin().compile(data, next, config);
    }

    return next(internalData); // Fully compiled code
}
```

**Comment by ematipico** [comment]
I think the philosophy of the bundler should reflect what the modern web development needs.

We still need a bundler for when we ship code to production (still) but we don't need a bundler for develop our applications locally. That's where snowpack and vite shine. I believe Rome should follow the same philosophy.

ESM modules for web development, optimized build for production.

That being said, about the plugin system, I think the concept of "plugin" is too broad and it's really difficult to understand what a plugin does. I like Parcel's approach, where they have specific naming convention that helps to understand the responsibility of a "plugin". They have transformers, optimizers, packagers, etc. and they are divided by file extension.

What do you think?

**Comment by jer3m01** [comment]
ESM modules for development and optimized builds for prod sound like the way to go.

Had a quick look to Parcel's plugin system, really like the idea of auto loading & splitting them.
The splitting is a bit similar to my example with the different stages, now how to implement it would need a bit more input.

@sebmck any takes on this?
