### ISSUE TITLE
📎 Vue + Sass

### ISSUE THREAD

**Issue by TheJaredWilcurt** [rome/tools#1222]
Everytime I see a new "webpack killer" I say "FINALLY, I hate webpack". Then I go look at it and the first thing I check is can it handle Vue Single File Components that use Sass. Then I say "Oh well, maybe next year".

```html
<template>
  <div>
    <p>{{ greeting }} World!</p>
    <OtherComponent />
  </div>
</template>
<script>
import OtherComponent from './OtherComponent.vue';
export default {
  components: {
    OtherComponent
  },
  data: function () {
    return {
      greeting: 'Hello'
    };
  }
};
</script>
<style lang="sass" scoped>
p
    font-size: 15px
    text-align: center
</style>

**Comment by sebmck** [comment]
Ok? Do you have a particular question or are you looking for a specific response?

Sass and Vue on their own aren't trivial to implement and would require significant time and engineering resource investment.

If you want us to support something it's probably a good idea to not be so inflammatory from the beginning. Nobody here gets paid to work on Rome.

**Comment by sebmck** [comment]
Actually this isn't the first time I've dealt with you before. 5 years later and you haven't changed. babel/babel#2056. Don't use my software.
