### ISSUE TITLE
📎  Typescript v4.1 & template literal types support

### ISSUE THREAD

**Issue by antonk52** [rome/tools#1244]
The new typescript version has been out for some time now and it introduced [Template liternal types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types).

This issue is for updating the typescript in node_modules and adding support for the new feature.

**Comment by ematipico** [comment]
I think the version 4.1 brings to the table more features (and we don't have yet all the features we should support form version 4.0):
- variadic tuples: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types
- labeled tuples: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements
- key remappings in mapped types: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types

**Comment by ematipico** [comment]
Closing, we now support all these features! 🎉
