### ISSUE TITLE
🐛 Incorrect .editorconfig generation in [rome init]

### ISSUE THREAD

**Issue by wingdeans** [rome/tools#1245]
Running the getting started steps from [here](https://rome.tools/#getting-started) creates an .editorconfig which does not apply to json files.

## Environment
```
[nix-shell:~/Projects/VisualImGui]$ cat .editorconfig 
[{*.js, *.json, *.rjson}]
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
charset = utf-8
indent_style = tab
indent_size = 2

[nix-shell:~/Projects/VisualImGui]$ yarn editorconfig package.json
yarn run v1.22.5
warning package.json: No license field
$ /home/dean/Projects/VisualImGui/node_modules/.bin/editorconfig package.json
Done in 0.11s.
```

## Steps To Reproduce
1. `yarn add rome`
2. `yarn rome init`
3. `yarn add editorconfig`
4. `yarn editorconfig package.json`

## Expected Results
Removing the spaces after the commas in the generated .editorconfig yields the expected results.
```
[nix-shell:~/Projects/VisualImGui]$ cat .editorconfig 
[{*.js,*.json,*.rjson}]
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
charset = utf-8
indent_style = tab
indent_size = 2

[nix-shell:~/Projects/VisualImGui]$ yarn editorconfig package.json
yarn run v1.22.5
warning package.json: No license field
$ /home/dean/Projects/VisualImGui/node_modules/.bin/editorconfig package.json
end_of_line=lf
trim_trailing_whitespace=true
insert_final_newline=true
charset=utf-8
indent_style=tab
indent_size=2
tab_width=2
Done in 0.12s.
```

## Fix
The space after the comma [here](https://github.com/rome/tools/blob/8edbed0c3505c8ed3724015df83817c2a92acce8/internal/core/server/commands/init.ts#L308) should be removed.

**Comment by ematipico** [comment]
This should really easy to fix! A good first issue, PR welcome :)
