### ISSUE TITLE
🐛 demon not starting

### ISSUE THREAD

**Issue by dareksob** [rome/tools#1311]
Version: 10.0.4-beta
OS: windows 10

`````
$ rome start
i No running daemon found. Starting one...

 net.js:1301:20 internalError/fatal  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Permission denied for C:\Users\USER\AppData\Local\Temp\rome-wait-10.0.4-beta.sock
`````

I try to start the demon as current user and as admin.
Rome try to create a socket file. After start I see 2 folders that created by rome rome-10.0.4-beta and rome-remote, and nothing else

**Comment by ematipico** [comment]
Is it the same issue of #1284 ?
If so, we could close this one and add your comment there

**Comment by dareksob** [comment]
Looks similar to this issue, but have an other operation system. My node version are the same or simular 14.15.x
