### ISSUE TITLE
🐛 "Expected end of file" error for file in node_modules/

### ISSUE THREAD

**Issue by wildlyinaccurate** [rome/tools#1320]
Rome doesn't appear to ignore node_modules and throws an `✖ Expected end of file` error during `rome init`. This also happens during `rome check` in a project where Rome is already initialised. The file it complains about seems to be valid JSON.

```
 Welcome to Rome! Let's get you started... 

[1/2] Generating .editorconfig

 node_modules/fast-xml-parser/package.json:104:18 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Expected end of file

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem
```

## Environment

```
$ rome rage --summary

Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_NZ.UTF-8"
    TERM: "xterm-256color"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  14.10.0

Platform
  linux x64 5.8.0-41-generic

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 173
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/home/joseph/dev/rome-bug-repro"
    realCwd: "/home/joseph/dev/rome-bug-repro"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 29_323_264
      pid: 163_429
      uptime: 0.880797629
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 29_323_264
        ownedBytes: 0
        ownedFileCount: 0
        pid: 163_429
        uptime: 0.880722256
      }
    ]
  }
```

## Steps To Reproduce

1. Clone [this repo](https://github.com/wildlyinaccurate/rome-bug-repro) (or set up a new project with only `@aws-sdk/client-s3` installed as a dependency)
2. Run `npx rome init`

## Expected Results

Ideally Rome should completely ignore node_modules. Failing that, it should not halt the entire `init` or `check` command.

**Comment by ematipico** [comment]
That's caused by another non-valid license. `fast-xml-parser` has the following license:

```
"license": "MIT Modified",
```

I think Rome should handle this particular case. Thank you for reporting this.

**Comment by sebmck** [comment]
We should support it only in `loose` mode (ie. when a license expression is in `node_modules`) as it's not valid otherwise and we treat users `package.json` more strictly. We should also make the error message a lot nicer here for sibling words like this.

**Comment by Andrew-Dyachenko** [comment]
I got the same problem, ignore rule seems to be not working.
Rome `10.0.4-beta`

```bash
 src/client/node_modules/highcharts/package.json:49:19 parse/spdxLicense ━━━━━━━━━━━━━━

  ✖ Unexpected character :

    47 │     "webpack"
    48 │   ],
  > 49 │   "license": "https://www.highcharts.com/license",
       │                    ^
    50 │   "main": "highcharts.js",
    51 │   "name": "highcharts",

```

**rome.rjson**
```rjson
// For configuration documentation see http://romefrontend.dev/#project-configuration
name: "main-site"
root: true
lint: {
	ignore: [
		"node_modules"
		"src/wordpress/wp-content/plugins/"
	]
	globals: []
}
```

**Comment by ematipico** [comment]
@Andrew-Dyachenko that is not a lint diagnostic. If you check it, it has `parse/spdxLicense` which is the category of the diagnostic. Lint diagnostics have `lint` inside their category name.

Hence, if you want to ignore that particular license, the setting you're looking for is this one: https://rome.tools/#dependenciesexceptionsinvalidlicenses
