### ISSUE TITLE
🐛 Errors handling default values with destructuring 

### ISSUE THREAD

**Issue by ajkachnic** [rome/tools#1348]
There appears to be a parsing error when handling default values within destructuring. It throws a parsing error on code like:
```js
const foo = ({ bar = 'foobar' }) => bar
```

This is my first time trying out Rome, so there might be something that I'm missing. I did a brief check for duplicates so there shouldn't be any, but I could be wrong

## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-kitty"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  14.15.4

Platform
  linux x64 5.4.89-1-MANJARO

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 89
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/home/andrew/dev/personal/projects/main/website-redesign"
    realCwd: "/home/andrew/dev/personal/projects/main/website-redesign"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 29_175_808
      pid: 234_262
      uptime: 0.574296348
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 29_175_808
        ownedBytes: 0
        ownedFileCount: 0
        pid: 234_262
        uptime: 0.574027092
      }
    ]
  }

```

## Steps To Reproduce

1. Add this code to a file in a rome project:
```js
const someFunction = ({
  message = "hello"
}) => {
  console.log(message)
}

someFunction({})
someFunction({message: 'hello world'})
```
2. Run `rome check`

## Expected Results

This should not fail to parse, as it is valid JavaScript. If you run `node` on this file, it executes fine. I assume this is just an edge case within the parser.

**Comment by ematipico** [comment]
Hi @ajkachnic , what's the actual error that you get?

**Comment by ajkachnic** [comment]
It outputs this error

```
 index.js:2:10 parse/js ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unexpected token, expected ,

    1 │ const someFunction = ({
  > 2 │   message = 'hello'
      │           ^
    3 │ }) => {
    4 │   console.log(message)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by ktfth** [comment]
Can I help solve that bug?

**Comment by ematipico** [comment]
> Can I help solve that bug?

This is a tricky one. Feel free to help but this is a subtle issue and would require time and more in depth knowledge of the scope.

**Comment by ktfth** [comment]
@ematipico Just to register an information about the bug.

Welcome to Node.js v16.4.2.
Type ".help" for more information.
> let a = ({ message = 'test'}) => message
undefined
> a()
Uncaught TypeError: Cannot read property 'message' of undefined
    at a (REPL1:1:12)
>

There is the behavior of a similar reproduction

**Comment by jer3m01** [comment]
Mostly a note to myself:
destructuring with a default value works in functions, results to a `JSBindingObjectPattern` but parser doesn't expect one since it's not sure we're in an arrow function yet. Might need to add it to add it as an expectation on https://github.com/rome/tools/blob/1d128b8e9c2c6facea36c7a6048a42e71a1f8488/internal/js-parser/parser/expression.ts#L1971
