### ISSUE TITLE
📎 Prefer shorter relative imports over module relative

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1358]
We have a lot of imports like:

```
import executeMain from "@internal/core/common/utils/executeMain";
```

when the file that imports it is closer using a relative path. This is likely due to VSCode being awful when using auto-imports.

We should make this a lint error and autofix.

**Comment by ematipico** [comment]
> This is likely due to VSCode being awful when using auto-imports.

You can add WebStorm too

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
