### ISSUE TITLE
📎 Consider annoying log when ESLint integration is enabled

### ISSUE THREAD

**Issue by sebmck** [rome/tools#1361]
Something like this when running `rome check`:

```
⚠ ESLint integration is enabled. Some description of caveats.
```

While we have this integration support, it is really not ideal and exists purely to offer an incremental migration path. We should make the experience reliable but we should not incentivize long-term usage.

**Comment by ematipico** [comment]
I think we should also consider highlighting the fact that with eslint integration enabled, the execution of the code becomes exposed and it's not sandboxed anymore.
