### ISSUE TITLE
🐛 https://rome.tools is down with a redirect loop

### ISSUE THREAD

**Issue by qrohlf** [rome/tools#1369]
## Environment

Chrome latest

## Steps To Reproduce

1. Click link to https://rome.tools under the **About** heading on this repo
2. Experience redirect loop:

<img width="753" alt="Screen Shot 2021-02-16 at 10 04 54 AM" src="https://user-images.githubusercontent.com/347189/108103384-b90f4100-703e-11eb-8c40-adfbed832eb7.png">

## Expected Results

Be taken to the project homepage

**Comment by ematipico** [comment]
Unfortunately I'm no netlify expert so I don't know where the issue could be: https://www.github.com/rome/tools/tree/main/website%2Fstatic%2F_redirects


This the file that is responsible of the redirects. PR welcome!

**Comment by sebmck** [comment]
This is an intermittent issue that occurs randomly and I don't believe it's our fault. It's something either on the Netlify or Cloudflare side.

**Comment by leothorp** [comment]
I was just running into this inconsistently as well.

**Comment by ematipico** [comment]
This should be fixed now
