### ISSUE TITLE
🐛 https://rome.tools/changelog/ contains no content

### ISSUE THREAD

**Issue by zlypher** [rome/tools#1374]
## Environment

Any browser (Chrome, Firefox, Opera)

## Steps To Reproduce

1. Open https://rome.tools/changelog

## Expected Results

The site displays changelog between the versions (or, since it is in development, some kind of indication that it is still in development and first release is planned on X)

![image](https://user-images.githubusercontent.com/820423/108604779-47bdee00-73b0-11eb-8f51-b590bc55b06c.png)

**Comment by MichaReiser** [comment]
We have removed the Changelog from the website for the time being.
