### ISSUE TITLE
http://rome.tools allows accessing the site without HTTPS

### ISSUE THREAD

**Issue by leothorp** [rome/tools#1376]
## Environment

Mac OS Chrome 88.0.4324.182 (likely occurs in any web browser)

## Steps To Reproduce

1. Enter http://rome.tools in your browser address bar, or just click that link.
2. You are able to view the site without HTTPS, with a "this connection is not secure" warning in the address bar (exact language browser dependent)

Note: as a different but potentially related issue, `http` versions of some of the other redirects in `website/static/_redirects`, (for example, `http://unreleased-preview-do-not-share.rome.tools`) are intercepted by a "this connection is unsafe" warning from Chrome. If I go to "Advanced" and click `Proceed to http://unreleased-preview-do-not-share.rome.tools (Unsafe)`, then the redirect occurs as expected. From past experience, I think it should be possible for the redirect to occur immediately without running into this.

## Expected Results

http://rome.tools is expected to redirect to https://rome.tools.

**Comment by ljharb** [comment]
@leothorp did you just share something that says "do not share" in it?

**Comment by leothorp** [comment]
@ljharb 
That's a copy-paste from the redirects file I referred to- it's in the public repo.

**Comment by ljharb** [comment]
ah ok, nvm then ¯\\\_(ツ)_/¯

**Comment by jer3m01** [comment]
Has been fixed.
