### ISSUE TITLE
🐛 Yarn 2 throws when running rome: "Error: Cannot find module '/node_modules/rome/bin/rome/index.js'"

### ISSUE THREAD

**Issue by jonahsnider** [rome/tools#1397]
## Environment

- Node.js 15.8.0
- Yarn 2.4.1
- Rome 10.0.7-nightly.2021.2.10

## Steps To Reproduce

Clone [jonahsnider/rome-bug-1397](https://github.com/jonahsnider/rome-bug-1397/), see attached reproduction zip [rome-bug-1397-main.zip](https://github.com/rome/tools/files/6119105/rome-bug-1397-main.zip), or:

1. Create new folder
2. `yarn set version 2.4.1`
3. `yarn add -ED 10.0.7-nightly.2021.2.10`
4. `yarn rome` (this shouldn't be throwing, but it is)

```js
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module '/src/node_modules/rome/bin/rome/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## Expected Results

`yarn rome` should run identify the Rome binary path and run it.

**Comment by gausie** [comment]
I think this means that `package.json` needs to have [a `bin` entry](https://yarnpkg.com/configuration/manifest#bin)

**Comment by yuzima** [comment]
@jonahsnider I think the latest version solves the problem, `10.0.7-nightly.2021.2.10` doesn't contain package.json to specify the entry of bin

**Comment by jonahsnider** [comment]
The issue is still occurring on the latest versions of Rome.
For whatever reason Yarn 2 installs the package as
```
node_modules/
└── rome
    ├── rome
    │   ├── index.js
    │   └── index.js.map
    └── rome.ts
```

whereas Yarn 1 installs it as

```
node_modules/
└── rome
    ├── LICENSE
    ├── README.md
    ├── bin
    │   ├── rome
    │   │   ├── index.js
    │   │   └── index.js.map
    │   └── rome.ts
    ├── bundlebuddy.json
    ├── index.js
    ├── index.js.map
    ├── index.ts
    └── package.json
```

Yarn 2 is just storing the `bin` directory (???). With no `package.json` it tries to run `index.js`, which doesn't exist and throws an error.
As a temporary workaround you can add a `rome` script that points to the actual binary path:

```json
{
  "name": "my-project",
  "scripts": {
    "rome": "node node_modules/rome/rome/index.js",
    "test": "rome test"
  },
  "devDependencies": {
    "rome": "nightly"
  }
}
```
