### ISSUE TITLE
🐛 Regression: `rome check` says "No files linted"

### ISSUE THREAD

**Issue by strager** [rome/tools#1437]
## Environment

```
$ rome rage --summary
Environment Variables
  {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
  }

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  15.12.0

Platform
  linux x64 5.4.86-stragerhard2

Terminal Features
  {
    background: "unknown"
    colorDepth: 24
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<50>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</home/strager/tmp/ro
    metest>
    realCwd: AbsoluteFilePath</home/strager/tm
    p/rometest>
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}]
    workers: [
      {
        astCacheSize: 0
        heapTotal: 46_706_688
        ownedBytes: 0n
        ownedFileCount: 0
        pid: 584_643
        uptime: 0.2336173
      }
    ]
    server: {
      heapTotal: 46_706_688
      pid: 584_643
      uptime: 0.233711546
    }
  }
```

## Steps To Reproduce

1. Clone Rome's source repository.
2. Check out Rome version v10.0.4-beta. (This is to avoid issues with `rome init`: #1418)
3. Create and cd into a temporary directory.
4. Run `/path/to/rome-tools/rome init`.
5. Check out Rome commit 3d09ea15e3e0baab005e4774822cdb1330320f4a (current `main`).
6. Create a file called `test.js` with contents `let x, x;`.
7. Run `/path/to/rome-tools/rome check`.

## Actual results

`rome check` succeeds with no errors, but emits a warning:
```
⚠ No files linted
✔ No known problems!
```

## Expected Results

`rome check` fails with errors:
```
 test.js:1 lint/js/useSingleVarDeclarator  FIXABLE
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Declare variables separately.

    let x, x;
    ^^^^^^^^^

  ℹ Safe fix

    1   │ - let·x,·x;
      1 │ + let·x;
      2 │ + let·x;

 test.js:1:7 lint/js/noUnusedVariables ━━━━━━━━━━━

  ✖ The let variable x is unused.

    let x, x;
           ^

  ℹ Unused variables are dead code and usually
    the result of incomplete refactoring.

 test.js lint/pendingFixes  FIXABLE  ━━━━━━━━━━━━━

  ✖ Pending formatting and safe fixes

    1   │ - let·x,·x;
      1 │ + let·x;
      2 │ + let·x;
    2 3 │   

  ℹ To apply fixes and formatting run
  $ rome check test.js --apply

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Fixes available. To apply safe fixes and
  formatting run
$ rome check --apply
ℹ To choose fix suggestions run
$ rome check --review
✖ Found 3 problems
```

## Other information

I bisected the issue. It looks like commit d4b8b5c5c436d4795958676ff40b8a61b3a6d7e3 is to blame:
```
$ git bisect log   
git bisect start
# good: [d4ff4dc26129ba0172600fb95c2ba68f9a995ab7] Release v10.0.4-beta
git bisect good d4ff4dc26129ba0172600fb95c2ba68f9a995ab7
# bad: [3d09ea15e3e0baab005e4774822cdb1330320f4a] feat(css-prefix): backdrop-filter support (#1435)
git bisect bad 3d09ea15e3e0baab005e4774822cdb1330320f4a
# good: [92f77ffbdc8eadb0625015201d6eb352af0520ae] Run fixes
git bisect good 92f77ffbdc8eadb0625015201d6eb352af0520ae
# good: [b99469b601c133efd73e467ee9308c99e235900e] Remove JSNumericLiteral["raw"] and add scientific format (#1319)
git bisect good b99469b601c133efd73e467ee9308c99e235900e
# bad: [edc6f14146afc5b5d63bb5780a8f99ecc4e5d978] Bump version
git bisect bad edc6f14146afc5b5d63bb5780a8f99ecc4e5d978
# good: [a030d7efe77ccbf3b4fcc1f1d86fd1de29e2743f] fix(lint): handle recursive reference in noUnusedVariables (#1265)
git bisect good a030d7efe77ccbf3b4fcc1f1d86fd1de29e2743f
# bad: [034ef818c409bed2e8862d083db4167c4e208191] Fix workflow output name
git bisect bad 034ef818c409bed2e8862d083db4167c4e208191
# bad: [5c6e97043ad4d515d8a79a877c4641a95ca4867a] feat(website): Add new barebones WIP website (#1389)
git bisect bad 5c6e97043ad4d515d8a79a877c4641a95ca4867a
# good: [8b992b675df325817b74e326decf0cd5b7a2a2ee] Feature/commit validation (#1011)
git bisect good 8b992b675df325817b74e326decf0cd5b7a2a2ee
# bad: [d4b8b5c5c436d4795958676ff40b8a61b3a6d7e3] Ch-ch-ch-ch-changes (#1384)
git bisect bad d4b8b5c5c436d4795958676ff40b8a61b3a6d7e3
# good: [8ead8e57a051719cea606b8977b1eddce564f53e] feat: add new package internal/codec-browsers (#1364)
git bisect good 8ead8e57a051719cea606b8977b1eddce564f53e
# first bad commit: [d4b8b5c5c436d4795958676ff40b8a61b3a6d7e3] Ch-ch-ch-ch-changes (#1384)
# good: [8ead8e57a051719cea606b8977b1eddce564f53e] feat: add new package internal/codec-browsers (#1364)
git bisect good 8ead8e57a051719cea606b8977b1eddce564f53e
# first bad commit: [d4b8b5c5c436d4795958676ff40b8a61b3a6d7e3] Ch-ch-ch-ch-changes (#1384)
```

**Comment by ematipico** [comment]
Have you tried to skip the step `rome init` (which is currently broken) and just adding a config yourself? Even inside the `package.json` is sufficient

```json
"rome" {
	"name": "test-rome":
}
```

Do you still have the issue?

**Comment by strager** [comment]
> Have you tried to skip the step `rome init` (which is currently broken) and just adding a config yourself? Even inside the `package.json` is sufficient
> 
> ```json
> "rome" {
> 	"name": "test-rome"
> }
> ```
> 
> Do you still have the issue?

Same issue (i.e. `./rome check` on the older commit finds issues but on a recent commit finds no issues) if I have only the following files:

`package.json`
```json
{
    "rome": {
        "name": "rometest"
    }
}
```

`test.js`
```js
let x, x;
```

**Comment by yassere** [comment]
I wasn't able to reproduce this even with the commits you mentioned. Are you still seeing this issue?

**Comment by yassere** [comment]
I was able to reproduce this when I created the temporary directory outside of any existing Rome project directories. Thanks for the bug report!

**Comment by ematipico** [comment]
Actually I was able to reproduce the issue even with files inside a Rome project. 

The underlying issue is around threads and queues, that occurs when there are few and small files.

**Comment by yassere** [comment]
Yeah, it looks like in a small enough project, `Checker#runSingle` is completing and returning a printer with an empty diagnostics processor before the first `ServerRequest#requestWorkerLint` has a chance to finish. I would assume that [this line](https://github.com/rome/tools/blob/0c870f6fb6bf4f35033afabc4dbd44eeafdc2e97/internal/core/server/checker/Checker.ts#L666) isn't successfully doing what I think it's intended to do.

**Comment by yassere** [comment]
I think that awaiting the `refreshFileEvent` push [here](https://github.com/rome/tools/blob/0c870f6fb6bf4f35033afabc4dbd44eeafdc2e97/internal/core/server/fs/MemoryFileSystem.ts#L1066) could solve the problem.

@sebmck Previously, the `newFileEvent` push had been awaited there. What was the reason for removing that await?
