### ISSUE TITLE
🐛 LSP violation: wrong $/progress types

### ISSUE THREAD

**Issue by strager** [rome/tools#1439]
## Environment

```
$ rome rage --summary
Environment Variables
  {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
  }

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  15.12.0

Platform
  linux x64 5.4.86-stragerhard2

Terminal Features
  {
    background: "unknown"
    colorDepth: 24
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<50>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</home/strager/tmp/Pr
    ojects/rome-tools>
    realCwd: AbsoluteFilePath</home/strager/tm
    p/Projects/rome-tools>
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}]
    workers: [
      {
        astCacheSize: 0
        heapTotal: 46_968_832
        ownedBytes: 0n
        ownedFileCount: 0
        pid: 586_802
        uptime: 0.228409642
      }
    ]
    server: {
      heapTotal: 46_968_832
      pid: 586_802
      uptime: 0.228502244
    }
  }
```

## Steps To Reproduce

1. Write a program using [lsp-test](https://hackage.haskell.org/package/lsp-test) which runs and communicates with `rome lsp` as an LSP client.

## Expected Results

`rome lsp` sends well-formed messages.

## Actual Results

`rome lsp` sends malformed `$/progress` messages, such as the following:
```
{"method":"$/progress","params":{"token":1,"value":{"kind":"report","cancellable":false,"message":"","percentage":0}}}
```
According to the [LSP specification version 3.17](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/) (latest version at time of writing), `$/progress` messages can only have a string or a number for the `"value"` key:
```
type ProgressToken = integer | string;

interface ProgressParams<T> {
	/**
	 * The progress token provided by the client or server.
	 */
	token: ProgressToken;

	/**
	 * The progress data.
	 */
	value: T;
}
```

This non-conformance breaks strict LSP clients such as lsp-test.

**Comment by lucastrvsn** [comment]
I'm having this issue right now using neovim builtin LSP. Simple way to test it is just install the neovim/lspconfig and enable rome lsp.

**Comment by yassere** [comment]
@strager It looks the token can only be an `integer | string` but is there a restriction on the value?

**Comment by strager** [comment]
> @strager It looks like the token can only be an `integer | string` but is there a restriction on the value?

Oh, you're right. `value` can be anything. I misread!

**Comment by yassere** [comment]
No worries!

And it looks like @lucastrvsn had a different problem (type vs method) that's now been fixed on main, so I'll close this issue.
