### ISSUE TITLE
📎 Completely remove ms prefixes from browsers-db

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#1441]
For some reason there still there, e.g. https://github.com/rome/tools/pull/1436/files#diff-d7c1cc83474cbc56c5207f06670b72433cdbc3faf8f41d06d8b3ff292d64e466R26

**Comment by imskr** [comment]
Is this open to work? @jer3m01

**Comment by jer3m01** [comment]
> 
> 
> Is this open to work? @jer3m01

Sure, the data is generated in https://github.com/rome/tools/blob/main/scripts/generated-files/browsers-db.ts.
Although I won't be able to help much until the end of the month.

**Comment by imskr** [comment]
I will look into this @jer3m01

**Comment by jer3m01** [comment]
Line 421 of https://www.github.com/rome/tools/tree/main/scripts%2Fgenerated-files%2Fbrowsers-db.ts should be converted to a for loop and a conditional continue if the prefix is `"ms"` should be added.

**Comment by imskr** [comment]
Thanks @jer3m01

**Comment by ematipico** [comment]
Currently working on this

**Comment by ematipico** [comment]
@imskr any idea when this will be implemented? If you don't have time it's fine, I can look into it.
