### ISSUE TITLE
🐛 No matching lint files found

### ISSUE THREAD

**Issue by antonk52** [rome/tools#1458]
Before seeing details please note that the issue went away after a machine restart. But I wanted to create an issue in case other people come across it for further troubleshooting.

While working on Rome I got a little tired of waiting for Rome having to recompile every time I run it so I ran `./rome start` to start the daemon(spoiler: it still gets recompiled). I suspect this to be the issue since prior to running `./rome start` file paths were handled correctly. During the trouble shooting I've tried `./rome cache clean`; `./rome stop` and manually removing `~/.cache/rome` (thanks for supporting XDG dirs btw 😊) but no luck. I could reproduce the problem on my branch as well the current `main`. The problem went away once I have restarted my computer.

## Environment

<details>
<summary><code>rome rage --summary</code></summary>
<pre>
Environment Variables
  {COLORTERM: "truecolor", LANG: "en_US.UTF-8", TERM: "xterm-256color", TERM_PROGRAM: "tmux", TMUX: "/private/tmp/tmux-1434521695/default,1341,3"}

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  14.16.1

Platform
  darwin x64 20.2.0

Terminal Features
  {
    background: "unknown"
    colorDepth: 8
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<160>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</Users/antonk52/Documents/dev/personal/rome>
    realCwd: AbsoluteFilePath</Users/antonk52/Documents/dev/personal/rome>
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}]
    workers: [{astCacheSize: 0, heapTotal: 47_661_056, ownedBytes: 0n, ownedFileCount: 0, pid: 50_254, uptime: 0.281108333}]
    server: {heapTotal: 47_661_056, pid: 50_254, uptime: 0.28117}
  }
</pre>
</details>

## Steps To Reproduce

1. `cd` in directory with checkout out Rome project
2. run `./rome start` to start a daemon
3. run `./rome check ./website`
4. see output

<details><summary>output</summary><pre>
▲ ./rome check ./website
✔ Connected to daemon

 argv:1:11 args/fileNotFound ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No matching lint files found

    rome check ./website --no-programmatic
               ^^^^^^^^^ website

</pre></details>

## Expected Results

See the result of running the linter against the `website` directory located in the root of the project. I can verify that I've also tried to run check command against other paths and `process.cwd()` was in the same as my checkout out Rome's repository.

**Comment by ematipico** [comment]
Could you add the daemon commands to the "Steps to Reproduce" section? I think it's really important. Without daemon, the result is different.

**Comment by yassere** [comment]
There was an issue where attempting to stop a daemon left it in a partially-ended state. That should be fixed now. And you should also be able to use a running dev daemon now without rebuilding trunk.

Has this problem reoccured at all?

**Comment by antonk52** [comment]
I've updated my local branch and things are well so far. If the problem reoccurs I will post and update here. I think we can close this issue for now.

**Comment by yassere** [comment]
Sounds good. Thanks!
