### ISSUE TITLE
🐛 CSS parser falls into infinity loop when parsing rules in media query

### ISSUE THREAD

**Issue by yeonjuan** [rome/tools#1460]
CSS parser falls into infinity loop when parsing rules in a media query. 

## Environment

```
$ rome rage --summary
Environment Variables
  {COLORTERM: "truecolor", LANG: "en_US.UTF-8", TERM: "xterm-256color", TERM_PROGRAM: "vscode"}

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  14.16.0

Platform
  darwin x64 18.7.0

Terminal Features
  {
    background: "unknown"
    colorDepth: 24
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<184>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</Users/yeonjuan/Desktop/open-source/tools>
    realCwd: AbsoluteFilePath</Users/yeonjuan/Desktop/open-source/tools>
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}]
    workers: [{astCacheSize: 0, heapTotal: 47_378_432, ownedBytes: 0n, ownedFileCount: 0, pid: 57_847, uptime: 0.387601542}]
    server: {heapTotal: 47_378_432, pid: 57_847, uptime: 0.387698762}
  }
```

## Steps To Reproduce

1. example.css

```css
@media (min-width: 576px) {
	a {
	}
}
```

2. `./rome parse example.css`

it falls into infinity loop and `heap out of memory error `occurred

## Expected Results

It should parse without error and print ast.

**Comment by ematipico** [comment]
That's weird, we have similar fixtures already.

https://www.github.com/rome/tools/tree/main/internal%2Fcss-parser%2Ftest-fixtures%2Fmedia%2Fcondition%2Finput.css

Are we missing something?

**Comment by yeonjuan** [comment]
@ematipico 
yes maybe :) 
it's uncovered cases in our test cases. we have no test about media queries with rules.
I'm not sure but maybe block parsing logic in the media query has some problem.

**Comment by ematipico** [comment]
I will look into it
