### ISSUE TITLE
📎 Review internal script to update browsers data

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1523]
Running `./script generated-files/browsers-db.ts` goes in loop/error and it doesn't finish anymore:

cc @jer3m01 

![Screenshot 2021-05-21 at 11 03 29](https://user-images.githubusercontent.com/602478/119120443-2fe41d80-ba24-11eb-9746-5d725d16e471.png)

**Comment by jer3m01** [comment]
Looks like it hangs during `regions.json`, will get on it soon.

**Comment by jer3m01** [comment]
Worked just took some time. Although the [progress bar](https://github.com/rome/tools/blob/c5a15d8cf48e2be40936ff3a8aa04def3a8740e0/scripts/generated-files/browsers-db.ts#L529) doesn't show for some reason?

Still closing as it doesn't stop it from working.
