### ISSUE TITLE
🐛 Incorrect output for optional chaining operator

### ISSUE THREAD

**Issue by UsamaHameed** [rome/tools#1526]
## Steps To Reproduce

As per the [discussion](https://discord.com/channels/678763474494423051/841927329265090590/847901441272053760) on discord, the output produced by Rome for optional chaining operators is wrong.

## Expected Results
It should access the property only once. 

For example, the correct output for `a.b?.c` would be: 
```javascript
let _temp;
(_temp = a.b) == null ? void 0 : _temp.c;
```

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
