### ISSUE TITLE
📎 Remove leftover flow types support

### ISSUE THREAD

**Issue by antonk52** [rome/tools#1535]
In the codebase there are some artefacts from the days when Rome was written using [flow](https://flowtype.org). Files such as

- `internal/js-analysis/types/EmptyT.ts`
- `internal/js-analysis/types/MaybeT.ts`
- `internal/js-analysis/types/MixedT.ts`
- `internal/js-analysis/types/OpaqueT.ts`

Since typescript does not support those and does not currently seem to be interested in implementing these anytime soon, perhaps they should be removed from the project.

**Comment by Caryyon** [comment]
is this still up for grabs?

**Comment by ematipico** [comment]
> is this still up for grabs?

No, this issue is not valid anymore.
