### ISSUE TITLE
🐛 Regex numeric backrefs parsed incorrectly and broken by `check --apply`

### ISSUE THREAD

**Issue by yassere** [rome/tools#1537]
## Environment

<details>
<summary>$ rome rage --summary</summary>

```
Environment Variables
  {COLORTERM: "truecolor", LANG: "en_US.UTF-8", TERM: "xterm-256color", TERM_PROGRAM: "vscode"}

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  14.17.0

Platform
  darwin x64 19.6.0

Terminal Features
  {
    background: "unknown"
    colorDepth: 24
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<145>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</Users/Yasser/Dev/rome>
    realCwd: AbsoluteFilePath</Users/Yasser/Dev/rome>
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}, {id: 2}, {id: 3}, {id: 4}, {id: 5}]
    workers: [{astCacheSize: 0, heapTotal: 425_517_056, ownedBytes: 398n, ownedFileCount: 4, pid: 37_503, uptime: 115_262.351506074}]
    server: {heapTotal: 425_517_056, pid: 37_503, uptime: 115_262.351883992}
  }
```
</details>

## Steps To Reproduce

Backreferences are parsed as octal escapes even if there are capturing groups they can refer to.

1.  Create a file `test.foo.ts` containing: 
```
/f(o)\1/;
```
2. Running `./rome parse test.foo.ts` results in this expression:
```
        expression: JSRegExpSubExpression {
          body: [
            JSRegExpCharacter {value: "f"}
            JSRegExpGroupCapture {
              expression: JSRegExpSubExpression {body: [JSRegExpCharacter {value: "o"}]}
            }
            JSRegExpCharacter {value: "\x01"}
          ]
        }
```
3. Running `./rome check --apply test.foo.ts` modifies the file to:
```
/f(o)\u0001/;
```
The same thing happens even the regex has a unicode flag: `/f(o)\1/u;`

## Expected Results

  - Running `check --apply` shouldn't turn a backref into a unicode escape sequence.
  - Numeric backrefs should be parsed as `JSRegExpNumericBackReference`.

And based on a quick look at the spec, so please someone correct me if I'm wrong:
  - Escapes should only be parsed as octal if the regex has fewer capturing groups than the decimal value of the escape.
  - Escapes should never be parsed as octal when a regex has a unicode flag.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
