### ISSUE TITLE
📎 Allow configurable output filename for bundler

### ISSUE THREAD

**Issue by yassere** [rome/tools#1542]
The bundler currently outputs source maps to `index.js.map` but the sourceMappingURL had been incorrectly based on the name of the entry file.
A temporary fix here #1541 allows source maps to work when debugging. This task is to decide the relevant configuration options and to fix it properly.

Related TODOs:
[Using basePath](https://github.com/rome/tools/blob/49ee439c3d44b05798a0b7a2833d1a7e6c9d3fd3/internal/core/server/bundler/BundleRequest.ts#L311-L315)
[Customizing basePath](https://github.com/rome/tools/blob/49ee439c3d44b05798a0b7a2833d1a7e6c9d3fd3/internal/core/server/ServerRequest.ts#L822-L823)

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
