### ISSUE TITLE
📎  Fail parser snapshot tests if they contain diagnostics unless explicitly permitted

### ISSUE THREAD

**Issue by jamiebuilds** [rome/tools#1549]
Right now it would be easy to accidentally commit snapshots that contain diagnostics, we've caught this [a few times](https://github.com/rome/tools/pull/1536/files#r648728867), but CI/tests should really be catching it first

**Comment by ematipico** [comment]
At the moment these kind of fixtures follow a predefined structure: `test-fixtures` folder and recursive discovery of `input.*` file.  

We could change it in a way that if we want to explicitly test diagnostics, the file name could be `invalid.*`.

This means `input.*` files can stay the same and the test runner will fail if there are diagnostics. If the file name is `invalid.*`, the test runner must expect diagnostics, if there aren't, the test will fail.
