### ISSUE TITLE
📎  Autogenerating AST tsdocs

### ISSUE THREAD

**Issue by jamiebuilds** [rome/tools#1574]
Having a strongly-typed AST is great for discoverability in Rome, but newcomers may still have trouble with understanding what each node and its properties mean. While working on new documentation on how to write visitors, I started playing around with auto-generating tsdocs for AST nodes

```ts
/**
 * JavaScript's try statements contain a "catch" clause:
 *
 * <!-- GENERATED:START(hash:xxx,id:tsdoc) -->
 * ```js
 *    try {} catch {}
 * //        ^^^^^^^^ catch clause
 * ```
 *
 * They may _optionally_ contain a {@link JSCatchClause.param param} with a {@link AnyJSBindingPattern}:
 *
 * ```js
 *    try {} catch (error) {}
 * //               ^^^^^ (optional) param
 * ```
 *
 * They contain a {@link JSCatchClause.body body} with a {@link JSBlockStatement}:
 *
 * ```js
 *     try {} catch {}
 * //               ^^ body block
 * ```
 *
 * They are constructed by {@link jsCatchClause}.
 * <!-- GENERATED:END(id:tsdoc) -->
 */
export interface JSCatchClause extends NodeBaseWithComments {
	readonly type: "JSCatchClause";
	readonly param?: AnyJSBindingPattern;
	readonly body: JSBlockStatement;
}
```

In editors like VSCode, this renders an intellisense tooltip like:

> **`interface JSCatchClause`**
> 
> JavaScript's try statements contain a "catch" clause:
> 
> ```js
>    try {} catch {}
> //        ^^^^^^^^ JSCatchClause
> ```
> 
> They may _optionally_ contain a [`param`](#) with a [`AnyJSBindingPattern`](#):
> 
> ```js
>    try {} catch (error) {}
> //               ^^^^^ (optional) param
> ```
> 
> They contain a [`body`](#) with a [`JSBlockStatement`](#):
>
> ```js
>     try {} catch {}
> //               ^^ body
> ```
>
> They are constructed by [`jsCatchClause`](#).

Same thing could be done for their builder:

```ts
/**
 * <!-- GENERATED:START(hash:xxx,id:tsdoc) -->
 * Builder for {@link JSCatchClause}
 *
 * ```js
 * jsCatchClause.create({
 *   param: AnyJSBindingPattern, // optional
 *   body: JSBlockStatement,
 * })
 * ```
 *
 * @see {@link AnyJSBindingPattern}
 * @see {@link JSBlockStatement}
 * <!-- GENERATED:END(id:tsdoc) -->
 */
export const jsCatchClause = createBuilder<JSCatchClause>(
	"JSCatchClause",
	{
		bindingKeys: {
			param: true,
		},
		visitorKeys: {
			param: true,
			body: true,
		},
	},
);
```

> **`const jsCatchClause: Builder<JSCatchClause>`**
> 
> Builder for [`JSCatchClause`](#)
> 
> ```ts
> jsCatchClause.create({
>   param: AnyJSBindingPattern, // optional
>   body: JSBlockStatement,
> })
> ```
>
> _see_ — [`AnyJSBindingPattern`](#)
> _see_ — [`JSBlockStatement`](#)

I think that we could generate docs like this for every AST node by using code examples from our tests and matching against source location information.

I think it might be kinda difficult to get the `<!-- GENERATED:START/END() -->` markers to work correctly, because they would have to be nested within the tsdoc comment (You can't have comments between the tsdoc comment and the target node reliably).

**Comment by ktfth** [comment]
Everyone can help on that task?
And the generation have a specific way to happen (`<!-- GENERATED:START/END() -->`)?
