### ISSUE TITLE
📎 Support for .editorconfig and multiple formatting

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1593]
Rome should use `.editorconfig` as first source of truth to apply formatting styles to a project. Even though `INI` and `TOML` share some similarities, they are not quite the same. We should create a mini parser for `INI` and being able to consume `.editorconfig` file.

On the other hand, this also unlocks a feature that now Rome could support, which is the possibility to apply different formatting based on the extension of the file. For example:

```ini
[{*.md, *.css}]
indent_style = space

[{.github/*.md}]
indent_style = tab

[{*.js, *.jsx}]
indent_style = tab
```

We should mirror this configuration inside Rome too. So inside a Rome's configuration file, we can have defaults, and we can override specific files like this:

```json5

{
	"format": {
		"indentStyle": "tab", // default style applied to all files
		"md": [
			{
				"path: "*", // wildcard, all CSS files
				"indentStyle": "space"
			},
			{
				"path": ".github", // .md files inside .github folder
				"indentStyle": "tab"
			}
		]
	}
}

```

The second configuration example is not actually needed because we will use the default one. The example serves only to show a different example for "path" key.

**Comment by jamiebuilds** [comment]
We should come up with an overall strategy to how we want to handle these sorts of things. Particularly how we avoid creating conflicts, and how we make it clear where certain configuration is coming from.

It would be easy for us to say we support all of these formats:

- Generic configuration like `.editorconfig` or `.gitattributes`
- Formatters like `.prettierrc`
- Linters like `.eslintrc`
- Language configs like `tsconfig.json` (paths, sourcemaps, etc)
- Editor settings like `.vscode/settings.json`
- etc.

But there are a number of questions to answer:

- If they conflict how to we prioritize them?
- Which types of settings to we want to copy? i.e. Should we allow people to configure Rome's bundler via `tsconfig.json`, should we ignore those options entirely? Should we alert the user of them?
- Should this configuration be copied over into `rome.toml`? Should it be more of a "sync"?
- If we don't copy settings over, how can we make it clear where we are picking configuration up from?
- Should we allow plugins like `rome-plugin-tsconfig` that would modify the Rome config (after its already loaded) to pull settings from another source? How do we keep that from getting out of control?
- How does this integrate with plugin settings? Should we discourage plugins from inventing their own config files? How would that work with integrations with tools like Babel or ESLint that already have their own config files? Should integrations like that only be internal?

**Comment by ematipico** [comment]
Here's my two cents.

All "external configuration" that Rome could benefit from, should stay external and Rome should not look for those unless the user **explicitly says so**.

For example, `.prettierrc` is always ignored, unless the user explicitly turn off the extension inside the configuration file.

We have the command `auto-config` that was born for this purpose. It's a command where we can look for this "external configuration" and copy over them to Rome's configuration. That's what we started doing with  path aliases. 
 
If a configuration changes, for example inside `.editorconfig` the user changes the tab size, the user should re run the `auto-config` command to update Rome's configuration. Ideally we could have some "first citizen" config files like `.editorconfig` and `.gitattributes`, where Rome can show a warning in case their configuration and Rome's configuration are out of sync (no changes though).

Doing so would avoid too much magic and the user will always be in control of what's going on. Better being explicit than being implicit. On the long run this would help us to. If we have a bug because we can't import a certain configuration, the user can always do it manually. If it was implicit, the user might need to wait a fix from our end to fix the issue.
