### ISSUE TITLE
🐛 Rome check: Cannot find ts files imported as js files

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#1632]
### What happened?

1. create two files `a.ts` and `b.ts` in the same folder
2. import `b.ts` as a js file in `b.ts`
3. run rome linter `rome check`.

Rome check outputs `Cannot find ./a.js from b.ts`

```ts
@filename a.ts
export function f(){}

@filename b.ts
import {f} from "./a.js"
```

### Expected result

Rome should identify js imports as ts imports if the js file does not exist.

The use of js extensions in imports is supported by TypeScript and enables direct execution of esm files in modern versions of nodejs.

### Rome version

10.0.0

### Configuration file of your project

```json
name: "xxx"
root: true
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Is it actually a bug? I'd say it's a feature request. Rome doesn't fully support ESM at the moment so I think it's expected as behaviour.

**Comment by Conaclos** [comment]
@ematipico
This makes sense. Should I close this issue and open a new one?

**Comment by ematipico** [comment]
Rome diagnostic (not a lint rule) should show you the type of [error you're getting](https://rome.tools/#anatomy), called category.

[Then add a suppression](https://rome.tools/#suppressions)

If you're not happy with the result, you could use the latest nightly where we disabled this kind of errors.
