### ISSUE TITLE
📎 Add rule to only allow 1 kind of TS array definition

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#1647]
### Description

Typescript has 2 ways to define an array:

```ts 
Type[]

// or

Array<Type>
```

However these become inconstant throughout a codebase.

We should add a lint rule to only allow 1 kind to be used everywhere, either should be configurable and autofixable.

**Comment by ematipico** [comment]
We already have it: https://rome.tools/docs/lint/rules/ts/preferShorthandArrayType/#tsprefershorthandarraytype

**Comment by jer3m01** [comment]
Oh my bad, thanks @ematipico
