### ISSUE TITLE
📎 Fix parsing destructuring default value assignment expression test

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#1650]
### Description

Context: #1651 

js-parser still can't handle
https://github.com/rome/tools/blob/6f1960fae2491a1403654a8eb0e6756f16891d42/internal/js-parser/test-fixtures/es2015/uncategorised/307/input.js#L1

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
