### ISSUE TITLE
🐛 Error occurs with --watch frag

### ISSUE THREAD

**Issue by tkeiyama** [rome/tools#1664]
### Environment information

```bash
% yarn rome rage --summary
yarn run v1.22.10
$ /Users/thomas/repos/react-sandbox/node_modules/.bin/rome rage --summary
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  16.6.1

Platform
  darwin arm64 20.6.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 139
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/thomas/repos/react-sandbox"
    realCwd: "/Users/thomas/repos/react-sandbox"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 65_601_536
      pid: 51_275
      uptime: 0.480403
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 65_601_536
        ownedBytes: 0
        ownedFileCount: 0
        pid: 51_275
        uptime: 0.480337417
      }
    ]
  }


✨  Done in 0.63s.
```

### What happened?

1. Ran `yarn rome check --apply --watch`
1. I pressed `Ctrl + V` in package.json
2. The following error occured in the console.

<details>
<summary>Error</summary>
 Linting: package.json                                                                                                      elapsed 0.17s 
 server project-rome/@internal/core/server/project/ProjectManager.ts:829:9 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Expected existing project for /Users/thomas/repos/react-sandbox/package.json only have /,
    /var/folders/d5/qff4sxnj43qg7vtyl_dn70r40000gn/T/rome-remote

   1. ___R$project$rome$$internal$core$server$project$ProjectManager_ts$default.assertProjectExisting (
      project-rome/@internal/core/server/project/ProjectManager.ts:829:9)
   2. ___R$project$rome$$internal$core$server$project$ProjectManager_ts$default.findProject (
      project-rome/@internal/core/server/project/ProjectManager.ts:892:17)
   3. ___R$project$rome$$internal$core$server$project$ProjectManager_ts$default.assertProject (
      project-rome/@internal/core/server/project/ProjectManager.ts:773:36)
   4. ___R$project$rome$$internal$core$server$ServerRequest_ts$default.maybePrefetchModuleSignatures (
      project-rome/@internal/core/server/ServerRequest.ts:1150:18)
   5. ___R$project$rome$$internal$core$server$ServerRequest_ts$default.requestWorkerLint (
      project-rome/@internal/core/server/ServerRequest.ts:979:37)
   6. Function.allowMissing (project-rome/@internal/fs/FileNotFound.ts:51:11)
   7. <anonymous> (project-rome/@internal/core/server/linter/Linter.ts:217:15)
   8. next (project-rome/@internal/core/server/WorkerQueue.ts:122:4)
   9. Function.all
  10. ___R$project$rome$$internal$core$server$WorkerQueue_ts$default.processWorker (
      project-rome/@internal/core/server/WorkerQueue.ts:134:3)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

(node:51234) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 11)
(Use `node --trace-warnings ...` to show where the warning was created)
 server project-rome/@internal/events/Bridge.ts:351:20 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Connection died

  1. ___R$project$rome$$internal$core$common$bridges$WorkerBridge_ts$default.end (project-rome/@internal/events/Bridge.ts:351:20)
  2. ___R$project$rome$$internal$core$server$WorkerManager_ts$default.end (project-rome/@internal/core/server/WorkerManager.ts:106:11)
  3. ___R$project$rome$$internal$core$server$Server_ts$default.onFatalError (project-rome/@internal/core/server/Server.ts:335:21)
  4. onFatalError (project-rome/@internal/core/server/Server.ts:459:8)
  5. <anonymous> (project-rome/@internal/core/common/utils/setupGlobalErrorHandlers.ts:26:3)
  6. process.processTicksAndRejections (node:internal/process/task_queues:96:4)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

(node:51234) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 12)
 worker 1 project-rome/@internal/core/server/WorkerManager.ts:323:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:323:5)
  2. Object.onceWrapper (node:events:514:25)
  3. ChildProcess.emit (node:events:394:27)
  4. Process.onexit (node:internal/child_process:290:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

 worker 2 project-rome/@internal/core/server/WorkerManager.ts:323:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:323:5)
  2. Object.onceWrapper (node:events:514:25)
  3. ChildProcess.emit (node:events:394:27)
  4. Process.onexit (node:internal/child_process:290:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

 worker 3 project-rome/@internal/core/server/WorkerManager.ts:323:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:323:5)
  2. Object.onceWrapper (node:events:514:25)
  3. ChildProcess.emit (node:events:394:27)
  4. Process.onexit (node:internal/child_process:290:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

 worker 4 project-rome/@internal/core/server/WorkerManager.ts:323:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:323:5)
  2. Object.onceWrapper (node:events:514:25)
  3. ChildProcess.emit (node:events:394:27)
  4. Process.onexit (node:internal/child_process:290:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.
</details>

### Expected result

Expected: No Error is shown.

All other files, for example `index.tsx` or `sample.json`, don't have this issue.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
