### ISSUE TITLE
🐛 `npx rome init`: Can only use AND/OR in between an expression

### ISSUE THREAD

**Issue by Songkeys** [rome/tools#1669]
### Environment information

```bash
macOS
node v14.15.3
npm v6.14.9
```

### What happened?

```
➜ npx rome init

 node_modules/pause-stream/package.json:54:15 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Can only use AND/OR in between an expression

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 1 problem
```

![image](https://user-images.githubusercontent.com/22665058/134636675-0603faef-e410-464c-8ba1-bef722373205.png)

A wrong-format package.json in node_modules prevents rome getting inited.

### Expected result

Correctly inited.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
The license field can't be an array. Please check https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license

You should revisit the field accordingly to the documention.

**Comment by Songkeys** [comment]
@ematipico  Of course I know the license field can't be an array... It's a deprecated and archived deep node module used by another and another and another node module. There're many node_modules not respecting the rules.  I'm just a user.

Please make Rome more robust.

**Comment by ematipico** [comment]
> Please make Rome more robust.

That's our plan! Please read our [latest blog post](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust)

Regarding the issue, you could use the latest nightly. There, we intentionally removed the check on dependencies. This should help to use Rome in your project!

We won't fix the issue because we are now in the middle of writing Rome in rust.

**Comment by Songkeys** [comment]
> we are now in the middle of writing Rome in rust.

That's what led me to meet this project! Great job so far. Can't wait to see the outcome! 👍
