### ISSUE TITLE
☂️ Use dprint as core lib for code formating

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rome/tools#1670]
### Description

https://github.com/dprint/dprint, Monorepo for dprint—a pluggable and configurable code formatting platform. which is the official formatting library used in deno.
We could reuse its ecosystem. For now it has some  plugin:
1. dprint-plugin-typescript
2. dprint-plugin-markdown
3. dprint-plugin-json

By reusing these libraries, we can reduce a lot of work

**Comment by ematipico** [comment]
I think we will focus on creating our own formatter with our own diagnostic system. This will give us more ownership. The core focus of deno is not formatting, so it would make sense to delegate that to a third party library. 

One of Rome's focus is formatting, so it would make more sense for us to actually build our own.
