### ISSUE TITLE
📎 Consider removing `hard_tab = true` from rustfmt config

### ISSUE THREAD

**Issue by yassere** [rome/tools#1689]
### Description

The Rust community seems to be largely in favor of spaces for indentation. There are even `rust-analyzer` completions that assume space-based indentation and produce incorrect formatting when using tabs.

We should consider following convention here.

**Comment by jamiebuilds** [comment]
Oh yeah, to be clear, hard tabs are objectively better. But if we're going to be fighting the rust ecosystem all the time I'd rather just follow convention

**Comment by ematipico** [comment]
I prefer tabs for all the reasons attached to issue I linked. And the formatter is there to solve these situations (and prevent bikeshedding). I just hope to not see another topic about it 🥺

**Comment by Boshen** [comment]
As a first timer, I was confused by the tab setup, and had to dig through old issues to understand why, and spent some time to configure my vim to support tabs properly.  

Breaking conventions here may create a little barrier of entry for new contributors, contributing to rust is already more difficult, and I think we should consider these barriers for this tab decision.

**Comment by strager** [comment]
> had to dig through old issues to understand why

Would a comment in [`.editorconfig`](https://github.com/rome/tools/blob/de73a963c897962b6e633d16d47146b58cba16cd/.editorconfig#L8) or [`rustfmt.toml`](https://github.com/rome/tools/blob/de73a963c897962b6e633d16d47146b58cba16cd/rustfmt.toml#L1) help? (Did you look in those files?)

> spent some time to configure my vim to support tabs properly.

Do you use [rust.vim](https://github.com/rust-lang/rust.vim)? Perhaps that plugin could automatically configure Vim's `softtabstop` and `expandtab` settings if a `rustfmt.toml` file exists.

**Comment by ematipico** [comment]
It seems that the rust ecosystem is really tight to `spaces`. Especially `clippy`. If you use tabs inside comment docs, it emits a warning saying that it was expecting spaces.

This is quite annoying and it doesn't seem to care about `.editorconfig` or `rustfmt.toml`. Given that, it seems that the only logical reason is to switch to spaces, even though I am not a big fun.
