### ISSUE TITLE
🐛 Broken links to GOVERNANCE.md

### ISSUE THREAD

**Issue by SimonSapin** [rome/tools#1711]
### Environment information

```bash
I use a web browser.
```

### What happened?

1. Navigate to https://rome.tools/
2. Click the "governance model" link in "Rome is maintained by a team of volunteers under an established governance model."
3. See a 404 error at https://github.com/rome/tools/blob/main/GOVERNANCE.md

### Expected result

The "governance model" link should go to a page that describes the governance model of the project.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Makes sense, we are still trying to figure things out. It's not an easy model to come up with but we are working on it.
