### ISSUE TITLE
Strip `Js` from codegen and enforce usage of labels in codegen

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1733]
> Change the codegen to strip the `Js` extensions from field names to reduce the need for explicit labels. For example, `ExpressionStatement` must use an explicit label for its inner expression so that it isn't named `js_expression`.

**Comment by MichaReiser** [comment]
What a title 😄

**Comment by ematipico** [comment]
Yeah I used the new github features that automatically creates tasks out of a checkbox list.
