### ISSUE TITLE
📎 Test coverage diff on PRs

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1747]
### Description

[Follow up from discord](https://discord.com/channels/678763474494423051/841927329265090590/905512345881694250).

We need to implement a way to show a diff of the coverage of the test262 on each PR. This can be done via bot or (better) via workflow directly. Via workflow would avoid us in some permission issue, where implementing a bot would require admin rights to enable them.

Ideally, the algorithm should do a diff between the test262 coverage on `main` against the one run the PR.

**Comment by Stupremee** [comment]
If you need inspiration, [boa](https://github.com/boa-dev/boa/blob/main/.github/workflows/test262.yml) has the same integration in their CI. They additionally publish a web version to GitHub Pages, but that isn't required I guess.

**Comment by jonahsnider** [comment]
Might be a good use case for [Danger](https://danger.systems/js/). React uses it to automate their bundle size diffs ([their config](https://github.com/facebook/react/blob/main/dangerfile.js), [example PR comment](https://github.com/facebook/react/pull/22674#issuecomment-956694730))

**Comment by Boshen** [comment]
This can be closed since we now have the bot and `xtask compare`?
