### ISSUE TITLE
📎 Optimize `cast` codegen for enums with only one variant

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1756]
### Description

We recently changed some logic around how we enums that fallback in other enums.

This change of logic can be optimized even more while checking if an enum has one variant OR more than one variant. 

In case of multiple variants, [we emit this code](https://github.com/rome/tools/blob/main/crates/rslint_parser/src/ast/generated/nodes.rs#L5429-L5435), which is correct.

What we can optimize is that, in case of **one single variant**, like [the linked example](https://github.com/rome/tools/blob/main/crates/rslint_parser/src/ast/generated/nodes.rs#L5404-L5407), the `.clone()` call can be removed because the value gets moved just once, making `.clone` not needed.

Once thing optimization is correctly implemented, we can also remove the [clippy rule](https://github.com/rome/tools/blob/main/crates/rslint_parser/src/ast/generated/nodes.rs#L5).

To generate the new nodes, `cargo xtask syntax` must be run.

**Comment by colinaaa** [comment]
I would like to work on this!
