### ISSUE TITLE
📎 optimize `can_cast` function for codegen

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1757]
### Description

We recently changed how we generate code when we encounter an enum and how the `can_cast` call should be during the code generation.

This function can be optimized.

If the node we are trying auto generate is not an enum, like the [example linked](https://github.com/rome/tools/blob/main/crates/rslint_parser/src/ast/generated/nodes.rs#L5323-L5327), we can optimize the code by generating a `matches!` call. [This is something we did before](https://github.com/rome/tools/blob/4128bb1134cf0eac2ecf8c6b6f9e6df072745b1f/crates/rslint_parser/src/ast/generated/nodes.rs#L4517). 

Instead, if what we are generating is an enum, the code should stay as it is.

The command `cargo xtask syntax` can be used to generate new nodes.

**Comment by mrkldshv** [comment]
I'd like to work on this issue!
