### ISSUE TITLE
📎 Detect overlaping sub-uninos

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#1765]
### Description

#1745 introduced codegen support for unions over sub-unions. For example, we can now write `JsExprOrSpread = JsExpr | JsSpread` in our grammar and the codegen then knows that `JsExprOrSpread` can be any expression or a spread element. 

The goal is to add a check to the codegen to fail if any two sub-unions of a union type are overlapping because it leads to disambiguity. For example, let's assume we have the following definition:

```
JsThisIsAnIssue = JsExprOrFunctionDeclaration | JsExprOrSpread
JsExprOrFunctionDeclaration = JsExpr | JsFunctionDeclaration
JsExprOrSpread = JsExpr | JsSpread
```

The sub-unions `JsExprOrFunctionDeclaration` and `JsExprOrSpread ` are overlapping because both contain `JsExpr`. 

The problem is that it's now unclear if an expression should be wrapped as a `JsExprOrFunctionDeclaration` or `JsExprOrSpread`. 

You can trigger the code gen by running `cargo xtask syntax` in the project root.

**Comment by ematipico** [comment]
We should explain why in this example there's ambiguity. :) 

I mean, I read `JsExprOrFunctionDeclaration` and `JsExprOrSpread` and I don't know where is the overlapping :) I can guess it by their name... because both nodes will contain `Expr`?

**Comment by daud9** [comment]
Need to learn about this coding pls

**Comment by loginn** [comment]
Hey I'd be down to try to work on this :)
