### ISSUE TITLE
📎 Unroll sub-unions in code gen

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#1766]
### Description

#1745 added support for union types over other union types. For example, `PatternOrExpr= Pattern | Expr` is a union that allows for any pattern (sub-union) or expression.

The codegen generates the following code today

https://github.com/rome/tools/blob/32a582a3178a4aa4b343b1708a96b0984f0e4bf6/crates/rslint_parser/src/ast/generated/nodes.rs#L5421-L5436

The problem is that the complexity of the `can_cast` and `cast` methods are linear to the number of sub-unions it contains (it probes to find the right union for the passed in element).

The goal of this task is to "unroll" the sub-unions in the `cast` and `can_ast` implementation. 

```rust
	fn can_cast(kind: SyntaxKind) -> bool {
		match kind {
			SyntaxKind::SinglePattern => true, // from Pattern
			SyntaxKind::RestPattern=> true, 
			//... other kinds from pattern
			SyntaxKind::ExpressionStatement => true,  // from Expr
			SyntaxKind::Literal => true
			// ...other kinds from Expr
			_ => false,
		}
	}
	fn cast(syntax: SyntaxNode) -> Option<Self> {
                let res = match syntax.kind() {
			SyntaxKind::SinglePattern => PatternOrExpr::Patern(Pattern::SinglePattern(SinglePattern { syntax })),
			SyntaxKind::RestPattern=> PatternOrExpr::Patern(Pattern::RestPattern(RestPattern{ syntax })),
                       // ... other kinds from pattern
			SyntaxKind::ExpressionStatement=> PatternOrExpr::Expr(Expr:ExpressionStatement(ExpressionStatement{ syntax })),
			SyntaxKind::LiteralPatternOrExpr::Expr(Expr:Literal(Literal { syntax })),
                       // other kinds from expr
			_ => None
		};
		Some(res)
	}
```

**Comment by ematipico** [comment]
The proposed changes are the changes that I initially made, but I decided to apply a different solution because I thought that what we generated was way different from what was written in the ungrammar file. 

> The problem is that the complexity of the `can_cast` and `cast` methods are linear to the number of sub-unions it contains (it probes to find the right union for the passed in element).

Though, how big is the complexity? Do you think that, in the future, we might have numbers up to 7/8? 

Overall I am not a fun of this change, even though it was my first attempted solution.

```
		match kind {
			SyntaxKind::SinglePattern => true, // from Pattern
			SyntaxKind::RestPattern=> true, 
			//... other kinds from pattern
			SyntaxKind::ExpressionStatement => true,  // from Expr
			SyntaxKind::Literal => true
			// ...other kinds from Expr
			_ => false,
		}

```

- `SyntaxKind::SinglePattern` doesn't exist. Did you mean `SINGLE_PATTERN`? 

```
			SyntaxKind::ExpressionStatement=> PatternOrExpr::Expr(Expr:ExpressionStatement(ExpressionStatement{ syntax })),
```

- We could risk to write something that might be difficult to read. Why not delegating the `cast` to `Expr::cast`? Do you think that keeping a single `match` is better in terms of performance?

**Comment by MichaReiser** [comment]
> The proposed changes are the changes that I initially made, but I decided to apply a different solution because I thought that what we generated was way different from what was written in the ungrammar file.

My understanding was that your initial solution changed the API as well. So instead of having `JsExprOrSpread::Expr` there were only `JsExprOrSpread::Literal`. What I'm suggesting here isn't changing the API. The API remains as is. It's just unrolling the inner match from the `Expr::cast` and `Expr::can_cast` into `JsExprOrSpread`. 

> We could risk to write something that might be difficult to read. Why not delegating the cast to Expr::cast? Do you think that keeping a single match is better in terms of performance?

Yeah, I think so. This is the LLVM IR that Rust generates for the `can_cast` function (optimized build)

```
; <rslint_parser::ast::expr_ext::PatternOrExpr as rslint_parser::ast::AstNode>::can_cast
; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone uwtable willreturn
define zeroext i1 @"_ZN91_$LT$rslint_parser..ast..expr_ext..PatternOrExpr$u20$as$u20$rslint_parser..ast..AstNode$GT$8can_cast17h95495085452cc7a0E"(i16 %kind) unnamed_addr #4 {
start:
; call <rslint_parser::ast::generated::nodes::Expr as rslint_parser::ast::AstNode>::can_cast
  %_2 = tail call fastcc zeroext i1 @"_ZN90_$LT$rslint_parser..ast..generated..nodes..Expr$u20$as$u20$rslint_parser..ast..AstNode$GT$8can_cast17h7c75fa5784e2d6b0E"(i16 %kind)
  br i1 %_2, label %bb3, label %bb2

bb2:                                              ; preds = %start
  switch i16 %kind, label %bb3 [
    i16 212, label %bb2.i
    i16 213, label %bb2.i
    i16 214, label %bb2.i
    i16 215, label %bb2.i
    i16 219, label %bb2.i
    i16 246, label %bb2.i
    i16 328, label %bb2.i
  ]

bb2.i:                                            ; preds = %bb2, %bb2, %bb2, %bb2, %bb2, %bb2, %bb2
  br label %bb3

bb3:                                              ; preds = %bb2.i, %bb2, %start
  %.0 = phi i1 [ true, %start ], [ true, %bb2.i ], [ false, %bb2 ]
  ret i1 %.0
}
```

You can see that it calls into the `Expr` cast function `call <rslint_parser::ast::generated::nodes::Expr as rslint_parser::ast::AstNode>::can_cast` but uses a switch when directly matching on `SyntaxKind`. The `Expr::can_cast` internally then has another switch, so we have a nested jump table.


I don't mind putting this aside until we have some more performance measurements on the impact. I just thought it useful but could be a pre-mature performance optimisation.

**Comment by MichaReiser** [comment]
Closing for now until we have evidence that this is an issue.

**Comment by ematipico** [comment]
> You can see that it calls into the Expr cast function call <rslint_parser::ast::generated::nodes::Expr as rslint_parser::ast::AstNode>::can_cast but uses a switch when directly matching on SyntaxKind. The Expr::can_cast internally then has another switch, so we have a nested jump table.

Yeah it's not the best to see, and I can see why unrolling the enums might make the code more performant. Let's keep it under our radar for a bit and see if we should apply the suggested solution later on.
