### ISSUE TITLE
🐛 <TITLE>Rome reformatted all source files after install and running check --review

### ISSUE THREAD

**Issue by rodcater** [rome/tools#1768]
### Environment information

```bash
Gentoo Linux X86_64
Node.js v14.15.4
npx v7.24.2
```

### What happened?

1. Installed with "npx rome init"
2. Ran with "npx rome check"

Output was an error with about a license file. Output was:
node_modules/utf8-binary-cutter/package.json:18:14 parse/spdxLicense âââââââââââââââââââââââââ

  â Unknown license public

  â
   ¹ The SPDX registry is used to ensure valid and legal licenses. See 
    https://spdx.org/licenses/ for more information.

âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

â Found 1 problem

Ran again with "npx rome check --review"
Same output as above.

After one of these commands all Javascript has been reformatted. This is not what I would expect from a command named "check" or an option named "review".

### Expected result

Source files should NEVER be modified without prompting. Ever.

### Configuration file of your project

```json
config/rome.rjson:
// For configuration documentation see http://romefrontend.dev/#project-configuration
name: "gateway"
root: true

package.json:
{
  name: gateway,
  version: 1.0.0,
  description: Meema database gateway build on Express,
  main: index.js,
  scripts: {
    test: jest,
    start: node gateway.js
  },
  repository: {
    type: git,
    url: .
  },
  author: "",
  license: ISC,
  dependencies: {
    cors: ^2.8.5,
    dayjs: 1.10.7,
    dayjs-twitter: 0.5.0,
    dotenv: 8.2.0,
    express: ^4.17.1,
    express-jwt: 6.1.0,
    helmet: 4.1.1,
    jest: 27.0.6,
    minimist: ^1.2.5,
    mongodb: 3.6.3,
    twing: 5.0.2,
    uuid-random: 1.3.2
  }
}
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Hi @rodcater , thank you for the report. That's the intended behaviour of the command of `check` together with `--review`.

I see why this might create confusion and we might probably change its behaviour. 

At the moment we are rewriting the tool, so the new logic might be applied with the rewrite. At the moment we can't apply a quick fix.
