### ISSUE TITLE
📎 Change test262 to target only two OS's

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1792]
### Description

The new coverage comparison workflow targets two operating systems.

We want to reduce them to two: `windows-latest` and `ubuntu-latest`

**Comment by mrkldshv** [comment]
I'd like to pick it up! And just to confirm, you meant that now this workflow targets three operating systems, right?

**Comment by ematipico** [comment]
Yes, exactly. We would like to remove `macos-latest` from `test262.yml` workflow file

**Comment by mrkldshv** [comment]
Alright, thanks for clarification!
