### ISSUE TITLE
🐛 [Website] Funding statistics are broken

### ISSUE THREAD

**Issue by vasilii-kovalev** [rome/tools#1824]
### Environment information

```bash
OS: Windows 11
Browsers:
* Google Chrome: 96.0.4664.45
* Mozilla Firefox: 94.0.2
```

### What happened?

Funding statistics are broken on the website.
![image](https://user-images.githubusercontent.com/10310491/143530767-091b721c-7bae-45fc-86aa-d432d7f6960d.png)

Response to `/funding` request (I have JavaScript enabled).
![image](https://user-images.githubusercontent.com/10310491/143530877-2ff48735-8748-4d30-ab58-22a34e745e9d.png)

Also, I can see the following error, but not sure if it is related to the issue.
![image](https://user-images.githubusercontent.com/10310491/143530922-ef536808-d8a7-4faa-bc9a-52d1675323f5.png)

### Expected result

The funding statistics are correctly displayed.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

P.S.: not sure if I have written the title and description correctly from the grammar perspective, but I tried :)

**Comment by ematipico** [comment]
@sebmck  you might want to take a look at this

**Comment by ematipico** [comment]
Closing. While it's a bug and it's useful to see the information, we won't accept contributions because Rome is now a company.
