### ISSUE TITLE
🐛 <Bug> Unexpected word workspace in monorepo yarn 3

### ISSUE THREAD

**Issue by harrytran998** [rome/tools#1825]
### Environment information

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 11.6
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 3.1.0 - /usr/local/bin/yarn
    npm: 7.24.2 - ~/Desktop/project/node_modules/.bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.0
  npmPackages:
    typescript: 4.5.2 => 4.5.2 
    rome: 10.0.4-beta
```
</details>

### What happened?

When I run `yarn rome check ` -->

```
 packages/vite-plugin/runtime-env/package.json:1 parse/semver ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ✖ Unexpected word workspace
  > 1 │ {
      │ ^
    2 │   "name": "@techmely/vite-plugin-runtime-env",
    3 │   "author": "Harry Tran <nhattq.coding@gmail.com>",
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✖ Found 1 problem
```

### Expected result

Everything work ok 🍏

Here its the repo: https://github.com/techmely/techmely
Hope your team can take time to look at this <3

### Configuration file of your project

```json
// For configuration documentation see http://romefrontend.dev/#project-configuration
name: "techmely"
root: true
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Thank you for reporting the issue @harrytran998 !

We will take this into account, but we won't be able to fix the issue in the foreseeable future as Rome is being rewritten from scratch at the moment.

I am going to close the issue, but I assure you that the next version of Rome won't have this bug!
