### ISSUE TITLE
📎 Gracefully remove TS parsing from JS parsing

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1835]
### Description

Myself and @MichaReiser had a chat this afternoon and we agreed that, for now, we should comment/remove all the TS parsing that we have inside a normal JS parsing until we consolidate the a way to parse super languages in a good way.

For example here https://github.com/rome/tools/blob/main/crates/rslint_parser/src/syntax/stmt.rs#L180-L187 we would like to commented it out and avoid the parsing of TS, as it's not needed and it would not create issue.

**Comment by MichaReiser** [comment]
I think we can keep the TS parsing in place as it is for now.
