### ISSUE TITLE
🐛 Incorrect parsing of JsBinaryExpression `>>` and `>>>`

### ISSUE THREAD

**Issue by Boshen** [rome/tools#1842]
### Environment information

```bash
rustc 1.56.1
commit b716a98
```

### What happened?

parsing 
```
a >> b
```
yields
```
0: JS_BINARY_EXPRESSION@0..7
		0: JS_REFERENCE_IDENTIFIER_EXPRESSION@0..2
			0: IDENT@0..2 "a" [] [Whitespace(" ")]
		1: SHR@2..4 ">>" [] []
		2: JS_REFERENCE_IDENTIFIER_EXPRESSION@4..7
			0: IDENT@4..7 ">> " [] []
```

### Expected result

The second IDENT should be `b`, not `>>`

Same applies to `>>>`.
All other binary operators are fine.
The bug is some where inside [`binary_or_logical_expression_recursive`](https://github.com/rome/tools/blob/main/crates/rslint_parser/src/syntax/expr.rs#L251)? or something about `consume_multiple_tokens`

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Boshen** [comment]
I was implementing todos inside the formatter and I found this bug. 
I haven't started learning the parser API yet, but I can tackle this later if no one wants to give this a try.

**Comment by MichaReiser** [comment]
@xunilrj it seems that this is a problem with the lossless tree sink, specifically with `consume_multiple_tokens`. `consume_multiple_tokens` is called when the parser groups multiple tokens together into a single token (the lexer returns two `>` tokens, we only want one in the parsed result). 

I also get the impression that `consume_multiple_tokens` isn't handling trivia yet?

**Comment by MichaReiser** [comment]
> I was implementing todos inside the formatter and I found this bug. I haven't started learning the parser API yet, but I can tackle this later if no one wants to give this a try.

Oh sorry. I only just saw this comment. It wasn't my intention to prevent you from investigating it. Sorry, I got a bit excited to fix this ASAP.
