### ISSUE TITLE
📎 Coverage Report: Compare results for each tests

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#1844]
### Description

I published #1839 as a draft and was surprised to see that I didn't break a single coverage test. I found that super suspicious and decided to run the `coverage` locally on `main` and on my branch and then diff the tests after sorting them... 

And indeed, I broke 5 tests, but also fixed 5 tests... So it theoretically is a net-zero change but it still would have introduced new regressions. 

The overall comparison is great but I do believe that the "diff" column can give a false impression of safety.
That's why I think we should change our comparison script to report the following numbers (and ideally, test names as well)

* Number of and names of the tests that are *passing* on `main` but are *failing* or *panicking* on the feature branch.
* Number of and names of the tests that are *failing* or *panicking* on main but are *passing* on the feature branch. 

We should be able to get these numbers by iterating over all the tests, mapping them with the test results from the other branch and then marking them as:

* `Regression`: passed on `main`, failing or panicking on the feature branch (bad)
* `Fixed`: panicked or failed on `main`, passing on the feature branch (good)
* `FailedToPanic`: failed on `main`, panicking on the feature branch (kind of bad)
* `PanicToFailed`: panicked on `main`, failing on the feature branch (kind of good?)
* `New`: Newly added tests
* `Removed`: Removed tests

**Comment by Boshen** [comment]
To make this work, we can commit in all the failed tests to a file, and then diff this file?

**Comment by ematipico** [comment]
This should be relatively easy: https://github.com/rome/tools/blob/main/xtask/src/compare/results.rs#L248-L272

**Comment by Boshen** [comment]
I'll work on this.

**Comment by MichaReiser** [comment]
Thank you again @Boshen for working on this. Super excited about the new detail lists with beautiful icons :)
