### ISSUE TITLE
🐛 Parser: Broken AST lookup for `JsComputedMemberAssignment`

### ISSUE THREAD

**Issue by Boshen** [rome/tools#1863]
### Environment information

```bash
main branch
```

### What happened?

While implementing the formatter for `JsComputedMemberAssignment`,

`a[b] = c[d]` will give you `a[a] = c[d]`

#### Exploration

given our ungram:
```
// a['b'] = a[expr] = "test"
// ^^^^^^   ^^^^^^^
JsComputedMemberAssignment =
	object: JsAnyExpression
	'['
	member: JsAnyExpression
	']'
```

`object` and `member` will end up with the same node as `object`,
```rust
impl JsComputedMemberAssignment {
	pub fn object(&self) -> SyntaxResult<JsAnyExpression> { support::required_node(&self.syntax) }
	pub fn member(&self) -> SyntaxResult<JsAnyExpression> { support::required_node(&self.syntax) }
}
```

because required_node just looks for the first `JsAnyExpression` it encounters
```rust
	pub(super) fn node<N: AstNode>(parent: &SyntaxNode) -> Option<N> {
		parent.children().find_map(N::cast)
	}

	pub(super) fn required_node<N: AstNode>(parent: &SyntaxNode) -> SyntaxResult<N> {
		node(parent).ok_or_else(|| SyntaxError::MissingRequiredChild(parent.clone()))
	}
```

### Expected result

`member` gives the correct node.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
This is a bug in the `AstFacade`. We need to manually override `member`. I'll have a PR in a few minutes
