### ISSUE TITLE
📎 Enable all test262 tests for parser coverage

### ISSUE THREAD

**Issue by Boshen** [rome/tools#1891]
### Description

@xunilrj pointed out in [discord](https://discord.com/channels/678763474494423051/678763474930761739/922602033406685204) that our coverage runs only 17608 tests (out of 40000+). 

We can make it cover more by filtering out [negative tests](https://github.com/tc39/test262/blob/main/INTERPRETING.md#negative) instead of the ones that [do not have a feature](https://github.com/rome/tools/blob/main/xtask/src/coverage/files.rs#L131)
> If a test configured with the negative attribute completes without throwing an exception, or if the name of the thrown exception's constructor does not match the specified constructor name, or if the error occurs at a phase that differs from the indicated phase, the test must be interpreted as "failing."

Changing to `.filter(|file| file.meta.negative.is_none())` gives us
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   40790   │ 40237  │  535   │   18   │  98.64   │
└───────────┴────────┴────────┴────────┴──────────┘
```

We can also add negative tests `.filter(|file| file.meta.negative.is_some())`, where it gives us 
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   4218    │  2531  │  1651  │   36   │  60.00   │
└───────────┴────────┴────────┴────────┴──────────┘
```

Note1: we need to filter out module tests
>  Test262 includes tests for ECMAScript 2015 module code, denoted by the "module" metadata flag. Files bearing a name which includes the sequence _FIXTURE MUST NOT be interpreted as standalone tests; they are intended to be referenced by test files.

Note2: our coverage tests run super slow at the moment, which should be looked into.

**Comment by MichaReiser** [comment]
That would be a nice improvement. Are you interested in working on this?

> We can also add negative tests .filter(|file| file.meta.negative.is_some()), where it gives us

We're only interested in negative tests with the `phase` `parse`. `resolution` will be interested when we work on the bundler (or semantic analysis) but isn't something the parser is concerned about. The `phase` `runtime` is probably only relevant for javascript runtimes.

**Comment by Boshen** [comment]
I'll work on this

**Comment by xunilrj** [comment]
> You can run them in release mode, which may help a bit (at the cost of compile-time)

I came here to suggest that... but when running on our CI.

**Comment by Boshen** [comment]
It seems we can enable all tests. Here's the whole dump (warning - large text file): https://gist.githubusercontent.com/Boshen/647c7d85b185fab78ea7bfb49a718293/raw/4d1301f8b2a7ad25f6bf494f35362a586be30785/gistfile1.txt

> We're only interested in negative tests with the phase parse

It's already handling this case:
https://github.com/rome/tools/blob/main/xtask/src/coverage/mod.rs#L234-L237

**Comment by Boshen** [comment]
Enabling all tests gives us
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   45008   │ 42768  │  2186  │   54   │  95.02   │
└───────────┴────────┴────────┴────────┴──────────┘
```

Shall we enable them all? Or exclude some of the features? https://github.com/tc39/test262/blob/main/features.txt

**Comment by MichaReiser** [comment]
I would enable all of them and we can exclude individual features if we work on fixing the issues and then decide that we don't want to support the feature at the time being. Or are you already aware of some features?
