### ISSUE TITLE
📎 Clean up LSP formatting handler and support FormattingOptions

### ISSUE THREAD

**Issue by yassere** [rome/tools#2003]
### Description

Currently, the LSP server supports `textDocument/formatting` requests but uses the default option `IndentStyle::Tab`

LSP clients can send a `FormattingOptions` which includes:
```
	/**
	 * Size of a tab in spaces.
	 */
	tabSize: uinteger;

	/**
	 * Prefer spaces over tabs.
	 */
	insertSpaces: boolean;
```
The LSP server should respect those options when formatting. Also, the `rome_lsp` formatting handler should be cleaned up.

**Comment by ematipico** [comment]
I will send a PR for the transformation. I will leave the cleanup to @yassere as I don't know what kind of work is involved

**Comment by ematipico** [comment]
PR has been merged and it works as expected. Only the cleanup is left.
