### ISSUE TITLE
CI: Add TypeScript coverage 

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2010]
#1990 added support for running the TypeScript spec tests against our parser.

The goal is to add the TypeScript spec tests to our CI coverage job. 

One option would be that `cargo coverage`  runs the coverage for all languages but prints the summary and failing tests for each language.

**Comment by Boshen** [comment]
The default coverage command prints a lot of messages: `Test 'xxx' panicked while parsing` by default, can we remove it from CI?

We can either put the behavior behind a `detailed` flag, or detect CI env.
