### ISSUE TITLE
Re-Lexing of tokens [Must]

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2035]
### Description

Lexing regular expressions and template literals follow different rules than lexing other grammars

* RegExp: Multiple otherwise valid punctuation tokens must be grouped together into a single token 
* RegExp: Requires tracking if a `/` is the division operator or the start of a regular expression
* Template Literals: Tagged template literals behave slightly different than normal template literals. 
* Backticks outside of an expression context shouldn't be parsed as template literals 

The way our parser currently handles this is that it tracks if it's in a position where an expression is allowed:

https://github.com/rome/tools/blob/64222927caa9705c5ce8762fc14b66f0436232a3/crates/rslint_lexer/src/state.rs#L33-L129

This logic is fragile and changes are hard to test and verify. Furthermore, it duplicates the parser logic that already tracks in which position expressions, or even more specific, regular expressions are valid. 

TypeScript, Babel, and Rome Classic, and SWC use a different approach. They have ways to signal to the lexer that it should re-lex the current token in a particular context:

https://github.com/microsoft/TypeScript/blob/b8f8fd7a3eda6573129f891e76444a6cb4857f68/src/compiler/scanner.ts#L2138-L2189

An example of the TypeScript parser. `rescanSlash` rescans the slash token assuming that it's a regular expression. 

Being able to re-lex from the current token may also become valuable when we start embedding different languages. Let's say we have an HTML file with script tags. We may want to parse the content of the `script` tag as JavaScript by re-lexing the current token as JavaScript (until we find a closing script tag). 

That's why I believe we should restructure our parser to lazily consume the tokens from the lexer. However, this will have implications on how we do look ahead today. 

## Tasks 

* [ ] Incremental lexing #2219 
* [ ] Replace `bump_multiple` with `re_lex` that correctly respects whitespace between tokens #2227

**Comment by MichaReiser** [comment]
@xunilrj you looked into this before. What were your findings?
@NicholasLYang you seemed to be familiar with this kind of problem. Are you aware of alternative solutions?

**Comment by MichaReiser** [comment]
The current approach is based on the work described in https://users.soe.ucsc.edu/~cormac/papers/dls14a.pdf

**Comment by MichaReiser** [comment]
It may be possible to correctly implement the `NonNullAssertionExpression` in TypeScript by recognizing the current context as an expression context only if an expression was allowed by the previous token. 

While this is working for correct problems, it fails to stay in sync if the parser performs error recovery: 

```
0#!/bin/deno
```

A potential recovery for the above invalid syntax is:

* Parse `0` as an expression statement 
* Skip `#` (by parsing it into an `UnknownStatement`)
* Parse `!/bin/deno` as an expression statement with the tokens: `BANG` (!), REGEX

However, the lexer will parse the `/bin/deno` as `SLASH`, `IDENT, `SLASH`, `IDENT` because no expression is allowed after a `0#` sequence (`#` isn't a valid start of an expression). This problem isn't specific to the bang operator. We can change the example to `0#/regex/` and the lexer will fail to parse the `/regex/` as a regex token because `#` isn't a valid start of an expression.

**Comment by xunilrj** [comment]
I think we need to make ```TokenSource``` lazy. With the most complex parts being:

1 - We need to store the ```Token``` iterator statically. dynamic dispatch here will drain performance for no gain;
2 - ```rewind``` will be super complicated, especially because our lexer has state. ```Parser::checkpoint``` would need to checkpoint everything;
3 - ```lookahead``` can be done naively (always lex everything, worst part would be lex trivia everytime); ou we can have a small buffer using ```VecDeque```;

I think it is worthy. Specially because we may be able to remove the state inside the lexer and as you said reuse this token source for embedded language.

I am thinkinh something like

```rust
pub struct TokenSource<'t> {
    source: &'t str,
    pub raw_tokens: &'t [rslint_lexer::Token],
    cur: usize,
}
```

1 -

**Comment by MichaReiser** [comment]
Thanks @xunilrj for taking the time to look into this. 

> 1 - We need to store the Token iterator statically. dynamic dispatch here will drain performance for no gain;

I'm not that familiar with `TokenSource` + `Lexer` but what would be useful in regards of re-using our framework for other languages is if it's possible to re-use the trivia logic from the `TokenSource` across multiple lexers. But there may be other ways to solve this. 



 > 2 - rewind will be super complicated, especially because our lexer has state. Parser::checkpoint would need to checkpoint everything;

We should be able to simplify our lexer state significantly: 
* `prev`: Only used to compute `expr_allowed`
* `expr_allowed`: Used to determine if a `/` is a binary expression or regex. This won't be needed anymore if the parser can trigger a re-lexing 
* `had_linebreak`: Only used to compute `expr_allowed`
* `ctx`: Only used to compute `expr_allowed` and if the lexer is in a template. Again, the second shouldn't be needed if the parser can tell the lexer that it is now inside of a template. 

I don't know about `after_newline` but that shouldn't be too expensive to track.

> lookahead can be done naively (always lex everything, worst part would be lex trivia everytime); ou we can have a small buffer using VecDeque;

I like the idea of a small vec dequeue that maybe holds on to a few tokens because our parser often does lookahead. But I would probably start without it and then add it if needed. 


One thing that's unclear to me still is how we plan to handle Diagnostics that flow from the Lexer to the Parser .

In your example: Is `tokens` the `Lexer`? Or is it a merge of `Lexer` and `TokenSource`?

**Comment by xunilrj** [comment]
> In your example: Is tokens the Lexer? Or is it a merge of Lexer and TokenSource?

hum... I think ```Tokens<'t>``` and ```TokenSource<'t>``` could be inside the lexer.

**Comment by MichaReiser** [comment]
TS tests that are blocked by not having re-lexing:

* `escapedIdentifiers 
* `RGI_Emoji_Flag_Sequence`
* `Emoji_Keycap_Sequence`
* `castExpressionParentheses`
