### ISSUE TITLE
📎 Utilities to access the value of literals

### ISSUE THREAD

**Issue by leops** [rome/tools#2053]
### Description

Currently the syntax tree only allows access to the textual value of nodes and tokens. For a variety of formatting and analysis purpose it might be useful to access the string value of a string literal (with the escape sequences interpreted) or mathematical value of a numeric literal.

**Comment by ematipico** [comment]
Should we track this in #1996  ?

**Comment by leops** [comment]
It's not directly related to the formatter, at least until we decide to rewrite literals. This is more of a general purpose, nice-to-have utility but is obviously very low priority until we have an actual use case for it.

**Comment by Conaclos** [comment]
This could be of use for #4108
