### ISSUE TITLE
Parse TS `namespace` / `module` syntax

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2090]
Parsing of TS `namespace` and `module` syntax ([documentation](https://www.typescriptlang.org/docs/handbook/namespaces.html))

```ts
module test {}

declare module "shorthand";

// creates nested namespaces
declare module test.b.c.d {}

namespace b {}
declare namespace abcd.c.d.e {}


// TsShorthandDeclareModuleStatement 'declare' 'module' id: string ';'?
// TsModuleStatement = 'declare'? 'module' id: (string | TsIdentifierBinding) body: TsAnyModuleBody
// TsAnyModuleBody = JsBlock | .id
// TsNamespaceStatement = 'declare'? namespace  TsIdentifierBinding body: JsBlock
```

**Comment by MichaReiser** [comment]
I'm currently planning to go with the following grammar: 

```
// TsShorthandModuleDeclaration = 'module' id: string ';'?
declare module "test";

// TsModuleDeclaration = 'module' name: TsAnyModuleName body: JsBlock
declare module test {}
declare module a.b.c.d {}
declare module "test" {}
module test {}
module a.b.c.d {}
module "test" {} // Not allowed

// TsNamespaceDeclaration = 'namespace' name: TsAnyName body: JsBlock
namespace test {}
namespace a.b.c.d {}
declare namespace test {}
declare namespace a.b.c.d {}

// TsAnyModuleName = string | TsIdentifierBinding | TsQualifiedName

// TsDeclareStatement = 'declare' declaration: JsAnyDeclaration

// JsAnyDeclaration = JsFunctionDeclaration | JsClassDeclaration | JsVariableDeclaration | TsEnumDeclaration | TsDeclareFunctionDeclaration | TsTypeAliasDeclaration | TsInterfaceDeclaration 
```

**Comment by MichaReiser** [comment]
> [This is how TS represents](https://ts-ast-viewer.com/#code/HYQwtgpgzgDiDGEAEIB0AjV9UBMkG8BfIA):
> 
> ```ts
> declare module a.b.c.d {}
> ```

Jep. I looked at it and find it weird. Making this work with a CST would require another node because the inner node now has a `.` token but misses the `module` token. 

What I describe is the same as how roslyn represents `namespace System.Console`.

**Comment by ematipico** [comment]
> > [This is how TS represents](https://ts-ast-viewer.com/#code/HYQwtgpgzgDiDGEAEIB0AjV9UBMkG8BfIA):
> > ```ts
> > declare module a.b.c.d {}
> > ```
> 
> Jep. I looked at it and I haven't figured out their reasoning for representing it that way. I assume it is to avoid another last node for the name? Making this work with a CST would require another node because the inner node now has a `.` token but misses the `module` token.
> 
> What I describe is the same as how roslyn represents `namespace System.Console`.

I think they represent it in this way because it's  the same AST applied to `JsStaticMemberExpression`, e.g. `some.then().catch()`. They have a similar syntax. So representing the grammar in the same way, sounds familiar. And agree with that.

Also, we would beneficent from this kind of grammar in the formatter too.

**Comment by MichaReiser** [comment]
Using a `TsQualifiedModuleName` gives you the same structure as `JsStaticMemberExpression`. The left is an identifier or another "nested" module name. The right is a `JsName`. 

We would need to use two different nodes anyway because we must attach the `.` token somewhere (and not require `module` in that case). We could implement this with a `TsNestedModuleDeclaration = '.' name: JsName body: TsModuleBlock` but I don't see a significant benefit over having a `TsQualifiedModuleName = left: TsAnyModuleName '.' right: JsName`.

**Comment by ematipico** [comment]
I am not sure having `JsBlock`  as body of the module/namespace is correct. Inside `namespace` we can use `export`/`import`, and `JsBlockStatement` uses `JsAnyStatement` as its body; `JsAnyStatement` doesn't have `import`/`export` syntax. 

Probably we would need to create a new `TsModuleBlock`?
