### ISSUE TITLE
🐛 Incorrect parsing of `TsNamedTupleTypeElement`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2135]
### Environment information

```bash
latest on main
```

### What happened?

While formatting `TsNamedTupleTypeElement`, I found that the following snippet, which throws an error in typescript playground, is valid for our parser:

```ts
type TupleE = [ ...name?: string[] ]
```

TS parser says: `A tuple member cannot be both optional and rest.(5085)`

These are valid instead:

```ts
type TupleC = [ ...name: string[] ]
type TupleD = [ name?: string[] ]
```

### Expected result

I would expect that parser would throw a SyntaxError

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by xunilrj** [comment]
I will look into it.

**Comment by MichaReiser** [comment]
Thanks @2154 for reporting this bug.

Our main focus, for the time being, is parsing valid TS/JS programs correctly. Emitting the diagnostics for invalid programs is something that we want to tackle later (potentially for 0.2?)

**Comment by xunilrj** [comment]
Fixed at https://github.com/rome/tools/pull/2155
