### ISSUE TITLE
☂️ Doesn't seem to support JSX?

### ISSUE THREAD

**Issue by yisar** [rome/tools#2143]
### Description

Doesn't seem to support JSX?

**Comment by IWANABETHATGUY** [comment]
Not support by now, but rome team has  focused on Typescript parser, It would be supported in the near future, you could tracked it here  `https://github.com/rome/tools/issues/2113#:~:text=arrowFunctionWithObjectLiteralBody6-,JSX,-doubleUnderscoreReactNamespace`

**Comment by xunilrj** [comment]
Hey, thanks for the input.
We will be tackling JSX at https://github.com/rome/tools/issues/2153
