### ISSUE TITLE
🐛 Spread elements are not allowed in call expressions

### ISSUE THREAD

**Issue by leops** [rome/tools#2169]
### Environment information

```bash
N/A
```

### What happened?

The expression `a(...b)` is parsed as an unknown expression with no diagnostics

### Expected result

The current grammar only allow for a list of `JsAnyExpression` in function calls arguments, I'm guessing it should have an optional JsSpread (or an entirely new node) after the expressions list

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
[Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&indentWidth=2&typescript=false&jsx=false#YSguLi5iKQ==)
