### ISSUE TITLE
📎 TS: Decorator Parsing

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2174]
### Description

TypeScript supports [decorators](https://www.typescriptlang.org/docs/handbook/decorators.html) (`@<ident>`) in various places. 

It isn't Rome's goal to support transforms or analyzers that use TypeScript decorators (for now). However, Rome's parser should be able to "parse over" any decorators present in the source code without emitting any errors.

**Comment by jpike88** [comment]
I'm an Angular developer, so this is a non-starter for me. Considering how prevalent Angular is, it would be a good idea to allow people like myself to look into this at some point

**Comment by MichaReiser** [comment]
Hy @jpike88 Thanks for your feedback.

We are aware of the importance of decorators in the angular (and TypeScript) ecosystem and we do plan to have full support for decorators once the JS decorator proposal reaches consensus which might happen soon. This is the main reason why we're holding back because we want to avoid implementing TypeScript's experimental decorators only then to have to remove it a few months later. It's also yet unclear how TypeScript plans to support decorators in the future and we must ensure that Rome's parser's compatible with whatever decision the TypeScript team makes.

**Comment by jpike88** [comment]
That to me seems like an odd position to take:

- There's no way TypeScript will remove decorators any time soon (most definitely not in a few months, not to mention years), massive frameworks like Angular 2 rely closely on both TypeScript (which in turn benefits heavily from it being a requirement for using Angular), and the use of decorators as a key aspect of this. 
- Other frameworks such as Vue, NestJS have decorators as a key component used in their ecosystems. 
- Google and Microsoft themselves have demonstrably created products and libraries that incorporate decorators into them

I'm sure the TypeScript team themselves would agree with me is saying that relying purely on the 'experimental' TC39 status when deciding to implement something would not be taking into account its prevalence in the JS/TS community.

In the end it means I and potentially millions of others will not be able to utilise Rome in its current state. Just my fifty cents.

**Comment by MichaReiser** [comment]
> In the end it means I and potentially millions of others will not be able to utilise Rome in its current state. Just my fifty cents.

We're aware of that but there are also many other limitations to Rome today that we believe are more important to address right now. 

The TC39 proposal is compatible in many ways with the proposal made from TS except that decorators aren't allowed in front of constructor parameters and transforming decorators doesn't depend on type information. That's why a TC39 implementation is likely going to be enough to support many frameworks (unfortunately, not angular).
