### ISSUE TITLE
format of `JsxElement`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2275]

**Comment by darrow-olykos** [comment]
RustPhilly will be Mob Programming on this issue on this on Monday, March 28th starting at 7:00pm EST! (RSVP to our Mob Programming events here: https://www.meetup.com/RustPhilly/)

We already have some working notes detailing how `rome_formatter` rules get executed and have a basic "happy path" implemented for `<a></a>` in our feature branch (The simplest AST to format for a JSX expression is one that needs no formatting). So if you're new to contributing to Rome, then we can help you help us help Rome (lol)!

If anyone thinks of example test cases that we can target, for example:
```rust
// before
<Foo>
    {myvar}
    </Foo>
    
// after
<Foo>{myvar}</Foo>
```
Then please feel free to recommend test cases on this thread

Link to our discord server is in the meetup linked above.

**Comment by darrow-olykos** [comment]
Learning notes: https://github.com/RustPhilly/documents/blob/main/knowledge/ROME.md

**Comment by darrow-olykos** [comment]
```rust
 // input
 <Foo>
     text
    </Foo>

// expected output
List [
    // TODO: define what this should look like
]
```

**Comment by darrow-olykos** [comment]
2.
For this, we want to find formatter helpers or utils that more or less achieve this behavior:
  - [ ] Let's make sure a `Group(Hard)` exists around both the opening and closing Jsx Element tags, so that they remain on their own lines.
  - [ ] Let's leave the JsxChild content (which in our simple case is just JsxText) alone until we determine how we're normalizing whitespace and returns in that text
  - [ ] Let's group jsx opening tag, child content, and jsx closing tag in a `Group` to see if this is enough to get the formatted output to break onto their own lines

**Comment by estaub** [comment]
The case above: 

>
> // before
> ```jsx
> <Foo>
>     text
>     </Foo>
> ```
> // after
> ```jsx
> <Foo>text</Foo>
> ```
> 

is incorrect, in that it entirely removes whitespace.  White space in html may be shrunk or expanded, but not _entirely_ added or removed.  In this example, imagine that `<Foo>` translates to `<b>`, and that there is adjacent text in the unknown surrounding context, like

```jsx
xxx<Foo>           text       </Foo>yyy
```

Space removal would change the output from "xxx **text** yyy" to "xxx**text**yyy".

**Comment by estaub** [comment]
Other input:

- [a draft JSX spec from Facebook](https://facebook.github.io/jsx/)
- [Prettier "needed" prettier-ignore directives to work in JSX](https://github.com/prettier/prettier/issues/2467); it might be good to know why.

**Comment by karl** [comment]
> The case above:
> 
> > // before
> > ```js
> > <Foo>
> >     text
> >     </Foo>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > // after
> > ```js
> > <Foo>text</Foo>
> > ```
> 
> is incorrect, in that it entirely removes whitespace. White space in html may be shrunk or expanded, but not _entirely_ added or removed.

Just to clarify, in HTML that white space cannot be removed, but in JSX it can.

See Prettier’s existing behaviour here:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXnQCgDwBiEEAfADpTpXryowXXp4D0RpAlCADQgQAOMAJbQAzslABDAE5SIAdwAK0hGJQSANnIkBPMTwBGUiWADWcGAGUJAWzgAZQVDjIAZhpFwDR0+Yt9jjgDmyDBSAK6eIHDW+nAAJnHxdhJQgWESgXBEUtYSMEKpyCASYTAQ3CAAFjDW6gDqlYLwIv5gcBYqTYIAbk3aRWAieiCOHlIwCkaBua7ukQBWIqgWQepwAIphEPCz6h48-lJjRfoSseoVfFKOMHWCcTCVyAAcAAwHsh51RnxFV3BjbrOHgARy28Em-FUxREAFonPF4hUpHAwYIUZMMjMkG49pEPNZBCFwvjVhtwc4cXMeDAzncHk8kAAmGlGQTqIIAYQg1mxUREAFYKmEPAAVM6qXH7EDdCIASSgiVgFjA1wEAEFFRYYNo1rsPABfA1AA

JSX and HTML have different white space rules which can trip people up when first working with it.

**Comment by karl** [comment]
The “Handling JSX white space” section in the blog post I wrote when I improved the JSX text handling for Prettier might useful:

https://medium.com/geckoboard-under-the-hood/adding-a-new-layout-strategy-to-prettier-8d33084c0f99

**Comment by darrow-olykos** [comment]
> JSX and HTML have different white space rules which can trip people up when first working with it.

@karl thanks so much!

...so...let me get this straight...

JSX syntax that is also _technically_ syntactically valid HTML syntax, does not represent the _same_ HTML syntax as the HTML syntax that it technically _represents_... Wow.

Can something like this be traced to the JSX Spec itself?

**Comment by karl** [comment]
> JSX syntax that is also technically syntactically valid HTML syntax

I don't think that this is even true 😂

Whereas TypeScript is a strict superset of JavaScript, JSX is NOT a superset of HTML. The semantics of JSX are different to those of HTML, so taking existing HTML and converting it to JSX generally always requires changes. 

It is also useful to remember that JSX compiles to JavaScript, not to HTML. While often that JavaScript ends up producing HTML, it doesn't always (for example react-three-fiber renders to three.js not to HTML https://github.com/pmndrs/react-three-fiber).

When I was working on the JSX formatting for Prettier I didn't find a spec that detailed the JSX to JavaScript coversion.

I tended to use the the Babel REPL for checking how JSX would be transformed in practice. For example:
https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDAFAKBjAPAEwJYBuAfBpjFAKYAeUpWA9PsWgJQDcaaoksARktiZFKNBkI7doMYANyEi5arDHyJ4KTllCA3gHIYugL4ioeg4ZXEOXdbApb52CAAc4YYUoYu3Cy0TU8MABmAuiYcsQwpOHe7iZeru5R4YzyrGxAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.17.9&externalPlugins=&assumptions=%7B%7D

**Comment by karl** [comment]
The Prettier snapshot tests for JSX text formatting should be really useful here:

https://github.com/prettier/prettier/blob/main/tests/format/jsx/text-wrap/__snapshots__/jsfmt.spec.js.snap

In general you should be able to follow what Prettier does.

Although you might not need to follow Prettier's hard coded support for Facebook `<fbt>` translation tags:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXnQCgDwAmAlgG4B8AOlOuoaWQGJEBOAzjOgO5EwAW6AWwjM46dgFcAZpPRFqPdAEMoBMRAGihIpSrUbBw0ctWt1mw3gD0xcgBo65AMpxIu7nwPaJ02fI7G9c20A030tI11QoLgrG0ooWPoASipUqAxsfEkAIxh4mjwcmCQAB0VmRQFGFnYuHn5wsRgpGTlZf0izTwiTLsaQvotLItLyyrJ7EbKKqudXVXcGwyaW33adXrDlga3gzt2Y4dzRmfirIrIUqBBbEAgSmCJoVmRQcuYITgAFcoQXlEUABtOIoAJ4vW7ZCpgADWcBgjkqcAAMnI4MhJEDWHBIdC4QiymA5ABzZAwZjiHEgOACbJwAgEenI5TE8SKYlwBjCASKGCPKCkgHiGAQG4gXgwASAgDqvB4cFYhLgzigrB4pB4oOQ4FYEJAcmxzBgXwqxJ5GKxVIAVqxUI4SYC4ABFcQQeAWwHY27TQ3a7KKOmAsUlZhyGDSogEPjIAAcAAZvR9sdKKiVtSGFXBmCR0bcAI6u+Am+7-ECKVgAWigcHp9LFIgLLDgJvZ5qQmM9VOxAiIZIpXYdzsL6PbltuMADEajvGQACZxxUiICSQBhdRt6msACsYvE2IAKgH-h2vSASJSAJIqBAIsChh4AQRUjhgoMdHuxAF9P0A

Support for `<fbt>` tags was added to Prettier to help get it adopted at Facebook:
https://github.com/prettier/prettier/issues/1581#issuecomment-300975032

**Comment by kungpaogao** [comment]
is there anywhere to view the current progress/code for this issue?

**Comment by darrow-olykos** [comment]
Hey @kungpaogao see the PR thread associated with: https://github.com/rome/tools/issues/2359. These issues are intertwined. If you're looking for more context/background on Rome codebase, besides Rome's own docs, here are some scratch notes: https://github.com/RustPhilly/documents/blob/main/knowledge/ROME.md
