### ISSUE TITLE
☂️ CLI

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2316]
## Description

The CLI is in an alpha state and needs some features/bug fixes

## Tasks

- [x] #2492
- [ ] Log level config
- [x] Run formatting without writing to files

**Comment by ematipico** [comment]
About the third checkbox, it already does that: https://rome.tools/#use-the-formatter-with-the-cli

**Comment by NicholasLYang** [comment]
With CI mode? What if I want to run the formatter and not exit if the files would get modified?

**Comment by MichaReiser** [comment]
> With CI mode? What if I want to run the formatter and not exit if the files would get modified?

What do you mean by not exiting? Do you mean that the program shouldn't end with a non zero exit code?

**Comment by ematipico** [comment]
> With CI mode? What if I want to run the formatter and not exit if the files would get modified?

Then the description of the requirement would  require more details, so we can understand what exactly we need.

**Comment by ematipico** [comment]
Closing, as the log level it's not a priority and we haven't a meaty document with features that we need for the CLI.

Feel free to open it once we have a project in mind
