### ISSUE TITLE
📎 Toggle SourceType in Rome Playground

### ISSUE THREAD

**Issue by Boshen** [rome/tools#2338]
### Description

For quickly testing out syntax errors.

Example from AST Explorer:
 <img height="200" src="https://user-images.githubusercontent.com/1430279/161208394-7bc22662-4592-4d1d-a5d9-c63f0ddbbfa2.png" />

**Comment by ematipico** [comment]
@NicholasLYang this is something we can add  right?

**Comment by NicholasLYang** [comment]
As in script vs module? Sure.
