### ISSUE TITLE
JSON Parser

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2351]
### Description

We are going to use this issue to track the various work around JSON. We don't plan, for the time being, to support super languages, like JSONC, which is the format used by TypeScript.

- [x] create a `json.ungram` file where we will slowly implement new grammars
- [x] create a `rome_json_syntax` crate, where we will have all things related to the JSON syntax, generated code too
- [x] expand the codegen of the grammar to include JSON too
- [ ] evaluate how to implement the parser, lexer, etc. (it will require a separate discussion)

**Comment by loginn** [comment]
Hey so I wrote a Json parser in rust not too long ago so I could maybe look into some of that if you'd like ?
