### ISSUE TITLE
🐛 Parsing error in Decorators with certain closure arguments

### ISSUE THREAD

**Issue by avandesa** [rome/tools#2358]
### Environment information

```bash
MacBook Pro (Intel i7), macOS Catalina 10.15.7, installed in project w/ yarn
```

### What happened?

I ran `rome format` and encountered several errors from certain closure arguments to decorator factories. An example:

```typescript
function Decorator(_arg: any): any {}

export class Foo {
  @Decorator((val) => val)
  badField!: number
  
  @Decorator(val => val)
  okField!: number
  
  @Decorator((val: any) => val)
  otherOkField!: number

  foo(@Decorator((val) => val) _badArg: any, @Decorator(val => val) _okArg: any) {}
}

```

This code compiles with no errors in typescript: [ts playground]
But the Rome parser reports syntax errors: [rome playground]

[ts playground]: https://www.typescriptlang.org/play?noImplicitAny=false#code/GYVwdgxgLglg9mABAEQKYTgJwIZSwCgH1tMBzALkWzAE8BKS6mxAbwF8AoD1ADwAcsURBAA22AM7jEAMThxWHRIgACaDDjyZ8+AG7YRdRAF4AfIj0HFiAEbYAJtJioRdgISUwIALbXUmK1aq6Fi4BBbGZhZ0VnAA1o7Obh7evv5KgWohmtoWjLSGpub60UpwUAAWfgDy8U4u7oiePn5cSsBy+EHqoVq6xRFFBoiEtnYAgmR5NAA0KpkaYfoDUcNxExRU+aycnEA
[rome playground]: https://play.rome.tools/?lineWidth=80&indentStyle=space&indentWidth=2&typescript=true&jsx=false&sourceType=module#ZgB1AG4AYwB0AGkAbwBuACAARABlAGMAbwByAGEAdABvAHIAKABfAGEAcgBnADoAIABhAG4AeQApADoAIABhAG4AeQAgAHsAfQAKAAoAZQB4AHAAbwByAHQAIABjAGwAYQBzAHMAIABGAG8AbwAgAHsACgAgACAAQABEAGUAYwBvAHIAYQB0AG8AcgAoACgAdgBhAGwAKQAgAD0APgAgAHYAYQBsACkACgAgACAAYgBhAGQARgBpAGUAbABkACEAOgAgAG4AdQBtAGIAZQByAAoAIAAgAAoAIAAgAEAARABlAGMAbwByAGEAdABvAHIAKAB2AGEAbAAgAD0APgAgAHYAYQBsACkACgAgACAAbwBrAEYAaQBlAGwAZAAhADoAIABuAHUAbQBiAGUAcgAKACAAIAAKACAAIABAAEQAZQBjAG8AcgBhAHQAbwByACgAKAB2AGEAbAA6ACAAYQBuAHkAKQAgAD0APgAgAHYAYQBsACkACgAgACAAbwB0AGgAZQByAE8AawBGAGkAZQBsAGQAIQA6ACAAbgB1AG0AYgBlAHIACgAKACAAIABmAG8AbwAoAEAARABlAGMAbwByAGEAdABvAHIAKAAoAHYAYQBsACkAIAA9AD4AIAB2AGEAbAApACAAXwBiAGEAZABBAHIAZwA6ACAAYQBuAHkALAAgAEAARABlAGMAbwByAGEAdABvAHIAKAB2AGEAbAAgAD0APgAgAHYAYQBsACkAIABfAG8AawBBAHIAZwA6ACAAYQBuAHkAKQAgAHsAfQAKAH0ACgA=

```
error[SyntaxError]: expected `,` but instead found `=>`
  ┌─ main.js:4:20
  │
4 │   @Decorator((val) => val)
  │                    ^^ unexpected

error[SyntaxError]: expected `,` but instead found `=>`
   ┌─ main.js:13:24
   │
13 │   foo(@Decorator((val) => val) _badArg: any, @Decorator(val => val) _okArg: any) {}
   │                        ^^ unexpected

```

The error is triggered in all types of decorators, specifically when a closure argument is passed to a decorator factory whose parameter list is parenthesized and does not contain at least one type annotation. The examples above demonstrate how just adding a type annotation resolves the error, even though the code is valid without it.

As a real-world example, this bug would be a problem for anyone using TypeORM's [`ManyToOne`] decorator or class-transformer's [`Transform`] decorator.

[`ManyToOne`]: https://typeorm.io/many-to-one-one-to-many-relations
[`Transform`]: https://www.npmjs.com/package/class-transformer#advanced-usage

Interestingly, something like this works fine, so this is possibly just an issue with decorators:
```typescript
function foo(_arg: any): any {}
foo((val) => val)
```

### Expected result

Any valid typescript code should not trigger a syntax error. I understand that due to their experimental status, decorators are more or less ignored, but there's apparently edge cases where Rome does attempt to parse decorator factories.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@MichaReiser you might want to have a look at this.

**Comment by avandesa** [comment]
So last night I traced it down to [line 480] in `function.rs`; `p.last()` was returning `L_CURL`. The examples with the type annotation were unambiguously arrow functions, so `Ambiguity::Allowed` was set during this function, meaning that the weird token was ignored. But without the type annotation, the parser wasn't certain that it was an arrow function, so `Ambiguity::Disallowed` was set, making the parser unwind and parse it as an expression.

So this issue with skipping tokens would be what caused `L_CURL` to show up as the last token?

[line 480]: https://github.com/rome/tools/blob/main/crates/rome_js_parser/src/syntax/function.rs#L480

**Comment by MichaReiser** [comment]
> So last night I traced it down to [line 480](https://github.com/rome/tools/blob/main/crates/rome_js_parser/src/syntax/function.rs#L480) in `function.rs`; `p.last()` was returning `L_CURL`. The examples with the type annotation were unambiguously arrow functions, so `Ambiguity::Allowed` was set during this function, meaning that the weird token was ignored. But without the type annotation, the parser wasn't certain that it was an arrow function, so `Ambiguity::Disallowed` was set, making the parser unwind and parse it as an expression.
> 
> So this issue with skipping tokens would be what caused `L_CURL` to show up as the last token?

Yes, this is precisely what happened. See  #2364 for a possible fix.

**Comment by MichaReiser** [comment]
Verified that this now parses correctly [playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&indentWidth=2&typescript=true&jsx=false&sourceType=module#ZgB1AG4AYwB0AGkAbwBuACAARABlAGMAbwByAGEAdABvAHIAKABfAGEAcgBnADoAIABhAG4AeQApADoAIABhAG4AeQAgAHsAfQAKAAoARABlAGMAbwByAGEAdABvAHIAKAAoAHYAYQBsACkAIAA9AD4AIAB2AGEAbAApADsACgAKACAAZQB4AHAAbwByAHQAIABjAGwAYQBzAHMAIABGAG8AbwAgAHsACgAgACAAQABEAGUAYwBvAHIAYQB0AG8AcgAoACgAdgBhAGwAKQAgAD0APgAgAHYAYQBsACkACgAgACAAYgBhAGQARgBpAGUAbABkACEAOgAgAG4AdQBtAGIAZQByAAoAIAAgAAoAIAAgAEAARABlAGMAbwByAGEAdABvAHIAKAB2AGEAbAAgAD0APgAgAHYAYQBsACkACgAgACAAbwBrAEYAaQBlAGwAZAAhADoAIABuAHUAbQBiAGUAcgAKACAAIAAKACAAIABAAEQAZQBjAG8AcgBhAHQAbwByACgAKAB2AGEAbAA6ACAAYQBuAHkAKQAgAD0APgAgAHYAYQBsACkACgAgACAAbwB0AGgAZQByAE8AawBGAGkAZQBsAGQAIQA6ACAAbgB1AG0AYgBlAHIACgAKACAAIABmAG8AbwAoAEAARABlAGMAbwByAGEAdABvAHIAKAAoAHYAYQBsACkAIAA9AD4AIAB2AGEAbAApACAAXwBiAGEAZABBAHIAZwA6ACAAYQBuAHkALAAgAEAARABlAGMAbwByAGEAdABvAHIAKAB2AGEAbAAgAD0APgAgAHYAYQBsACkAIABfAG8AawBBAHIAZwA6ACAAYQBuAHkAKQAgAHsAfQAKAH0A)
