### ISSUE TITLE
📎 format of JsxText should clean jsx text

### ISSUE THREAD

**Issue by darrow-olykos** [rome/tools#2359]
### Description

Opportunity identified by this conversation here: https://discord.com/channels/678763474494423051/841927329265090590/959760493092933643

Formatting `JsxText` should change any two sequential ascii whitespace characters into a single space.

Examples of ascii whitespace characters:
```rust
'\n' // newline

'\t' // tab

' ' // space
```

Please assign this to @darrow-olykos , I have a solution and will open a PR

**Comment by darrow-olykos** [comment]
Hey @ematipico, I cannot commit to finishing this for personal reasons. I sincerely appreciate all of the education you and others shared with me while looking into this!

**Comment by NicholasLYang** [comment]
@darrow-olykos, thanks for all of your work! I'm going to take over the issue, just so we can get this feature out
