### ISSUE TITLE
🐛 CLI Ignores Nested .gitignores

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2394]
### Environment information

```bash
MacBook Air M1 w/8gb RAM
macOS Monterey
```

### What happened?

If we run the CLI in a repository with nested .gitignore files, i.e. the `website/playground` folder has its own .gitignore, it doesn't use them. 

### Expected result

We should use .gitignores even in nested folders.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by leops** [comment]
The root issue here is that `.gitignore` files (or any other kind of dot-ignore file) are not supported at all by the CLI at the moment (it just has a hardcoded filter to ignore `.git` and `node_modules` directories), we may want to re-classify this from a bug to a task to implement ignore files ?
Additionally this should probably be explained to the user somehow, besides saying it's not implemented in the documentation we could emit a warning in the CLI when it encounters an ignore file to let the user know it won't be used ?
