### ISSUE TITLE
📎 TypeScript 4.7

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2400]
### Description

Add parsing and formatter support for the Syntax introduced by TypeScript 4.7

* [x] Instantiation Expressions: [PR](https://github.com/microsoft/TypeScript/pull/47607), [Announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#instantiation-expressions) #3147
* [x] `extends` constraints on `infer` type variables: [Announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#extends-constraints-on-infer-type-variables) #4018
* [ ] Type parameter variance: [Announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#optional-variance-annotations-for-type-parameters) @nissy-dev  
* [ ] ~`typeof` on `private` fields: [Announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#typeof-on-private-fields)~ Being [reverted](https://github.com/microsoft/TypeScript/pull/48959)

**Comment by nissy-dev** [comment]
I'll take the support for "extends constraints on infer type variables" 🚀

**Comment by Louis-Michalak** [comment]
I'll try to take the support for variance annotations 😃

**Comment by Louis-Michalak** [comment]
Is anyone currently supporting the type parameter variance?

**Comment by MichaReiser** [comment]
> Is anyone currently supporting the type parameter variance?

No one is working on this at the moment. Do you want to tackle it?

**Comment by Louis-Michalak** [comment]
> No one is working on this at the moment. Do you want to tackle it?

Yes I'll take it

**Comment by LouisStairwage** [comment]
@MichaReiser by the way why has this PR been closed https://github.com/rome/tools/pull/2556

**Comment by Louis-Michalak** [comment]
@MichaReiser by the way why has this PR been closed https://github.com/rome/tools/pull/2556

**Comment by Conaclos** [comment]
Hi [Louis-Michalak](https://github.com/Louis-Michalak)! Did you make some progress?

**Comment by nissy-dev** [comment]
This issue is assigned to @Louis-Michalak , but the PR is not submitted for a long time. 
Therefore, I will take the "Type parameter variance"🚀
