### ISSUE TITLE
☂️ Prettier Formatting compatibility

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2403]
### Description

Rome formatter's goal is to match Prettier's formatting as closely as possible where reasonable, and we have no good reasons to deviate. 

This umbrella task tracks the syntaxes that Rome formats differently than prettier. 

## Statements
* [x] #2406
* [x] #2407
* [x] #2423
* [x] #2448
* [x] #2437

## Module Items 

* [x] #2440
* [x] #2441

## Expressions 
* [x] #2405
* [x] #2408
* [ ] #2411
* [x] #2413
* [x] #2414
* [x] #2421
* [ ] #2427
* [x] #2430
* [x] #2431
* [x] #2425
* [ ] #2449
* [x] #2720
* [ ] #2815

## Assignment
* [x] #2410
* [x] #2416
* [x] #2417
* [x] #2424

## Functions
* [x] #2439

## TypeScript
* [x] #2404
* [x] #2418 (on hold)
* [x] #2419
* [x] #2420

## Literals
* [x] #2426
* [ ] #2442
* [x] #2443
* [x] #2436
* [x] #2444
* [x] #2445
* [ ] #2446

## Infrastructure

* [x] #2415
* [x] #2450
* [x] #2529
* [x] #2532
* [x] #2533
* [x] #2546
* [ ] #2550
* [ ]  #2664
* [ ] #2814

[Report](https://gist.github.com/MichaReiser/0db0865302d83ca37f97055e94fd17fa) of all tests that Rome formats differently than Prettier (created on the 12th of April 22).

**Comment by MichaReiser** [comment]
I haven't gone through the TypeScript reports yet. Something we should do in the near future

**Comment by hustcer** [comment]
Any update on this issue after the latest 0.7.0 release?

**Comment by harrytran998** [comment]
Happy when I see only 10 checkboxes 😂. Your team has worked really hard! 🙏

**Comment by MichaReiser** [comment]
Closing in favour of #3046  and #3047
