### ISSUE TITLE
Semicolon vs colons in TypeScript types

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2404]
## Description

Rome uses `,` to separate `interface` or object type literal members whereas prettier uses `;`

```ts
// Prettier
type X = {
  a: string;
  b: number;
}

// Rome
type X = {
  a: string,
  b: number,
}
```

## Proposal

Change Rome to use semicolons. Personally, I prefer commas but I adopted prettier's style and I'm fine with it.

by @cpojer 

[Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&indentWidth=2&typescript=true&jsx=false&sourceType=module#dAB5AHAAZQAgAFgAIAA9ACAAewAKACAAIABhADoAIABzAHQAcgBpAG4AZwA7AAoAIAAgAGIAOgAgAG4AdQBtAGIAZQByADsACgB9AA==)

**Comment by MichaReiser** [comment]
Just keep in mind that this would be a perfect first issue (part of the reason why I spent so much time writing this up ;))

**Comment by ematipico** [comment]
Sorry, I didn't see any label but it's actually true! Let's do that

**Comment by ematipico** [comment]
For whoever wants to contribute: https://github.com/rome/tools/blob/main/crates/rome_js_formatter/src/ts/lists/type_member_list.rs#L24-L31

**Comment by cpojer** [comment]
Sorry, I need this fixed. I reported it, so I fixed it :P
