### ISSUE TITLE
Put closing curly on new line for empty blocks.

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2406]
Rome's formatter collapses empty block statements on a single line whereas Prettier enforces a line break before the closing `}` for the following statements. 

* `for..in` 
* `for..of` 
* `with` 
* `switch` 
* `switch case`

[Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#LwAvACAATABpAG4AZQAgAGIAcgBlAGEAawAgAGIAZQBmAG8AcgBlACAAYwBsAG8AcwBpAG4AZwAgAGAAfQBgAAoAaQBmACAAKAB0AHIAdQBlACkAIAB7AH0ACgBpAGYAIAAoAHQAcgB1AGUAKQAgAHsAfQAgAGUAbABzAGUAIAB7AH0ACgAKAGYAbwByACAAKAB4ACAAaQBuACAAWwBdACkAIAB7AH0ACgBmAG8AcgAgACgAeAAgAG8AZgAgAFsAXQApACAAewB9AAoACgB3AGkAdABoACgAewB9ACkAIAB7AH0ACgAKAAoAcwB3AGkAdABjAGgAIAAoACIAdABlAHMAdAAiACkAIAB7AAoAfQAKAAoAcwB3AGkAdABjAGgAIAAoACIAdABlAHMAdAAiACkAIAB7AAoAIAAgAGMAYQBzAGUAIAAiAHQAZQBzAHQAIgA6ACAAewB9AAoAfQAKAAoAdABlAHMAdAA6ACAAewB9AAoACgB0AHIAeQAgAHsACgB9ACAAYwBhAHQAYwBoACAAewAKAH0AIABmAGkAbgBhAGwAbAB5ACAAewAKAH0ACgAKAC8ALwAgAE4AbwAgAEwAaQBuAGUAIABiAHIAZQBhAGsAcwAKAGMAbABhAHMAcwAgAFQAZQBzAHQAIAB7AH0ACgBpAG4AdABlAHIAZgBhAGMAZQAgAFgAIAB7AH0ACgB0AHkAcABlACAAWAAgAD0AIAB7AH0AOwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAdABlAHMAdAAoACkAIAB7AH0ACgAKAGYAbwByACAAKAA7ADsAKQAgAHsAfQAKAHcAaABpAGwAZQAgACgAdAByAHUAZQApACAAewB9AAoAZABvACAAewB9ACAAdwBoAGkAbABlACAAKAB0AHIAdQBlACkAOwAKAA==)

## Input 

```ts
// Line break before closing `}`
if (true) {}
if (true) {} else {}

for (x in []) {}
for (x of []) {}

with({}) {}


switch ("test") {
}

switch ("test") {
  case "test": {}
}

test: {}

try {
} catch {
} finally {
}

// No Line breaks
class Test {}
interface X {}
type X = {};

function test() {}

for (;;) {}
while (true) {}
do {} while (true);
```

## Prettier

```ts
// Line break before closing `}`
if (true) {
}
if (true) {
} else {
}

for (x in []) {
}
for (x of []) {
}

with ({}) {
}

switch ("test") {
}

switch ("test") {
	case "test": {
	}
}

test: {
}

try {
} catch {
} finally {
}

// No Line breaks
class Test {}
interface X {}
type X = {};

function test() {}

for (;;) {}
while (true) {}
do {} while (true);
```

## Rome

```ts
// Line break before closing `}`
if (true) {
}
if (true) {
} else {
}

for (x in []) {}
for (x of []) {}

with({}) {}

switch ("test") {}

switch ("test") {
	case "test":
		{}
}

test: {}

try {} catch {} finally {}

// No Line breaks
class Test {}
interface X {}
type X = {};

function test() {}

for (;;) {}
while (true) {}
do {} while (true);

```

**Comment by ematipico** [comment]
I think here we should diverge or make everything look the same. If we liked prettier style (breaking before closing curly bracket), then we should apply the same behaviour to all the cases.

For example [this](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#dwBoAGkAbABlACAAKAB0AHIAdQBlACkAIAB7AH0ACgB3AGkAdABoACgAewB9ACkAIAB7AH0A): 

```js
// prettier
while (true) {}
with ({}) {
}
```

Why one case it breaks while the other it doesn't?

**Comment by MichaReiser** [comment]
My understanding is that it doesn't break for the more traditional loops like a `for(;;)` or the `while` loops because there are valid use cases where you don't need a body

```
while (iter.next() != null) {}
console.log(iter.last());
```

**Comment by ematipico** [comment]
Although `do {} while ()` needs a body, I mean... I can't find a case where a `do/while` might have an empty body. In this case breaking might make sense? That's weird

**Comment by MichaReiser** [comment]
> Although `do {} while ()` needs a body, I mean... I can't find a case where a `do/while` might have an empty body. In this case breaking might make sense? That's weird

But then you probably want to keep `while` and `do while` consistent.
