### ISSUE TITLE
Switch-case block body placement

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2407]
Rome's formatter places a switch case's block body on a new line and indents it whereas Prettier formats the block start on the same line as the case start. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#CgBzAHcAaQB0AGMAaAAgACgAIgB0AGUAcwB0ACIAKQAgAHsACgAgACAAYwBhAHMAZQAgACIAdABlAHMAdAAiADoAIAB7AH0ACgB9AAoA)

## Input

```ts
switch ("test") {
  case "test": {}
}
```

## Prettier
```ts
switch ("test") {
	case "test": {
	}
}
```

## Rome 
```ts
switch ("test") {
	case "test":
		{}
}
```

## Expected

Formatting to match Prettier's formatting.

**Comment by ematipico** [comment]
For contributors: https://github.com/rome/tools/blob/main/crates/rome_js_formatter/src/js/auxiliary/case_clause.rs#L27-L35
