### ISSUE TITLE
📎 Sorting imports as unstable feature

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2409]
### Description

From discord discussion: https://discord.com/channels/678763474494423051/895012159011053599/962364285177176104 and forward.

We as a team decided to implement this feature as **unstable** and only opt-in via option. This is because it might break people's code, and as for that we want to make sure to release a feature that doesn't break all people's code.

As it's unstable, there are two course of actions:
- it will be stabilized and made it as a default after possible fixes and feedback
- it will be removed if we think if it bring more harm than advantages

**Comment by MichaReiser** [comment]
I wouldn't implement this feature as `unstable` but rather have different presets:

* stable: Default
* experimental: Includes all experimental features. Can be enabled by a single `--experimental` flag that opts you in into ALL of rome's experimental features. 

Only having two presets greatly simplifies the combinations that must be tested. 


I'm still having some concerns about the priority of this feature compared to supporting other languages and fixing Prettier incompatibilities.

**Comment by ematipico** [comment]
> experimental: Includes all experimental features. Can be enabled by a single --experimental flag that opts you in into ALL of rome's experimental features.

I am not sure this is safe. As a user, I would like to know what features e experiments I want to try, so giving a finer control might be safer.

Also, let's say we decided to make an experiment official (e.g. 1 out of 5 that we currently have), how do you plan telling the user that now something is stable and they don't need to use the experiment anymore?

That's why I think each experiment should be opted-in singularly.

**Comment by MichaReiser** [comment]
> Also, let's say we decided to make an experiment official (e.g. 1 out of 5 that we currently have), how do you plan telling the user that now something is stable and they don't need to use the experiment anymore?

The point I see behind experimental features is to give us more time stabilizing a feature and collecting feedback. I don't think we should give users any guarantees about experimental features so that it's safe for us to even remove experimental features in a patch release. Having explicit flags won't allow that because the flag then no longer works or we need to support it for longer than necessary. 

The other issue I see with explicit options is that it fundamentally differs from our formatter philosophy to support as few options as possible.

Overall, it seems there are many unanswered questions, including how we want to support experimental features which we should discuss/solve first.

**Comment by mattmarcello** [comment]
any updates here? I understand the complexity around reordering imports given possible side effects but I would like to opt in if possible.

**Comment by ematipico** [comment]
> any updates here? I understand the complexity around reordering imports given possible side effects but I would like to opt in if possible.

At the moment Rome doesn't have a wait to opt-in unstable features and, as a team, we haven't come up with a strategy to do so because it's not on the top list of our priorities. 

I am going to close this issue for the time being, because we don't have the infrastructure to provide these experiments. We will discuss again the topic once we have some time to work on it.
