### ISSUE TITLE
Assignment of array/object literals

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2410]
Prettier keeps the opening `[` or `{` on the same line as the assignment expression when it exceeds the line width. Rome formats the whole array or object literal on a new line.

## Input

```ts
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers = [1, 2, 3, 4, 5];
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers = { a: 10 };
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder = bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawderArrayNumbes = { a: 10 };
```

## Prettier

```ts
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers = [
	1, 2, 3, 4, 5,
];
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers = {
	a: 10,
};
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder =
	bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawderArrayNumbes = {
		a: 10,
	};
```

## Rome

```ts
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers =
	[1, 2, 3, 4, 5];
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers =
	{ a: 10 };
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder =
	bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawderArrayNumbes =
		{ a: 10 };
```

## Expected

Rome's formatting should match Prettiers formatting by putting the opening `{` and `[` tokens on the same line as the `=` token.

[Playground](https://play.rome.tools/?lineWidth=83&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#YgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AC4AYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AFMAYQB3AGQAZQByAC4AYQByAHIAYQB5AE8AZgBOAHUAbQBiAGUAcgBzACAAPQAgAFsAMQAsACAAMgAsACAAMwAsACAANAAsACAANQBdADsACgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgALgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAUwBhAHcAZABlAHIALgBhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAHMAIAA9ACAAewAgAGEAOgAgADEAMAAgAH0AOwAKAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeAAuAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeABTAGEAdwBkAGUAcgAgAD0AIABiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgALgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAUwBhAHcAZABlAHIAQQByAHIAYQB5AE4AdQBtAGIAZQBzACAAPQAgAHsAIABhADoAIAAxADAAIAB9ADsACgAKAA==)

**Comment by ematipico** [comment]
I will look after this
