### ISSUE TITLE
Formatting long conditional expressions & types

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2411]
Rome's formatter doesn't break long conditional expressions across multiple lines when they exceed the line width. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#YgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AC4AYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AFMAYQB3AGQAZQByAC4AYQByAHIAYQB5AE8AZgBOAHUAbQBiAGUAcgBzACAAPwAgAGIAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQAgADoAIABjADsACgAKAHQAeQBwAGUAIABFAHgAYQBtAHAAbABlADEAIAA9ACAAYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4ACAAZQB4AHQAZQBuAGQAcwAgAEEAbgBpAG0AYQBsACAAPwAgAGIAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQAgADoAIABhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAHMAOwAKAAoALwAvACAAbgBlAHMAdABlAGQACgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgALgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAUwBhAHcAZABlAHIALgBhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAHMAIAA/ACAAYgBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlACAAOgAgAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeAAuAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeABTAGEAdwBkAGUAcgAuAGEAcgByAGEAeQBPAGYATgB1AG0AYgBlAHIAcwAgAD8AIABiAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAIAA6ACAAYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AC4AYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AFMAYQB3AGQAZQByAC4AYQByAHIAYQB5AE8AZgBOAHUAbQBiAGUAcgBzACAAPwAgAGIAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQAgADoAIAAiAHQAZQBzAHQAIgA7AAoACgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgALgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAUwBhAHcAZABlAHIALgBhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAHMAIAA/ACAACgAgACAAYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AC4AYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AFMAYQB3AGQAZQByAC4AYQByAHIAYQB5AE8AZgBOAHUAbQBiAGUAcgBzACAAPwAgAGIAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQAgADoAIABiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgALgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAUwBhAHcAZABlAHIALgBhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAHMAIAA/ACAAYgBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlACAAOgAgACIAdABlAHMAdAAiACAACgAgACAAOgAgACIAbwB0AGgAZQByACIAOwAKAAoACgB0AHkAcABlACAARQB4AGEAbQBwAGwAZQAxACAAPQAgAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeAAgAGUAeAB0AGUAbgBkAHMAIABBAG4AaQBtAGEAbAAgAD8AIABiAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAIAA6ACAACgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAIABlAHgAdABlAG4AZABzACAAQQBuAGkAbQBhAGwAIAA/ACAAYgBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlACAAOgAgAAoAYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4ACAAZQB4AHQAZQBuAGQAcwAgAEEAbgBpAG0AYQBsACAAPwAgAGIAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQAgADoAIABhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAHMAOwAKAAoAdAB5AHAAZQAgAEUAeABhAG0AcABsAGUAMQAgAD0AIABiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAIABlAHgAdABlAG4AZABzACAAQQBuAGkAbQBhAGwAIAA/ACAACgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAIABlAHgAdABlAG4AZABzACAAQQBuAGkAbQBhAGwAIAA/ACAAYgBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlACAAOgAgAAoAYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4ACAAZQB4AHQAZQBuAGQAcwAgAEEAbgBpAG0AYQBsACAAPwAgAGIAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQBlAGUAZQAgADoAIABhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAHMAIAA6ACAAdABlAHMAdAA7AA==)

## Input

```ts
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : c;

type Example1 = bifornCringerMoshedPerplex extends Animal ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : arrayOfNumbers;

// nested
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : "test";

bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? 
  bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : "test" 
  : "other";


type Example1 = bifornCringerMoshedPerplex extends Animal ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : 
bifornCringerMoshedPerplex extends Animal ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : 
bifornCringerMoshedPerplex extends Animal ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : arrayOfNumbers;

type Example1 = bifornCringerMoshedPerplex extends Animal ? 
bifornCringerMoshedPerplex extends Animal ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : 
bifornCringerMoshedPerplex extends Animal ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : arrayOfNumbers : test;
```

## Prettier

```ts
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: c;

type Example1 = bifornCringerMoshedPerplex extends Animal
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: arrayOfNumbers;

// nested
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: "test";

bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
	? bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: "test"
	: "other";

type Example1 = bifornCringerMoshedPerplex extends Animal
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: bifornCringerMoshedPerplex extends Animal
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: bifornCringerMoshedPerplex extends Animal
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: arrayOfNumbers;

type Example1 = bifornCringerMoshedPerplex extends Animal
	? bifornCringerMoshedPerplex extends Animal
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: bifornCringerMoshedPerplex extends Animal
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: arrayOfNumbers
	: test;

```

## Rome

```ts
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : c;

type Example1 = bifornCringerMoshedPerplex extends Animal ? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee : arrayOfNumbers;

// nested
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
			? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
			: "test";

bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
	? bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumbers
			? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
			: "test"
	: "other";

type Example1 = bifornCringerMoshedPerplex extends Animal
	? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
	: bifornCringerMoshedPerplex extends Animal
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: bifornCringerMoshedPerplex extends Animal
			? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
			: arrayOfNumbers;

type Example1 = bifornCringerMoshedPerplex extends Animal
	? bifornCringerMoshedPerplex extends Animal
		? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
		: bifornCringerMoshedPerplex extends Animal
			? beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
			: arrayOfNumbers
	: test;
```

## Expected

Rome's formatting should match Prettier's.

If we decide to keep Rome's current formatting of nested conditional expressions then add a section to Rome's website that explains why Rome's formatting differs and why we prefer it over Prettiers. The reason must be compelling enough because it makes it more difficult to adopt Rome.

**Comment by ematipico** [comment]
@yassere @NicholasLYang 

Do you think the indentation for each sub conditional helps or not?

**Comment by yassere** [comment]
For now, I think we should almost always try to match Prettier's style. It feels pretty important for adoption to reduce migration friction. Later, we can consider adding an option that enables opinionated Rome formatting if we have enough possible enhancements that it's worth it.

**Comment by ematipico** [comment]
> Later, we can consider adding an option 

Too many options already 😝 

Thank you for your input!

**Comment by ematipico** [comment]
@yassere @NicholasLYang  Could you please make some sense [into this code](https://play.rome.tools/1d07d6a/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#ZgBlAGUACgAJAD8AIABmAGUAZQAKAAkACQA/ACAAZQBlAGUACgAJAAkAOgAgAGYAZQBlAGUACgAJAAkAPwAgAGQAZQBlAAoACQAJADoAIABkAGUAZQAKAAkAOgAgAGYAZQBlAGUACgAJAAkAPwAgAGYAZQBlAAoACQAJADoAIABlAGQAZABlAGUAZgBlAGUAZQBmAGYAZQBmAGUAZgBlAAoACQAJAD8AIABmAGQAZABlAGYAZQBmAGYAZQBmAGUACgAJAAkAOgAgACIAdABlAHMAdAAiAA==)?

You're saying that we have to match prettier, but to me it seems bugged. It doesn't have any consistent logic. One branch is indented while the other is not. To me, it seems a bug.

**Comment by yassere** [comment]
I'm seeing that snippet formatted by Prettier as:
```js
fee
	? fee
		? eee
		: feee
		? dee
		: dee
	: feee
	? fee
	: eddeefeeeffefefe
	? fddefeffefe
	: "test";
```

I haven't looked at the relevant Prettier code, but here's what I think is happening:

In a typical ternary chain, each `JsConditionalExpression` is the `alternate` of the one before it. And Prettier prints those without increasing the indentation level.

But if you use a `JsConditionalExpression` as the `consequent` of the one before it, it adds a level of indentation to identify that there's another  "subchain" that's nested inside the outer one.

Does that make sense?

**Comment by ematipico** [comment]
Assigning to Yasser as he understands better then me these damn expressions 😛 Thank you Yasser!

**Comment by ematipico** [comment]
The problem is self-contained, but it requires a good understanding of how nested conditionals folds and how the grouping is applied.

**Comment by MichaReiser** [comment]
This should be fixed in the latest release.
