### ISSUE TITLE
Rome prints over configured line width

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2415]
Rome sometimes exceeds the configured print width even if the syntax could be formatted over multiple lines (not a single token exceeding the line width). [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#LwAvACAAUAByAGUAdAB0AGkAZQByACAAYgByAGUAYQBrAHMAIABhAHQAIAA4ADAAIABjAGgAYQByAGEAYwB0AGUAcgBzACwAIABSAG8AbQBlACAAYQB0ACAAOAAxAAoAYQBhAGEAYQBhAGEAYQBhAGEAYQBhAGEAYQBhAGEAYQBhAGEAYQBhAGEAYQBhACAAKwAgAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAYgBiAGIAIAArACAAYwBjAGMAYwBjAGMAYwBjAGMAYwBjACAACgAKAC8ALwAgAFAAcgBlAHQAdABpAGUAcgAgAGIAcgBlAGEAawBzACAAYQB0ACAAOAAwACAAYwBoAGEAcgBhAGMAdABlAHIAcwAsACAAUgBvAG0AZQAgAGEAdAAgADgAMwAKAGwAZQB0ACAAewAgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAGsAbQBuAG8AcABxAHIAcwB0AHUAZgB3AGsAZABzAGYAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAZABkAGQAfQAgAD0AIAB7AH0A)

## Input 
```ts
// Prettier breaks at 80 characters, Rome at 81
aaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb + ccccccccccc 

// Prettier breaks at 80 characters, Rome at 83
let { abcdefghijklkmnopqrstufwkdsfdddddddddddddddddddddddddddddddddddddddddd} = {}
```

## Prettier

```ts
// Prettier breaks at 80 characters, Rome at 81
aaaaaaaaaaaaaaaaaaaaaaa +
	bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb +
	ccccccccccc;

// Prettier breaks at 80 characters, Rome at 83
let { abcdefghijklkmnopqrstufwkdsfdddddddddddddddddddddddddddddddddddddddddd } =
	{};

```

## Rome
```ts
// Prettier breaks at 80 characters, Rome at 81
aaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb + ccccccccccc;

// Prettier breaks at 80 characters, Rome at 83
let { abcdefghijklkmnopqrstufwkdsfdddddddddddddddddddddddddddddddddddddddddd } = {};

```

## Expected 
Rome respects the configured line width.

**Comment by MichaReiser** [comment]
@leops you mentioned that you have an idea of how to tackle this issue. Would you have time to take a look sometime between fleshing out the linter architecture?

**Comment by leops** [comment]
Sure, so the root issue here is that going over the maximum line width cause the printer to break the current group across multiple lines but sometimes this may not be effective for a variety of reasons:
- The printer is not currently printing any group, for instance when only the semicolon token is overflowing after an expression statement nothing will happen as the semicolon is not part of the group that's created by the expression
- Breaking the group does not result in enough / any line breaks to be created to prevent going over the max width: in `let {} = {};` the entire statement (minus the semicolon) as well as the final expression `{}` both create a group, but those groups do not include any soft break and will print the same in single line and multiline mode

So the solution I have in mind is also in two parts, the first half would be to keep track of the last group that was seen in the printer even after it gets exited up to the next line break, to allow it to backtrack to that group and break it even after it finishes printing. The second part would be to avoid creating groups when they do not contain any soft line breaks or conditional groups, either by inspecting the content and skipping creating the element in `group_elements`, or performing that check manually in the few places that may create non-breaking groups (along with a debug assert to error when such a group would be created to help rooting out issues)

**Comment by ematipico** [comment]
I just tested the cases highlighted in the issue and they seem to be fixed. Closing
