### ISSUE TITLE
Nested assignments

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2416]
Rome's formatter breaks nested assignments onto a new line compared to Prettier that only prints the right-hand side expression on a new line. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#LwAvACAARgBpAHQAcwAKAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeAAgAD0AIABiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAUwBhAHcAZABlAHIAIAA9ACAAYQByAHIAYQB5AE8AIAA9ACAAIgB0AGUAcwB0ACIACgAKAC8ALwAgAEUAeABjAGUAZQBkAGkAbgBnADoACgAvAC8AIABPAG4AZQAgAGEAcwBzAGkAZwBuAG0AZQBuAHQACgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgALgBiAGkAZgBvAHIAbgBDAHIAaQBuAGcAZQByAE0AbwBzAGgAZQBkAFAAZQByAHAAbABlAHgAUwBhAHcAZABlAHIALgBhAHIAcgBhAHkATwBmAE4AdQBtAGIAZQByAC4AbQA9ACAAIgB0AGUAcwB0ACIACgAKAC8ALwAgAFQAdwBvACAAYQBzAHMAaQBnAG4AbQBlAG4AdABzAAoAYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AC4AYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4AFMAYQB3AGQAZQByAC4AYQByAHIAYQB5AE8AZgBOAHUAbQBiAGUAcgAgAD0AIABhAGIAIAA9ACAAIgB0AGUAcwB0ACIACgAKAC8ALwAgAE0AbwByAGUAIAB0AGgAYQBuACAAdAB3AG8AIABhAHMAcwBpAGcAbgBtAGUAbgB0AHMAIABhAG4AZAAgAGUAeABjAGUAZQBkAGkAbgBnADoAIABFAGEAYwBoACAAYQBzAHMAaQBnAG4AbQBlAG4AdAAgAG8AbgAgAHQAaABlAGkAcgAgAG8AdwBuACAAbABpAG4AZQAKAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeAAuAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeABTAGEAdwBkAGUAcgAuAGEAcgByAGEAeQAgAD0AIABwACAAPQAgAGEAYgAgAD0AIAAiAHQAZQBzACIACgAKAAoAYgBpAGYAbwByAG4AQwByAGkAbgBnAGUAcgBNAG8AcwBoAGUAZABQAGUAcgBwAGwAZQB4ACAAPQAgAGIAaQBmAG8AcgBuAEMAcgBpAG4AZwBlAHIATQBvAHMAaABlAGQAUABlAHIAcABsAGUAeABTAGEAdwBkAGUAcgAgAD0AIABhAHIAcgBhAHkATwBmAE4AdQBtAGIAIAA9ACAAYQAgAD0AIAAiAHQAZQBzAHQAIgA=)

## Input

```ts
// Fits
bifornCringerMoshedPerplex = bifornCringerMoshedPerplexSawder = arrayO = "test"

// Exceeding:
// One assignment
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumber.m= "test"

// Two assignments
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumber = ab = "test"

// More than two assignments and exceeding: Each assignment on their own line
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.array = p = ab = "tes"


bifornCringerMoshedPerplex = bifornCringerMoshedPerplexSawder = arrayOfNumb = a = "test"
```

## Prettier

```ts
// Fits
bifornCringerMoshedPerplex = bifornCringerMoshedPerplexSawder = arrayO = "test";

// Exceeding:
// One assignment
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumber.m =
	"test";

// Two assignments
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumber = ab =
	"test";

// More than two assignments and exceeding: Each assignment on their own line
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.array =
	p =
	ab =
		"tes";

bifornCringerMoshedPerplex =
	bifornCringerMoshedPerplexSawder =
	arrayOfNumb =
	a =
		"test";
```

## Rome

```ts
// Fits
bifornCringerMoshedPerplex = bifornCringerMoshedPerplexSawder = arrayO = "test";

// Exceeding:
// One assignment
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumber.m =
	"test";

// Two assignments
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.arrayOfNumber =
	ab = "test";

// More than two assignments and exceeding: Each assignment on their own line
bifornCringerMoshedPerplex.bifornCringerMoshedPerplexSawder.array =
	p = ab = "tes";

bifornCringerMoshedPerplex =
	bifornCringerMoshedPerplexSawder = arrayOfNumb = a = "test";
```

## Expected

Rome to match Prettier's output. 

I'm not entirely sure if I figured out Prettier's heuristic. It could make sense to study prettier's source code before tackling this issue to confirm. But my understanding is that Prettier:

* Breaks between the assignment operator and the right-hand side expression
* Tries to fit up to two assignments on the same line (except if all of them fit).
* The right-hand side is indented one level deeper than the last assignment expression.
* 3+ assignments and exceeding line width: Each assignment on its own line.

**Comment by ematipico** [comment]
> 3+ assignments and exceeding line width: Each assignment on its own line.

And different indentation too 🤔

**Comment by ematipico** [comment]
![Screenshot 2022-04-13 at 14 04 02](https://user-images.githubusercontent.com/602478/163186272-c4732389-595b-4444-b891-8b466b020bd4.png)

I see two level of indentation. Is it a github rendering issue?

**Comment by ematipico** [comment]
This requires understanding Prettier's heuristic.

**Comment by ematipico** [comment]
I will work on this one
