### ISSUE TITLE
Function and class expression assignment

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2417]
Rome breaks any `function` or `class` expression assignment over at least two lines if their bodies aren't empty. Prettier formats them on a single line (as one would expect). [Playground](https://play.rome.tools/?lineWidth=120&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#LwAvACAAQQBzAHMAaQBnAG4AaQBuAGcAIAB0AG8AIABmAHUAbgBjAHQAaQBvAG4ALwBjAGwAYQBzAHMAZQBzACAAdwBpAHQAaAAgAGEAbgAgAGUAbQBwAHQAeQAgAHkAaQBlAGwAZABzACAAdABoAGUAIABkAGUAcwBpAHIAZQBkACAAZgBvAHIAbQBhAHQAdABpAG4AZwAKAGEAIAA9ACAAZgB1AG4AYwB0AGkAbwBuACgAKQAgAHsAfQAKAGEAIAA9ACAAYwBsAGEAcwBzACAAewB9AAoACgAvAC8AIABBAHMAcwBpAGcAbgBpAG4AZwAgAHQAbwAgAGEAIABmAHUAbgBjAHQAaQBvAG4ALwBjAGwAYQBzAHMAIAB3AGkAdABoACAAYQAgAG4AbwBuAC0AZQBtAHAAdAB5ACAAYgBvAGQAeQAgAGcAcgBvAHUAcABzACAAdABoAGUAIAB3AGgAbwBsAGUAIABhAHMAcwBpAGcAbgBtAGUAbgB0ACAAZQB4AHAAcgBlAHMAcwBpAG8AbgAuAAoAYQAgAD0AIABmAHUAbgBjAHQAaQBvAG4AIAAoACkAIAB7AAoAIAAgAGMAbwBuAHMAbwBsAGUALgBsAG8AZwAoADEAKQAKAH0AOwAKAAoAZQB4AHQAcgBhAEwAbwBuAGcATABlAGYAdABIAGEAbgBkAFMAaQBkAGUATABlAHQAcwBTAGUAZQBIAG8AdwBQAHIAZQB0AHQAaQBlAHIAQgByAGUAYQBrAHMAVABoAGEAdABBAGMAcgBvAHMAcwBNAHUAbAB0AGkAcABsAGUATABpAG4AZQBzAFMAdABpAGwAbABOAG8AdABMAG8AbgBnAEUAbgBvAHUAZwBoAE0AdQBzAHQAQgBlAEwAbwBuAGcAZQByAEEAbgBkAEwAbwByAGEAIAA9ACAAZgB1AG4AYwB0AGkAbwBuACAAKAApACAAewAKACAAIABjAG8AbgBzAG8AbABlAC4AbABvAGcAKAAxACkACgB9ADsACgAKAGEAIAA9ACAAZgB1AG4AYwB0AGkAbwBuACAAZQB4AHQAcgBhAEwAbwBuAGcATABlAGYAdABIAGEAbgBkAFMAaQBkAGUATABlAHQAcwBTAGUAZQBIAG8AdwBQAHIAZQB0AHQAaQBlAHIAQgByAGUAYQBrAHMAVABoAGEAdABBAGMAcgBvAHMAcwBNAHUAbAB0AGkAcABsAGUATABpAG4AZQBzAFMAdABpAGwAbABOAG8AdABMAG8AbgBnAEUAbgBvAHUAZwBoAE0AdQBzAHQAQgBlAEwAbwBuAGcAZQByAEEAbgBkAGEAcgBhACAAKAApACAAewAKACAAIABjAG8AbgBzAG8AbABlAC4AbABvAGcAKAAxACkACgB9ADsACgAKAGEAIAA9ACAAYwBsAGEAcwBzACAAewAKACAAIABwAHIAbwBwADsACgB9AAoACgAvAC8AIABGAHUAbgBjAHQAaQBvAG4AIAB3AGkAdABoACAAbgBvAG4ALQBlAG0AcAB0AHkAIABiAG8AZAB5ACAAaQBzACAAcAByAGkAbgB0AGUAZAAgAG8AbgAgAHQAaABlACAAbgBlAHgAdAAgAGwAaQBuAGUACgBBAC4AcAByAG8AdABvAHQAeQBwAGUALgBmACAAPQAgAGYAdQBuAGMAdABpAG8AbgAoACkAIAB7AAoAIAAgAGMAbwBuAHMAbwBsAGUALgBsAG8AZwAoADEAKQAKAH0ACgAKAA==)

## Input

```ts
// Assigning to function/classes with an empty yields the desired formatting
a = function() {}
a = class {}

// Assigning to a function/class with a non-empty body groups the whole assignment expression.
a = function () {
  console.log(1)
};

extraLongLeftHandSideLetsSeeHowPrettierBreaksThatAcrossMultipleLinesStillNotLongEnoughMustBeLongerAndLora = function () {
  console.log(1)
};

a = function extraLongLeftHandSideLetsSeeHowPrettierBreaksThatAcrossMultipleLinesStillNotLongEnoughMustBeLongerAndara () {
  console.log(1)
};

a = class {
  prop;
}

// Function with non-empty body is printed on the next line
A.prototype.f = function() {
  console.log(1)
}
```

## Prettier

```ts
// Assigning to function/classes with an empty yields the desired formatting
a = function () {};
a = class {};

// Assigning to a function/class with a non-empty body groups the whole assignment expression.
a = function () {
  console.log(1);
};

extraLongLeftHandSideLetsSeeHowPrettierBreaksThatAcrossMultipleLinesStillNotLongEnoughMustBeLongerAndLora =
  function () {
    console.log(1);
  };

a =
  function extraLongLeftHandSideLetsSeeHowPrettierBreaksThatAcrossMultipleLinesStillNotLongEnoughMustBeLongerAndara() {
    console.log(1);
  };

a = class {
  prop;
};

// Function with non-empty body is printed on the next line
A.prototype.f = function () {
  console.log(1);
};

```

## Rome

```
// Assigning to function/classes with an empty yields the desired formatting
a = function () {};
a = class {};

// Assigning to a function/class with a non-empty body groups the whole assignment expression.
a =
  function () {
    console.log(1);
  };

extraLongLeftHandSideLetsSeeHowPrettierBreaksThatAcrossMultipleLinesStillNotLongEnoughMustBeLongerAndLora =
  function () {
    console.log(1);
  };

a =
  function extraLongLeftHandSideLetsSeeHowPrettierBreaksThatAcrossMultipleLinesStillNotLongEnoughMustBeLongerAndara() {
    console.log(1);
  };

a =
  class {
    prop;
  };

// Function with non-empty body is printed on the next line
A.prototype.f =
  function () {
    console.log(1);
  };
```

## Expected

Rome formats `class` and `function` expressions on a single line if there name fits on a single line.

**Comment by MichaReiser** [comment]
I'm currently looking into formatting classes that should help with this.

**Comment by ematipico** [comment]
This is now solved.
