### ISSUE TITLE
No trailing commas for tuple types

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2418]
Rome formatter inserts a trailing comma for tuple types, Prettier doesn't

## Input

```ts
type A = [
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD,
  String,
  Number
 ];
```

## Prettier

```ts
type A = [
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD,
  String,
  Number
];
```

## Rome

```ts
type A = [
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD,
  String,
  Number,
];

```

## Expected

No trailing comma after `Number`

**Comment by ematipico** [comment]
# **I don't think we should adhere to this.**

So sorry guys, but I am adamant on this one, count me out 😆 
Of course, if the majority of people think we should adhere, I am all in.

Trailing commas are really useful (I hated them but now I love them) when we want to add additional members at the end of the list. By duplicating the last line, the list is not broken and we can add stuff without the worry of the autocomplete not working.

Plus, it's consistent with the rest of the formatting (where trailing commas are allowed)

**Comment by MichaReiser** [comment]
> # **I don't think we should adhere to this.**
> 
> So sorry guys, but I am adamant on this one, count me out laughing Of course, if the majority of people think we should adhere, I am all in.
> 
> Trailing commas are really useful (I hated them but now I love them) when we want to add additional members at the end of the list. By duplicating the last line, the list is not broken and we can add stuff without the worry of the autocomplete not working.
> 
> Plus, it's consistent with the rest of the formatting (where trailing commas are allowed)

Prettier's [`trailingComma`](https://prettier.io/docs/en/options.html#trailing-commas) defaults to `es5` which doesn't insert any trailing commas. Changing the option to `all` makes Prettier insert the semicolon too. 

The Option's documentation explains why they aren't adding a trailing comma by default:

> Trailing commas wherever possible (including [function parameters and calls](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Trailing_commas_in_functions)). To run, JavaScript code formatted this way needs an engine that supports ES2017 (Node.js 8+ or a modern browser) or [downlevel compilation](https://babeljs.io/docs/en/index). This also enables trailing commas in type parameters in TypeScript (supported since TypeScript 2.7 released in January 2018).

So the issue is that TypeScript didn't support trailing commas until the 2.7 release. I think we can put this back on hold until we made a decision if Rome should support a `trailingComma` option or not.

**Comment by ematipico** [comment]
@NicholasLYang @yassere do you mind weight in and share your thoughts? Given the history shard by Micha and the fact that language targets are a non-goal for us, what's your take?

**Comment by yassere** [comment]
> language targets are a non-goal for us

What do you mean by this?

If we're choosing not to support a `trailingComma` option at all, then I think it's reasonable to add trailing commas wherever possible. They're widely enough supported.

If we find that not including a `trailingComma` option is causing lots of migration friction for existing Prettier users, that's something we can revisit later if it seems to be an actual problem rather than a hypothetical one.

**Comment by ematipico** [comment]
> > language targets are a non-goal for us
> 
> What do you mean by this?
> 
> If we're choosing not to support a `trailingComma` option at all, then I think it's reasonable to add trailing commas wherever possible. They're widely enough supported.
> 
> If we find that not including a `trailingComma` option is causing lots of migration friction for existing Prettier users, that's something we can revisit later if it seems to be an actual problem rather than a hypothetical one.
> 

We don't target versions of the languages that are old.

For example es3 or old Node.js 8, as quoted by Micha.

**Comment by ematipico** [comment]
As for now, target version is a non-goal for us and as we decided to not support `trailingComma` option, we won't implement this issue for the time being. If this causes frictions for adoptions, we can re-open and implement it.
