### ISSUE TITLE
Call expression arguments formatting

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2421]
Prettier has sophisticated formatting for call arguments that prevents unnecessary line breaks. For example, it formats the following snipped without breaking the passed arrow function over multiple lines (except the body). 

```
// Grouped if less than 3 arguments
testMethod(() => {
  expected(() =>
    moduleMocker.generateFromMetadata(moduleMocker.getMetadata(/a/))
  ).not.toThrow();
}, "string");

// Prettier:
// Grouped if less than 3 arguments
testMethod(() => {
  expected(() => moduleMocker.generateFromMetadata(moduleMocker.getMetadata(/a/))).not.toThrow();
}, "string");
```

Relevant test cases: 
* [`arrow/call.js`](https://gist.github.com/MichaReiser/77799fe4363bcc48838a159e581d8229#jsarrow-callarrow_calljs)
* [`break-call/react.js`](https://gist.github.com/MichaReiser/77799fe4363bcc48838a159e581d8229#jsbreak-callsreactjs)
* [`last-argument/expensions/empty-lines.js`](https://gist.github.com/MichaReiser/77799fe4363bcc48838a159e581d8229#jslast-argument-expansionempty-linesjs)
* [`preserve-line/argument-list.js`](https://gist.github.com/MichaReiser/77799fe4363bcc48838a159e581d8229#jspreserve-lineargument-listjs)
* [`js/functional-composition/functional_compose.js`](https://gist.github.com/MichaReiser/77799fe4363bcc48838a159e581d8229#jsfunctional-compositionfunctional_composejs)

## Expected
Output matches Prettier's output (or closely)

**Comment by ematipico** [comment]
We need to study prettier' source and see what they are doing. They use [`Alternatives`](https://github.com/rome/tools/pull/2534) for their solution. So probably we should wait until we have a better IR that matches prettier's.

**Comment by ematipico** [comment]
I am going to a look at this now
