### ISSUE TITLE
Object pattern formatting

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2424]
Rome tries to fit all object pattern members on a single line. Prettier uses a more sophisticated approach to determine if the pattern should be formatted on a single line or broken across multiple ones. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#LwAvACAAQgByAGUAYQBrACAAbwB2AGUAcgAgAG0AdQBsAHQAaQBwAGwAZQAgAGwAaQBuAGUAcwAgAGkAZgAgAGkAdAAgAGMAbwBuAHQAYQBpAG4AcwAgAGEAIABzAHUAYgAgAHAAYQB0AHQAZQByAG4ACgBjAG8AbgBzAHQAIAB7AGIAOgAgAHsAdABlAHMAdAB9AH0AIAA9ACAAdABlAHMAdAA7AAoACgAvAC8AIABuAG8AbgAtAHMAaABvAHIAdABoAGEAbgBkACAAYQBuAGQAIAB3AGgAbwBsAGUAIABzAHQAYQB0AGUAbQBlAG4AdAAgAGUAeABjAGUAZQBkAHMAIABsAGkAbgBlACAAdwBpAGQAdABoAAoAYwBvAG4AcwB0ACAAewAgAGkAZAAsACAAaQBzAFMAdABhAHQAaQBjADoAIABpAHMAUwB0AGEAdABpAGMALAAgAG0AZQB0AGgAbwBkACwAIABtAGUAdABoAG8AZABJAGQALAAgAGcAIAB9ACAAPQAgAHAAcgBpAHYAYQB0AGUATgBhAG0AZQBzAE0AYQBwAC4AZwBlAHQAKABuAGEAbQBlACkAOwAKAAoALwAvACAAZABlAGYAYQB1AGwAdAAgAGEAbgBkACAAdwBoAG8AbABlACAAcwB0AGEAdABlAG0AZQBuAHQAIABlAHgAYwBlAGUAZABzACAAbABpAG4AZQAgAHcAaQBkAHQAaAAKAGMAbwBuAHMAdAAgAHsAIABpAGQALAAgAGkAcwBTAHQAYQB0AGkAYwAgAD0AIAB0AHIAdQBlACwAIABtAGUAdABoAG8AZAAsACAAbQBlAHQAaABvAGQASQBkACwAIABnAGUAZQAgAH0AIAA9ACAAcAByAGkAdgBhAHQAZQBOAGEAbQBlAHMATQBhAHAALgBnAGUAdAAoAG4AYQBtAGUAKQA7AAoACgAvAC8AIABzAHUAYgAgAHAAYQB0AHQAZQByAG4ACgBjAG8AbgBzAHQAIAB7ACAAaQBkACwAIABpAHMAUwB0AGEAdABpAGMAOgAgAHsAcwB1AGIAfQAsACAAbQBlAHQAaABvAGQALAAgAG0AZQB0AGgAbwBkAEkAZAAsACAAZwBlAGUAIAB9ACAAPQAgAHAAcgBpAHYAYQB0AGUATgBhAG0AZQBzAE0AYQBwADsACgAKAA==)

A few examples:

## Input 

```ts
// Break over multiple lines if it contains a sub pattern
const {b: {test}} = test;

// non-shorthand and whole statement exceeds line width
const { id, isStatic: isStatic, method, methodId, g } = privateNamesMap.get(name);

// default and whole statement exceeds line width
const { id, isStatic = true, method, methodId, gee } = privateNamesMap.get(name);

// sub pattern
const { id, isStatic: {sub}, method, methodId, gee } = privateNamesMap;
```

## Prettier

```ts
// Break over multiple lines if it contains a sub pattern
const {
  b: { test },
} = test;

// non-shorthand and whole statement exceeds line width
const {
  id,
  isStatic: isStatic,
  method,
  methodId,
  g,
} = privateNamesMap.get(name);

// default and whole statement exceeds line width
const {
  id,
  isStatic = true,
  method,
  methodId,
  gee,
} = privateNamesMap.get(name);

// sub pattern
const {
  id,
  isStatic: { sub },
  method,
  methodId,
  gee,
} = privateNamesMap;

```

## Rome

```ts
// Break over multiple lines if it contains a sub pattern
const { b: { test } } = test;

// non-shorthand and whole statement exceeds line width
const { id, isStatic: isStatic, method, methodId, g } = privateNamesMap.get(
  name,
);

// default and whole statement exceeds line width
const { id, isStatic = true, method, methodId, gee } = privateNamesMap.get(name);

// sub pattern
const { id, isStatic: { sub }, method, methodId, gee } = privateNamesMap;
```

## Expected

Rome's formatting to match Prettier's

**Comment by ematipico** [comment]
Currently looking at implement this for type alias parameters

**Comment by ematipico** [comment]
Currently looking at class members
