### ISSUE TITLE
Break long object literal members over two lines

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2425]
Rome doesn't break object literal members over multiple lines even if they exceed the print width but Prettier breaks the initializer onto the new line [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#bABlAHQAIABhACAAPQAgAHsACgAgACAAIgB0AGgAaQBzAC0AaQBzAC0AYQAtAHYAZQByAHkALQBsAG8AbgBnAC0AawBlAHkALQBhAG4AZAAtAHQAaABlAC0AYQBzAHMAaQBnAG4AbQBlAG4AdAAtAHMAaABvAHUAbABkAC0AYgBlAC0AcAB1AHQALQBvAG4ALQB0AGgAZQAtAG4AZQB4AHQALQBsAGkAbgBlACIAOgAgAG8AcgBNAGEAeQBiAGUASQBBAG0ATQBpAHMAdQBuAGQAZQByAHMAdABhAG4AZABpAG4AZwBBAG4AZABJAEgAYQB2AGUAUwBlAHQAUwBvAG0AZQB0AGgAaQBuAGcAVwByAG8AbgBnAEkAbgBNAHkAQwBvAG4AZgBpAGcAKAApACwACgAgACAAIAAiAGMAYQBuAC0AcwBvAG0AZQBvAG4AZQAtAGUAeABwAGwAYQBpAG4AIgA6ACAAdABoAGEAdAAoACkALAAKACAAfQA7AAoAIAAKACAALwAvACAARABvAGUAcwBuACcAdAAgAGEAcABwAGwAeQAgAGYAbwByACAAdAB5AHAAZQBzACAAOgBPAAoAIAB0AHkAcABlACAAQQAgAD0AIAB7AAoAIAAgACIAdABoAGkAcwAtAGkAcwAtAGEALQB2AGUAcgB5AC0AbABvAG4AZwAtAGsAZQB5AC0AYQBuAGQALQB0AGgAZQAtAGEAcwBzAGkAZwBuAG0AZQBuAHQALQBzAGgAbwB1AGwAZAAtAGIAZQAtAHAAdQB0AC0AbwBuAC0AdABoAGUALQBuAGUAeAB0AC0AbABpAG4AZQAiADoAIABPAHIATQBhAHkAYgBlAEkAQQBtAE0AaQBzAHUAbgBkAGUAcgBzAHQAYQBuAGQAaQBuAGcAQQBuAGQASQBIAGEAdgBlAFMAZQB0AFMAbwBtAGUAdABoAGkAbgBnAFcAcgBvAG4AZwBJAG4ATQB5AEMAbwBuAGYAaQBnACwACgAgAH0AOwA=)

## Input

```ts
let a = {
  "this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line": orMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig(),
   "can-someone-explain": that(),
 };
 
 // Doesn't apply for types :O
 type A = {
  "this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line": OrMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig,
 };
```

## Prettier

```ts
let a = {
  "this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line":
    orMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig(),
  "can-someone-explain": that(),
};

// Doesn't apply for types :O
type A = {
  "this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line": OrMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig;
};
```

## Rome

```ts
let a = {
  "this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line": orMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig(),
  "can-someone-explain": that(),
};

// Doesn't apply for types :O
type A = {
  "this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line": OrMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig;
};
```

## Expected

Rome's output to match Prettier's.

**Comment by Dominionys** [comment]
Hi,
I'd like to try to fix this issue. 🙏🏽

**Comment by Dominionys** [comment]
Hm,
My first guess was to try `group_elements` and `soft_line_indent_or_space` for `FormatNodeRule<JsPropertyObjectMember>`  in `property_object_member.rs` file.

```        
Ok(group_elements(formatted![
    formatter,
    [
        name.format(),
        colon_token.format(),
        soft_line_indent_or_space(formatted![formatter, [value.format()]]?),
    ]
]?))
```

 Unfortunately, it changes formatting for any member value. 
 Prettier doesn't break all object literal member over two lines. [Rome playground](https://play.rome.tools/?lineWidth=20&indentStyle=space&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&isTypeScript=false&isJsx=false#JwAxADIAMwAyADEAMwAxADIAMwAxADIAMwAxADIAMwAyADEAMwAxADIAMwAxADIAMQAyADMAMQAyADMAMgAxADMAMgAxADMAMQAyADMAMQAyADMAMQAnACwAIAAnADEAMgAzADIAMQAzADEAMgAzADEAMgAzADEAMgAzADIAMQAzADEAMgAzADEAMgAxADIAMwAxADIAMwAyADEAMwAyADEAMwAxADIAMwAxADIAMwAxACcAOwAKAGwAZQB0ACAAbABvAG4AZwBzAHQAcgBpAG4AZwAgAD0AIAAnADEAMgAzADIAMQAzADEAMgAzADEAMgAzADEAMgAzADIAMQAzADEAMgAzADEAMgAxADIAMwAxADIAMwAyADEAMwAyADEAMwAxADIAMwAxADIAMwAxACcAOwAKAGwAZQB0ACAAbABvAG4AZwBuAHUAbQBiAGUAcgAgAD0AIAAxADIAMwAyADEAMwAxADIAMwAxADIAMwAxADIAMwAyADEAMwAxADIAMwAxADIAMQAyADMAMQAyADMAMgAxADMAMgAxADMAMQAyADMAMQAyADMAMQA7AAoAbABlAHQAIABsAG8AbgBnAGIAaQBnAEkAbgBnACAAPQAgAEIAaQBnAEkAbgB0ACgAIgAwAGIAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxACIAKQA7AAoAbABlAHQAIABmAHUAbgBjAHQAaQBvAG4AMQAgAD0AIABsAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcAKAAxACwAMgAsADMALAA0ACkAOwAKAGwAZQB0ACAAcwB0AHIAaQBuAGcAVABlAG0AcABsAGEAdABlACAAPQAgAGAAMQAyADMAMgAxADMAMQAyADMAMQAyADMAMQAyADMAMgAxADMAMQAyADMAMQAyADEAMgAzADEAMgAzAAoAMgAxADMAMgAxADMAMQAyADMAMQAyADMAMQBgADsACgAKAGwAZQB0ACAAdABlAHMAdABPAGIAagBlAGMAdAAgAD0AIAB7AAoAIAAgAHMAdAByAGkAbgBnAEYAaQBlAGwAZAA6ACAAJwAxADIAMwAyADEAMwAxADIAMwAxADIAMwAxADIAMwAyADEAMwAxADIAMwAxADIAMQAyADMAMQAyADMAMgAxADMAMgAxADMAMQAyADMAMQAyADMAMQAnACwACgAgACAAcwB0AHIAaQBuAGcAVABlAG0AcABsAGEAdABlADEAOgAgAGAAMQAyADMAMgAxADMAMQAyADMAMQAyADMAMQAyADMAMgAxADMAMQAyADMAMQAyADEAMgAzADEAMgAzADIAMQAzADIAMQAzADEAMgAzADEAMgAzADEAYAAsAAoAIAAgAHMAdAByAGkAbgBnAFQAZQBtAHAAbABhAHQAZQAyADoAIABgADEAMgAzADIAMQAzADEAMgAzADEAMgAzADEAMgAzADIAMQAzADEAMgAzADEAMgAxADIAMwAxADIAMwAKADIAMQAzADIAMQAzADEAMgAzADEAMgAzADEAYAAsAAoAIAAgAG4AdQBtAGIAZQByAEYAaQBlAGwAZAA6ACAAMQAyADMAMgAxADMAMQAyADMAMQAyADMAMQAyADMAMgAxADMAMQAyADMAMQAyADEAMgAzADEAMgAzADIAMQAzADIAMQAzADEAMgAzADEAMgAzADEALAAKACAAIABiAGkAZwBJAG4AdAA6ACAAQgBpAGcASQBuAHQAKAAiADAAYgAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAMQAxADEAIgApACwACgAgACAAYwBsAGEAcwBzAEYAaQBlAGwAZAA6ACAAYwBsAGEAcwBzACAAbQB5AEMAbABhAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwAgAHsAIABjAG8AbgBzAHQAcgB1AGMAdABvAHIAKAApACAAewB9AH0ALAAKACAAIABmAHUAbgBjAHQAaQBvAG4AQwBhAGwAbAA6ACAAbABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnACgAKQAsAAoAIAAgAGYAdQBuAGMAdABpAG8AbgBDAGEAbABsAFcAaQB0AGgAUABhAHIAYQBtAHMAOgAgAGwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwAoADEALAAyACwAMwAsADQALAA1ACwANgAsAHsAfQApACwACgAgACAACgAgACAAYQByAHIAYQB5ADoAIABbADEALAAyACwAMwAsADQALAA1ACwANgAsADcALAA4ACwAOQAsADEALAAyACwAMwAsADQALAA1ACwANgBdACwACgAgACAAbgBlAHMAdABlAGQATwBiAGoAZQBjAHQAOgAgAHsACgAgACAAIAAgACAAIABzAHQAcgBpAG4AZwBGAGkAZQBsAGQAOgAgACcAMQAyADMAMgAxADMAMQAyADMAMQAyADMAMQAyADMAMgAxADMAMQAyADMAMQAyADEAMgAzADEAMgAzADIAMQAzADIAMQAzADEAMgAzADEAMgAzADEAJwAsAAoAIAAgACAAIAAgACAAcwB0AHIAaQBuAGcAVABlAG0AcABsAGEAdABlADEAOgAgAGAAMQAyADMAMgAxADMAMQAyADMAMQAyADMAMQAyADMAMgAxADMAMQAyADMAMQAyADEAMgAzADEAMgAzADIAMQAzADIAMQAzADEAMgAzADEAMgAzADEAYAAsAAoAIAAgACAAIAAgACAAcwB0AHIAaQBuAGcAVABlAG0AcABsAGEAdABlADIAOgAgAGAAMQAyADMAMgAxADMAMQAyADMAMQAyADMAMQAyADMAMgAxADMAMQAyADMAMQAyADEAMgAzADEAMgAzAAoAIAAgACAAIAAyADEAMwAyADEAMwAxADIAMwAxADIAMwAxAGAALAAKACAAIAAgACAAIAAgAG4AdQBtAGIAZQByAEYAaQBlAGwAZAA6ACAAMQAyADMAMgAxADMAMQAyADMAMQAyADMAMQAyADMAMgAxADMAMQAyADMAMQAyADEAMgAzADEAMgAzADIAMQAzADIAMQAzADEAMgAzADEAMgAzADEALAAKACAAIAAgACAAIAAgAGMAbABhAHMAcwBGAGkAZQBsAGQAOgAgAGMAbABhAHMAcwAgAG0AeQBDAGwAYQBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAcwBzAHMAIAB7ACAAYwBvAG4AcwB0AHIAdQBjAHQAbwByACgAKQAgAHsAfQB9ACwACgAgACAAIAAgACAAIABmAHUAbgBjAHQAaQBvAG4AQwBhAGwAbAA6ACAAbABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnAEwAbwBuAGcATABvAG4AZwBMAG8AbgBnACgAKQAsAAoAIAAgAAkAYQByAHIAYQB5ADoAIABbADEALAAyACwAMwAsADQALAA1ACwANgAsADcALAA4ACwAOQAsADEALAAyACwAMwAsADQALAA1ACwANgBdACwACgAgACAAfQAKAH0ACgA=) and [Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEByAjAJgMyfdrAnQvIowk-Ui41AGgAIMdri3d8aaOfv1UA3AB0oAGzgwGo6AHMAzjABOASygyGAXiaUy3VuXal9FQSPGTpaqAFcAtgCM4izQx18WnNnqqfdwsRJSsvbKMgCSai4AQqERMAAUQiAADPbo6RmZWdk5uXm5SQCU-maB8AoA8vYAVnBgklrAIgwMCipqAGLKcKIAJkjaHrqGvljevOz8dM2tSqoyACpwtgAOogCG8OgDAAZuk0NcIxO6O9NQLW3zS6sb8Ji7+8MnY+wiRqPEZzM2Dk5dPX6rkOBxeeGOxmI5xaIXCsAGMThCSSqXyaPRGJyRWhDDAGzkcgBfQGePWBIYtgAngBhfEE+kMxlM5ks1nk4C46Btaz1CCKeKFBjAAC+wpxADNrFB6spoNT1qJRANLDIADKydVqTVqjW6rV6nX6tQCiVSmVyhWiADqyhgAAsAArrRTrWxyZUG7Vez0+o2GmTxdB0TB0bB0AAsdAArHQAGx0EWFHEzZ0uykDADaQZDYcjMfjAHY6AAOOgATjo2dDEejcYAujioHAFHBelVavUBk0Li1e1dOt1iYMwWRIeNIQR6DNe7N2otlmtNnBtgw9iDnmOIZ8CN8ezP+-PbkuHqunuMjmRpwwPs90LuZy1fo5FESgWfjhedBOg1eWqSCa+JJ0hSNJ0my4EQRBQqclA3K8vygoimKv4MJK0owLKUDyoqHp+t6eG+v6+EBkmMxCDAqbrOmDBZsG1Z5nGdBFqWFZVrmtaxg2MzCiIPFQCAdAgBAKwYVyyCgKmEAAO5OooCByMgIAKlJVEKYJ9gumAADWEgAMqunAqqqHAyDigqchwOpmk6TAukrOsYDzMgSjWJZIDLI4vS9K2qrrGo1jrDIcAdHytibBhaiKes1gwBAAkgHaMC2Nadq2s29lgHAunybaygAG62pSilgAS8WqBZigwA6LoyGFpnmW51RyAAHrp8ziAAitYEDwPVogWYJ9mKBVin2OsjiiPFKztDANq9PayDhskg2KBAFlWi6KyKdNzZOHlJmCQAjt18DVcJCkoGSAC0Tatq28VycdyhydVgV1UgZn9W5Fm2MozmKK5glyO1cBdT1JkfQ1gkUfYc0LUgIYgEo6zKKI8zUhAtjve5chRvF1gWQs40XZ9A0gHlrkRN5sC6WAKgiQAglAvS6TAlLiH1FmikAA). 

 It seems that prettier uses the same logic for object member and assignment (other cases?). I'm going to check all variants from `JsAnyExpression`. But I'm not sure that is the best options to solve the problem.
1. Add  `soft_line_indent_or_space` only for expressions which prettier breaks over two line in `property_object_member.rs`.  
2. Wrap individual expression in `soft_block_indent`.

**Comment by Dominionys** [comment]
It seems that we need to implement something like [prettier does for property](https://github.com/prettier/prettier/blob/5b113e71b1808d6916f446c3aa49c3c53e3bdb98/src/language-js/print/property.js#L92). It uses [assignment](https://github.com/prettier/prettier/blob/5b113e71b1808d6916f446c3aa49c3c53e3bdb98/src/language-js/print/assignment.js#L25) which chooses [layout](https://github.com/prettier/prettier/blob/5b113e71b1808d6916f446c3aa49c3c53e3bdb98/src/language-js/print/assignment.js#L93) for object member.

Does Rome have this layout function/enum? 
What solution is better for this issue? Implement layout function only for object member or for assignment too?

**Comment by ematipico** [comment]
> It uses [assignment](https://github.com/prettier/prettier/blob/5b113e71b1808d6916f446c3aa49c3c53e3bdb98/src/language-js/print/assignment.js#L25) which chooses [layout](https://github.com/prettier/prettier/blob/5b113e71b1808d6916f446c3aa49c3c53e3bdb98/src/language-js/print/assignment.js#L93) for object member.

Assignment layout is just an internal signal that they use to print arrow functions, it's not used inside their printer.

- this is it's used for the arrow functions: https://github.com/prettier/prettier/blob/5b113e71b1808d6916f446c3aa49c3c53e3bdb98/src/language-js/print/function.js#L252
- this is where it's used inside the assignment: https://github.com/prettier/prettier/blob/5b113e71b1808d6916f446c3aa49c3c53e3bdb98/src/language-js/print/assignment.js#L37-L75


As you can see, each option create a different IR. 

> Am I on the right way?😬

I haven't looked my at their code unfortunately, so I am not sure. Even if the examples shows an assignment, the issue is about the members of the objects. Check this [example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAJT7D4A6U+VN+ATnDOgzcNbZSDABY4BnALSChAQyEA3OAwCeQgDbQA5kIDWceWKgATIXzjiBAnMqgBbBDCEDeEdAr0AjQwAd016Pt6GocAB7WCjh+3EictPgQDACyYrIuAJIAguYxgpg6MgIw2johysm6iQASYtIAyswVEJZ8BQDqDCqJUDGyAMLQqKakADQR3GDaNrVw0IYBrgpiIWH4fGIw-dQAvmsgfSAQrrjQAsigYgzNAO4ACscIByhiCqfxB1tODGJgGjAVYpYAMiFwyFQdwEcGer3e1VcbwKyBgDHQoJAcHMLh0WR0P20ynQYmUcAAYtFzEtcFBlMgQGIPBBNiBeDBzAoGvx4AIoWA4FUoCZcJIcDBZBSwMZaSEQQwYOdXspiYDgYiAFYCfwVAoKOAARXQEHgcoUIK2UIY4opTjELgUtNcDBCMAaOB0fGQAA4AAyG5ogppiVwU61wcXSWkAR218ClOxulOEfjg6NpTFDOCYUtxsqQQP1iJB5hwsPh2bVmrDAIz8q2uSc9sdvGQACYK68cMEyV1zOmkQIAKy09AggAq5pumYNIEkCNaWVgFTANt2RR0FQF6r1INWqyAA), where I used the object inside a function. The formatting is the same. 

>  What solution is better for this issue? Implement layout function only for object member or for assignment too?

I would focus, for now, on the object literal part and ignore the assignment. I believe we have another issue to track it. Do you think the issues are somehow related? If so, we can think about creating a function that will be used by both nodes. But for now let's stick to the object literal.

[If you check Prettier's IR](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAE8DOMDyARgFZxhYC8mwAOlJpgGYCuU5AltAMICGqqAdXYwAFgAUeAJx4BbHEkypoAcwAyK9VDUadWzdr26DygBQBGADQAmCwGYLAFgsBWCwDYLwAL4BKC3TovOhALEAgABxhOKBxkUClJCAB3CUkEWJQ+JJ4AT1jQwmkwAGsMAGVZOFV2KDhkRj4cOAKi0pgy8J4wGuVkGElmZpA4GUI4ABNxidUeLWYeZTgAMQhJGR4YKK1kEB5mGAgQkBEYGUERYTgcTrA4MvThdgA3YRydsBx8kBqmyRgxaTKdb1RpDYg4AAeZR66AAiswIPAQagmqFOpJfjtCDwxqgjuFJDUYEJxqJkA4AAxoxJNATScI7AlXOCSJ51UIARwR8ABEQyuxwAFpahMJkc0lz2GkAQtgUgGiihk0ZOw+gMlTC4PDEXV5aDQjAcSSyUgbCB+jx2KgelwIDI5cMcM4jswmgAVHEZBWokBPQYASSgU1gZTAhMiAEEg2UYDl0Miml4vEA),  they use group IDs to add the breaking logic to a group:

```
  group(indent(line), { id: Symbol.for("assignment #1") }),
  lineSuffixBoundary,
  indentIfBreak( ... )
```

We can achieve something similar using our internal function called `if_group_with_id_fits_on_line` and `if_group_with_id_breaks`
