### ISSUE TITLE
Preserve new-lines after directives

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2437]
Prettier preserve's any empty line placed between a directive and the first statement, Rome doesn't. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#IgB1AHMAZQAgAHMAdAByAGkAYwB0ACIAOwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZgAxACgAKQAgAHsACgAgACAAIgB1AHMAZQAgAHMAdAByAGkAYwB0ACIAOwAKAH0ACgAKAGYAdQBuAGMAdABpAG8AbgAgAGYAMgAoACkAIAB7AAoAIAAgACcAbgBnAEkAbgBqAGUAYwB0ACcAOwAKACAAIABPAGIAagBlAGMAdAAuAGEAcwBzAGkAZwBuACgAdABoAGkAcwAsACAAewAgACQAbABvAGcALAAgACQAdQBpAGIATQBvAGQAYQBsACAAfQApADsACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABmADMAKAApACAAewAKAAoAIAAgACcAbgBnAEkAbgBqAGUAYwB0ACcAOwAKAAoAIAAgAE8AYgBqAGUAYwB0AC4AYQBzAHMAaQBnAG4AKAB0AGgAaQBzACwAIAB7ACAAJABsAG8AZwAsACAAJAB1AGkAYgBNAG8AZABhAGwAIAB9ACkAOwAKAAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZgA0ACgAKQAgAHsACgAgACAAJwBuAGcASQBuAGoAZQBjAHQAJwA7AAoAIAAgAAoAIAAgACIAdQBzAGUAIABzAHQAcgBpAGMAdAAiAAoACgAKACAAIABPAGIAagBlAGMAdAAuAGEAcwBzAGkAZwBuACgAdABoAGkAcwAsACAAewAgACQAbABvAGcALAAgACQAdQBpAGIATQBvAGQAYQBsACAAfQApADsACgB9AAoA)

## Input

```ts
"use strict";

function f1() {
  "use strict";
}

function f2() {
  'ngInject';
  Object.assign(this, { $log, $uibModal });
}

function f3() {

  'ngInject';

  Object.assign(this, { $log, $uibModal });

}

function f4() {
  'ngInject';
  
  "use strict"


  Object.assign(this, { $log, $uibModal });
}

```

## Prettier

```ts
"use strict";

function f1() {
  "use strict";
}

function f2() {
  "ngInject";
  Object.assign(this, { $log, $uibModal });
}

function f3() {
  "ngInject";

  Object.assign(this, { $log, $uibModal });
}

function f4() {
  "ngInject";

  "use strict";

  Object.assign(this, { $log, $uibModal });
}

```

## Rome

```ts
"use strict";
function f1() {
  "use strict";
}

function f2() {
  "ngInject";
  Object.assign(this, { $log, $uibModal });
}

function f3() {
  "ngInject";
  Object.assign(this, { $log, $uibModal });
}

function f4() {
  "ngInject";

  "use strict";
  Object.assign(this, { $log, $uibModal });
}
```

## Expected
Rome's formatting to match prettier's.

**Comment by IWANABETHATGUY** [comment]
Little mistake, the playground link that you pasted is wrong.
https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#IgB1AHMAZQAgAHMAdAByAGkAYwB0ACIAOwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZgAxACgAKQAgAHsACgAgACAAIgB1AHMAZQAgAHMAdAByAGkAYwB0ACIAOwAKAH0ACgAKAGYAdQBuAGMAdABpAG8AbgAgAGYAMgAoACkAIAB7AAoAIAAgACcAbgBnAEkAbgBqAGUAYwB0ACcAOwAKACAAIABPAGIAagBlAGMAdAAuAGEAcwBzAGkAZwBuACgAdABoAGkAcwAsACAAewAgACQAbABvAGcALAAgACQAdQBpAGIATQBvAGQAYQBsACAAfQApADsACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABmADMAKAApACAAewAKAAoAIAAgACcAbgBnAEkAbgBqAGUAYwB0ACcAOwAKAAoAIAAgAE8AYgBqAGUAYwB0AC4AYQBzAHMAaQBnAG4AKAB0AGgAaQBzACwAIAB7ACAAJABsAG8AZwAsACAAJAB1AGkAYgBNAG8AZABhAGwAIAB9ACkAOwAKAAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZgA0ACgAKQAgAHsACgAgACAAJwBuAGcASQBuAGoAZQBjAHQAJwA7AAoAIAAgAAoAIAAgACIAdQBzAGUAIABzAHQAcgBpAGMAdAAiAAoACgAKACAAIABPAGIAagBlAGMAdAAuAGEAcwBzAGkAZwBuACgAdABoAGkAcwAsACAAewAgACQAbABvAGcALAAgACQAdQBpAGIATQBvAGQAYQBsACAAfQApADsACgB9AA==
