### ISSUE TITLE
Empty import/export assertions

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2440]
Prettier strips empty `import`/`export` assertions whereas Rome retains them. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=true&sourceType=module#ZQB4AHAAbwByAHQAIAAqACAAYQBzACAAYgBhAHIAIABmAHIAbwBtACAAIgBiAGEAcgAuAGoAcwBvAG4AIgAgAGEAcwBzAGUAcgB0ACAAewAgAH0ACgBlAHgAcABvAHIAdAAgACoAIABhAHMAIABiAGEAegAgAGYAcgBvAG0AIAAiAGIAYQB6AC4AagBzAG8AbgAiACAAYQBzAHMAZQByAHQAIAB7ACAALwAqACAAYwBvAG0AbQBlAG4AdAAgACoALwAgAH0ACgAKAGkAbQBwAG8AcgB0ACAAKgAgAGEAcwAgAGIAYQByACAAZgByAG8AbQAgACIAYgBhAHIALgBqAHMAbwBuACIAIABhAHMAcwBlAHIAdAAgAHsAIAB9AAoAaQBtAHAAbwByAHQAIAAqACAAYQBzACAAYgBhAHoAIABmAHIAbwBtACAAIgBiAGEAegAuAGoAcwBvAG4AIgAgAGEAcwBzAGUAcgB0ACAAewAgAC8AKgAgAGMAbwBtAG0AZQBuAHQAIAAqAC8AIAB9AA==)

## Input

```ts
export * as bar from "bar.json" assert { }
export * as baz from "baz.json" assert { /* comment */ }

import * as bar from "bar.json" assert { }
import * as baz from "baz.json" assert { /* comment */ }
```

## Prettier

```ts
export * as bar from "bar.json";
export * as baz from "baz.json" /* comment */;

import * as bar from "bar.json";
import * as baz from "baz.json" /* comment */;

```

## Rome

```ts
export * as bar from "bar.json" assert {};
export * as baz from "baz.json" assert { /* comment */ };

import * as bar from "bar.json" assert {};
import * as baz from "baz.json" assert { /* comment */ };

```

## Expeced

Rome to remove empty import assertions to match Prettier's formatting.

**Comment by ematipico** [comment]
I am not sure this is the right thing to do here. Removing a whole node seems a lot to me. 

If the user is typing and didn't write anything inside the block, hits save (and has format on save), they have to write everything again...

I have mixed feeling.

**Comment by Boshen** [comment]
I think this is the perfect case where CST shines, prettier doesn't know whether the assertion exists, it simply checks for an empty array.

```javascript
function printImportAssertions(path, options, print) {
  const node = path.getNode();
  if (isNonEmptyArray(node.assertions)) {
    return [
      " assert {",
      options.bracketSpacing ? " " : "",
      join(", ", path.map(print, "assertions")),
      options.bracketSpacing ? " " : "",
      "}",
    ];
  }
  return "";
}
```

https://github.com/prettier/prettier/blob/c50f2bbe3075757840bbd7ed941647a9bde84266/src/language-js/print/module.js#L267-L279

**Comment by MichaReiser** [comment]
> I think this is the perfect case where CST shines, prettier doesn't know whether the assertion exists, it simply checks for an empty array. This is our killing feature!
> 
> ```js
> function printImportAssertions(path, options, print) {
>   const node = path.getNode();
>   if (isNonEmptyArray(node.assertions)) {
>     return [
>       " assert {",
>       options.bracketSpacing ? " " : "",
>       join(", ", path.map(print, "assertions")),
>       options.bracketSpacing ? " " : "",
>       "}",
>     ];
>   }
>   return "";
> }
> ```
> 
> https://github.com/prettier/prettier/blob/c50f2bbe3075757840bbd7ed941647a9bde84266/src/language-js/print/module.js#L267-L279

Do you mean this is actually unintentional?

**Comment by Boshen** [comment]
> Do you mean this is actually unintentional?

Yes I think this is unintentional. I thought the whole point of using CST is to avoid problems like this, where we typed a partial code block and hit save, and boom prettier deletes it, but Rome won't.

**Comment by cpojer** [comment]
Agree with @Boshen on this one. I think it is fine to keep the empty assertion.

**Comment by MichaReiser** [comment]
Closing because the current behaviour is the intended behaviour
