### ISSUE TITLE
Preferred string quotes

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2443]
Prettier detects the ideal quote to use for a string so that the least amount of escaped quotes are necessary: 

```
function getPreferredQuote(rawContent, preferredQuote) {
  /** @type {{ quote: '"', regex: RegExp, escaped: "&quot;" }} */
  const double = { quote: '"', regex: /"/g, escaped: "&quot;" };
  /** @type {{ quote: "'", regex: RegExp, escaped: "&apos;" }} */
  const single = { quote: "'", regex: /'/g, escaped: "&apos;" };

  const preferred = preferredQuote === "'" ? single : double;
  const alternate = preferred === single ? double : single;

  let result = preferred;

  // If `rawContent` contains at least one of the quote preferred for enclosing
  // the string, we might want to enclose with the alternate quote instead, to
  // minimize the number of escaped quotes.
  if (
    rawContent.includes(preferred.quote) ||
    rawContent.includes(alternate.quote)
  ) {
    const numPreferredQuotes = (rawContent.match(preferred.regex) || []).length;
    const numAlternateQuotes = (rawContent.match(alternate.regex) || []).length;

    result = numPreferredQuotes > numAlternateQuotes ? alternate : preferred;
  }

  return result;
}
```

[Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=true&sourceType=module#IAAvAC8AIABTAGkAbgBnAGwAZQAgAGQAbwB1AGIAbABlACAAcQB1AG8AdABlAC4ACgAoACcAIgAnACkAOwAKACgAJwAiACcAKQA7AAoAIAAKACAALwAvACAAUwBpAG4AZwBsAGUAIABzAGkAbgBnAGwAZQAgAHEAdQBvAHQAZQAuAAoAKAAiACcAIgApADsACgAoACIAJwAiACkAOwAKAAoALwAvACAATwBuAGUAIABvAGYAIABlAGEAYwBoAAoAIgBcACIAJwAiADsACgAnACIAXAAnACcAOwAKAAoALwAvACAATwBuAGUAIABvAGYAIABlAGEAYwBoACAAdwBpAHQAaAAgAHUAbgBuAGUAYwBlAHMAcwBhAHIAeQAgAGUAcwBjAGEAcABlAHMALgAKACgAIgBcACIAJwAiACkAOwAKACgAIgBcACIAJwAiACkAOwAKACAACgAgAC8ALwAgAE0AbwByAGUAIABkAG8AdQBiAGwAZQAgAHEAdQBvAHQAZQBzACAAdABoAGEAbgAgAHMAaQBuAGcAbABlACAAcQB1AG8AdABlAHMALgAKACgAJwAiAFwAJwAiACcAKQA7AAoAKAAnACIAXAAnACIAJwApADsACgAgAAoAIAAvAC8AIABNAG8AcgBlACAAcwBpAG4AZwBsAGUAIABxAHUAbwB0AGUAcwAgAHQAaABhAG4AIABkAG8AdQBiAGwAZQAgAHEAdQBvAHQAZQBzAC4ACgAoACIAXAAiACcAJwAiACkAOwAKACgAIgBcACIAJwAnACIAKQA7AAoAIAAKACAALwAvACAAVAB3AG8AIABvAGYAIABlAGEAYwBoAC4ACgAoACIAXAAiAFwAIgAnACcAIgApADsACgAoACIAXAAiAFwAIgAnACcAIgApADsACgAKAAoAKAAiAEgAZQAnAHMAIABzAGEAeQBpAG4AJwA6ACAAXAAiAEgAbwB3ACcAcwAgAGkAdAAgAGcAbwBpAG4AJwA/AFwAIgAgAEQAbwBuACcAdAAgAGEAcwBrACAAbQBlACAAdwBoAHkALgAiACkAOwAKACgAIgBIAGUAJwBzACAAcwBhAHkAaQBuACcAOgAgAFwAIgBIAG8AdwAnAHMAIABpAHQAIABnAG8AaQBuACcAPwBcACIAIABEAG8AbgAnAHQAIABhAHMAawAgAG0AZQAgAHcAaAB5AC4AIgApADsACgAgAAoAIAAvAC8AIABTAG8AbQBlAHcAaABhAHQAIABtAG8AcgBlACAAcgBlAGEAbAAtAHcAbwByAGQAIABlAHgAYQBtAHAAbABlACAAMgAuAAoAKAAnAHYAYQByACAAYgBhAGMAawBzAGwAYQBzAGgAIAA9ACAAIgBcAFwAIgAsACAAZABvAHUAYgBsAGUAUQB1AG8AdABlACAAPQAgAFwAJwAiAFwAJwA7ACcAKQA7AAoAKAAnAHYAYQByACAAYgBhAGMAawBzAGwAYQBzAGgAIAA9ACAAIgBcAFwAIgAsACAAZABvAHUAYgBsAGUAUQB1AG8AdABlACAAPQAgAFwAJwAiAFwAJwA7ACcAKQA7AA==)

Rome should do the same when printing string literal tokens. 

## Input

```ts
 // Single double quote.
('"');
('"');
 
 // Single single quote.
("'");
("'");

// One of each
"\"'";
'"\'';

// One of each with unnecessary escapes.
("\"'");
("\"'");
 
 // More double quotes than single quotes.
('"\'"');
('"\'"');
 
 // More single quotes than double quotes.
("\"''");
("\"''");
 
 // Two of each.
("\"\"''");
("\"\"''");


("He's sayin': \"How's it goin'?\" Don't ask me why.");
("He's sayin': \"How's it goin'?\" Don't ask me why.");
 
 // Somewhat more real-word example 2.
('var backslash = "\\", doubleQuote = \'"\';');
('var backslash = "\\", doubleQuote = \'"\';');
```

## Prettier

```ts
// Single double quote.
('"');
('"');

// Single single quote.
("'");
("'");

// One of each
("\"'");
("\"'");

// One of each with unnecessary escapes.
("\"'");
("\"'");

// More double quotes than single quotes.
('"\'"');
('"\'"');

// More single quotes than double quotes.
("\"''");
("\"''");

// Two of each.
("\"\"''");
("\"\"''");

("He's sayin': \"How's it goin'?\" Don't ask me why.");
("He's sayin': \"How's it goin'?\" Don't ask me why.");

// Somewhat more real-word example 2.
('var backslash = "\\", doubleQuote = \'"\';');
('var backslash = "\\", doubleQuote = \'"\';');

```

## Rome

```ts
// Single double quote.
('"');
('"');

// Single single quote.
("'");
("'");

// One of each
"\"'";
'"\'';

// One of each with unnecessary escapes.
("\"'");
("\"'");

// More double quotes than single quotes.
('"\'"');
('"\'"');

// More single quotes than double quotes.
("\"''");
("\"''");

// Two of each.
("\"\"''");
("\"\"''");

("He's sayin': \"How's it goin'?\" Don't ask me why.");
("He's sayin': \"How's it goin'?\" Don't ask me why.");

// Somewhat more real-word example 2.
('var backslash = "\\", doubleQuote = \'"\';');
('var backslash = "\\", doubleQuote = \'"\';');

```

## Expected

Rome's formatting to match prettier's.

**Comment by ktfth** [comment]
Learning the new code base of Rome, someone can point out a place to begin with that contribution?

**Comment by MichaReiser** [comment]
> Learning the new code base of Rome, someone can point out a place to begin with that contribution?

https://github.com/rome/tools/blob/77ab407a94e0329fbb8eb65a7d2c39a11a7b1484/crates/rome_js_formatter/src/utils/mod.rs#L614-L637

This part is responsible for formatting string literals but currently always picks the option specified in the options.

**Comment by ematipico** [comment]
I will look into this

**Comment by ematipico** [comment]
Removing the "good first issue" because it's a sensitive part of the formatter (string manipulation)
