### ISSUE TITLE
Sort regular expression flags

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2445]
Prettier sorts the regular expression flags and so should Rome's formatter [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=false&jsx=true&sourceType=module#LwBbAC8AXQBcAC8AXAB1ADAAYQBCAGMALwBtAGcAaQA7AAoA)

## Input 

```ts
/[/]\/\u0aBc/mgi;
```

## Prettier

```ts
/[/]\/\u0aBc/gim;
```

## Rome

```ts
/[/]\/\u0aBc/mgi;
```

## Expected

Rome's formatting to match Prettier's

**Comment by IWANABETHATGUY** [comment]
Since our `regex literal` is `SyntaxToken` would it be alright to use `regex` extract flag and rewrite when formatting `JsRegexLiteralExpression`
[read_regex](https://github.com/IWANABETHATGUY/tools/blob/03dc7236ff33f4a8177ceddb0b608d05947f7801/crates/rome_js_parser/src/lexer/mod.rs#L1536)

**Comment by ematipico** [comment]
I think we can achieve the same using string manipulation. Is there something that needs `regex` that we can't do ourselves?

**Comment by IWANABETHATGUY** [comment]
> ?

https://tc39.es/ecma262/#prod-RegularExpressionLiteral 
I didn't see spec before.
You are right, indexOf is enough for us.
