### ISSUE TITLE
📎 Create rome environment command

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#2460]
### Description

When making bug reports the templates asks users for environment information. It *suggests* `OS and OS version, CPU architecture, installation method, etc.`.

Rome previously had a command `rome rage --summary` (#852) that would output all relevant info for the user to copy & paste.

This would simplify bug reports and debugging.

Specifically:
- Rome version (`env!("CARGO_PKG_VERSION")`)
- OS & arch (https://doc.rust-lang.org/std/env/consts/index.html)
- Node version
- Terminal info
- Flags (? if we already have any)

**Comment by leops** [comment]
Adding a note here: when running the CLI through the npm package, the node.js wrapper script could inject a few "private" environment variables to let the prebuilt binary know it's running through the wrapper, and what version of the package is being used (it could also inject the value of `process.version` to let the binary know about the version of node that's in use)

**Comment by NicholasLYang** [comment]
I like this! I was also thinking of having something that'd make it easy to open an issue or even have a panic handler that says "hey, Rome crashed, here's a template to open an issue"

**Comment by IWANABETHATGUY** [comment]
Maybe we could reference this package https://github.com/tabrindle/envinfo

**Comment by ematipico** [comment]
> Maybe we could reference this package [tabrindle/envinfo](https://github.com/tabrindle/envinfo)

I think we can reuse what we had in Rome classic :) which has an output that is more tailored to our needs


<img width="907" alt="Screenshot 2022-07-19 at 14 14 26" src="https://user-images.githubusercontent.com/602478/179758977-e9f0f458-6ccf-46f3-97b0-137775be0f04.png">


Here the code: https://github.com/rome/tools/blob/6b47011c5f3d5ed783855b821cdbc9cf1d687266/internal/cli-environment/index.ts

**Comment by MichaReiser** [comment]
Rome now has a `rome rage` command that you can use to get that kind of information
