### ISSUE TITLE
📎 Improve the formatting of call chains

### ISSUE THREAD

**Issue by leops** [rome/tools#2475]
### Description

Currently the call expression formatter makes a decision on whether or not to introduce a new group for a "call chain" by partially emulating the way the printer works and inspecting the emitted IR to check for hard line breaks. This logic breaks down if the content of the expression contain hard or soft line breaks depending on the input source code (like in the change proposed in #2458), since the formatting of the entire expression is no longer stable between runs.

Since we're aiming for a better compatibility with Prettier, the fix for this would be to use the logic Prettier is using to decide on how to print call chains as a direct reference for our implementation instead of the current ad-hoc solution.

**Comment by ematipico** [comment]
I believe this is what Prettier does to understand when a call chain should break: https://github.com/prettier/prettier/blob/main/src/language-js/print/member-chain.js#L381-L405
