### ISSUE TITLE
Fails to build from source with `--features serde1`

### ISSUE THREAD

**Issue by lnicola** [rome/tools#2486]
### What happened?

```
error[E0432]: unresolved import `crate::syntax::RawLanguage`
 --> crates/rome_rowan/src/serde_impls.rs:5:24
  |
5 |     syntax::{Language, RawLanguage, SyntaxNode, SyntaxToken},
  |                        ^^^^^^^^^^^
  |                        |
  |                        no `RawLanguage` in `syntax`
  |                        help: a similar name exists in the module: `Language`
```

That's because the path to `RawLanguage` is `crate::raw_language`, not `crate::syntax`. I would have sent a PR, but I don't know whether you want a to re-export it from `syntax` or not.

Spotted in https://github.com/rust-lang/rust-analyzer/issues/12062.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by NicholasLYang** [comment]
Fixed by #2509
