### ISSUE TITLE
Add .gitignore support

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2492]
Currently we have hard coded folders that we ignore. We should change that to follow the .gitignore

**Comment by ematipico** [comment]
What are the requirements of `.gitignore`? Is it necessary?

My concern is that we should not ignore files that are ignored by the VCS. Mainly because Rome is not a VCS and there's value in processing files that are ignored.

It can provide value for operations that involve VCS, so we should carefully understand the when and how.

**Comment by NicholasLYang** [comment]
IMO we should revisit this along with #2493. It's an extremely common use case and has prior art in ripgrep and fd.

**Comment by ematipico** [comment]
Should we add support to of `.gitignore` file only when we are inside a project that has our config file? (`rome.json`)

We don't have support of a configuration file yet, but once we do, we could add support for `.gitignore` too.

**Comment by NicholasLYang** [comment]
That could work, although we'd have to figure out a way to make that clear to users. It might be very confusing to have Rome obey the .gitignore, then when a `rome.json` file is added, suddenly it ignores the `.gitignore`.

**Comment by ematipico** [comment]
> IMO we should revisit this along with #2493. It's an extremely common use case and has prior art in ripgrep and fd.

I've been thinking more about this, and I am more convinced that we should not supported this out of the box (maybe behind flag). The examples you mentioned are different from us (they don't write files, for example). If you have examples of CLIs similar to Rome (formatter, bundler, test framework, linter, etc.), that would build your case.

Still, I think it should an opt in feature, if we really want to support it.

**Comment by ematipico** [comment]
Closing

**Comment by IanVS** [comment]
Hi, just wanted to voice my personal experience.  I just downloaded rome to try it out, and was surprised when it tried to format files that are in my .gitignore.  I find it mildly annoying that I need to duplicate my .gitignore in my rome config.  Feel free to ignore me, I'm just providing a bit of unsolicited feedback.  :)

**Comment by mbrevda** [comment]
does #https://github.com/rome/tools/pull/2493 help here?

**Comment by ematipico** [comment]
> Hi, just wanted to voice my personal experience. I just downloaded rome to try it out, and was surprised when it tried to format files that are in my .gitignore. I find it mildly annoying that I need to duplicate my .gitignore in my rome config. Feel free to ignore me, I'm just providing a bit of unsolicited feedback. :)

Do you know if other tools - e.g. prettier, eslint, esbuild, etc. - ignore files inside the `.gitignore` folder automatically?

**Comment by ematipico** [comment]
Yeah, I think it makes sense to try to cover the majority of the cases and meet the users halfway. 

Still, I think we should provide an option to opt out this feature - if it becomes the default. I know it seems weird, but as a web developer - and especially a tool developer - many times I wanted to run locally the very tool on some files while keeping them ignored in `git`. Surely these use cases are way more less then the average, so opt-out  the `.gitignore` might work.

**Comment by Th3S4mur41** [comment]
There is currently a [similar discussion going on in prettier](https://github.com/prettier/prettier/issues/8048)...
This shows that there is a need at least for an option to reuse .gitignore in the formatter, even though not as the only config for ignoring files.

**Comment by ematipico** [comment]
Yeah, it makes sense to add support for it. My only concern was a way to opt out of this feature. Other than that, I think we should make a PR to add support for it!
