### ISSUE TITLE
🐛 Fail to format `Oq = wq(1 .toString);`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2501]
### Environment information

```bash
Latest version of Rome
```

### What happened?

Given `Oq = wq(1 .toString);`

The formatter doesn't preserve the space. [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=true&sourceType=module#TwBxACAAPQAgAHcAcQAoADEAIAAuAHQAbwBTAHQAcgBpAG4AZwApADsACgA=)

### Expected result

It should match Prettier's formatting and not result in a broken code.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by mrkldshv** [comment]
I'd like to work on it!
