### ISSUE TITLE
📎 Handle different rome versions in playground

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2518]
### Description

The first implementation of multiple Rome versions uses a very simple approach of just building the playground on each commit and having these instances in different folders in an S3 bucket. This is great for a simple solution, but it does make it harder to add features like:

- Linking the PR to the playground version
- Compare two different versions of Rome, like for a pull request
- Keeping a list of old playground versions

Instead, we can have one playground that uses client side routing to dynamically import the version of Rome requested. Basically, we take a url like `https://play.rome.tools/1d07d6a`, use the commit hash to dynamically import `1d07d6a/rome_playground.js`, then load that instance of Rome.

If someone is willing to take this on, I'd be happy to give them guidance.

**Comment by NicholasLYang** [comment]
Sure! I'll warn you, this might be an involved task, but I'm happy to help if you're willing to take this on. Basically, I'd like the playground to use `import("1d07d6a/rome_playground.js")` instead of a static import, because then we can load multiple versions of Rome at once. Are you familiar with dynamic imports?

**Comment by mduclehcm** [comment]
I understood the concept of dynamic import. But I don't really know how could we compile multiple version rome and output to the same folder at one.
My idea: we compile and store all version of rome in some cdn. Playground can import any version of rome via <script/> tag.

```
importScript(HARD_CODE_CDN_SERVER + `${commit}/rome_playground.js\`) // umd or amd
```

**Comment by NicholasLYang** [comment]
We have a deploy script that runs on every commit that builds Rome and uploads it to an S3 bucket under a folder named with the git commit hash. You could use that to load the different versions of Rome.

**Comment by ematipico** [comment]
This has been implemented
