### ISSUE TITLE
Groups that always break

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2532]
This might not be needed in our IR until we have.

Prettier have groups that always break that are used in some cases: [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATOA6GALBACkIEoACAXgD4zgBfE7VAQwAdCAdKDmYMgMwgAnJGTj9+cMnS4kQAGhARWMAJbQAzslDMhQiAHcACroRaUzADYHmATy2KARkOZgA1nBgBlZqjgAZVSg4ZH4rDTgnF3dPL1ZXIIBzZBghAFdIkDhURzgMLAx-ZihEtOZEuAAxYRYYNRLkEGY0mAgFEDwYVEsAdTxVeA14sDgvMwHVADcB20awDQcQIIihGCMXRJZQ8MyAKw0ADy8kyzgARTSIeG3LCMV4oRXGmFtWOA0wIVUVdtYv2B6qgw+GQAA4AAz3fQRHouViNP7vOBCSYhRQAR0u8HWynMTQ0AFpgnk8u0hHBMapyetylskGFbpkIqhVCl0kyTucsSF6TtFDBmI5AcC8MgAEz8lyqSxJADCEFQdKyGgArO00hEACqC8ypDKKSYZACSUCwsC8n2+MAAgqavC9TjcInQ6EA)

When you see a `{ shouldBreak: true }`. We should understand if we really need this modality or not.

**Comment by MichaReiser** [comment]
It's unclear to me what the benefit of this is. The main intent of a `group` is to have some content that must be printed in flat mode. Setting `shouldBreak: true` undoes that behaviour, which prints the content the exact same way as if it wouldn't have been wrapped in a group. The only difference is that it will also expand all parent groups. 

I think we can get this behaviour without having to support `should_break` by either creating a helper or write the following IR directly

```
// Prettier
group(content, { shouldBreak: true });

// Rome

format_elements![content, expand_parent()]
```

`expand_parent` expands all parent groups.

**Comment by MichaReiser** [comment]
Let's close this for now and re-open the issue if there's a use case where this is needed. Shouldn't be hard to add.
