### ISSUE TITLE
Document infrastructure and behavior of the printer

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2550]
As agreed during our last standup, I created this is to track and improve our internal documentation of our printer

**Comment by yassere** [comment]
This is on hold for now because we’re considering rewriting the printer to make its behavior more closely match Prettier.

**Comment by MichaReiser** [comment]
@ematipico are you looking for a more extensive documentation than what's exposed in the [API documentation](https://rome.github.io/tools/rome_formatter/prelude/index.html)

**Comment by ematipico** [comment]
I think we did a good job :) happy to close it
