### ISSUE TITLE
📎 Format JSX Elements with Facebook Translation Tag

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2552]
### Description

Prettier has specific logic for formatting a JSX element with a Facebook translation tag. We currently do not handle this. At some point, we probably should, assuming Facebook still has this need.

Relevant issues/PRs:
- https://github.com/prettier/prettier/issues/1581#issuecomment-300975032.
- https://github.com/prettier/prettier/issues/2233

**Comment by cpojer** [comment]
Does this matter anywhere except Facebook? Facebook uses Flow, so wouldn't be able to use Flow anyway. It's open source here: https://github.com/facebook/fbt but I don't know how many people use it with TypeScript. I don't think this matters a lot right now.

**Comment by MichaReiser** [comment]
Is the logic specific for `fbt`, meaning Prettier tests if the element name is `fbt` or is the rule about how Prettier formats e.g. commas following another element?

**Comment by MichaReiser** [comment]
I think it's OK for us to close this for now. If you read this in the future and this is something that's dear to you, please open a new issue asking for adding support with examples why adding it is important.
