### ISSUE TITLE
📎 Run benchmark integration tests on CI

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2554]
### Description

We have benchmarks that profile our formatter / parser against popular JavaScript libraries but these only run when they are explicitly triggered by a `bench_formatter` or `bench_parser` comment. While this is intentional, it would still be valuable to test our parser/formatter against popular libraries to make sure they don't panic. 

## Goal

Add a new or extend our existing PR pipeline and run the following commands. 

```
cargo bench_formatter --criterion=false
cargo bench_parser --criterion=false
```

The job should fail if either of the commands fails. 

## Extensions

Only run the formatter/parser command if any of their dependencies changed.

**Comment by IWANABETHATGUY** [comment]
> .

The benchmark like `!bench_formatter` would take a lot of time , for examples:
![image](https://user-images.githubusercontent.com/17974631/167250685-75642bfe-9e1a-4eb0-917a-ac885272700f.png)
about 25m, 
Would it introduce too heavy time during a contribution workflow if we add benchmark job in CI?

**Comment by MichaReiser** [comment]
It takes less time to run them if you pass '--criterion=false'. It then only runs each file once. Obviously, this isn't creating statistical correct data but we don't care about that here.

**Comment by IWANABETHATGUY** [comment]
> 

Got it.

**Comment by ematipico** [comment]
What's the status of this issue @MichaReiser ?

**Comment by MichaReiser** [comment]
Let's close it. I still see this as being valuable to catch regressions early
