### ISSUE TITLE
☂️ Internal Tooling

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2616]
### Description

Internal tools are helpful for both the Rome core team and for other contributors. They let people gain an understanding of our various data structures; they facilitate debugging and bug reporting; they help with comparing to other tools. They're also great because they're (relatively) easy to make without too much knowledge of the codebase. 

That said, we shouldn't devote too much time to internal tooling, as we do need to ship the actual product, and internal tooling can be a great way of procrastinating that actual work.

My hope is that by documenting potential internal tooling tasks, contributors can potentially take them over.

- [x] #2617
- [x] #2618
- [x] #2619
- [x] #2620 
- [x] #2621 
- [x] #2587
- [x] #2622 
- [ ] #2984
- [x] #3010

**Comment by MichaReiser** [comment]
Closing, we can track the code mirror plugin in it's own issue.
