### ISSUE TITLE
📎 Generated playground links for tests

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2618]
### Description

Currently when I debug a failing test, I have to copy the code into a playground manually. Instead, we could have the link automatically generated. This could be pretty simple to implement, as stdout is only shown on a test failure, so we could just preemptively print a playground link and it'll show up on a test failure.

Playground links pass the code via a base64 encoded string appended to the url after a `#`. Therefore we could do something like:
```
format!("http://localhost:3000/#{}", code)
```

Note that we produce a localhost link, because play.rome.tools is main by default. We could also print out a command for starting the playground if necessary.

**Comment by MichaReiser** [comment]
@NicholasLYang is the goal to create these links on CI test failures? It will be hard for others to contribute this behaviour because they aren't allowed to run CI jobs.
