### ISSUE TITLE
📎 Tiling Views

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2620]
### Description

There are some views I'd like to see at the same time, such as Rome IR and Prettier IR. Currently we're using tabs as our abstraction for navigating views, but it might be better to use tiles. Tiles allow multiple views to be available at once, and allows us to resize views that may not need to take up a lot of space.

**Comment by andreyvolfman** [comment]
Hello! I have a proposal how to implement this feature. I created several drafts.
If you have any suggestions how to improve this mockups please let me know.
If everything is okay I will take this issue and send PR.
Thanks!

<img width="1920" alt="Screenshot 2022-06-03 at 10 44 12 AM" src="https://user-images.githubusercontent.com/36608344/171812644-6d6e987b-51f9-4c30-99bd-b7a0224c47c9.png">

<img width="1920" alt="Screenshot 2022-06-03 at 10 48 08 AM" src="https://user-images.githubusercontent.com/36608344/171812679-a4a554c7-7fbb-4ea0-865c-0e3eee7b2a77.png">

<img width="1920" alt="Screenshot 2022-06-03 at 10 41 42 AM" src="https://user-images.githubusercontent.com/36608344/171812714-5d9406cf-86dc-434f-b2f3-206f28c089ce.png">

**Comment by andreyvolfman** [comment]
Updated drafts and mobile layout:

**1. Desktop appearance**
By default `Input`, `Rome output` and `Prettier output` tiles are enabled.

![Desktop](https://user-images.githubusercontent.com/36608344/171941940-887ccbfa-333e-4e9f-97fb-d1aed2babf70.png)

**2. Middle appearance (responsive layout from desktop to mobile resolution)**
 If element doesn't have enough space it will breaks to the next line.

![Tablet](https://user-images.githubusercontent.com/36608344/171942873-f49b8a38-ea54-459d-8826-86be427b6b6c.png)

**3. Mobile appearance**
Settings panel extended with checkboxes.

Default state (`Input` tile is enabled):

![Mobile_1](https://user-images.githubusercontent.com/36608344/171945520-afcecbf8-588b-4e13-a7b4-a53a43024ef1.png)

If press Settings button It will open settings panel.

![Mobile_2](https://user-images.githubusercontent.com/36608344/171945857-a203b1e6-503a-4a3c-adba-1e57e4855eae.png)

Select checkboxes with tiles and press `Settings` button again.

![Mobile_3](https://user-images.githubusercontent.com/36608344/171945973-dc2c5378-2e02-4d53-a971-623a6aba5a54.png)

Choosed tiles will be added to playground.

![Mobile_4](https://user-images.githubusercontent.com/36608344/171945983-0b231891-a181-43de-b570-8dee49bc7f0a.png)

**Comment by MichaReiser** [comment]
@andreyvolfman that looks awesome!

**Comment by andreyvolfman** [comment]
Great, thanks!
Can I solve this issue?:)

**Comment by MichaReiser** [comment]
> Great, thanks!
> 
> @MichaReiser  can I solve this issue?:)

Sure! I'll assign the issue to you

**Comment by NicholasLYang** [comment]
I like this idea! Some feedback:

- I don't think we need a toggle for input. 
- To reduce visual clutter, we could group the Rome outputs and Prettier outputs
- Instead of check boxes we could try using buttons that you can click and highlight

I did a quick mockup in Figma:
<img width="615" alt="Screen Shot 2022-06-06 at 7 40 52 PM" src="https://user-images.githubusercontent.com/7357863/172266639-e72064df-bdb3-49bd-9b3d-8379219b1c47.png">

**Comment by ematipico** [comment]
@andreyvolfman this issue was assigned to you but it seems there haven't been progresses. Are you still interested?

**Comment by DhrjArun** [comment]
Hi, @MichaReiser if nobody is working on this can I work on this? I've created some layouts on figma https://www.figma.com/file/ZMJ4mENMTr3ISy6Y9F9GgP/Rome?node-id=0%3A1


### Rome IR and Prettier IR grouped

![Image](https://user-images.githubusercontent.com/69076988/199431564-0239cb95-cdd4-4dda-80db-fadae1bdd8f2.jpg)


### Resizable Playground with Settings
![Image](https://user-images.githubusercontent.com/69076988/199431647-b028185e-4dce-4196-8ff6-42237866dc04.jpg)


### Resizable Playground (Settings hidden)

![Image](https://user-images.githubusercontent.com/69076988/199431664-c05bba74-a714-44bb-93fb-0ec437b4e80f.jpg)

### Resizable Playground mob (Only Settting)

![Image](https://user-images.githubusercontent.com/69076988/199431685-3927e2b3-a354-47a4-b2fe-597001bea8e5.png)

### Resizable Playground mob (Settings hidden)
![Image](https://user-images.githubusercontent.com/69076988/199431699-b025b06c-9799-4408-93ad-3a69d520a880.png)

**Comment by MichaReiser** [comment]
@DhrjArun sure. These look great!
