### ISSUE TITLE
noExtraBooleanCast

### ISSUE THREAD

**Issue by remmycat** [rome/tools#2660]
### Description

From umbrella ticket #2642 
>[noExtraBooleanCast](https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/noExtraBooleanCast.md)
Disallow unnecessary boolean casts
Example fix:
`if (Boolean(foo)) {} -> if (foo) {}`

**Comment by IWANABETHATGUY** [comment]
Hello, do you still have time to address this issue? I saw this issue has been assigned to you for about one month, if you don't have time to handle this issue, I could help.

**Comment by remmycat** [comment]
Hey there, sorry for the missing updates.
I had indeed less time than I expected to work on this - but I did get a good collection of example cases and figured out most of the implementation.

I totally get if it's better for the project to reassign it now - But if it doesn't matter so much / if there are still other open tasks up for grabs, I would still like to try to solve it during the next weekend @IWANABETHATGUY @ematipico 🙂

**Comment by IWANABETHATGUY** [comment]
> Hey there, sorry for the missing updates. I had indeed less time than I expected to work on this - but I did get a good collection of example cases and figured out most of the implementation.
> 
> I totally get if it's better for the project to reassign it now - But if it doesn't matter so much / if there are still other open tasks up for grabs, I would still like to try to solve it during the next weekend @IWANABETHATGUY @ematipico slightly_smiling_face

Feel free to finish this issue.

**Comment by remmycat** [comment]
Welp, I really did not have the time to finish this, sorry for this. I'm glad you picked the issue up again after I didn't deliver on what I said 😕
