### ISSUE TITLE
📎 (rome_analyze): useSortedSpecifiers

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rome/tools#2671]
### Description

useSortedSpecifiers

https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/useSortedSpecifiers.md

**Comment by ematipico** [comment]
Closing in favour  of #2755 

@IWANABETHATGUY I noticed that you closed the initial PR. If you're still interested in PR, please comment in #2755 so I can assign that to you
