### ISSUE TITLE
🐛 Formatter adds incorrect unnecessary `,`

### ISSUE THREAD

**Issue by RobinMalfait** [rome/tools#2676]
### Environment information

```bash
I could reproduce it in the Rome Playground:

https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&typescript=false&jsx=false#ZgBvAG8AKAB7AAoAIAAgAGIAYQByADoAIABiAGEAegAKAH0AKQA=
```

### What happened?

https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&typescript=false&jsx=false#ZgBvAG8AKAB7AAoAIAAgAGIAYQByADoAIABiAGEAegAKAH0AKQA=

I was playing around with Rome in the Tailwind CSS codebase, and noticed an incorrect formatting pattern. I reduced it to the smallest example I could think of. Given this input:

```js
foo({
  bar: baz
})
```

Rome will format it as:
```js
foo({
	bar: baz,
},);
```

Whereas Prettier formats it as:
```js
foo({
	bar: baz,
});
```

### Expected result

I expect the output to be the same as the one from Prettier:
```js
foo({
	bar: baz,
});
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by leops** [comment]
I think this is related to #2421
