### ISSUE TITLE
📎 noRedundantUseStrict

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2678]
### Description

We should not allow redundant `use strict` directives.

```
function test() {
  "use strict";
  function inner_a() {
    "use strict"; // redundant directive
  }
  function inner_b() {
    function inner_inner() {
      "use strict"; // additional redundant directive
    }
  }
}
```

Previously this was a parser warning but it'd be better as a lint rule.

**Comment by ematipico** [comment]
Could please add this rule to the list of rules? https://github.com/rome/tools/issues/2642

**Comment by ematipico** [comment]
@xunilrj what do you think of this lint rule? Mainly as a follow up of https://github.com/rome/tools/issues/2960.

If so, then we could close this issue and making it part of the document you're writing?

**Comment by ematipico** [comment]
@xunilrj for follow up

**Comment by mzbac** [comment]
Hi, I would like to work on this if you guys don't mind.
