### ISSUE TITLE
🐛 Incorrect parsing of mapped types

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2790]
### Environment information

```bash
Latest version on `main`
```

### What happened?

Rome fails to parse the following snippet:

```ts
var x: {
  [A in keyof B]?: any;
 };
```

[Playground](https://play.rome.tools/94bc262/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=1&typescript=true&jsx=true#dgBhAHIAIAB4ADoAIAB7AAoACgAKAAoAIAAgAFsAQQAgAGkAbgAgAGsAZQB5AG8AZgAgAEIAXQA/ADoAIABhAG4AeQA7AAoACgAgAH0AOwA=)

There aren't any diagnostics, but there's a missing token which is required, which is the `operator_token`.

Well, it should be required: https://www.typescriptlang.org/play?#code/G4QwTgBAHgXBDeAoZiIQNoEEIEsB2EA1gKYCeA9gGYQBCAugPxwh6kDcyEAvm0A

### Expected result

It should not emit any syntax errors.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by IWANABETHATGUY** [comment]
I don't see any syntax error emitted by our ts parser ?

![image](https://user-images.githubusercontent.com/17974631/176227274-86ea5b66-0603-4ff9-90e0-9a14b5e541fa.png)

**Comment by IWANABETHATGUY** [comment]
```

TsMappedTypeOptionalModifierClause =
	operator_token: ('+' | '-')?
	'?'

```
I guess change our `js.ungram` like above should fix this problem?

**Comment by ematipico** [comment]
> I don't see any syntax error emitted by our ts parser ?
> 
> ![image](https://user-images.githubusercontent.com/17974631/176227274-86ea5b66-0603-4ff9-90e0-9a14b5e541fa.png)

Exactly, but if you check the CST, you will see a missing (required) token.

**Comment by IWANABETHATGUY** [comment]
I think the `operator_token` should be optional ?

**Comment by ematipico** [comment]
> ```
> 
> TsMappedTypeOptionalModifierClause =
> 	operator_token: ('+' | '-')?
> 	'?'
> ```
> 
> I guess change our `js.ungram` like above should fix this problem?

One change is definitely this one, but I am not sure if also the parser also needs some fix.

**Comment by IWANABETHATGUY** [comment]
> 

lol, I have been proposed a new pr to fix this issue. :rofl:
