### ISSUE TITLE
☂️ Configuration file

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2813]
### Description

This issue tracks the works around the implementation of configuration file for rome.

Relative discussion: https://github.com/rome/tools/discussions/2632

- [x] #2823
- [x] #2826
- [x] #2861
- [x] #2824
- [x] #2862
- [x] ~add CLI commands to manipulate the configuration~
- [x] #2887
- [x] command `rome init` too bootstrap a project
- [x] #2912
- [x] #2938
- [x] #2946
- [x] #2827
- [x] ~#2828~
- [x] #3015

**Comment by IWANABETHATGUY** [comment]
Do we need to split this task into multiple issues?

**Comment by ematipico** [comment]
The remaining features were removed as they are nice to have. 
When we will start the project to revamp the CLI, we will bring them back again

**Comment by JackSparO3** [comment]
***@***.***
