### ISSUE TITLE
🐛 Formatting of TSX file may differ from Prettier

### ISSUE THREAD

**Issue by tsteckenborn** [rome/tools#2830]
### Environment information

Probably not relevant due to the visible differences in the playground.

### What happened?

Formatting a TSX file there's a [deviation ](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&typescript=true&jsx=true#aQBtAHAAbwByAHQAIAB7ACAARgBvAG8AdABlAHIAIAB9ACAAZgByAG8AbQAgACcAfgAvAGMAbwBtAHAAbwBuAGUAbgB0AHMALwBGAG8AbwB0AGUAcgAnADsACgBpAG0AcABvAHIAdAAgAHsAIABIAGUAYQBkAGUAcgAgAH0AIABmAHIAbwBtACAAJwB+AC8AYwBvAG0AcABvAG4AZQBuAHQAcwAvAEgAZQBhAGQAZQByACcAOwAKAGkAbQBwAG8AcgB0ACAAewAgAEgAZQByAG8AIAB9ACAAZgByAG8AbQAgACcAfgAvAGMAbwBtAHAAbwBuAGUAbgB0AHMALwBIAGUAcgBvACcAOwAKAAoAZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAZgB1AG4AYwB0AGkAbwBuACAASQBuAGQAZQB4ACgAKQAgAHsACgAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAPgAKACAAIAAgACAAIAAgADwASABlAGEAZABlAHIAIAAvAD4ACgAgACAAIAAgACAAIAA8AG0AYQBpAG4APgAKACAAIAAgACAAIAAgADwASABlAHIAbwAgAC8APgAKACAAIAAgACAAIAAgADwALwBtAGEAaQBuAD4ACgAgACAAIAAgACAAIAA8AEYAbwBvAHQAZQByACAALwA+AAoAIAAgACAAIAAgACAAPAAvAD4ACgAgACAAKQA7AAoAfQAKAAoACgAKAAoACgAKAAoA) between Prettier Playground and Rome Playground

Input:
```TSX
import { Footer } from '~/components/Footer';
import { Header } from '~/components/Header';
import { Hero } from '~/components/Hero';

export default function Index() {

  return (
    <>
      <Header />
      <main>
      <Hero />
      </main>
      <Footer />
      </>
  );
}
```

### Expected result

Expected Output:
```TSX
import { Footer } from "~/components/Footer";
import { Header } from "~/components/Header";
import { Hero } from "~/components/Hero";

export default function Index() {
	return (
		<>
			<Header />
			<main>
				<Hero />
			</main>
			<Footer />
		</>
	);
}
```

Received Output:
```TSX
import { Footer } from "~/components/Footer";
import { Header } from "~/components/Header";
import { Hero } from "~/components/Hero";

export default function Index() {
	return <><Header /><main><Hero /></main><Footer /></>;
}
```

Expected Rome to match Prettier.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
This should be fixed in the upcoming 0.9.0 release.
