### ISSUE TITLE
🐛 Formatter might remove intentionally set spaces in TSX files

### ISSUE THREAD

**Issue by tsteckenborn** [rome/tools#2840]
### Environment information

```bash
IDE: VSCode
Extension: rome.rome v0.10.0
Package: "rome": "^0.7.0-next"
OS: Windows
```

### What happened?

1. TSX file contains spaces between two spans
```tsx          
          <h1
            className="..."
          >
            Some Text<br />
            <span
              className="..."
            >
              Text 1{' '}
            </span>
            and{' '}
            <span
              className="..."
            >
              Text 2
            </span>
          </h1>
```
2. The spaces ({' '}) are getting removed

### Expected result

I would expect the spaces to be preserved.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by IWANABETHATGUY** [comment]
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&typescript=false&jsx=true#IAAgACAAIAAgACAAIAAgACAAIAA8AGgAMQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgAuAC4ALgAiAAoAIAAgACAAIAAgACAAIAAgACAAIAA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAUwBvAG0AZQAgAFQAZQB4AHQAPABiAHIAIAAvAD4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA8AHMAcABhAG4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYwBsAGEAcwBzAE4AYQBtAGUAPQAiAC4ALgAuACIACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFQAZQB4AHQAIAAxAHsAJwAgACcAfQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgADwALwBzAHAAYQBuAD4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABhAG4AZAB7ACcAIAAnAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA8AHMAcABhAG4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYwBsAGEAcwBzAE4AYQBtAGUAPQAiAC4ALgAuACIACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFQAZQB4AHQAIAAyAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPAAvAHMAcABhAG4APgAKACAAIAAgACAAIAAgACAAIAAgACAAPAAvAGgAMQA+AA==, It seems prettier has the same behavior.

**Comment by tsteckenborn** [comment]
Alright. I'll use {` `} which is apparently not picked up by Prettier / Rome for now.

**Comment by IWANABETHATGUY** [comment]
I am just curious why you prefer to use `{' '}` , because this should be transformed to the same HTML finally.

**Comment by ematipico** [comment]
It's actually a bug: 

[Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&typescript=false&jsx=true#IAAgACAAIAAgACAAIAAgACAAIAA8AGgAMQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgAuAC4ALgAiAAoAIAAgACAAIAAgACAAIAAgACAAIAA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAUwBvAG0AZQAgAFQAZQB4AHQAPABiAHIAIAAvAD4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA8AHMAcABhAG4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYwBsAGEAcwBzAE4AYQBtAGUAPQAiAC4ALgAuACIACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFQAZQB4AHQAIABmAGUAaQBqAGUAZgBpAGoAZQBmAGkAagBlAGYAaQBqAGUAZgBqAGkAZQBmAGoAaQBpAGYAagBlAGkAagBmAGUAagBmAGUAaQBqAGYAZQBpAGoAZQBmAGkAagBlAGYAagBpAGUAZgBqAGkAZgBlAGoAaQBpAGoAZgBlAGoAaQB7ACcAIAAnAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA8AC8AcwBwAGEAbgA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYQBuAGQAewAnACAAJwB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPABzAHAAYQBuAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgAuAC4ALgAiAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABUAGUAeAB0ACAAMgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgADwALwBzAHAAYQBuAD4ACgAgACAAIAAgACAAIAAgACAAIAAgADwALwBoADEAPgA=)

The issue occurs when the children should go on multiple lines

**Comment by tsteckenborn** [comment]
> I am just curious why you prefer to use `{' '}` , because this should be transformed to the same HTML finally.

Due to two reasons:

1. Spaces got stripped out by something, so the first idea was to make them explicit
2. Visibility

**Comment by IWANABETHATGUY** [comment]
> > I am just curious why you prefer to use `{' '}` , because this should be transformed to the same HTML finally.
> 
> Due to two reasons:
> 
> 1. Spaces got stripped out by something, so the first idea was to make them explicit
> 2. Visibility

Got it.

**Comment by ematipico** [comment]
The last release seems to have fixed the bug. If there's something else, please feel free to create a new issue.
