### ISSUE TITLE
📎 (rome_playground) Improve playground performance

### ISSUE THREAD

**Issue by vramana** [rome/tools#2856]
### Problems:

- Currently formatting (rome & prettier) happens in `App` component in the rendering phase. It seems to result in sluggish keystrokes.
- `react-textarea-code-editor` chokes when I paste 1000 lines of text. Close to 1.2 secs
![image](https://cdn.discordapp.com/attachments/942845655611748353/995683136954433546/unknown.png)

### Possible solutions:

- For the first issue, a simple solution is to debounce formatting. A more complex solution is to move all the computation to  worker thread
- For the second issue, we can use either use codemirror or monaco editors.

**Comment by ematipico** [comment]
> For the second issue, we can use either use codemirror or monaco editors.

How do the two editors compare to each other?

**Comment by vramana** [comment]
I don't have much experience with either editors. Here is a experience report from Replit https://blog.replit.com/code-editors. I have a local prototype with CodeMirror and it was a pretty easy change.

**Comment by IWANABETHATGUY** [comment]
Would you mind taking some video recording compare two editor paste large text content? That would be more intuitive.

**Comment by ematipico** [comment]
> I don't have much experience with either editors. Here is a experience report from Replit https://blog.replit.com/code-editors. I have a local prototype with CodeMirror and it was a pretty easy change.

Feel free to make a PR, if you want to contribute :) 

We'd welcome any improvement!
