### ISSUE TITLE
(rome_playground): XSS attack 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rome/tools#2904]
### Environment information

```bash
Chrome
```

### What happened?

https://play.rome.tools/?code=%3Cscript%3Ealert%28%27test%27%29%3C%2Fscript%3E%3B%3Ca+href%3D%22gogole.com%22%3E%3C%2Fa%3E%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=false&jsx=true#PABzAGMAcgBpAHAAdAA+AGEAbABlAHIAdAAoACcAdABlAHMAdAAnACkAPAAvAHMAYwByAGkAcAB0AD4AOwA8AGEAIABoAHIAZQBmAD0AIgBnAG8AZwBvAGwAZQAuAGMAbwBtACIAPgA8AC8AYQA+ADsA

this code snippet could insert a `script` tag into our playground html.Also the diagnostic result is wrong.
![image](https://user-images.githubusercontent.com/17974631/179965520-11d95cd9-b6f2-47cc-9491-fbb62f577564.png)
HTML,

### Expected result

The dangerous tag should be escaped.
Diagnostic should display the right result.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Actually, the suggestion is correct, but it's not escaped when printed here: 

![Screenshot 2022-07-20 at 12 09 15](https://user-images.githubusercontent.com/602478/179967910-31671e7d-451e-4dc9-9cc3-dcd112d5b001.png)

**Comment by IWANABETHATGUY** [comment]
> 
Yes, we have tested it. But on the user side, it is wrong because of the display.

**Comment by IWANABETHATGUY** [comment]
I change it to 
> Diagnostic should display the right result.

This should be more clear.

**Comment by leops** [comment]
Replacing the `ErrorOutput` printer used to print diagnostics in the playground with the `HTML` printer for markup provided by `rome_console` should fix this, unlike the custom printer the default implementation automatically escapes HTML special characters
