### ISSUE TITLE
🐛 Playground is not working

### ISSUE THREAD

**Issue by sacarvy** [rome/tools#2916]
### Environment information

```bash
Browser https://play.rome.tools/?lineWidth=80&indentStyle=tab&indentWidth=2&typescript=true&jsx=false#ZnVuY3Rpb24gLy8gc29tZXRoaW5nCiBhKGIsIGMpICB7CiAgbGV0IGEgPSAiZiI7Cn0KCmZ1bmN0aW9uIGEoYiwgYykgLy8gc29tZXRoaW5nIAp7CiAgICBsZXQgYSA9ICJmIjsKfQ==
```

### What happened?

blank white screen
`Uncaught RangeError: byte length of Uint16Array should be a multiple of 2`

### Expected result

It should not show blank white screen

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Where did you take that URL? It seems old. I can open the playground just fine.

**Comment by IWANABETHATGUY** [comment]
![image](https://user-images.githubusercontent.com/17974631/180342264-c6aff3ad-416f-4b70-9a14-3e269b9ec9ae.png)
I could reproduce this issue both in Chrome and Firefox

**Comment by ematipico** [comment]
> ![image](https://user-images.githubusercontent.com/17974631/180342264-c6aff3ad-416f-4b70-9a14-3e269b9ec9ae.png)
> I could reproduce this issue both in Chrome and Firefox

But that URL is old, it belongs to an old version of the playground. The current one doesn't store the hashed source code on in the hash part of the URL.

**Comment by IWANABETHATGUY** [comment]
> it belongs to an old version of the playground. The current one doesn't store the hashed source code on in the hash part of the URL.

Would you mind pasting your code here?

**Comment by AkifumiSato** [comment]
Same [here](https://rome.tools/#differences-with-prettierdprint) with the `playground` link.
