### ISSUE TITLE
🐛 Unfriendly error messages for syntax errors inside jsx

### ISSUE THREAD

**Issue by Boshen** [rome/tools#2944]
### Environment information

[Playground](https://play.rome.tools/?code=function+foo%28%29+%7B%0A++return+%28%0A++++%3Cdiv+className%3D%7Basdf+asdf%7D+%2F%3E%0A++%29%3B%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=true&jsx=true#ZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAIABjAGwAYQBzAHMATgBhAG0AZQA9AHsAYQBzAGQAZgAgAGEAcwBkAGYAfQAgAC8APgAKACAAIAApADsACgB9AA==)

### What happened?

For syntax errors inside jsx, Rome will output a lot of unfriendly error messages and even code fixes.

For example, 
```
function foo() {
  return (
    <div className={asdf asdf} />
  );
}
```

will give you
```
error[SyntaxError]: expected `}` but instead found `asdf`
  ┌─ main.js:3:26
  │
3 │     <div className={asdf asdf} />
  │                          ^^^^ unexpected

error[SyntaxError]: expected a JSX attribute but instead found '}'
  ┌─ main.js:3:30
  │
3 │     <div className={asdf asdf} />
  │                              ^ Expected a JSX attribute here

error[SyntaxError]: expected `<` but instead the file ends
  ┌─ main.js:5:2
  │
5 │ }
  │  ^ the file ends here

error: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
  ┌─ main.js:3:30
  │
3 │     <div className={asdf asdf} />
  │                              ^

error: Unexpected token. Did you mean `{'>'}` or `&gt;`?
  ┌─ main.js:3:33
  │
3 │     <div className={asdf asdf} />
  │                                 ^

error: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
  ┌─ main.js:5:1
  │
5 │ }
  │ ^

warning[[jsx/noImplicitBoolean](https://rome.tools/docs/lint/rules/noImplicitBoolean/)]: Use explicit boolean values for boolean JSX props.
  ┌─ main.js:3:26
  │
3 │     <div className={asdf asdf} />
  │                          ----

Safe fix: Add explicit `true` literal for this attribute
    | @@ -1,5 +1,5 @@
0 0 |   function foo() {
1 1 |     return (
2   | -     <div className={asdf asdf} />
  2 | +     <div className={asdf asdf={true}} />
3 3 |     );
4 4 |   }
```

### Expected result

I'm expecting the syntax error to be contained inside the boundary of `{}` (JsxExpression), and see no other jsx errors.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@MichaReiser and @xunilrj could you triage the issue and if this is an issue or not?

**Comment by MichaReiser** [comment]
Error recovery in JSX is difficult because of it's nested nature. [TypeScript](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBKRBvAUIxAJwFMoRCk18DEAeAExgDdEIAbAQwGcuA5DgLbEAvNm71giccAC+iAPQA+ahgDcuGUA) also giving you 4 errors for the same snipped. 

Having a better recovery here would be possible tough by testing if the next token is a `}` and if so, parse the second `asdf` as a skipped token trivia (while still adding the diagnostic). Maybe someone is interested in trying this out?

**Comment by IWANABETHATGUY** [comment]
> Error recovery in JSX is difficult because of it's nested nature. [TypeScript](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBKRBvAUIxAJwFMoRCk18DEAeAExgDdEIAbAQwGcuA5DgLbEAvNm71giccAC+iAPQA+ahgDcuGUA) also giving you 4 errors for the same snipped.
> 
> Having a better recovery here would be possible tough by testing if the next token is a `}` and if so, parse the second `asdf` as a skipped token trivia (while still adding the diagnostic). Maybe someone is interested in trying this out?

I would like to try
