### ISSUE TITLE
🐛 Parser: `TsModuleDeclaration` name should allow builtin types

### ISSUE THREAD

**Issue by Boshen** [rome/tools#2959]
### Environment information

[Playground](https://play.rome.tools/?code=module+number+%7B%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&typescript=true&jsx=true#bQBvAGQAdQBsAGUAIABuAHUAbQBiAGUAcgAgAHsAfQA=)

Found in [NativeScript](https://github.com/NativeScript/NativeScript/blob/main/packages/types-android/src/lib/android/android-platform-31.d.ts)

### What happened?

```
module number {}
module string {}
```

errored with

```
error[SyntaxError]: Type alias cannot be number
  ┌─ main.js:1:8
  │
1 │ module number {}
  │        ^^^^^^

error[SyntaxError]: Type alias cannot be string
  ┌─ main.js:2:8
  │
2 │ module string {}
  │        ^^^^^^

```

### Expected result

No error.

---

p.s. This [NativeScript](https://github.com/NativeScript/NativeScript/blob/main/packages/types-android/src/lib/android/android-platform-31.d.ts) file is huge, and it took ~1.5s to parse, there's probably a bottleneck somewhere.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by IWANABETHATGUY** [comment]
For this checking,  https://github.com/IWANABETHATGUY/tools/blob/253af80a4e42b876404de327fbc5467ca7d92032/crates/rome_js_parser/src/syntax/typescript/types.rs#L36-L52
## Interface
https://www.typescriptlang.org/play?ssl=22&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgM5iqA5sg3gXwChDRJZEUQBXAGxryJPGniWWoFsAjaB40lhWQB7LgCsICMHyZlWKOCACeMgeTZUQAaxDCA7iFXN1KLsOE0Iio3KFdgWUjcFtUS7hecnkAN2HAAEy95dggfXgJCIA
**necessary checking**

## Type Alias
https://www.typescriptlang.org/play?ssl=22&ssc=1&pln=1&pc=1#code/C4TwDgpgBAzsBOBLAdgcygXigbwL4Ch9RIpkBXAGwsxwKPGnIFsAjCeGvQ46AexYBWEAMbBOdHlACGyEOO4MoZZAGtkvAO7J59Ei168KEGTsktEqFGKxdd0GCFaHTigG69EAExclkEV+zyQA
**necessasry checking**
## Module
https://www.typescriptlang.org/play?ssl=22&ssc=1&pln=1&pc=1#code/LYewJgrgNgpgBAZwC4CcCWA7A5nA3gXwChDRJY4Noo8iTxp5LgAjGFG40huEZgKxgBjJBzpl4AQwwBPUV3IQMAawwgA7hjn1yzECFhSt4uMzRZMIgp23wE0lvqPcAbiDRgn5DDGdsOQA
for `module` we only need to check `null` and `void`
