### ISSUE TITLE
📎 Format code when running `check` command

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2967]
### Description

At the moment the `check` command just runs only the lint rules, but in the future it should be able to format the code too.

**Comment by imskr** [comment]
Can I work on this?

**Comment by ematipico** [comment]
@imskr Thank you for volunteering , but we're holding off this feature on purpose because the linter is in alpha state, and there are still issues that we would need to fix.

**Comment by ematipico** [comment]
Closing for now
