### ISSUE TITLE
📎Adding a grammar for Rome's formatter IR

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rome/tools#2976]
### Description

Adding a grammar for Rome's formatter IR

**Comment by ematipico** [comment]
@IWANABETHATGUY could you please add more description to this issue? I have really difficult time to understand what's this issue is about.

**Comment by IWANABETHATGUY** [comment]
> 

From here, https://github.com/rome/tools/pull/2974#pullrequestreview-1056350592

**Comment by ematipico** [comment]
Cheers. I am going to close this in favour of https://github.com/rome/tools/issues/2984
