### ISSUE TITLE
noUnusedVariables

### ISSUE THREAD

**Issue by xunilrj** [rome/tools#2979]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/noUnusedVariables.md

**Comment by xunilrj** [comment]
This rule is incorrectly flagging:

- [ ] Parameters in Typescript abstract classes and other signature methods
- [ ] Exported functions

**Comment by xunilrj** [comment]
Given some comments on https://github.com/rome/tools/pull/3071. We may break ```noUnusedVariables``` into two rules: one checking names/bindings, another one checking values.

**Comment by ematipico** [comment]
I am going to close this rule as implemented, and take note that in the next iteration we should split the rule in two.
