### ISSUE TITLE
🐛 Configration `javascript.globals` seems to be required, but not undocumented

### ISSUE THREAD

**Issue by p1ass** [rome/tools#2996]
### Environment information

```bash
$ uname -a
Darwin MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
```

```
Version: Rome CLI v0.8.0-next
```

### What happened?

1. `yarn add rome@next` 
2. add `rome.json`

```json
{
    "javascript": {
      "formatter": {
        "quoteStyle": "single"
      }
  }
}
```

3. Execute `yarn rome format .`, and get errors.
```
$ yarn rome format .
yarn run v1.22.17
$ /PATH/TO/PROJECT/node_modules/.bin/rome format .
Error: Rome couldn't load the configuration file, here's why: 
missing field `globals` at line 6 column 3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected result

It works to add the `javascript.globals` option. 
Is this the expected behavior?
If expected, we should add a note to documents because the description of `javascript.globals` is not found.
Or is it the unexpected behavior？
```json
{
    "javascript": {
      "formatter": {
        "quoteStyle": "single"
      },
      "globals": []
  }
}
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
This is not expected, `globals` should not be mandatory.

**Comment by p1ass** [comment]
Thank you for quick fix 👍

**Comment by ematipico** [comment]
No problem! We will release a nightly version with this fix. It seems that this bug has a workaround, so it doesn't block you from using Rome?

**Comment by p1ass** [comment]
I've already used Rome with a workaround, so nothing is blocking me 👌
