### ISSUE TITLE
New tab in the playground to show lint diagnostics

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rome/tools#3010]
### Description

Currently, we enable lint in our playground by default, and there is no way to disable it.
Adding a new tab or checkbox to disable the linter would be helpful in some scenarios,  
For example: 
When you debug the parser, you want to see syntax errors only.

**Comment by PatrM** [comment]
Hey!
Is this still a relevant issue? If so, I'd love to have a look at it 👍🏻

**Comment by MichaReiser** [comment]
Having the option to enable/disable lints is still something that would be useful. Feel free @PatrM to give it a try
