### ISSUE TITLE
Implement the low-level transport for the JavaScript API

### ISSUE THREAD

**Issue by leops** [rome/tools#3029]
Intended changes for this task are:
- Merge the CLI and Language Server binary (the server is run by calling `rome __run_server`)
- Add a new `rome __print_socket` command that ensures the server is running in a daemon process and prints the domain socket / named pipe it's listening on to stdout

**Comment by ematipico** [comment]
@leops you might want to take a look at the old CLI commands as inspiration: 
- [lsp](https://github.com/rome/tools/blob/archived-js/website/src/_includes/docs/cli-commands.md#rome-lsp)
- [deamon commands](https://github.com/rome/tools/blob/archived-js/website/src/_includes/docs/cli-commands.md#rome-restart)

**Comment by leops** [comment]
> @leops you might want to take a look at the old CLI commands as inspiration:
> 
>     * [lsp](https://github.com/rome/tools/blob/archived-js/website/src/_includes/docs/cli-commands.md#rome-lsp)
> 
>     * [deamon commands](https://github.com/rome/tools/blob/archived-js/website/src/_includes/docs/cli-commands.md#rome-restart)

One thing I'm considering is to prefix these CLI commands with a double underscore instead (like `__run_server` and `__print_socket`) to signify these are internal commands, not intended to be used outside of the stable JS wrapper library at the moment

**Comment by ematipico** [comment]
It makes sense. `esbuild` just doesn't document them. It has a command called `node` and a bunch of arguments, for example `--ping` to check if the service is running.
