### ISSUE TITLE
📎 Batch Mutation: Remove token

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3087]
### Description

I'm currently working on a pre-processing step in the formatter that removes all parenthesized expressions and I use the `BatchMutation` to do the job. 

One use case that I don't see covered by the `BatchMutation` API is the case where one needs to remove a token but wants to retain the trivia. 

```javascript
a + ( /* inline comment */ b) 
a + 
  // own line comment 
  (b)
```

Removing the `(` token shouldn' remove the associated comments (or other trivia). Instead, it should associate the trivia with the previous/next token in a way that adheres to our leading/trivia definition:

* Removing the first token in the program: All its leading and trailing trivia must be pre-pended to the next token's leading trivia 
* Removing the last token: guaranteed to be the EOF token, Error
* any other token:
  * without leading trivia: Append the dangling comment to the previous token's dangling trivia because there's no new line separating the two comments (leading trivia must always start with a new line except for the first token): `a + /* inline comment */ b` -> comment becomes a dangling comment of `+`
  * otherwise: Pre-append the leading and dangling trivia to the next token's leading trivia. `a + \n //own line comment b` `// own line comment` becomes a leading comment of `b`

## Challenges

There are two challenges that I see that this new operation introduces: 

### Overlapping operations

Mutating the same token multiple times: It is possible that removing a token may add leading and trailing trivia to the same token but in two different operations. 

```javascript
(a
  /* leading */ )  + ( /* trailing */ + c)
```

Let's play through the mutations for removing the parentheses

* Removing the `(` of `(a`. The `(` token has no trivia, sufficient to remove the child. 
* Removing the `)` of `a\n)` The `/* leading *` comment must be prepended to `+`'s leading trivia
* Removing the `(` of `+ (`: The `/* trailing */` comment must be appended to `+`s trailing trivia. 

The problem is that this involves two mutations to the `+` from individual `mutation.remove_token(token)` calls. 

### Co-existence with `replace_element` 

Removing the parentheses requires 3 operations: 

```javascript
(/* comment */ a) + b
```

* Remove the `(` token
* Remove the `)` token
* Replace the  `(a)` node with `a` in the `BinaryExpression`

Replacing a node ensures that trivia is copied over from the existing node. The problem is similar to the one with overlapping mutations. The `BatchMutation` must use the latest trivia of a node, meaning, it should use **new** leading trivia of `a` that has the `/* comment */` to avoid that the trivia is later lost. 

## Other use cases

A new `remove_token` is useful in all rules where it is necessary to remove a token. For example, removing an `async` token for a function that calls no other `async` function, Remove the optional call `?.()` token if it is known that the left side can never be null. 

## Potential Bugs

The `noUnusedVar` rule uses the current `batch.remove_token` implementation that does not retain trivia to remove a trailing `,`. Today's implementation will, incorrectly, drop any comments attached to the `,` comma 

```
function test(
  a, // My comment
) {} 
```

We should validate if this is desired.

**Comment by MichaReiser** [comment]
@xunilrj what are your thoughts on this?

**Comment by xunilrj** [comment]
I think this should be considered inside my PR https://github.com/rome/tools/pull/3148
