### ISSUE TITLE
🐛 VSCode extension doesn't always use `rome.json`

### ISSUE THREAD

**Issue by lgarron** [rome/tools#3088]
### Environment information

```bash
VSCode Version: 1.70.2
macOS 12.5.1
rome v0.8.0-next.ff4153b
Rome VSCode extension v0.12.0
```

### What happened?

1. Create `rome.json` in the root of the project (same folder as `package.json`).
2. Verify that `npx rome format` works.
3. Format a file in VSCode using the Rome extension.

Example config:
```json
{
  "formatter": {
    "indentStyle": "space",
    "indentSize": 2
  }
}

```

Sometimes, the extension uses `rome.json` successfully for formatting (in this case, format using spaces). But most of the time for me, it just seems to act as if `rome.json` doesn't exist, and formats using the defaults (in this case, format using tabs).

### Expected result

The extension always uses `rome.json`.

Apologies for such a vague issue. I'd be happy to debug if I could have some hints to figure out where to look.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
How do you format your code? Do you have the format on save option enabled?

**Comment by lgarron** [comment]
> How do you format your code? Do you have the format on save option enabled?

The same issue happens for all of the following invocations:

- Command palette > "Format Document With…" > "Rome" (`editor.formatOnPaste`, `editor.formatOnSave`, and `editor.formatOnType` all set to `false`, default formatter set to built-in)
- Command palette > "Format Document" (with `"rome.rome"` set as the default TS formatter)
- `editor.formatOnSave` + save file (with `"rome.rome"` set as the default TS formatter)

**Comment by ematipico** [comment]
I can't seem to reproduce it :( 

I might try to add some more logging, maybe that would help to understand what's going on.

**Comment by lgarron** [comment]
> I can't seem to reproduce it :(

Yeah, unfortunately, I still have this issue consistently, on two different macOS devices. :-/
I've tried using a blank `settings.json` for VSCode, and that doesn't seem to make a difference either.

Happy to try it with any debug logging you see fit!

**Comment by lgarron** [comment]
Okay, I'm still able to reproduce this in the most minimal macOS environment I can:

- Fresh macOS user profile
- Default macOS shell (`/bin/zsh`), no shell initialization or customization, no custom env vars
- No custom VSCode settings, not signed into VSCode
- `rome-rome` extension installed in VSCode, but no other extensions
- Run:

```shell
git clone https://github.com/cubing/cubing.js && cd cubing.js
git checkout rome-again
npm install
code .
```

- Open `src/cubing/twisty/views/TwistyPlayer.ts`
- Command palette > "Format Document With…" > Rome

Is it possible that the this is an issue on all macOS installations?

**Comment by ematipico** [comment]
I identified the issues and a PR should be ready soon. The issue is caused by the language client, that is setting up the base path differently than expected.

**Comment by lgarron** [comment]
> I identified the issues and a PR should be ready soon. The issue is caused by the language client, that is setting up the base path differently than expected.

Thanks for the fix! 😍
Any chance I could ask for a patch release so that I can start using the extension? 😃

**Comment by ematipico** [comment]
> > I identified the issues and a PR should be ready soon. The issue is caused by the language client, that is setting up the base path differently than expected.
> 
> Thanks for the fix! 😍
> Any chance I could ask for a patch release so that I can start using the extension? 😃

We're preparing for a release, which will be next week :)

**Comment by lgarron** [comment]
I was glad to try the new release! I'm sorry to say that it doesn't seem to be any better at using `rome.json`. It managed to do so initially, but now I can't get it to do so at all. 😔

This is using stable VSCode with no `rome.lspBin` config.

- macOS 12.5.1
- Rome CLI v0.9.2-next (I don't think this is relevant? I can't figure out how to get the extension to use a relative path for the bin, anyhow.)
- VSCode 1.71.0
- VSCode Rome extension v0.14.1

**Comment by lgarron** [comment]
Okay, I figured it out, my `rome.json` format was no longer valid for the latest LSP.

**Comment by lgarron** [comment]
Is it possible there was a regression for this? I've had issues again for the last few weeks, and I can't figure out how to fix it.

**Comment by ematipico** [comment]
> Is it possible there was a regression for this? I've had issues again for the last few weeks, and I can't figure out how to fix it.

From last week? (latest release)
Feel free to open a new issue.
