### ISSUE TITLE
Formatter: TS Intersection & Union types

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3162]

**Comment by denbezrukov** [comment]
@MichaReiser Would you mind assigning me this task?

**Comment by denbezrukov** [comment]
https://github.com/prettier/prettier/issues/13153
Need to look this issue before implementing union.

**Comment by MichaReiser** [comment]
> [prettier/prettier#13153](https://github.com/prettier/prettier/issues/13153) Need to look this issue before implementing union.

Using a closer formatting to intersection types would be beneficial. Implementing comments around union type feels like a big awful hack [source](https://github.com/rome/tools/blob/refactor/comments-v100/crates/rome_js_formatter/src/ts/lists/union_type_variant_list.rs)
