### ISSUE TITLE
rome ci does not care about rome.json

### ISSUE THREAD

**Issue by anonrig** [rome/tools#3167]
### Environment information

```bash
node 18.8.0
macos latest version
rome 0.9.0 - installed using pnpm add -D rome@next
```

### What happened?

`npm run format:ci` which is `rome ci .` does not care about rome.json configuration. 

there isn't any clear way of running formatter on CI and throwing errors if it fails.

```json
{
  "formatter": {
    "indentStyle": "space",
    "indentSize": 2
  },
  "linter": {
    "enabled": false
  }
}
```

<img width="1616" alt="Screen Shot 2022-09-06 at 12 29 02 PM" src="https://user-images.githubusercontent.com/1935246/188687872-54ef1738-ca07-4e3a-955b-87eb00a1f3c2.png">

### Expected result

It should care linter enabled false configuration and not check for linting.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
It seems that the `ci` command doesn't respect the configuration all together as it also doesn't take formatting options into account. @ematipico @leops would you be able to have a look and I think we should consider doing a follow up release with the fix included

**Comment by anonrig** [comment]
You can reproduce the same behaviour with this pull request: https://github.com/anonrig/fast-querystring/pull/11

**Comment by leops** [comment]
I've noted two slightly unrelated bugs here:
- From what I can see the configuration file is correctly being loaded (changing the indent size / style in the `rome.json` works as expected for instance), but the `ci` command is hard-coded to call into both the formatter and the linter and doesn't respect the `enabled` setting for either tool. This should be fixed at two points: the Workspace should return an error the the linting or formatting methods are called but the corresponding tool is disabled, and the CLI should not attempt to call into these methods in the first place if the `supports_feature` method has returned `false` / `Some(_)`
- The CLI flags like `--indent-style` are being ignored, specifically they get read into a `WorkspaceSettings` struct but this information never gets used or applied anywhere
