### ISSUE TITLE
rome format . does not log to stderr

### ISSUE THREAD

**Issue by anonrig** [rome/tools#3168]
### Environment information

```bash
macos latest
rome 0.9.0
node 18.8.0
```

### What happened?

rome format . does not print to stderr when `---write` configuration is missing

```
➜  fast-querystring git:(feat/stringify) ✗ npm run format:ci

> fast-querystring@0.4.0 format:ci
> rome format .

./test/node.ts: help[Formatter]: Formatter would have printed the following content:
      | @@ -23,7 +23,7 @@
22 22 |       { frappucino: "muffin", "goat[]": "scone", pond: "moose" },
23 23 |     ],
24 24 |     ["trololol=yes&lololo=no", { trololol: "yes", lololo: "no" }],
25    | - ]
   25 | + ];
26 26 |   export const qsTestCases = [
27 27 |     [
28 28 |       "__proto__=1",

Compared 9 files in 1626µs
```

### Expected result

It should log to stderr

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Hi @anonrig , how did you verify that diagnostics are not wrote on `stderr`?  I can't reproduce it.

I just created a file with some errors, run `rome ci teset.js &> errors.txt`  and I can correctly see that this file show the diagnostics.

**Comment by leops** [comment]
I think this is intentional, `rome ci` emits an error if the current content of the file differs from the output of the formatter and this correctly gets printed to stderr, but `rome format` only emits an informational message that displays the diff to the console so that gets printed to stdout since it's not an error (it also doesn't cause the CLI to exit with a non-zero result code)

**Comment by anonrig** [comment]
> `rome format` only emits an informational message that displays the diff to the console so that gets printed to stdout since it's not an error (it also doesn't cause the CLI to exit with a non-zero result code)

I expected `--write` to give stdout and stderr output without using it. Can you add a footnote to the rome format documentation regarding it? 

`rome ci` forces the developer to use `rome.json` and I just want to run `run format` and throw an error if it fails.

**Comment by anonrig** [comment]
What about removing `rome ci` and just have a `rome format --fail-on-error` or `--ci` kind of flag?

**Comment by anonrig** [comment]
![image](https://user-images.githubusercontent.com/1935246/191970066-9f648c50-a736-42b9-985d-276e97bbfbc6.jpeg)

**Comment by ematipico** [comment]
> ![image](https://user-images.githubusercontent.com/1935246/191970066-9f648c50-a736-42b9-985d-276e97bbfbc6.jpeg)

Don't worry :) we are going to track this feature in a separate issue as we are about to plan our next release cycle.
