### ISSUE TITLE
🐛 Typescript Declaration File noUnusedVariable

### ISSUE THREAD

**Issue by ZachHaber** [rome/tools#3169]
### Environment information

```bash
Rome Extension: v0.14.0
No Rome CLI installed globally or locally,

VSCode Env Info:
Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

### What happened?

When viewing a manually created `.d.ts` file, `noUnusedVariables` erroneously triggers.

For reference, this is setting up an environment that's outside the normal browser environment (Adobe Acrobat), so the default typescript lib files don't apply in a lot of cases.

```
declare const ANSB_None: number;

interface MapConstructor {
	new <K, V>(
		iterable?:
			| Iterable<readonly [K, V] | LegacyIterator<readonly [K, V]>>
			| null,
	): Map<K, V>;
}

declare class StopIteration {
	private constructor();
}

```
[Playground Link](https://play.rome.tools/?code=declare+const+ANSB_None%3A+number%3B%0A%0Ainterface+MapConstructor+%7B%0A%09new+%3CK%2C+V%3E%28%0A%09%09iterable%3F%3A%0A%09%09%09%7C+Iterable%3Creadonly+%5BK%2C+V%5D+%7C+LegacyIterator%3Creadonly+%5BK%2C+V%5D%3E%3E%0A%09%09%09%7C+null%2C%0A%09%29%3A+Map%3CK%2C+V%3E%3B%0A%7D%0A%0Adeclare+class+StopIteration+%7B%0A%09private+constructor%28%29%3B%0A%7D%0A%0A&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&typescript=true&jsx=false#ZABlAGMAbABhAHIAZQAgAGMAbwBuAHMAdAAgAEEATgBTAEIAXwBOAG8AbgBlADoAIABuAHUAbQBiAGUAcgA7AAoACgBpAG4AdABlAHIAZgBhAGMAZQAgAE0AYQBwAEMAbwBuAHMAdAByAHUAYwB0AG8AcgAgAHsACgAJAG4AZQB3ACAAPABLACwAIABWAD4AKAAKAAkACQBpAHQAZQByAGEAYgBsAGUAPwA6AAoACQAJAAkAfAAgAEkAdABlAHIAYQBiAGwAZQA8AHIAZQBhAGQAbwBuAGwAeQAgAFsASwAsACAAVgBdACAAfAAgAEwAZQBnAGEAYwB5AEkAdABlAHIAYQB0AG8AcgA8AHIAZQBhAGQAbwBuAGwAeQAgAFsASwAsACAAVgBdAD4APgAKAAkACQAJAHwAIABuAHUAbABsACwACgAJACkAOgAgAE0AYQBwADwASwAsACAAVgA+ADsACgB9AAoACgBkAGUAYwBsAGEAcgBlACAAYwBsAGEAcwBzACAAUwB0AG8AcABJAHQAZQByAGEAdABpAG8AbgAgAHsACgAJAHAAcgBpAHYAYQB0AGUAIABjAG8AbgBzAHQAcgB1AGMAdABvAHIAKAApADsACgB9AAoACgA=) (Note: there's no declaration file option in the playground)

### Expected result

It should not flag these declarations as unused.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
@xunilrj would you mind taking a look at this
