### ISSUE TITLE
🐛 `rome format` ignores command line options

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3175]
### Environment information

```bash
Version: `main`
```

### What happened?

Run `rome` with `quote-style="single"` 

```bash
cargo run --bin rome --release format ~/Desktop/jquery.min.js --quote-style=single
```

Rome formats the string literals in `jquery.min.js` with double quotes.

### Expected result

The command line arguments take precedence over the configuration and Rome formats the string literals in `jquery.min.js` with single quotes 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
The problem seems to be in the CLI/Workspace as @leops pointed out in https://github.com/rome/tools/issues/3167#issuecomment-1239021869

I verified that quickly by adding a `dbg!(&options)` to `format_node` in `rome_js_formatter` and can confirm that the options use `QuoteStyle::Double` instead of single

**Comment by jfeltesse-mdsol** [comment]
I might be missing something but here it stills insists on using double quotes

```
rome -v
Rome CLI v0.9.1-next
```

```
cat rome.json
{
  "formatter": {
    "indentStyle": "space",
    "indentSize": 2,
    "lineWidth": 120
  },
  "linter": {
    "rules": {
      "ts": {
        "recommended": true
      }
    }
  }
}
```

```
rome format --quote-style single

# diffs like
# 0   | - import React from 'react';
#  0 | + import React from "react";
```

**Comment by hustcer** [comment]
I have met the same issue, maybe we should reopen this

**Comment by ematipico** [comment]
I was able to replicate the issue. I am going to re-open the issue and fix it
