### ISSUE TITLE
🐛 In JSX, some spaces are removed

### ISSUE THREAD

**Issue by pradel** [rome/tools#3211]
### Environment information

```bash
Hey all, I was trying Rome in one of my codebases using prettier and found an issue with spaces in JSX expressions.
As you can see in this playground, a space right after the `a` tag is removed, prettier is behaving normally and keeping that space.

[Playground link](https://play.rome.tools/?code=const+a+%3D+%3Cdiv%3E%0A++Text+%3Ca+data-very-long-prop-breakline-rome-playground+data-other%3E%0A++++++++++++++some+link%0A++++++++++++%3C%2Fa%3E%7B%27+%27%7D%0A++++++++++++%7C+some+other+text%2C%7B%27+%27%7D%0A++++++++++++++++%3C%2Fdiv%3E&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&typescript=false&jsx=false#YwBvAG4AcwB0ACAAYQAgAD0AIAA8AGQAaQB2AD4ACgAgACAAVABlAHgAdAAgADwAYQAgAGQAYQB0AGEALQB2AGUAcgB5AC0AbABvAG4AZwAtAHAAcgBvAHAALQBiAHIAZQBhAGsAbABpAG4AZQAtAHIAbwBtAGUALQBwAGwAYQB5AGcAcgBvAHUAbgBkACAAZABhAHQAYQAtAG8AdABoAGUAcgA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHMAbwBtAGUAIABsAGkAbgBrAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPAAvAGEAPgB7ACcAIAAnAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB8ACAAcwBvAG0AZQAgAG8AdABoAGUAcgAgAHQAZQB4AHQALAB7ACcAIAAnAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgADwALwBkAGkAdgA+AA==)
```

### What happened?

1. Open the [playground](https://play.rome.tools/?code=const+a+%3D+%3Cdiv%3E%0A++Text+%3Ca+data-very-long-prop-breakline-rome-playground+data-other%3E%0A++++++++++++++some+link%0A++++++++++++%3C%2Fa%3E%7B%27+%27%7D%0A++++++++++++%7C+some+other+text%2C%7B%27+%27%7D%0A++++++++++++++++%3C%2Fdiv%3E&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&typescript=false&jsx=false#YwBvAG4AcwB0ACAAYQAgAD0AIAA8AGQAaQB2AD4ACgAgACAAVABlAHgAdAAgADwAYQAgAGQAYQB0AGEALQB2AGUAcgB5AC0AbABvAG4AZwAtAHAAcgBvAHAALQBiAHIAZQBhAGsAbABpAG4AZQAtAHIAbwBtAGUALQBwAGwAYQB5AGcAcgBvAHUAbgBkACAAZABhAHQAYQAtAG8AdABoAGUAcgA+AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHMAbwBtAGUAIABsAGkAbgBrAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPAAvAGEAPgB7ACcAIAAnAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB8ACAAcwBvAG0AZQAgAG8AdABoAGUAcgAgAHQAZQB4AHQALAB7ACcAIAAnAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgADwALwBkAGkAdgA+AA==)
2. Check the Rome result and compare it to prettier to see the missing space after the a tag.

### Expected result

That the space is preserver like this
```
const a = (
	<div>
		Text <a data-very-long-prop-breakline-rome-playground data-other>
			some link
		</a>{" "}
		| some other text,{" "}
	</div>
);
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment]
@MichaReiser 
If you don't mind I can try to look this issue (=

**Comment by MichaReiser** [comment]
> @MichaReiser If you don't mind I can try to look this issue (=

That would be awesome. Be warned, our JSX formatting differs from Prettier in thus that we use custom intermediate representation for children before turning it into format elements.

**Comment by denbezrukov** [comment]
Need to check also:
[Playground](https://play.rome.tools/?code=const+a+%3D%0A++%3C%3E%0A++++%3Ca%3E%3C%2Fa%3E%0A++++%0A++++%7B%27+%27%7D%0A1%0A++%3C%2F%3E%0A&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&typescript=false&jsx=true#YwBvAG4AcwB0ACAAYQAgAD0ACgAgACAAPAA+AAoAIAAgACAAIAA8AGEAPgA8AC8AYQA+AAoAIAAgACAAIAAKACAAIAAgACAAewAnACAAJwB9AAoAMQAKACAAIAA8AC8APgAKAA==)
