### ISSUE TITLE
🐛 VSCode Extension shows errors for projects without Rome installed

### ISSUE THREAD

**Issue by probablykasper** [rome/tools#3271]
### Environment information

```bash
macOS 10.15.7, x86
```

### What happened?

The Rome extension is giving lint errors for projects where I don't have Rome installed

### Expected result

Only run Rome if Rome is actually used in the project so Rome doesn't interfere with the project's linter/formatter

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Assuming that the Rome extension expects to work even when a `rome.json` is not present, how would you expect to "turn off" Rome for a project inside the VSCode extension? Via settings?

**Comment by probablykasper** [comment]
I would expect Rome to only be enabled if Rome is used. I'm not sure how eslint or prettier do it, but I don't get any errors from them. Besides, how would the extension know what Rome version to use if Rome isn't installed in the project?

**Comment by ZachHaber** [comment]
I currently use Rome only on one particular project, so I have the extension disabled globally, and then enable it for that workspace. I tend to do that for most of my framework specific extensions (i.e. Volar, Angular, etc) to prevent them from taking up too much start up time generically.
Personally, I like that I don't have to necessarily install the Rome cli to use Rome extension, though if my project was being edited by multiple people, I'd probably have to anyway for consistency.

**Comment by ematipico** [comment]
I am going to close this issue. We acknowledged the use case and we plan to work on it, but that's not something that we consider as a quick fix, because it requires some work on the resolution of the configuration file.
