### ISSUE TITLE
`noAutoFocus`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3297]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/noAutofocus.md

**Comment by jk-gan** [comment]
Hi, I would like to try to implement this. May I know where should I start?

**Comment by jk-gan** [comment]
After some scanning on the source code, I believe it should be in the `rome_js_analyze` crate. Am I correct?

**Comment by ematipico** [comment]
> Hi, I would like to work on this. May I know where should I start?

Thank you! I will assign this to you! 

I am a going to do a write up about how to start writing rules, in the meantime, that's what you have to do:

- inside `rome_js_analyze` folder, you have `analyzers` folder and `semantic_analyzers` folder. Inside these folder, you have folders that are the groups. Inside `analyzers/nursery` create file called `no_auto_focus.rs`
- then launch the command `cargo codegen analyzer`, this command will update the registry, which is code generated
- now you can start editing the files, by following what we have in the other rules - use the macro `declare_rule` and the `impl Rule` on the new struct

Some guidelines are found here: https://github.com/rome/tools/blob/main/CONTRIBUTING.md#creating-rules

**Comment by jk-gan** [comment]
Alright, got it!

**Comment by ematipico** [comment]
Here's a link to the contribution guidelines: https://rome.github.io/tools/rome_analyze/index.html

**Comment by ematipico** [comment]
> I just want to confirm, should the rule only apply to `<input />` component or should it apply to all components, `<div>`, `<button>` and so on?

Only for input elements
