### ISSUE TITLE
`useAltText`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3298]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/useAltText.md

**Comment by b4s36t4** [comment]
Hey, @ematipico any documentation or reference to build the lint rule?!

**Comment by ematipico** [comment]
The umbrella issue has a link to the guide. You can reach the same link from `CONTRIBUTING.md`

**Comment by ematipico** [comment]
I removed the "good first issue" because the logic of this rule is substantial. Still, anyone that feel adventurous can try to implement it

**Comment by b4s36t4** [comment]
I'm working on it. I think I'm going in correct path. Please assign it to me.

**Comment by b4s36t4** [comment]
@ematipico as per the doc provided above we need to catch spread operator with alt prop should be a valid case.

Any help on catching spread prop?

<img width="560" alt="Screenshot 2022-10-08 at 4 19 34 PM" src="https://user-images.githubusercontent.com/59088937/194703788-4f4e691a-e1b1-49f0-8857-2038fd893042.png">
