### ISSUE TITLE
`useKeyWithClickEvents` 

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3301]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/useKeyWithClickEvents.md

**Comment by jk-gan** [comment]
can I try this?

**Comment by jk-gan** [comment]
I believe we want to be the same as this eslint a11y rule where the rule only apply to visible, non-interactive elements.
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/click-events-have-key-events.md

**Comment by jk-gan** [comment]
is there a way to check if the element is interactive or not in rome?

**Comment by ematipico** [comment]
> is there a way to check if the element is interactive or not in rome?

I think we can start the implementation by copying the implementation we had in the old rule.

From there, we can extend the logic by taking into account ARIA attributes.

Usually, interactive elements are those elements that do something when there's interaction with the mouse (`onClick` for example), and the rule should enforce that these elements should have some interactive via a keyboard event too.

**Comment by jk-gan** [comment]
I saw the old rule is implemented for JSX and HTML, do I need to support HTML as well? (I'm not sure the current parser support that tho)

**Comment by ematipico** [comment]
> I saw the old rule is implemented for JSX and HTML, do I need to support HTML as well? (I'm not sure the current parser support that tho)

No, just JSX
