### ISSUE TITLE
`noPositiveTabIndex` 

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3304]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/noPositiveTabindex.md

**Comment by kaioduarte** [comment]
Hi there 👋🏻 

I'd like to work on this one as my first contribution!

**Comment by ematipico** [comment]
> Hi there 👋🏻 
> 
> I'd like to work on this one as my first contribution!

Thank you!

I assigned the issue to you, here's a link to the contribution guidelines: https://rome.github.io/tools/rome_analyze/index.html

**Comment by kaioduarte** [comment]
@ematipico, while debugging the rule, I found that the [inner_string_text](https://github.com/rome/tools/blob/main/crates/rome_js_syntax/src/jsx_ext.rs#L18) helper doesn't strip the quotes for this JSX:
```jsx
<div tabIndex="1" />
```

The trailing space at the end is causing the issue, as you can see here:
```rust
Split(
    SplitInternal {
        start: 0,
        end: 4,
        matcher: StrSearcher {
            haystack: "\"1\" ",
            needle: "",
            searcher: Empty(
                EmptyNeedle {
                    position: 0,
                    end: 4,
                    is_match_fw: true,
                    is_match_bw: true,
                    is_finished: false,
                },
            ),
        },
        allow_trailing_empty: true,
        finished: false,
    },
)
```

Is this a known issue or limitation?

**Comment by ematipico** [comment]
I am not aware of any issue, as far as I know. We use this function in another rule, and it works: https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs#L89

If you think this doesn't help you, feel free to open a draft PR, so we can move the discussion on the actual code.

**Comment by kaioduarte** [comment]
Yes, I checked that rule, and the helper works fine for `JsxOpeningElement` but not for `JsxSelfClosingElement`.

I'll try to create a draft PR later, thank you!
