### ISSUE TITLE
📎 Formatter: Trailing Comma option

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3305]
### Description

Add support for a [`trailing_comma`](https://prettier.io/docs/en/options.html#trailing-commas) option that can either be `es5` or `all` (default)

**Comment by denbezrukov** [comment]
I'd like to try!🙏🏼

**Comment by MichaReiser** [comment]
One thing I had in mind for the trailing comma (may not work out as well as I have in mind ;)) is to introduce a `TrailingSeparator` struct/enum that implements `Format`. It can either be an `enum` with `Es5`, `All` and potentially `None` variants or accept a `TrailingSeparatorMode` that has the before mentioned variants. 

What's mainly unclear to me right now is how to best integrate it with `format_separated` (that ideally, a lighter version would be part of `rome_formatter`)
