### ISSUE TITLE
`for-direction` 

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3363]
https://eslint.org/docs/rules/for-direction

**Comment by nissy-dev** [comment]
Hi 👋🏻 I'd like to work on this one as my first contribution! Can I take this issue?

**Comment by ematipico** [comment]
> Hi 👋🏻 I'd like to work on this one as my first contribution! Can I take this issue?

It's all yours! The issue is assigned to you

**Comment by nissy-dev** [comment]
@ematipico When I implement it, I'm thinking of naming this rule `use_valid_for_direction`.  How do you think?

**Comment by ematipico** [comment]
> @ematipico When I implement it, I'm thinking of naming this rule `use_valid_for_direction`.  How do you think?

It seems a good name!
