### ISSUE TITLE
`no-dupe-keys` 

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3364]
https://eslint.org/docs/rules/no-dupe-keys

**Comment by MoskalykA** [comment]
I take care of that

**Comment by ematipico** [comment]
> I take care of that

I assigned the issue to you @MoskalykA !

**Comment by jeysal** [comment]
Since this appears to be inactive, I'm trying this one out to write my first lint rule, let's see how they are written in Rome :smile:

**Comment by MichaReiser** [comment]
> Since this appears to be inactive, I'm trying this one out to write my first lint rule, let's see how they are written in Rome :smile: 

Go for it!
