### ISSUE TITLE
`match_str_case_mismatch` 

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3368]
https://rust-lang.github.io/rust-clippy/master/#match_str_case_mismatch

For this rule, we should try to implement simple cases such as:

```js
const lorem = "foo";

if (lorem == "Foo") { // trigger the rule
}
```

**Comment by 95th** [comment]
Hi @ematipico.
Is the goal here to find mismatching comparison of const/effectively const variables?
or is it to find `toUpperCase`/`toLowerCase` comparisons?

**Comment by MichaReiser** [comment]
```
const lorem = "foo";

if (lorem == "Foo") { // trigger the rule
}
```

I doubt that a rule limited to this pattern will catch many bugs and isn't what the clippy equivalent is testing for. 

>  or is it to find toUpperCase/toLowerCase comparisons?

This feels more valuable to me (testing in all places where conditions can appear: `if/else`, `for`, `switch`)

**Comment by 95th** [comment]
Should it only raise for conditional statements mentioned above or in general as well?

For example, this also look right to me:
```
! This expression always returns false.

> 10 │ const a = s.toUpperCase() === "abc";
     │           ^^^^^^^^^^^^^^^^^^^^^^^^^
  11 │

i This call convert the string to upper case

> 10 │ const a = s.toUpperCase() === "abc";
     │           ^^^^^^^^^^^^^^^
  11 │

i ... but this value is not in upper case

> 10 │ const a = s.toUpperCase() === "abc";
     │                               ^^^^^
  11 │

```

**Comment by MichaReiser** [comment]
It probably makes sense in all positions where a value is compared with a string.
