### ISSUE TITLE
🐛 Formatter: JSX Expression child closing parentheses

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3376]
### Environment information

[Playground](https://play.rome.tools/?code=function+BackTopContent%28props%29%7B%0A%09return+%28%0A%09%09%3CCSSMotion%3E%0A%09%09%09%7B%28%7B+className%3A+motionClassName+%7D%29+%3D%3E%0A%09%09%09%09cloneElement%28className+%3D%3E+%28%7B%0A%09%09%09%09%09className%0A%09%09%09%09%7D%29%29%7D%0A%09%09%3C%2FCSSMotion%3E%0A%09%29%3B%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=false&jsx=true#ZgB1AG4AYwB0AGkAbwBuACAAQgBhAGMAawBUAG8AcABDAG8AbgB0AGUAbgB0ACgAcAByAG8AcABzACkAewAKAAkAcgBlAHQAdQByAG4AIAAoAAoACQAJADwAQwBTAFMATQBvAHQAaQBvAG4APgAKAAkACQAJAHsAKAB7ACAAYwBsAGEAcwBzAE4AYQBtAGUAOgAgAG0AbwB0AGkAbwBuAEMAbABhAHMAcwBOAGEAbQBlACAAfQApACAAPQA+AAoACQAJAAkACQBjAGwAbwBuAGUARQBsAGUAbQBlAG4AdAAoAGMAbABhAHMAcwBOAGEAbQBlACAAPQA+ACAAKAB7AAoACQAJAAkACQAJAGMAbABhAHMAcwBOAGEAbQBlAAoACQAJAAkACQB9ACkAKQB9AAoACQAJADwALwBDAFMAUwBNAG8AdABpAG8AbgA+AAoACQApADsACgB9AA==)

Extracted from 

https://github.com/ant-design/ant-design/blob/975def492b97a2fc5c1e1fc9eda7f1984b93bb4b/components/back-top/index.tsx#L33-L50

### What happened?

1. Open the example in the playground
2. Observe how Rome puts the closing `}` of the expression child on the same line as the other closing parentheses but prettier formats it on its own line. 

### Expected result

Prettier's layout looks nicer because it makes the indention level clearer.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment]
Could I take it?
