### ISSUE TITLE
🐛 Formatter: Assignment layout

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3386]
### Environment information

main (3263f956fcc27bedc1c7d60fa25473cc42f2abf7)

### What happened?

1. Open [this playground](https://play.rome.tools/?code=class+SourceRemoveUnused+extends+SourceAction+%7B%0A%09static+readonly+kind+%3D+vscode.CodeActionKind.Source.append%28%0A%09%09%22removeUnused%22%2C%0A%09%29.append%28%22ts%22%29%3B%0A%0A++public+static+readonly+id+%3D+%22javascript-walkthrough.commands.nodeInstallationFound%22%3B%0A%7D%0A%0Aconst+gitBaseExtension+%3D+extensions.getExtension%3CGitBaseExtension%3E%28%0A+++++++++++++++++++++++++++++++%22vscode.git-base%22%2C%0A+++++++++++++++++++++++%29%21.exports%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=false#YwBsAGEAcwBzACAAUwBvAHUAcgBjAGUAUgBlAG0AbwB2AGUAVQBuAHUAcwBlAGQAIABlAHgAdABlAG4AZABzACAAUwBvAHUAcgBjAGUAQQBjAHQAaQBvAG4AIAB7AAoACQBzAHQAYQB0AGkAYwAgAHIAZQBhAGQAbwBuAGwAeQAgAGsAaQBuAGQAIAA9ACAAdgBzAGMAbwBkAGUALgBDAG8AZABlAEEAYwB0AGkAbwBuAEsAaQBuAGQALgBTAG8AdQByAGMAZQAuAGEAcABwAGUAbgBkACgACgAJAAkAIgByAGUAbQBvAHYAZQBVAG4AdQBzAGUAZAAiACwACgAJACkALgBhAHAAcABlAG4AZAAoACIAdABzACIAKQA7AAoACgAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAHIAZQBhAGQAbwBuAGwAeQAgAGkAZAAgAD0AIAAiAGoAYQB2AGEAcwBjAHIAaQBwAHQALQB3AGEAbABrAHQAaAByAG8AdQBnAGgALgBjAG8AbQBtAGEAbgBkAHMALgBuAG8AZABlAEkAbgBzAHQAYQBsAGwAYQB0AGkAbwBuAEYAbwB1AG4AZAAiADsACgB9AAoACgBjAG8AbgBzAHQAIABnAGkAdABCAGEAcwBlAEUAeAB0AGUAbgBzAGkAbwBuACAAPQAgAGUAeAB0AGUAbgBzAGkAbwBuAHMALgBnAGUAdABFAHgAdABlAG4AcwBpAG8AbgA8AEcAaQB0AEIAYQBzAGUARQB4AHQAZQBuAHMAaQBvAG4APgAoAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAiAHYAcwBjAG8AZABlAC4AZwBpAHQALQBiAGEAcwBlACIALAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAApACEALgBlAHgAcABvAHIAdABzADsA)
2. Observe how prettier breaks the initializers differently from Prettier		

### Expected result

Align the output with Prettier

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment]
Could I take the isssue?
