### ISSUE TITLE
Formatter: Avoid unnecessary string escapes

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3387]
### Environment information

```bash
main (3263f956fcc27bedc1c7d60fa25473cc42f2abf7)
```

### What happened?

1. Open [this playground](https://play.rome.tools/?code=%2F%2F+Not+for+directives%0A%22%5C%5C%5C%24%5C%7B%22%3B%0A%0Alet+a+%3D+%22%5C%5C%5C%24%5C%7B%22%3B%0A%0Alet+snipped+%3D+%27%5Cn++%5C%22%24%7B1%3A3000%7D%22%3A+%7B%5Cn++++%5C%22label%22%3A+%22%24%7B2%3AApplication%7D%22%2C%5Cn++++%5C%22onAutoForward%22%3A+%22%24%7B3%3AopenPreview%7D%22%5Cn++%7D%5Cn%27%3B%0A%0Aresult.push%28%27%5C%5C%5C%27%27%29&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=false#LwAvACAATgBvAHQAIABmAG8AcgAgAGQAaQByAGUAYwB0AGkAdgBlAHMACgAiAFwAXABcACQAXAB7ACIAOwAKAAoAbABlAHQAIABhACAAPQAgACIAXABcAFwAJABcAHsAIgA7AAoACgBsAGUAdAAgAHMAbgBpAHAAcABlAGQAIAA9ACAAJwBcAG4AIAAgAFwAIgAkAHsAMQA6ADMAMAAwADAAfQAiADoAIAB7AFwAbgAgACAAIAAgAFwAIgBsAGEAYgBlAGwAIgA6ACAAIgAkAHsAMgA6AEEAcABwAGwAaQBjAGEAdABpAG8AbgB9ACIALABcAG4AIAAgACAAIABcACIAbwBuAEEAdQB0AG8ARgBvAHIAdwBhAHIAZAAiADoAIAAiACQAewAzADoAbwBwAGUAbgBQAHIAZQB2AGkAZQB3AH0AIgBcAG4AIAAgAH0AXABuACcAOwAKAAoAcgBlAHMAdQBsAHQALgBwAHUAcwBoACgAJwBcAFwAXAAnACcAKQA=)
2. Observe how Prettier removes the unnecessary escapes in front of `$`, `"`, `'` and `{`

### Expected result

Rome to remove unnecessary escapes

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
@ematipico is this something you could help me with? If I remember correctly then it was you who implemented our current string cleaning.

**Comment by nissy-dev** [comment]
I try to take this issue 🚀

**Comment by MichaReiser** [comment]
> I try to take this issue 🚀

Awesome. I assigned the task to you. You can find the current logic [here](https://github.com/rome/tools/blob/5e45610dc563a64808fdbf127334226a3141e271/crates/rome_js_formatter/src/utils/string_utils.rs#L407) (it's a bit involved)

**Comment by 95th** [comment]
I raised a PR for this
