### ISSUE TITLE
📎 Add `rage` command 

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3411]
### Description

Add a `rage` command to the CLI that prints useful information about the environment to help debug issues. 

## Collected information

* CLI version (see #3410)
* Server version (if connected,  see #3410))
* [OS](https://doc.rust-lang.org/std/env/consts/constant.OS.html)
* [CPU Architecture](https://doc.rust-lang.org/std/env/consts/constant.ARCH.html)
* Path to the resolved `rome.json` configuration if any
* Path to the server socket if any
* supported terminal features
* Relevant environment variables? 
* Versions and names of all connected clients [Stretch]
* Traces [Stretch]

## Open Question

- [ ] Are we okay with including absolute paths in the rage output. Absolute paths may reveal information that a user doesn't feel comfortable sharing (e.g. their full or real name, name of the project, name of the company ).

**Comment by ematipico** [comment]
Here's an example of the old `rage --summary` command:

```shell
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_GB.UTF-8"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  16.17.0

Platform
  darwin x64 20.6.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 160
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: ""
    realCwd: ""
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 28_581_888
      pid: 80_113
      uptime: 0.224003897
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 28_581_888
        ownedBytes: 0
        ownedFileCount: 0
        pid: 80_113
        uptime: 0.223890422
      }
    ]
  }
```

What we could add: 
- terminal features (we have some crate that might help us with that). 

What we should ignore for now:
- "Server status", we have no projects and workers. Maybe info around the server itself if applicable
- "Client Flags", not sure we can have some info here

**Comment by ematipico** [comment]
> Are we okay with including absolute paths in the rage output. Absolute paths may reveal information that a user doesn't feel comfortable sharing (e.g. their full or real name, name of the project, name of the company ).

I think we should **not** share them.
