### ISSUE TITLE
🐛 Undocummented `start` and `stop` commands

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3415]
### Environment information

main (3a6e4346ee26a5a5d2f777ce62995cb900e0ce66)

### What happened?

1. Run `rome --help`
2. Observe that the `start` and `stop` commands aren't documented

```bash
❯ cargo run --bin rome -- --help
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rome --help`
Rome CLI v0.0.0

COMMANDS:
    - check
    - ci
    - format
    - init
    - help

OPTIONS:
    --no-colors      Disable the formatting of markup (print everything as plain text)
    --use-server     Connect to a running instance of the Rome daemon server

```

### Expected result

`start` and `stop` should be mentioned by `--help`.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
CC: @leops

**Comment by JackSparO3** [comment]
***@***.***
