### ISSUE TITLE
🐛 Message from `rome init` needs updating

### ISSUE THREAD

**Issue by egilsster** [rome/tools#3440]
### Environment information

```bash
- Rome: 0.10.1-next
- npm -v: 8.11.0
- node -v: v16.15.1
- macOS: 12.6
- Intel CPU
```

Happens on CI as well which uses ubuntu-latest on GHA (which I think is 20.04 at the time of writing)

### What happened?

After running the `npx rome@next init` the printed message states the following: "rome check is used to validate your code, verify formatting, and check for lint errors.". The reality is that `rome ci .` can be used to verify formatting and linting while separate commands are needed to apply any code changes, `rome format . --write` and `rome check . --apply[-suggestions]` respectively.

~With that said, I assume `rome format .` would not be necessary to enforce formatting. However, the results shown in `check` do not match with `rome format .` on the same project.~

**Side issue**: (which I can report separately): the extension in VSCode does not respect the current projects `rome.json`

### Expected result

I expect `rome check .` to detect formatting issues and `rome check . --apply[-suggested]` to fix them.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
Thanks for reporting this bug. The message printed by the `init` command needs updating. You can use `rome ci` to test the formatting and linting of your files. 

There's currently no command that allows you to fix lint errors and the formatting in a single pass but you can use `rome check --apply` and `rome format --write`

```
Rome CLI v0.0.0

COMMANDS:
    - check        Run the linter on a set of files
    - ci           Run the linter and check the formatting of a set of files
    - format       Run the formatter on a set of files
    - init         Bootstraps a new rome project
    - start        Start the Rome daemon server process
    - stop         Stop the Rome daemon server process
    - rage         Prints information for debugging
    - version      Shows the Rome version information and quit
    - help         Prints this help message

OPTIONS:
    --no-colors      Disable the formatting of markup (print everything as plain text)
    --use-server     Connect to a running instance of the Rome daemon server
    --version        Show the Rome version information and quit
```

**Comment by egilsster** [comment]
Re. using `rome ci` – shoulda checked that before. Cheers!

> There's currently no command that allows you to fix lint errors and the formatting in a single pass but you can use `rome check --apply` and `rome format --write`

I'll rename the issue to reflect the `rome init` message instead of my expectations from the message. Just for my own curiosity, is that something that might change? 🙂

Another one I mentioned as a side note in the report, regarding the VSCode extension not respecting the project configurations, would you like a report on that one or is it something that's on your radar?

Thanks for the quick reply, astonishing work you guys are doing and I am really looking forward to the future for Rome.

**Comment by MichaReiser** [comment]
>  Just for my own curiosity, is that something that might change? 

I'm not aware of it but @ematipico knows better than me.

> Another one I mentioned as a side note in the report, regarding the VSCode extension not respecting the project configurations, would you like a report on that one or is it something that's on your radar?

I must have missed that, sorry. Is it related to #3289? If not, then a report would help us to investigate the issue.

**Comment by egilsster** [comment]
> I must have missed that, sorry. Is it related to #3289? If not, then a report would help us to investigate the issue.

I'll report it if its unrelated but otherwise will follow that issue, thanks!

Feel free to assign this issue to me and I'll chef up a PR in the next few days!
