### ISSUE TITLE
🐛 `useSimplifiedLogicExpression`: double negation

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3454]
### Environment information

```bash
Rome CLI v0.10.1-next
```

### What happened?

```javascript
function isTrue(arg: String): boolean {
  return !!arg;
}
```

Rome emits a diagnostic that `!!arg` can be simplified to `arg`

```
main.ts:2:3 [lint/correctness/useSimplifiedLogicExpression](https://rome.tools/docs/lint/rules/useSimplifiedLogicExpression)  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Logical expression contains unnecessary complexity.
  
    1 │ function isTrue(arg: String): boolean {
  > 2 │   return !!arg
      │   ^^^^^
    3 │ }
  
  ℹ Suggested fix: Discard redundant terms from the logical expression.
  
    2 │ ··!!arg
      │   --
```

This is correct but may be problematic in situations where the tested value is a `truthy` value and the returned value is expected to be a `boolean`. An explicit conversion may be necessary in APIs, particularly when communicating with a backend. 

Furthermore, TypeScript yields an error if we remove the `!!` that `String` cannot be assigned to `boolean` [TypeScript Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAzgFQE4gKYAoCGGA5gFyIDKUGMYRAlGQEZxwA22+SA3gFCKIZsUEBiSEiPAL5A)

[Play](https://play.rome.tools/?code=function+isTrue%28arg%3A+String%29+%7B%0A++%21%21arg%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=false#ZgB1AG4AYwB0AGkAbwBuACAAaQBzAFQAcgB1AGUAKABhAHIAZwA6ACAAUwB0AHIAaQBuAGcAKQAgAHsACgAgACAAIQAhAGEAcgBnAAoAfQA=)

### Expected result

Ideally, Rome would only report `!!` on boolean values, but that would require type information. 

But I do think that we should consider a safer transformation that doesn't change the type of the returned value by either suggesting:

```javascript
Boolean(arg)
```

or only report `!!value` inside of logical expressions and not if the result of `!!arg` is the result of an expression (either because it is stored in a property, returned, or assigned to a variable)

A third option may be to keep the rule as is but explicitly promote `Boolean(arg)` or `arg === true` (may be a candidate for another stylistic lint rule to flag) in an advice. 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I am going to remove the logic that checks the double negation, because it's not an error and it's a valid usage.

The suggestion of `Boolean()` could be a good proposal for a new rule under the `style` group, because they essentially do the same thing.

**Comment by Boshen** [comment]
FYI eslint only check these inside boolean "positions": https://eslint.org/docs/latest/rules/no-extra-boolean-cast

**Comment by ematipico** [comment]
> FYI eslint only check these inside boolean "positions": [eslint.org/docs/latest/rules/no-extra-boolean-cast](https://eslint.org/docs/latest/rules/no-extra-boolean-cast)

https://rome.tools/docs/lint/rules/noextrabooleancast/
