### ISSUE TITLE
📎 Remove WASM dependencies from `rome` package

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3482]
### Description

Remove the wasm dependencies from the `rome` and `backend-jsonrpc` npm package

* `@rometools/wasm-bundler`
* `@rometools/wasm-nodejs`
* `@rometools/wasm-web`

> These dependencies are no longer required now that the `js-api` is in its own package.
This reduces the size of the `rome` package including its dependencies from 20 to 12mb

**Comment by ematipico** [comment]
The task should be "Move WASM dependencies from `rome` to `@rometools/js-api`" :)

**Comment by MichaReiser** [comment]
> The task should be "Move WASM dependencies from `rome` to `@rometools/js-api`" :)

Oh, I didn't know that. Since you're the expert. Would you mind updating the task with what must be done?
