### ISSUE TITLE
🐛 Parser: export default function in declare module

### ISSUE THREAD

**Issue by Boshen** [rome/tools#3485]
### Environment information

[PlayGround](https://play.rome.tools/?code=declare+module+%27x%27+%7B%0A++export+default+function+%28option%3A+any%29%3A+void%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=true#ZABlAGMAbABhAHIAZQAgAG0AbwBkAHUAbABlACAAJwB4ACcAIAB7AAoAIAAgAGUAeABwAG8AcgB0ACAAZABlAGYAYQB1AGwAdAAgAGYAdQBuAGMAdABpAG8AbgAgACgAbwBwAHQAaQBvAG4AOgAgAGEAbgB5ACkAOgAgAHYAbwBpAGQACgB9AA==)

### What happened?

```typescript
declare module 'x' {
  export default function (option: any): void
}
```

reports

`  ✖ expected an identifier, an array pattern, or an object pattern but instead found '('`

### Expected result

It should parse without syntax error

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment]
Could I try it?
