### ISSUE TITLE
🐛 Parser: `<` inside a chained optional call expression

### ISSUE THREAD

**Issue by Boshen** [rome/tools#3486]
### Environment information

[PlayGround](https://play.rome.tools/?code=item+%3D%3E+String%28item%29%3F.indexOf%28filterIdPrefix%29+%3C+0&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=script&enabledNurseryRules=true&typescript=false&jsx=false#aQB0AGUAbQAgAD0APgAgAFMAdAByAGkAbgBnACgAaQB0AGUAbQApAD8ALgBpAG4AZABlAHgATwBmACgAZgBpAGwAdABlAHIASQBkAFAAcgBlAGYAaQB4ACkAIAA8ACAAMAA=)

### What happened?

```javascript
item => String(item)?.indexOf(filterIdPrefix) < 0
```

errored with

```
  ✖ expected an identifier but instead found '<'
```

### Expected result

It should parse

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
This is an interesting one. For some reason, the parser starts an unnecessary `JsStaticMemberExpression` for the whole left side of the binary expression

**Comment by MichaReiser** [comment]
Minimal repro: [playground](https://play.rome.tools/?code=String%28item%29%3F.b+%3C+0&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=script&enabledNurseryRules=true&typescript=false&jsx=false#UwB0AHIAaQBuAGcAKABpAHQAZQBtACkAPwAuAGIAIAA8ACAAMAA=)
