### ISSUE TITLE
🐛 `formatter.enabled = false` breaks the linter with `rome ci .`

### ISSUE THREAD

**Issue by nstepien** [rome/tools#3495]
### Environment information

```bash
OS: win11, 64bit
Installation method: `npm i -D rome@0.10.1-next.e8dd9b4`
```

### What happened?

1. Install `rome@0.10.1-next.e8dd9b4`
2. Have the formatter disabled
3. run `rome ci .`

### Expected result

Rome should run the linter, instead nothing happens:
```
Checked 0 files in 4ms
```
Adding an explicit
```json
  "linter": {
    "enabled": true,
```
doesn't help.

I believe this doesn't happen with `0.10.1-next`, might be a recent regression.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I think issue might be the dot `.` in the command `rome ci` command. Could you try by speechifying the folder instead? 

I believe it's an issue of each command that traverses the file system.

**Comment by nstepien** [comment]
I tried
```
npx rome ci D:\repos\my-repo\
```
and that didn't work either.
FWIW if I remove `"enabled": false,` from the formatter config then it does work fine, with the dot.

**Comment by ematipico** [comment]
I could reproduce the issue, thank you!
