### ISSUE TITLE
🐛 Rome enforces an empty newline after a hashbang, prettier doesn't

### ISSUE THREAD

**Issue by nstepien** [rome/tools#3497]
### Environment information

```bash
OS: win11, 64bit
installation method: `npm i -D rome@0.10.1-next.e8dd9b4`
```

### What happened?

1. Open this [playground](https://play.rome.tools/?code=%23%21%2Fusr%2Fbin%2Fenv+node%0Aimport+fs+from+%27node%3Afs%27%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=false#IwAhAC8AdQBzAHIALwBiAGkAbgAvAGUAbgB2ACAAbgBvAGQAZQAKAGkAbQBwAG8AcgB0ACAAZgBzACAAZgByAG8AbQAgACcAbgBvAGQAZQA6AGYAcwAnADsA)
2. Notice that Rome always enforces an empty newline after a [hashbang](https://github.com/tc39/proposal-hashbang), while prettier allows 0 or 1 newline

### Expected result

Prettier compatibility.

TBH this is very minor, and I don't have a strong opinion about this, but maybe someone else does.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by unvalley** [comment]
I'll take a look.

**Comment by MichaReiser** [comment]
> I'll take a look.

Awesome. I assigned the issue to you. The formatting of directives is implemented in [FormatJsDirectiveList](https://github.com/rome/tools/blob/a38f2ef910119633232b04fb4ea1ee8e31002757/crates/rome_js_formatter/src/js/lists/directive_list.rs). Feel free to ping me on GitHub or discord if you have any questions.

**Comment by unvalley** [comment]
@MichaReiser 
Let me ask you a question.
Based on AST result in [reproduction](https://play.rome.tools/?code=%23%21%2Fusr%2Fbin%2Fenv+node%0Aimport+fs+from+%27node%3Afs%27%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=false#IwAhAC8AdQBzAHIALwBiAGkAbgAvAGUAbgB2ACAAbgBvAGQAZQAKAGkAbQBwAG8AcgB0ACAAZgBzACAAZgByAG8AbQAgACcAbgBvAGQAZQA6AGYAcwAnADsA), should I need to check [FormatNodeFile](https://github.com/rome/tools/blob/a9563e484843b245382e5d9057450774918fc9cc/crates/rome_js_formatter/src/js/auxiliary/module.rs#L12) ? (screenshot below) 
I tried to check FormatJsDirectiveList for the `JS_SHEBANG` handling. But, I thought that it might be necessary to access the `interpreter_token` to check the usage of `JS_SHEBANG`.

![Screen Shot 2022-11-02 at 2 21 51](https://user-images.githubusercontent.com/38400669/199296889-bee8211a-d3e7-4002-b3cd-e11a7222d915.png)

**Comment by MichaReiser** [comment]
Oh right, sorry. I pointed you to the wrong file. You're right. You need to see where the `interpreter_token` is formatted:

https://github.com/rome/tools/blob/a9563e484843b245382e5d9057450774918fc9cc/crates/rome_js_formatter/src/js/auxiliary/module.rs#L21-L28

You can see that this calls into `FormatInterpreterToken` which is implemented here https://github.com/rome/tools/blob/45545d881db7ce8465b41c94102c33e3092bac90/crates/rome_js_formatter/src/utils/mod.rs#L112-L132

**Comment by unvalley** [comment]
@MichaReiser I made a PR!
