### ISSUE TITLE
🐛 VSCode extension not applying rome.json settings

### ISSUE THREAD

**Issue by dev-ardi** [rome/tools#3513]
### Environment information

```bash
Windows 10
Last version of VSCode, rome and the extension
Installed the extension via the extension manager, installed rome (both globally and locally) via npm.
```
rome.json:
```json
{
  "linter": {
    "enabled": true,
    "rules": {
      "correctness": {
        "useBlockStatements": "off"
      },
      "style": {
        
      }
    }
  }
}
```

### What happened?

Explained in [#3492 ](https://github.com/rome/tools/discussions/3492?notification_referrer_id=NT_kwDOAtbUh7M0Njg2ODkwOTk1OjQ3NjMzNTQz&notifications_query=is%3Adone#discussion-4505338)

### Expected result

It should load the settings from rome.json. 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
I'm suspecting that the configuration may not be automatically reloaded (that's what I can reproduce locally). Can you try to run *Command Palette* -> *Reload Window* (or restart VS code).

**Comment by dev-ardi** [comment]
This has persisted for several days and computer reboots, though.

**Comment by MichaReiser** [comment]
Interesting. Can you share the output of the log written by rome (make sure to review its content first in case it contains information you aren't comfortable sharing).

You can find the log file under `%TEMP%/rome-logs/server.log.yyyy-mm-dd-hh` where `%TEMP` is the path to your temporary directory. The temp directory on windows is most likely the `AppData/Local/Temp/` in your home folder [source](https://helpcenter.trendmicro.com/en-us/article/tmka-20576).

**Comment by dev-ardi** [comment]
[server.log.2022-10-28-09.txt](https://github.com/rome/tools/files/9887307/server.log.2022-10-28-09.txt)

**Comment by dev-ardi** [comment]
I just finished reinstalling VSCode... it's working now. Really strange, maybe something was corrupted?

**Comment by ematipico** [comment]
_Maybe_ the version of the server that it was running was old. It happened to me too.

**Comment by dev-ardi** [comment]
Thanks, I'm happy it's going to get easier track.

**Comment by TylerJNewman** [comment]
I am having this same issue, I am on a mac.  where do i find the temp files to paste the log?

**Comment by ematipico** [comment]
> I am having this same issue, I am on a mac.  where do i find the temp files to paste the log?

Make sure to check the known limitations of the extension and the workarounds. https://github.com/rome/tools/blob/main/editors/vscode/README.md

If you still have the issue, please open a new issue. Use `rome rage` to get the info you need for the isse (like last logs)

**Comment by TylerJNewman** [comment]
> > I am having this same issue, I am on a mac.  where do i find the temp files to paste the log?
> 
> Make sure to check the known limitations of the extension and the workarounds. https://github.com/rome/tools/blob/main/editors/vscode/README.md
> 
> If you still have the issue, please open a new issue. Use `rome rage` to get the info you need for the issue (like last logs)

Rome rage helped show me that my rome.json was not configured correctly and was crashing.  thanks.  would be nice to have this error show up without rome rage, but thank you very much
