### ISSUE TITLE
🐛  Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by dev-ardi** [rome/tools#3519]
### Environment information

```bash
Windows 10
VSCode, everything up to date
```

### What happened?

```bash
[Info  - 08:26:11] Server initialized with PID: 4912
[Error - 08:36:57] Request textDocument/codeAction failed.
  Message: failed to access range Range { start: Position { line: 79, character: 32 }, end: Position { line: 79, character: 32 } } in document file:///c%3A/repos/PlayerTS/PlayerTS/src/Common/Network/http.ts
  Code: -32603 
failed to access range Range { start: Position { line: 79, character: 32 }, end: Position { line: 79, character: 32 } } in document file:///c%3A/repos/PlayerTS/PlayerTS/src/Common/Network/http.ts

Caused by:
    position Position { line: 79, character: 32 } is out of range
```

### Expected result

I'm not really sure what this is but I might as well share it.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Thank you for reporting this. This is a code action, it's probably something that the extension was trying to suggest due to some lint rule. 

In order to triage the issue we need the source code of the file

**Comment by MichaReiser** [comment]
> Thank you for reporting this. This is a code action, it's probably something that the extension was trying to suggest due to some lint rule.
> 
> In order to triage the issue we need the source code of the file

Or it would help to get some more information what actions you performed so that we can try performing the same steps on another file.

**Comment by leops** [comment]
> Thank you for reporting this. This is a code action, it's probably something that the extension was trying to suggest due to some lint rule.

The `textDocument/codeAction` request is sent from the editor to the language server to enumerate possible code actions at the current cursor position. The specific "failed to access range" error message is emitted if the cursor position sent by the editor cannot be mapped to a byte offset in the content of the document, even before the analyzer starts running to generate code actions. This points at a possible synchronization issue between the state of the editor's text buffer and document in the language server, and depending on which version is being used here may be caused or solved by #3504

**Comment by dev-ardi** [comment]
> In order to triage the issue we need the source code of the file
I'm not able to provide the source since it's company code. I don't want to get in trouble :P 
 
> Or it would help to get some more information what actions you performed so that we can try performing the same steps on another file.

The action I performed was just click around or hover words, every time I did the error would pop up. It went away restarting VSCode.

> The textDocument/codeAction request is sent from the editor to the language server to enumerate possible code actions

Yep. I can add that `position Position { line: 79, character: 32 } is out of range`  line 79 was just an empty line, a mis sync makes sense.

**Comment by ematipico** [comment]
@dev-ardi could you try version `v0.10.1-nightly.a9db0f0` and see if this is fixed?

**Comment by dev-ardi** [comment]
I was unable to replicate the bug with the previous version
