### ISSUE TITLE
📎 Improve `noUnusedVariable` advice 

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3520]
### Description

Unused parameters and variables can be intentional. 

However, it is unclear from the diagnostic that prefixing a variable with `_` silences the lint. [play](https://play.rome.tools/?code=helper.runAgain%28%28stats%2C+files%2C+iteration%29+%3D%3E+%7B%0A%09%09%09%09%09%09%2F%2F+Cached+the+third+run%0A%09%09%09%09%09%09expect%28stats.assets%5B0%5D.name%29.toBe%28%22bundle.js%22%29%3B%0A%09%09%09%09%09%09expect%28stats.assets%5B0%5D.emitted%29.toBe%28true%29%3B%0A%0A%09%09%09%09%09%09done%28%29%3B%0A%09%09%09%09%09%7D%29%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=false&jsx=false#aABlAGwAcABlAHIALgByAHUAbgBBAGcAYQBpAG4AKAAoAHMAdABhAHQAcwAsACAAZgBpAGwAZQBzACwAIABpAHQAZQByAGEAdABpAG8AbgApACAAPQA+ACAAewAKAAkACQAJAAkACQAJAC8ALwAgAEMAYQBjAGgAZQBkACAAdABoAGUAIAB0AGgAaQByAGQAIAByAHUAbgAKAAkACQAJAAkACQAJAGUAeABwAGUAYwB0ACgAcwB0AGEAdABzAC4AYQBzAHMAZQB0AHMAWwAwAF0ALgBuAGEAbQBlACkALgB0AG8AQgBlACgAIgBiAHUAbgBkAGwAZQAuAGoAcwAiACkAOwAKAAkACQAJAAkACQAJAGUAeABwAGUAYwB0ACgAcwB0AGEAdABzAC4AYQBzAHMAZQB0AHMAWwAwAF0ALgBlAG0AaQB0AHQAZQBkACkALgB0AG8AQgBlACgAdAByAHUAZQApADsACgAKAAkACQAJAAkACQAJAGQAbwBuAGUAKAApADsACgAJAAkACQAJAAkAfQApADsA)

## Goal

Add an advice to the diagnostic that explains that prefixing a variable with `_` silence the lint (you may want to take inspiration from Rust).

**Comment by leops** [comment]
Rustc goes even further and provides a code action to rename the variable and add the `_` prefix
