### ISSUE TITLE
🐛 initializer parameter considered as "duplicated binding" in deconstruction

### ISSUE THREAD

**Issue by Jack-Works** [rome/tools#3521]
### Environment information

```bash
v0.10
```

### What happened?

https://play.rome.tools/?code=const+%7B+value%2C+f+%3D+%28value%29+%3D%3E+value+%7D+%3D+item&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=false&jsx=false#YwBvAG4AcwB0ACAAewAgAHYAYQBsAHUAZQAsACAAZgAgAD0AIAAoAHYAYQBsAHUAZQApACAAPQA+ACAAdgBhAGwAdQBlACAAfQAgAD0AIABpAHQAZQBtAA==

![image](https://user-images.githubusercontent.com/5390719/198535308-12082472-694b-4481-9649-d6b42b6457fd.png)

### Expected result

No error.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
Duplicate of  #2960
