### ISSUE TITLE
🐛 Various spacing/line length formatting incompatibilities with Prettier

### ISSUE THREAD

**Issue by nstepien** [rome/tools#3531]
### Environment information

```bash
OS: win11, 64bit
install: `npm i rome@nightly`
```

### What happened?

1. Open this [playground](https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=LwAvACAAcAByAGUAdAB0AGkAZQByACAAcwBlAGUAbQAgAHQAbwAgAGYAYQB2AG8AcgAgADEALQBsAGkAbgBlACAAaQBtAHAAbwByAHQAcwAvAGUAeABwAG8AcgB0AHMAIAB3AGgAZQBuACAAcABvAHMAcwBpAGIAbABlAAoAaQBtAHAAbwByAHQAIAB7ACAAYQAgAGEAcwAgAGIAIAB9ACAAZgByAG8AbQAgACcAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6ACcAOwAKAGkAbQBwAG8AcgB0ACAAewAgAGMAIABhAHMAIABkACAAfQAgAGYAcgBvAG0AIAAnAHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAJwA7AAoAZQB4AHAAbwByAHQAIAB7ACAAZQAgAGEAcwAgAGYAIAB9ACAAZgByAG8AbQAgACcAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegAnADsACgAvAC8AIABpAG0AcABvAHIAdAAgAGkAcwAgADEAIABsAGkAbgBlACwAIABlAHgAcABvAHIAdAAgAGkAcwAgAG4AbwB0AD8ACgBpAG0AcABvAHIAdAAgAHsAIAB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegAgAH0AIABmAHIAbwBtACAAJwB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6ACcAOwAKAGUAeABwAG8AcgB0ACAAewAgAHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6ACAAfQAgAGYAcgBvAG0AIAAnAHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAJwA7AAoACgAvAC8AIABSAG8AbQBlACAAZgBvAHIAbQBhAHQAdABpAG4AZwAgAGkAcwAgAGQAaQBmAGYAZQByAGUAbgB0ACAAaABlAHIAZQAKAGYAdQBuAGMAdABpAG8AbgAgAEMAbwBtAHAAbwBuAGUAbgB0ADEAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwATwB0AGgAZQByAEMAbwBtAHAAbwBuAGUAbgB0AAoAIAAgACAAIAAgACAAYQA9AHsAMQB9AAoAIAAgACAAIAAgACAAYgA9AHsAMgB9ACAALwAvACAAYwBvAG0AbQBlAG4AdAAKACAAIAAgACAALwA%2BAAoAIAAgACkAOwAKAH0ACgAKAC8ALwAgAFIAbwBtAGUAIABmAG8AcgBtAGEAdAB0AGkAbgBnACAAaQBzACAAaQBkAGUAbgB0AGkAYwBhAGwAIABoAGUAcgBlACAAPdhN3AoAZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAMgAoACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAKAAKACAAIAAgACAAPABPAHQAaABlAHIAQwBvAG0AcABvAG4AZQBuAHQACgAgACAAIAAgACAAIABhAD0AewAxAH0ACgAgACAAIAAgACAAIABiAD0AewAyAH0AIAAvAC8AIABjAG8AbQBtAGUAbgB0AAoAIAAgACAAIAAgACAAYwA9AHsAMwB9AAoAIAAgACAAIAAvAD4ACgAgACAAKQA7AAoAfQAKAAoALwAvACAAcAByAGUAdAB0AGkAZQByACAAbQBhAGsAZQBzACAAdABoAGkAcwAuAC4ALgAgAHAAcgBlAHQAdABpAGUAcgAgAHQAaABhAG4AIAByAG8AbQBlAAoAZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAMwAoACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAKAAKACAAIAAgACAAPABkAGkAdgA%2BAAoAIAAgACAAIAAgACAAewBmAG4AKABkAGEAdABhACkAfQB7ACcAIAAnAH0ACgAgACAAIAAgACAAIAA8AEMAbwBtAHAAbwBuAGUAbgB0ACAALwA%2BAAoAIAAgACAAIAA8AC8AZABpAHYAPgAKACAAIAApADsACgB9AAoACgAvAC8AIABkAGkAZgBmAGUAcgBlAG4AdAAgAG8AdQB0AHAAdQB0ACAAdABoAGEAbgAgAHAAcgBlAHQAdABpAGUAcgAKAGYAdQBuAGMAdABpAG8AbgAgAEMAbwBtAHAAbwBuAGUAbgB0ADQAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAPgAKACAAIAAgACAAIAAgAHsAZgBuACgAZABhAHQAYQBkAGEAdABhAGQAYQB0AGEAZABhAHQAYQBkAGEAdABhAGQAYQB0AGEAZABhAHQAYQBkAGEAdABhAGQAYQB0AGEAZABhAHQAYQBkAGEAdABhAGQAYQB0AGEAZABhAHQAYQBkAGEAdABhAGQAYQB0AGEAZABhAHQAYQApAH0AewAnACAAJwB9AAoAIAAgACAAIAAgACAAPABDAG8AbQBwAG8AbgBlAG4AdAAgAC8APgAKACAAIAAgACAAPAAvAGQAaQB2AD4ACgAgACAAKQA7AAoAfQA%3D)
2. Notice the multiple formatting differences between the Rome output and Prettier output

### Expected result

Prettier compatibility.

I've tested Nightly Rome's formatter in our biggest codebase, and these were the only differences I found.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by unvalley** [comment]
I'll take a look.  We can split this task to: 
- [ ] imports/exports line break
- [ ] JSX comment to props (specifically props count is 2, and comment to 2nd)
- [ ] JSX space in childNodes
- [ ] JSX space in childNodes with long strings

**Comment by nstepien** [comment]
I have found some more incompatibility with prettier: [playground](https://play.rome.tools/?code=export+function+formatNumber1%28%0A++value%3A+string%2C%0A++%7B%0A++++a%2C%0A++++b%2C%0A++++c%2C%0A++++formatNumber%2C%0A++++...props%0A++%7D%3A+Omit%3CNumberFormatterProps%2C+%27value%27+%7C+%27defaultFractionDigits%27%3E+%26+%7B%0A++++useGrouping%3F%3A+boolean%3B%0A++%7D%0A%29%3A+string+%7B%7D%0A%0Aexport+function+formatNumber2%28%0A++value%3A+string%2C%0A++%7B+a+%7D%3A+Omit%3CNumberFormatterProps%2C+%27value%27+%7C+%27defaultFractionDigits%27%3E+%26+%7B%0A++++useGrouping%3F%3A+boolean%3B%0A++%7D%0A%29%3A+string+%7B%7D&lineWidth=100&indentStyle=space&quoteStyle=single&quoteProperties=as-needed&trailingComma=none&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=true#ZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABmAG8AcgBtAGEAdABOAHUAbQBiAGUAcgAxACgACgAgACAAdgBhAGwAdQBlADoAIABzAHQAcgBpAG4AZwAsAAoAIAAgAHsACgAgACAAIAAgAGEALAAKACAAIAAgACAAYgAsAAoAIAAgACAAIABjACwACgAgACAAIAAgAGYAbwByAG0AYQB0AE4AdQBtAGIAZQByACwACgAgACAAIAAgAC4ALgAuAHAAcgBvAHAAcwAKACAAIAB9ADoAIABPAG0AaQB0ADwATgB1AG0AYgBlAHIARgBvAHIAbQBhAHQAdABlAHIAUAByAG8AcABzACwAIAAnAHYAYQBsAHUAZQAnACAAfAAgACcAZABlAGYAYQB1AGwAdABGAHIAYQBjAHQAaQBvAG4ARABpAGcAaQB0AHMAJwA+ACAAJgAgAHsACgAgACAAIAAgAHUAcwBlAEcAcgBvAHUAcABpAG4AZwA/ADoAIABiAG8AbwBsAGUAYQBuADsACgAgACAAfQAKACkAOgAgAHMAdAByAGkAbgBnACAAewB9AAoACgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAGYAbwByAG0AYQB0AE4AdQBtAGIAZQByADIAKAAKACAAIAB2AGEAbAB1AGUAOgAgAHMAdAByAGkAbgBnACwACgAgACAAewAgAGEAIAB9ADoAIABPAG0AaQB0ADwATgB1AG0AYgBlAHIARgBvAHIAbQBhAHQAdABlAHIAUAByAG8AcABzACwAIAAnAHYAYQBsAHUAZQAnACAAfAAgACcAZABlAGYAYQB1AGwAdABGAHIAYQBjAHQAaQBvAG4ARABpAGcAaQB0AHMAJwA+ACAAJgAgAHsACgAgACAAIAAgAHUAcwBlAEcAcgBvAHUAcABpAG4AZwA/ADoAIABiAG8AbwBsAGUAYQBuADsACgAgACAAfQAKACkAOgAgAHMAdAByAGkAbgBnACAAewB9AA==)

**Comment by nstepien** [comment]
Yet another example: [playground](https://play.rome.tools/?code=function+Component%28%29+%7B%0A++return+%28%0A++++%3COtherComponent%0A++++++value%3D%7B%0A++++++++new+Set%28veryLongConditionZzzzzzzzzzzzzzzzz+%3F+%5B1%2C+2%2C+3%5D+%3A+undefined%29%0A++++++%7D%0A++++%2F%3E%0A++%29%3B%0A%7D%0A%0Afunction+Component2%28%29+%7B%0A++return+%28%0A++++%3COtherComponent%0A++++++value%3D%7B%0A++++++++new+Set%28veryLongConditionZzzzzzzzzzzzzzzzzzzzzzz+%3F+%5B1%2C+2%2C+3%5D+%3A+undefined%29%0A++++++%7D%0A++++%2F%3E%0A++%29%3B%0A%7D%0A&lineWidth=80&indentStyle=space&quoteStyle=single&quoteProperties=as-needed&trailingComma=none&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=true#ZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwATwB0AGgAZQByAEMAbwBtAHAAbwBuAGUAbgB0AAoAIAAgACAAIAAgACAAdgBhAGwAdQBlAD0AewAKACAAIAAgACAAIAAgACAAIABuAGUAdwAgAFMAZQB0ACgAdgBlAHIAeQBMAG8AbgBnAEMAbwBuAGQAaQB0AGkAbwBuAFoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegAgAD8AIABbADEALAAgADIALAAgADMAXQAgADoAIAB1AG4AZABlAGYAaQBuAGUAZAApAAoAIAAgACAAIAAgACAAfQAKACAAIAAgACAALwA+AAoAIAAgACkAOwAKAH0ACgAKAGYAdQBuAGMAdABpAG8AbgAgAEMAbwBtAHAAbwBuAGUAbgB0ADIAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwATwB0AGgAZQByAEMAbwBtAHAAbwBuAGUAbgB0AAoAIAAgACAAIAAgACAAdgBhAGwAdQBlAD0AewAKACAAIAAgACAAIAAgACAAIABuAGUAdwAgAFMAZQB0ACgAdgBlAHIAeQBMAG8AbgBnAEMAbwBuAGQAaQB0AGkAbwBuAFoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegAgAD8AIABbADEALAAgADIALAAgADMAXQAgADoAIAB1AG4AZABlAGYAaQBuAGUAZAApAAoAIAAgACAAIAAgACAAfQAKACAAIAAgACAALwA+AAoAIAAgACkAOwAKAH0ACgA=)

**Comment by MichaReiser** [comment]
> I'll take a look. We can split this task to:
> 
>     * [ ]  imports/exports line break
> 
>     * [ ]  JSX comment to props (specifically props count is 2, and comment to 2nd)
> 
>     * [ ]  JSX space in childNodes
> 
>     * [ ]  JSX space in childNodes with long strings

Are you looking into all these issues or some of them? Can other contributors help you with some of the work?

**Comment by unvalley** [comment]
@MichaReiser 

> Can other contributors help you with some of the work?
Yes, thanks.
I'm working on import/exports line break now. Other tasks remains.

**Comment by denbezrukov** [comment]
> I have found some more incompatibility with prettier: [playground](https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=ZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABmAG8AcgBtAGEAdABOAHUAbQBiAGUAcgAxACgACgAgACAAdgBhAGwAdQBlADoAIABzAHQAcgBpAG4AZwAsAAoAIAAgAHsACgAgACAAIAAgAGEALAAKACAAIAAgACAAYgAsAAoAIAAgACAAIABjACwACgAgACAAIAAgAGYAbwByAG0AYQB0AE4AdQBtAGIAZQByACwACgAgACAAIAAgAC4ALgAuAHAAcgBvAHAAcwAKACAAIAB9ADoAIABPAG0AaQB0ADwATgB1AG0AYgBlAHIARgBvAHIAbQBhAHQAdABlAHIAUAByAG8AcABzACwAIAAnAHYAYQBsAHUAZQAnACAAfAAgACcAZABlAGYAYQB1AGwAdABGAHIAYQBjAHQAaQBvAG4ARABpAGcAaQB0AHMAJwA%2BACAAJgAgAHsACgAgACAAIAAgAHUAcwBlAEcAcgBvAHUAcABpAG4AZwA%2FADoAIABiAG8AbwBsAGUAYQBuADsACgAgACAAfQAKACkAOgAgAHMAdAByAGkAbgBnACAAewB9AAoACgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAGYAbwByAG0AYQB0AE4AdQBtAGIAZQByADIAKAAKACAAIAB2AGEAbAB1AGUAOgAgAHMAdAByAGkAbgBnACwACgAgACAAewAgAGEAIAB9ADoAIABPAG0AaQB0ADwATgB1AG0AYgBlAHIARgBvAHIAbQBhAHQAdABlAHIAUAByAG8AcABzACwAIAAnAHYAYQBsAHUAZQAnACAAfAAgACcAZABlAGYAYQB1AGwAdABGAHIAYQBjAHQAaQBvAG4ARABpAGcAaQB0AHMAJwA%2BACAAJgAgAHsACgAgACAAIAAgAHUAcwBlAEcAcgBvAHUAcABpAG4AZwA%2FADoAIABiAG8AbwBsAGUAYQBuADsACgAgACAAfQAKACkAOgAgAHMAdAByAGkAbgBnACAAewB9AA%3D%3D)

I can help with this =)

**Comment by nstepien** [comment]
Probably the last prettier incompatibility I'll find, seems very very minor though: [playground](https://docs.rome.tools/playground/?indentStyle=space&trailingComma=none&code=ZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAPgAKACAAIAAgACAAIAAgADwAcwBwAGEAbgA%2BAHQAZQB4AHQAPAAvAHMAcABhAG4APgAuADwAYgByACAALwA%2BAAoAIAAgACAAIAA8AC8APgAKACAAIAApADsACgB9AAoA)

**Comment by nstepien** [comment]
Yeah I personally don't mind if this doesn't get fixed.
Maybe it affects other repos differently.

**Comment by nstepien** [comment]
Does anyone want to look into the [single-character-in-jsx formatting](https://docs.rome.tools/playground/?indentStyle=space&trailingComma=none&code=ZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAPgAKACAAIAAgACAAIAAgADwAcwBwAGEAbgA%2BAHQAZQB4AHQAPAAvAHMAcABhAG4APgAuADwAYgByACAALwA%2BAAoAIAAgACAAIAA8AC8APgAKACAAIAApADsACgB9AAoA) incompatibility?

Otherwise I'm happy with closing this issue, thank you everyone!

**Comment by denbezrukov** [comment]
> Does anyone want to look into the [single-character-in-jsx formatting](https://docs.rome.tools/playground/?indentStyle=space&trailingComma=none&code=ZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAPgAKACAAIAAgACAAIAAgADwAcwBwAGEAbgA%2BAHQAZQB4AHQAPAAvAHMAcABhAG4APgAuADwAYgByACAALwA%2BAAoAIAAgACAAIAA8AC8APgAKACAAIAApADsACgB9AAoA) incompatibility?
> 
> Otherwise I'm happy with closing this issue, thank you everyone!

I'll check it =)
