### ISSUE TITLE
📎 Decide on `noUnusedVariables` stability

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3539]
### Description

Decide whether `noUnusedVariables` should be shipped as stable or nursery rule.

**Comment by xunilrj** [comment]
I vote for yes. Don't know any major issue with it.

**Comment by xunilrj** [comment]
I would not recommend it for the moment, and for one simple reason: on the eslint repo, for example, it flags dozens of unused variables. A lot of the cases are silly things like copy and paste, function contracts etc...  They are really not bugs.

We would be forcing a lot of code changes with no obvious gains for the users.  
As time passes, we will give time for people to fix this issues and this rule will generate less churn for nothing.

**Comment by ematipico** [comment]
> I would not recommend it for the moment, and for one simple reason: on the eslint repo, for example, it flags dozens of unused variables. A lot of the cases are silly things like copy and paste, function contracts etc... They are really not bugs.
> 
> We would be forcing a lot of code changes with no obvious gains for the users. As time passes, we will give time for people to fix this issues and this rule will generate less churn for nothing.

Good point!
