### ISSUE TITLE
Website: maxFileSizeDefault is incorrect 

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3568]
### Environment information

```bash
Website
```

### What happened?

Mentions that the default is 1024 bytes = 1Kb

### Expected result

Default is 1 MB. 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
The expected result should be 1,048,576 (1024*1024). The setting accepts only numbers
