### ISSUE TITLE
🐛 Add `--files-max-size` to help

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3571]
### Environment information

```bash
main
```

### What happened?

`--files-max-size` isn't mentioned when running `rome --help` or `rome check --help`. 

### Expected result

The option should be documented.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
https://github.com/rome/tools/blob/998e1008d01814843e98bab39f7ce74e05cdb02c/crates/rome_cli/src/commands/help.rs

This issue will closed by the release PR. @MichaReiser could you do me favour and update that PR, so this issue gets closed automatically, please? From mobile it's hard as hell.. 🤣
