### ISSUE TITLE
📎 `init` separators are too long

### ISSUE THREAD

**Issue by sebmck** [rome/tools#3589]
### Description

Can we use the console width to decide how wide to make these?

![313774620_1140239643577186_3071873384434397001_n](https://user-images.githubusercontent.com/853712/200599350-540bfad9-503a-44c4-83f0-0713c67f3748.png)

**Comment by DhrjArun** [comment]
I have done some research on how to implement this. 

For **winodws**, `windows_sys` crate provide [`GetConsoleScreenBufferInfo`](https://docs.rs/windows-sys/latest/windows_sys/Win32/System/Console/fn.GetConsoleScreenBufferInfo.html) method which takes `HANDLE`

For **unix** `rustix` crate provide [`tcgetwinsize`](https://docs.rs/rustix/latest/rustix/termios/fn.tcgetwinsize.html) method which takes [Fd (Function Descriptor)](https://www.youtube.com/watch?v=-gP58pozNuM&ab_channel=BugsWriter)

Here are some of the github repo 
- **https://github.com/eminence/terminal-size** (best one)
- https://github.com/softprops/termsize
- https://github.com/clap-rs/term_size-rs
- https://github.com/nicokoch/termsize-rs
- https://github.com/JohnTitor/termize

Assign this issue to me and let me know if you have any suggestions.

**Comment by ematipico** [comment]
@DhrjArun FYI we already such logic in our code base, but it's internal to our diagnostics.

https://github.com/rome/tools/blob/main/crates/rome_diagnostics/src/v2/display.rs#L58-L176

An interesting refactor might be to make it a bit generic, so we can use it outside of a diagnostic

**Comment by DhrjArun** [comment]
> @DhrjArun FYI we already such logic in our code base, but it's internal to our diagnostics.
> 
> https://github.com/rome/tools/blob/main/crates/rome_diagnostics/src/v2/display.rs#L58-L176
> 
> An interesting refactor might be to make it a bit generic, so we can use it outside of a diagnostic 

I would love to do this.

**Comment by DhrjArun** [comment]
> 

@ematipico `CountWidth` struct counts the width of content in the header. Everytime `write_str` method is called it takes content and increases its width value. 

let's say width is 50, Which will be subtracted from the `HEADER_WIDTH` which is a hardcoded value of 100 to produce `line_width`.

but if the terminal size is less than 100, the horizontal line will overflow like this.
![Screenshot 2022-11-20 at 16 44 50](https://user-images.githubusercontent.com/69076988/202899018-d9054d53-0b37-44e4-90b7-3eb386ea9a2c.png)

That is why we need to know the console width (which is not implemented) to replace the hardcoded 100 with the current console width.
