### ISSUE TITLE
🐛 Trailing comma inside import

### ISSUE THREAD

**Issue by ritz078** [rome/tools#3600]
### Environment information

```block
CLI:
  Version:              10.0.0
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      true

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Server:
  Status:               stopped
```

### What happened?

Here is the code snippet: [playground](https://play.rome.tools/?code=const+StandaloneBackendWASMModule+%3D+await+import%28%2F*+webpackChunkName%3A+%22standalone%22+*%2F%27.%2FStandaloneBackendWASM%27%29%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=false&jsx=false#YwBvAG4AcwB0ACAAUwB0AGEAbgBkAGEAbABvAG4AZQBCAGEAYwBrAGUAbgBkAFcAQQBTAE0ATQBvAGQAdQBsAGUAIAA9ACAAYQB3AGEAaQB0ACAAaQBtAHAAbwByAHQAKAAvACoAIAB3AGUAYgBwAGEAYwBrAEMAaAB1AG4AawBOAGEAbQBlADoAIAAiAHMAdABhAG4AZABhAGwAbwBuAGUAIgAgACoALwAnAC4ALwBTAHQAYQBuAGQAYQBsAG8AbgBlAEIAYQBjAGsAZQBuAGQAVwBBAFMATQAnACkAOwA=)

Rome adds a trailing comma inside `import` and babel parser throws an error (`Trailing comma is disallowed inside import(...) arguments`) during compilation. This isn't a problem with prettier.

### Expected result

```js
const StandaloneBackendWASMModule = await import(
	/* webpackChunkName: "standalone" */ "./StandaloneBackendWASM"
);
``` 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment]
Could I fix it?
