### ISSUE TITLE
📎 JSON Schema

### ISSUE THREAD

**Issue by Rawnly** [rome/tools#3601]
### Description

Create a JSON schema (following [json-schema](https://json-schema.org/learn/getting-started-step-by-step.html) standard) would be a nice improvement to the configuration file.

I would be happy to help into this. It can be uploaded on the website then (like [turbo](https://turbo.build/schema.json) does.) or  on [SchemaStore](https://github.com/SchemaStore/schemastore)

**Comment by milesj** [comment]
I use this in moon and it works great https://crates.io/crates/schemars

As an example, these are the schemas it creates: https://github.com/moonrepo/moon/tree/master/website/static/schemas

**Comment by spartanatreyu** [comment]
Unrelated tangent: 
@Rawnly 

What editor and theme is that in your screenshot? It looks quite nice.

**Comment by Rawnly** [comment]
> Unrelated tangent: 
> 
> @Rawnly 
> 
> 
> 
> What editor and theme is that in your screenshot? It looks quite nice.

Hey is neovim with catppuccin theme

**Comment by simon04** [comment]
For now, while writing the configuration file you can reference https://raw.githubusercontent.com/rome/tools/main/editors/vscode/configuration_schema.json like so:

```json
{
  "$schema": "https://raw.githubusercontent.com/rome/tools/main/editors/vscode/configuration_schema.json",
  "formatter": {
    "indentStyle": "space"
  },
  "javascript": {
    "formatter": {
      "trailingComma": "none"
    }
  }
}
```

However `$schema` cannot be used when running `rome`, see #3690.
