### ISSUE TITLE
🐛 some parse failures from a fuzzer

### ISSUE THREAD

**Issue by bakkot** [rome/tools#3607]
### Environment information

```block
CLI:
  Version:              10.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Server:
  Status:               stopped
```

### What happened?

The following syntactically valid programs are rejected by `rome check` as invalid, even with all lint rules turned off.

I found these with [a fuzzer](https://github.com/bakkot/fuzz-js/blob/b1ad61c1be5b2264cbc677ff28cd9c864ed23b28/rome.js); prioritize accordingly. If you'd prefer I not submit bugs found by fuzzing, let me know. Alternatively, if you'd prefer I open distinct bugs for each issue, I'm happy to do that.

Of these errors only the first is likely to come up in real code, in my estimation.

```js
chars</^\w*/.exec(str)[0].length;
```
```js
async: for(a of b) continue async;
```
```js
async(...null);
```
```js
class A extends B {
  constructor(c = super()) {}
}
```
```js
(class extends {}._ {});
```

### Expected result

All of these programs are valid JavaScript and should not be rejected.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
> chars</^\w*/.exec(str)[0].length;

Rome parses this correctly when the source type is JS and not JSX. It fails to parse in JSX mode (so does TypeScript). We should add a way for users to disable JSX parsing #3611 

> async(...null); 
> (class extends {}._ {});

TypeScript doesn't like these either :D

**Comment by MichaReiser** [comment]
I'm splitting this into a couple of smaller issues. We don't plan to fix the issues that TypeScript fails to parse as well:

* #3612
* #3613
