### ISSUE TITLE
🐛 Playground: JSX always enabled

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3610]
### What happened?

* Open [Playground](https://play.rome.tools/?code=%2F%2F+chars%3C%2F%5E%5Cw*%2F.exec%28str%29%5B0%5D.length%3B%0A%0Afunction+a%28%29+%7B%0A++return+%3Ctest%3Ea%3C%2Ftest%3E%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&trailingComma=all&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=false&jsx=false#LwAvACAAYwBoAGEAcgBzADwALwBeAFwAdwAqAC8ALgBlAHgAZQBjACgAcwB0AHIAKQBbADAAXQAuAGwAZQBuAGcAdABoADsACgAKAGYAdQBuAGMAdABpAG8AbgAgAGEAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgADwAdABlAHMAdAA+AGEAPAAvAHQAZQBzAHQAPgAKAH0A)
* The file parses correctly regardless if the JSX setting is enabled or not

### Expected result

* There should be parse errors if JSX is disabled

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by kaioduarte** [comment]
`rome check` can also parse JSX inside a JS file, is there any flag or config we should add to the CLI to make it fail?

**Comment by MichaReiser** [comment]
> `rome check` can also parse JSX inside a JS file, is there any flag or config we should add to the CLI to make it fail?

There's no such flag yet (to my knowledge) for the CLI. This work is tracked in #3611. I would expect it to be possible in the playground by passing the `SourceType`
