### ISSUE TITLE
🐛 Parser: Allow `super` in constructor parameter. 

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3613]
### Environment information

```block
Playground
```

### What happened?

Rome emits syntax errors for the following valid program:

```javascript
class A extends B {
  constructor(c = super()) {}
}
```

### Expected result

Rome parses the program without syntax errors.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment]
Could I try to fix it?🙏
