### ISSUE TITLE
🐛 Rome with pnpm workspace fails

### ISSUE THREAD

**Issue by yagiz-noonlight** [rome/tools#3621]
### Environment information

```block
➜  ~ npx rome rage
CLI:
  Version:              10.0.0
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               unset

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Rome server.

✖ Workspace rage failed: Method not found

Rome Server Log:

⚠ Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

├─369287484ms INFO rome_lsp::server Starting Rome Language Server...
├─369307284ms INFO rome_lsp::server Starting Rome Language Server...
├─369307285ms ERROR tower_lsp::transport failed to encode message: failed to encode response: Socket is not connected (os error 57)
```
```


### What happened?

```➜  developer npx rome check .
/Users/yagiz_nizipli/Developer/developer/node_modules/.pnpm/rome@10.0.0/node_modules/rome/bin/rome:28
		throw result.error;
		^

Error: spawnSync /Users/yagiz_nizipli/Developer/developer/node_modules/.pnpm/@rometools+cli-darwin-arm64@10.0.0/node_modules/@rometools/cli-darwin-arm64/rome EACCES
    at Object.spawnSync (node:internal/child_process:1110:20)
    at Object.spawnSync (node:child_process:857:24)
    at Object.<anonymous> (/Users/yagiz_nizipli/Developer/developer/node_modules/.pnpm/rome@10.0.0/node_modules/rome/bin/rome:21:42)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawnSync /Users/yagiz_nizipli/Developer/developer/node_modules/.pnpm/@rometools+cli-darwin-arm64@10.0.0/node_modules/@rometools/cli-darwin-arm64/rome',
  path: '/Users/yagiz_nizipli/Developer/developer/node_modules/.pnpm/@rometools+cli-darwin-arm64@10.0.0/node_modules/@rometools/cli-darwin-arm64/rome',
  spawnargs: [ 'check', '.' ]
}```

### Expected result

To run correctly.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
I understand that you installed `rome` with `pnpm`. Is this correct? 

If so, can you try running rome with `pnpm exec rome`

**Comment by nicksrandall** [comment]
I am also seeing this issue. `pnpm exec rome` spits out the same error as above.

**Comment by yagiz-noonlight** [comment]
Unfortunately not. These are steps:

1. mkdir test-folder && cd test-folder
2. npm init -y
3. touch pnpm-workspace.yml && nano pnpm-workspace.yml
4. Add `packages: \n - 'packages/*'`
5. run `pnpm add -D rome -w` in root directory
6. add `rome format .` to any `scripts.format` in package.json
7. run `pnpm run format`

**Comment by leops** [comment]
Since the `spawnSync` function fails with the code `EACCES` is suspect this is caused by incorrect permissions being set on the `rome` prebuilt binary. The `rome` package makes use of a postinstall script (here: https://github.com/rome/tools/blob/1c08b8f6f31b803111752fa8169c740ae82daeab/npm/rome/scripts/postinstall.js) to ensure the permissions are set correctly on the binary file, maybe the script isn't being run correctly ?

**Comment by MichaReiser** [comment]
> Unfortunately not. These are steps:
> 
>     1. mkdir test-folder && cd test-folder
> 
>     2. npm init -y
> 
>     3. touch pnpm-workspace.yml && nano pnpm-workspace.yml
> 
>     4. Add `packages: \n - 'packages/*'`
> 
>     5. run `pnpm add -D rome -w` in root directory
> 
>     6. add `rome format .` to any `scripts.format` in package.json
> 
>     7. run `pnpm run format`

I followed your instruction and added a `format` command to one of the packages and to the workspace root and both run successfully. Does the setup look correct? I haven't yet tested it on MacOs

[pnpm-workspace-test.zip](https://github.com/rome/tools/files/9980066/pnpm-workspace-test.zip)

**Comment by ydcjeff** [comment]
I think this isn't specially tied to pnpm workspace, but only with pnpm. Rome failed to run with pnpm.

Reproduction:

1. `pnpm create vite test-vite`
2. Choose vanilla JS
3. `pnpm i`, `pnpm add rome -D`
4. `pnpm exec rome format --write .`
5. You will see the errors below.

![Screenshot 2022-11-10 at 19 05 12](https://user-images.githubusercontent.com/32727188/201093072-dc86ad04-b03d-4a95-87cf-1ea602147fda.png)

Workaround:

Run `node node_modules/.pnpm/rome@10.0.0/node_modules/rome/scripts/postinstall.js` and `pnpm exec rome format` works. Looks like `postinstall` script doesn't run.

**Comment by MichaReiser** [comment]
Thanks for the vite example. It allows me to reproduce the issue on macos (linux is fine)

**Comment by lzm0x219** [comment]
mark

**Comment by ematipico** [comment]
> Thanks for the vite example. It allows me to reproduce the issue on macos (linux is fine)

I can't replicate the issue on macOS using the instructions provided. The posinstall script works: 

```shell
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/*/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/esbuild@0.15.13/node_modules/esbuild: Running postinstall script, done in 423ms
Progress: resolved 43, reused 11, downloaded 6, added 17, done
node_modules/.pnpm/rome@10.0.1/node_modules/rome: Running postinstall script, done in 160ms
```

**Comment by lzm0x219** [comment]
> > Thanks for the vite example. It allows me to reproduce the issue on macos (linux is fine)
> 
> I can't replicate the issue on macOS using the instructions provided. The posinstall script works:
> 
> ```shell
> Packages are copied from the content-addressable store to the virtual store.
>   Content-addressable store is at: /Users/*/Library/pnpm/store/v3
>   Virtual store is at:             node_modules/.pnpm
> node_modules/.pnpm/esbuild@0.15.13/node_modules/esbuild: Running postinstall script, done in 423ms
> Progress: resolved 43, reused 11, downloaded 6, added 17, done
> node_modules/.pnpm/rome@10.0.1/node_modules/rome: Running postinstall script, done in 160ms
> ```

You can use this [template](https://github.com/lzm0x219/template-vite-react), you can reproduce the problem

**Comment by ematipico** [comment]
Great, I can re create the issue here. For some unknown reason the `postinstall` script is not run in this using this template.

**Comment by lzm0x219** [comment]
> Great, I can re create the issue here. For some unknown reason the `postinstall` script is not run in this using this template.

Yes, thank you very much for coming to see the reason for this issue.🥳

**Comment by lzm0x219** [comment]
This question is related to pnpm. https://github.com/pnpm/pnpm/issues/4649

**Comment by southorange1228** [comment]
> This question is related to pnpm. [pnpm/pnpm#4649](https://github.com/pnpm/pnpm/issues/4649)
> 
> Create a .npmrc file in the current project:
> 
> ```
> side-effects-cache = false
> ```
> 
> remove node_modules and reinstall.

same problem, this worked

**Comment by MichaReiser** [comment]
We changed the way we set the executable bits. Can you try out the latest nightly release and test if the problem remains?

```
pnpm add rome@nightly
```

**Comment by lzm0x219** [comment]
> We changed the way we set the executable bits. Can you try out the latest nightly release and test if the problem remains?
> 
> ```
> pnpm add rome@nightly
> ```

it's work.
