### ISSUE TITLE
🐛 Some formatting options are not supported in rome.json

### ISSUE THREAD

**Issue by IanVS** [rome/tools#3632]
### Environment information

```block
CLI:
  Version:              10.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Server:
  Status:               stopped
```

### What happened?

I want to control the quote style, and it seems the only way to do this currently is to use the command line flag `--quote-style`.  If I try to set `formatter.quoteStyle` I get an error:

```
Error: Rome couldn't load the configuration file, here's why:
unknown field `quoteStyle`, expected one of `enabled`, `formatWithErrors`, `indentStyle`, `indentSize`, `lineWidth`, `ignore` at line 10 column 16
```

Which also means that the CLI options of `--quote-properties` and `--trailing-comma` are also not supported in the config file.

### Expected result

I should be able to set the same config from the `rome.json` file as I can on the CLI.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by IanVS** [comment]
Thanks, I read the docs but didn't notice the formatting options were spread out like that. Maybe the error message could be improved to mention where it should be set?

**Comment by ematipico** [comment]
> Thanks, I read the docs but didn't notice the formatting options were spread out like that. Maybe the error message could be improved to mention where it should be set?

We could, although this is valid for **all the options** and suggesting these kind of fixes requires some work. We use `serde` to deserialiaze `rome.json` to an internal object. Thank you for the feedback though.

**Comment by MichaReiser** [comment]
> Thanks, I read the docs but didn't notice the formatting options were spread out like that. Maybe the error message could be improved to mention where it should be set?

We plan to improve the messaging once we have our own JSON parser that gives us better error recovery than serde, that we use today.

**Comment by IanVS** [comment]
Would you be open to a PR that adds some text to https://docs.rome.tools/configuration/#formatter noting that there are other formatting objects in the `javascript` section?

**Comment by IanVS** [comment]
One other thought/question.   If `quoteStyle` is a javascript-only formatting option, should the CLI option be called something like `--javascript-quote-style`?

**Comment by ematipico** [comment]
> One other thought/question.   If `quoteStyle` is a javascript-only formatting option, should the CLI option be called something like `--javascript-quote-style`?

Yes, this is something we plan to change in the next releases, and name all the options similar to the configuration.

In this case `--formatter-javascript-quote-style`. This is my suggestion and not set on stone, but you get the idea

**Comment by IanVS** [comment]
Cool, thanks.  Though I think `--formatter-javascript-quote-style` would be confusing if the config option was `javascript.formatter.quoteStyle`.  But if you're planning to change the config to `formatter.javascript.quoteStyle` I'd be wholeheartedly in agreement with that.

**Comment by ematipico** [comment]
Yeah my bad, you got that right 😂

**Comment by IanVS** [comment]
Bummer, lol.  My brain thinks the other way, which is why I got confused in this issue to begin with.  I think it's nice to have all the formatting options under one heading, the linting options under another mean level, etc.  But, I'm sure y'all have a reason for this approach too, so I won't argue.  :)
