### ISSUE TITLE
📎 VS Extension: Resolve `rome` binary from workspace

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3635]
### Description

The Rome VS Code extension uses the bundled version of Rome or tries to resolve the binary specified by the `lspBind` setting. This has the downside that the VS Code extension and CLI may disagree on the version and thus, supported configuration options, formatting, lint rules, etc... 

## Goal

Resolve the Rome binary from the workspace for **trusted** workspaces. 

## Related work

* [ESLint resolution](https://github.com/microsoft/vscode-eslint/blob/fd83c6cba80c07c703e92cf3b8da1bcd5f42909d/server/src/eslint.ts#L1093-L1126) which calls into [files](https://github.com/microsoft/vscode-languageserver-node/blob/292dd0d88b6465337e42ba40ad986fdfdeb42d4d/server/src/node/files.ts) (do copy pasta?)
* [Prettier resolution](https://github.com/prettier/prettier-vscode/blob/1b7e051f932c166bd222c29ea7947ef86b076f42/src/ModuleResolver.ts#L136-L149)

**Comment by nstepien** [comment]
Also related, in `.vscode/settings.json` we have
```ts
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```
to use the locally installed version of TypeScript instead of the one bundled by vscode.

**Comment by MichaReiser** [comment]
> Also related, in `.vscode/settings.json` we have
> 
> ```ts
> {
>   "typescript.tsdk": "node_modules/typescript/lib"
> }
> ```
> 
> to use the locally installed version of TypeScript instead of the one bundled by vscode.

This' use case is supported today. You can specify a custom path using the `rome.lspBin` setting and the extension will use that binary instead.

**Comment by lgarron** [comment]
> This' use case is supported today. You can specify a custom path using the `rome.lspBin` setting and the extension will use that binary instead.

Thanks, this seems to work now! :-D

Looks like this was fixed in https://github.com/rome/tools/pull/3224 , but I missed it because my issue was turned into a discussion, which doesn't show backlinks to PRs.

**Comment by MichaReiser** [comment]
> Thanks, this seems to work now! :-D

Glad to hear it!

> Looks like this was fixed in https://github.com/rome/tools/pull/3224 , but I missed it because my issue was turned into a discussion, which doesn't show backlinks to PRs.

Oh, sorry for that!
