### ISSUE TITLE
📎 A11y Rules: Support aria-roles

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3640]
### Description

Aria roles allow specifying the type of an element. E.g. `<div role="button">` changes the "role" of the div to a button. 

Proper support for aria roles is necessary to correctly implement many of the accessibility rules. For example, the `useKeyWithClickEvent` rule must know if the element is an interactive element and, if so, not emit an error 

https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/2b133ecc0ba1b882ca06f0813b1afcdf64195757/src/util/isInteractiveElement.js

Requires metadata similar to [`aria-query`](https://github.com/A11yance/aria-query/tree/main/src)

**Comment by ematipico** [comment]
Closing, as completed by https://github.com/rome/tools/pull/3832

A complete list of rules and properties will be added as part of `useAriaProps` and `useAriaPropsTypes` rules

**Comment by MichaReiser** [comment]
> Closing, as completed by #3832
> 
> A complete list of rules and properties will be added as part of `useAriaProps` and `useAriaPropsTypes` rules

What about existing rules like `useKeyWithClickEvents`

See TODO here

https://github.com/rome/tools/blob/2655264565608e29229490101f7abbfa89a35598/crates/rome_js_analyze/src/analyzers/a11y/use_key_with_click_events.rs#L70-L72

**Comment by ematipico** [comment]
@MichaReiser  I added I checked in the umbrella as a separated task

**Comment by MichaReiser** [comment]
> kbox in the u

I see. Would you mind linking to the umbrella (and then close this issue again :))

**Comment by ematipico** [comment]
There's task in the umbrella https://github.com/rome/tools/issues/3739
