### ISSUE TITLE
🐛 @rometools/js-api has no exported members

### ISSUE THREAD

**Issue by nikolaxhristov** [rome/tools#3646]
### Environment information

```block
CLI:
  Version:              10.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               unset

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.        

Server:
  Version:              10.0.0
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   windows

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       2
  Client Name:          Visual Studio Code - Insiders
  Client Version:       1.74.0-insider

Workspace:
  Open Documents:       0
  Client Name:          Visual Studio Code - Insiders
  Client Version:       1.74.0-insider

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

├─12996221ms INFO rome_lsp::server Starting Rome Language Server...
```

### What happened?

After

```bash
npm i rome
npm i @rometools/js-api
```

I'm trying to run the `@rometools/js-api` but the `Rome` object is empty and the `node_modules` holds no files. Only 

node_modules
package.json
README.md

and inside `node_modules` a `.bin`

rome
rome.CMD
rome.ps1

which points back to the cli.

### Expected result

To be able to do

```ts
import {Rome} from "@rometools/js-api"

const rome = await Rome.create({
    backendKind: BackendKind.NODE,
});

const result = await rome.formatContent("function f   () {  }", {
    filePath: "example.js",
});

console.log(result.content)
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
This is only partially solved. It's still not possible to use the API because the module statically imports all backends and the bundling of the `backend-jsonrpc` is broken too #3647 . 

#3652 should fix the static imports so that the API can then be used with the WASM backend

**Comment by MichaReiser** [comment]
It should now be possible to use the package with 

```
import { Rome, BackendKind } from "@rometools/js-api";

const rome = await Rome.create({
	backendKind: BackendKind.NODE,
});

const result = await rome.formatContent("function f   () {  }", {
	filePath: "example.js",
});

console.log(result.content);
```

You have to manually install the optional `@rometools/wasm-nodejs` that runs Rome as a WASM module. 

Be aware that the API is experimental.

**Comment by nikolaxhristov** [comment]
Thank you!

**Comment by ematipico** [comment]
> how can i specify formatting options? because currently it ignores my rome.json settings
> thanks

You would need to manually pass the confirmation, here's an example: https://github.com/rome/tools/blob/main/website/src/playground/workers/romeWorker.ts#L143

The API, at the moment, don't look for the configuration file
