### ISSUE TITLE
🐛 Bug on landing page with light theme showing VS Code Extension Preview

### ISSUE THREAD

**Issue by brianinoa** [rome/tools#3667]
### Environment information

```block
Doesn't have much to do with the Rome tooling, but with the landing page for the tools
```

### What happened?

Landed on the landing page and changed the theme setting to light
The VS Code Extension preview I completely white

<img width="722" alt="image" src="https://user-images.githubusercontent.com/54530642/201315698-09efe164-4989-4341-bb4e-bbd1196ceea9.png">

### Expected result

To be similar to the dark setting where there's a VS Code Extension preview

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
CC: @sebmck

**Comment by ematipico** [comment]
Closing, I can't replicate in Firefox, Chrome or Safari. Maybe it's been fixed.

Please open a new issue with more information in case you're still experiencing this issue.
