### ISSUE TITLE
🐛 `noArrayIndexKey` ignores valid cases

### ISSUE THREAD

**Issue by nstepien** [rome/tools#3670]
### Environment information

```block
Rome playground
```

### What happened?

1. Open this [playground](https://play.rome.tools/?code=function+Component%28%29+%7B%0A++%5B%5D.map%28%28_%2C+index%29+%3D%3E+%3CComponent+key%3D%7Bindex%7D+%2F%3E%29%3B%0A%0A++return+%5B%5D.map%28%28_%2C+index%29+%3D%3E+%3CComponent+key%3D%7Bindex%7D+%2F%3E%29%3B%0A%7D%0A%0Aconst+test1+%3D+%28%29+%3D%3E+%7B%0A++%5B%5D.map%28%28_%2C+index%29+%3D%3E+%3CComponent+key%3D%7Bindex%7D+%2F%3E%29%0A%7D%3B%0A%0Aconst+test2+%3D+%28%29+%3D%3E+%5B%5D.map%28%28_%2C+index%29+%3D%3E+%3CComponent+key%3D%7Bindex%7D+%2F%3E%29%3B%0A&lineWidth=80&indentStyle=space&quoteStyle=single&quoteProperties=as-needed&trailingComma=none&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=true#ZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAApACAAewAKACAAIABbAF0ALgBtAGEAcAAoACgAXwAsACAAaQBuAGQAZQB4ACkAIAA9AD4AIAA8AEMAbwBtAHAAbwBuAGUAbgB0ACAAawBlAHkAPQB7AGkAbgBkAGUAeAB9ACAALwA+ACkAOwAKAAoAIAAgAHIAZQB0AHUAcgBuACAAWwBdAC4AbQBhAHAAKAAoAF8ALAAgAGkAbgBkAGUAeAApACAAPQA+ACAAPABDAG8AbQBwAG8AbgBlAG4AdAAgAGsAZQB5AD0AewBpAG4AZABlAHgAfQAgAC8APgApADsACgB9AAoACgBjAG8AbgBzAHQAIAB0AGUAcwB0ADEAIAA9ACAAKAApACAAPQA+ACAAewAKACAAIABbAF0ALgBtAGEAcAAoACgAXwAsACAAaQBuAGQAZQB4ACkAIAA9AD4AIAA8AEMAbwBtAHAAbwBuAGUAbgB0ACAAawBlAHkAPQB7AGkAbgBkAGUAeAB9ACAALwA+ACkACgB9ADsACgAKAGMAbwBuAHMAdAAgAHQAZQBzAHQAMgAgAD0AIAAoACkAIAA9AD4AIABbAF0ALgBtAGEAcAAoACgAXwAsACAAaQBuAGQAZQB4ACkAIAA9AD4AIAA8AEMAbwBtAHAAbwBuAGUAbgB0ACAAawBlAHkAPQB7AGkAbgBkAGUAeAB9ACAALwA+ACkAOwAKAA==)
2. check diagnostics, notice that the returned parts are ignored.

### Expected result

`return` should not break the rule.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
Uh, that's odd. 

Issue: `noArrayIndexKey` ignores expressions in return statements (and potentially other statements?)
