### ISSUE TITLE
🐛 The tsx code in Markdown cannot be formatted.

### ISSUE THREAD

**Issue by JarvisArt** [rome/tools#3671]
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Server:
  Status:               stopped
```

### What happened?

The tsx code in Markdown cannot be formatted.
<img width="645" alt="image" src="https://user-images.githubusercontent.com/38420763/201354967-387dd275-73e4-4a0f-bde7-6844c721f1e3.png">

```json
{
  "formatter": {
    "enabled": true,
    "ignore": ["./dist/*", "./es/**/*", "./lib/**/*", "_site/**/*"],
    "indentStyle": "space",
    "lineWidth": 100,
    "indentSize": 2
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single"
    }
  }
}
```

### Expected result

<img width="704" alt="image" src="https://user-images.githubusercontent.com/38420763/201355108-d3402469-6687-4485-8dc8-691a509558a2.png">

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
Thanks @JarvisArt 

Rome doesn't support markdown yet. We hope to get to it soon, but it may take us a while (building a parser, and formatter). I'll close this for now.
