### ISSUE TITLE
🐛 LSP/parser get in a buggy state when encountering some strings

### ISSUE THREAD

**Issue by nstepien** [rome/tools#3733]
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 unset

Rome Configuration:
  Status:               loaded
  Formatter disabled:   true
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     x86_64
  OS:                   windows

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       1
  Client Name:          Visual Studio Code
  Client Version:       1.73.1
```

### What happened?

1. Copy/paste the following string into a file then press enter: `'Jan 1, 2018 – Jan 1, 2019'` (some unusual characters in the middle, output is from [`formatRange`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange), specifically from Node.js 19.1.0/ICU 72.1)
2. Notice the red squiggles from Rome

Demo:
![Recording 2022-11-15 at 00 15 19](https://user-images.githubusercontent.com/567105/201794866-10322e9e-6d8f-459e-bfbb-07d2d5c234a9.gif)

### Expected result

No parsing error, should at least fully recover when removing the string, unlike in the GIF above.
ts/eslint/prettier all handle it well.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by nstepien** [comment]
I can't reproduce the issue in the playground though, was this fixed already perhaps?

**Comment by xunilrj** [comment]
If there is a strange unicode char in the middle, something may be sanitizing it. Can you open the original string with a hex editor and paste the bytes here?

For example, on linux:

```
$ cat a.txt
123​456
$ xxd a.txt
00000000: 3132 33e2 808b 3435 360d 0a              123...456..
``` 

on windows:

```
$ format-hex .\a.txt


           Path: C:\github\tools\a.txt

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   31 32 33 E2 80 8B 34 35 36 0D 0A                 123â456..
```

**Comment by nstepien** [comment]
@xunilrj 
```


           Path: D:\repo\txt.txt

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   27 4A 61 6E 20 31 2C 20 32 30 31 38 E2 80 89 E2  'Jan 1, 2018ââ
00000010   80 93 E2 80 89 4A 61 6E 20 31 2C 20 32 30 31 39  âJan 1, 2019
00000020   27                                               '


```

**Comment by leops** [comment]
Ah right I also started looking into this, this is caused by incorrectly calculating offsets into the unicode string while applying edits coming from the editor (characters indices are being used as byte offsets)

**Comment by leops** [comment]
I think I have a pretty clear idea of how to fix it so I can take care of it if you want

**Comment by thhermansen** [comment]
Hi,

I might have a similar issue to this, where source code is utf-8 and contains the following:

```tsx
Måler må importeres til bedriften før de kan tas i bruk. Bedriftens maler administreres{' '}
<Link to={type === 'DOCUMENT' ? routes.accountTemplateDocuments() : routes.accountTemplateForms()}>
  her
</Link>
.
```

When I save it in vscode (and the source code is ran through Rome) it ends up being:


```tsx
Måler må importeres til bedriften før de kan tasbruk. Bedriftens maler administreres{' '}
<Link to={type === 'DOCUMENT' ? routes.accountTemplateDocuments() : routes.accountTemplateForms()}>
  her
</Link>
.
```

Note the "før de kan tas i bruk" becomes "før de kan tasbruk" on save. 

------

I also got the following in my terminal:

```
Rome encountered an unexpected error

This is a bug in Rome, not an error in your code, and we would appreciate it if you could report it to https://github.com/rome/tools/issues/ along with the following information to help us fixing the issue:

Source Location: /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/string.rs:1812:29
Thread Name: tokio-runtime-worker
Message: assertion failed: self.is_char_boundary(n)
```

<details>
<summary>Environment info</summary>
rome rage
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     aarch64
  OS:                   macos

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       7
  Client Name:          Visual Studio Code
  Client Version:       1.73.1
</details>

Please let me know if there is anything I can do to provide more information.
