### ISSUE TITLE
🐛 [Playground] changes in Formatter are only reflected after a code change

### ISSUE THREAD

**Issue by daKmoR** [rome/tools#3755]
### Environment information

```block
-
```

### What happened?

https://user-images.githubusercontent.com/24378/202027173-dadedb64-589f-4ec2-96aa-64be92657de5.mp4

Link to playground
https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&code=YwBvAG4AcwB0ACAAbwBiAGoAIAA9ACAAewAKACAAIABmAG8AbwA6ACAAJwBsAG8AcgBlAG0AIABpAHAAcwB1AG0AJwAKAH0AIAAgACAAIAA%3D&typescript=false&jsx=false

### Expected result

Changes in Formatter settings should update the output directly

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Fixed
