### ISSUE TITLE
🐛 Undefined variables are not flagged?

### ISSUE THREAD

**Issue by mhkeller** [rome/tools#3769]
### Environment information

```block
This appears in the playground
```

### What happened?

The following code shows no errors even though `y` is undefined.

```js
let x = 5;

x = y + 2;
```

Is this not part of the rules?

### Expected result

It should flag that `y` is undefined.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by leops** [comment]
This is bug in the playground, the `noUndeclaredVariables` correctly raises a diagnostic for this but since it's not part of the recommended set, it's not enabled in the playground. I guess we should also enable non-recommended rules when `enabledNurseryRules` is true ?

**Comment by MichaReiser** [comment]
> I guess we should also enable non-recommended rules when `enabledNurseryRules` is true ?

That, and/or change the option to a select where users can pick from: All/Recommended
