### ISSUE TITLE
🐛 noUnusedVariables with class

### ISSUE THREAD

**Issue by sonnyp** [rome/tools#3779]
### Environment information

# rome rage

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
```

# rome.json

```
{
  "formatter": {
    "enabled": true,
    "ignore": ["./icon-development-kit-www", ".flatpak", "src/lib", "troll"],
    "indentStyle": "space",
    "indentSize": 2
  },
  "linter": {
    "enabled": true,
    "ignore": ["./icon-development-kit-www", ".flatpak", "src/lib", "troll"],
    "rules": {
      "recommended": true,
      "correctness": {
        "noUnusedVariables": "error",
        "noUselessFragments": "error"
      },
      "style": {
        "useBlockStatements": "off"
      },
    }
  }
}
```

# reproducer.js

```
const Foo = hello(class Foo {})
console.log(Foo)
```

### What happened?

![image](https://user-images.githubusercontent.com/19673/202534374-7bd7c387-4b63-4a85-9e4e-f5d6adf41a66.png)

### Expected result

Rome doesn't report the `Foo` as unused.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
@xunilrj is this something you could look into. See [playground](https://docs.rome.tools/playground/?indentStyle=space&trailingComma=none&lintRules=all&code=YwBvAG4AcwB0ACAARgBvAG8AIAA9ACAAaABlAGwAbABvACgAYwBsAGEAcwBzACAARgBvAG8AIAB7AH0AKQAKAGMAbwBuAHMAbwBsAGUALgBsAG8AZwAoAEYAbwBvACkA)
