### ISSUE TITLE
noNoninteractiveTabindex

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3817]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/noNoninteractiveElementToInteractiveRole.md

**Comment by unvalley** [comment]
I think the rule document is this one. https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/noNoninteractiveTabindex.md
And, I'll work on this.
