### ISSUE TITLE
🐛 Playgound crashes after pasting long files

### ISSUE THREAD

**Issue by qweered** [rome/tools#3824]
### Environment information

```block
rome rage
```

### What happened?

1. Copy and paste https://github.com/terser/terser/blob/master/lib/ast.js to playground
2. Press Ctrl-A -> Backspace -> Ctrl-V fast for a few times

![chrome_Bn83kANQm3](https://user-images.githubusercontent.com/41731334/203299186-78f81fc9-cba7-4f3d-853e-90092280dd43.png)

This happens after page refreshing

![image](https://user-images.githubusercontent.com/41731334/203299363-c855250e-360c-4502-aa83-5b89773a6213.png)

### Expected result

1. Url should be cleanised faster
2. Maybe algorithm for url params encoding should be more space-efficent
3. Back/forward buttons for history should work to quicky retun to previous state after this or any other error

![image](https://user-images.githubusercontent.com/41731334/203300351-acac0888-942f-4cf8-9791-a4ce687235d9.png)
 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Closing. It takes few moments to get the result but it doesn't crash.
