### ISSUE TITLE
🐛 LSP VSCode ignores comments not applying

### ISSUE THREAD

**Issue by Louis-Michalak** [rome/tools#3841]
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:              10.0.1
  Name:                 rome_lsp
  CPU Architecture:     aarch64
  OS:                   macos

Workspace:
  Open Documents:       0

Other Active Server Workspaces:

Workspace:
  Open Documents:       12
  Client Name:          Visual Studio Code
  Client Version:       1.73.1

Rome Server Log:

⚠ Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

├─141510694ms INFO rome_lsp::server Starting Rome Language Server...
```

### What happened?

It looks like the LSP is ignoring ignore comments, this line has an error on "Function" with rule "lint/nursery/noBannedTypes" :
```
type ImmutablePrimitive = undefined | null | boolean | string | number | Function;
```
And like this, the error is still thrown in VSCode :
```
// rome-ignore lint/nursery/noBannedTypes: well that's a reason
type ImmutablePrimitive = undefined | null | boolean | string | number | Function;
```

### Expected result

Should have ignored the error

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by leops** [comment]
The syntax change for suppression comments will only be rolled out as part of the v11 release cycle, so for version 10.0.1 this suppression comment still needs to be written as `// rome-ignore lint(nursery/noBannedTypes): ...`
I do still think there's a "bug" here but that would be the linter silently ignoring comments if they do not parse as suppressions, when it should be reasonably safe to assume that anything starting with `rome-ignore` is intended to be a suppression comment and emit a diagnostic if the rest of the comment fails to parse
