### ISSUE TITLE
📎 `useShorthandArrayType` should handle read-only arrays

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#3864]
## Summary

For now, *Rome*'s `useShorthandArrayType` does not handle read-only arrays.
ESLint's rule [array-type](https://typescript-eslint.io/rules/array-type) handles read-only arrays.

## Examples

This code:

```ts
const y: ReadonlyArray<string> = ['a', 'b'];
```

should be turned into:

```ts
const y: readonly string[] = ['a', 'b'];
```

**Comment by unvalley** [comment]
I'll take a look.

**Comment by xunilrj** [comment]
We need to be careful with this problem here: https://github.com/rome/tools/issues/3111

**Comment by unvalley** [comment]
I think we may not need to handle #3111 for now.
My understanding is that current `useShorthandArrayType` follows [typescript-eslint array-type (array-simple)](https://typescript-eslint.io/rules/array-type/#array-simple).
In this case, `const c: Array<() => void> = [() => {}];` is correct (it doesn't need suggested fix).
And, current [playground](https://docs.rome.tools/playground/?lintRules=all&code=LwAvACAAbgBvACAAcwB1AGcAZwBlAHMAdABlAGQAIABmAGkAeAAKAGMAbwBuAHMAdAAgAHYAIAA9ACAAWwBdACAAYQBzACAAQQByAHIAYQB5ADwAKAAuAC4ALgBhAHIAZwBzADoAIABzAHQAcgBpAG4AZwApACAAPQA%2BACAAdgBvAGkAZAA%2BADsACgAvAC8AIABzAHUAZwBnAGUAcwB0AGUAZAAgAGYAaQB4AAoAYwBvAG4AcwB0ACAAeAAgAD0AIABbAF0AIABhAHMAIABBAHIAcgBhAHkAPABzAHQAcgBpAG4AZwA%2BADsACgAKAGMAbwBuAHMAbwBsAGUALgBsAG8AZwAoAHYALAAgAHgAKQA%3D&jsx=false) doesn't suggest the fix.
