### ISSUE TITLE
`useLiteralKeys`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3889]
> 3. `no-literal-computed-keys` (autofix e.g. `["a"]` to `a`, safe)

cc @jeysal

**Comment by notmd** [comment]
@ematipico I would like to take this one.

**Comment by notmd** [comment]
I don't really understand the rule. The issue title seems like [https://eslint.org/docs/latest/rules/no-useless-computed-key](https://eslint.org/docs/latest/rules/no-useless-computed-key). But the fix suggestion is like [https://eslint.org/docs/latest/rules/dot-notation](https://eslint.org/docs/latest/rules/dot-notation). We didn't have both of these rules yet.

**Comment by ematipico** [comment]
Sorry for the lack of context. In this issue https://github.com/rome/tools/issues/3731 there's more information about why we decided to split the ESLint rule into three rules.

They are more specialised, allowing us to give more control and put them in different groups.

**Comment by MichaReiser** [comment]
Naming. How about noComputedLiteralKeys (or MemberNames) or useLiteralKeys?

**Comment by ematipico** [comment]
> Naming. How about noComputedLiteralKeys (or MemberNames) or useLiteralKeys?

I like these names.

I wonder if we should narrow down the name to include "string", I don't think the rule will be applied to numerical literals, for example.

**Comment by jeysal** [comment]
> I wonder if we should narrow down the name to include "string", I don't think the rule will be applied to numerical literals, for example.

I think it should actually! Any numeric literal should be valid directly as a literal property name (even weird stuff like `{ .1: 42 }` works), so we should also unwrap those out of a computed property name.

![image](https://user-images.githubusercontent.com/16069751/204623041-23cbbd8d-11af-4240-ba33-d004bd9efb12.png)

Boolean and null literals too (trivial)

**Comment by jpike88** [comment]
this is a super important one, I'd even suggest putting it in the recommended set. It's super dangerous to allow people to accidentally reference a non-literal key due to it sidestepping type checks.
