### ISSUE TITLE
🐛 "Cannot find package" for Node API with ts-node-esm

### ISSUE THREAD

**Issue by Gregoor** [rome/tools#3890]
### Environment information

```block
CLI:
  Version:              10.0.1
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   macos
```

### What happened?

1. Installed Rome's Node API according to https://github.com/rome/tools/tree/main/npm/js-api
2. Imported the module according to the docs
3. Got
```
/Users/gregor/code/tofu/tree-trimmer/node_modules/.pnpm/ts-node@10.9.1_c7vtmw4r5lhzpzjntnohxhujqu/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:286
  throw new ERR_MODULE_NOT_FOUND(
        ^
CustomError: Cannot find package '/Users/gregor/code/tofu/tree-trimmer/node_modules/@rometools/js-api/' imported from /Users/gregor/code/tofu/tree-trimmer/bench.ts
```

### Expected result

I expected it'd just work™️ .

I'm wondering if using it with `ts-node-esm` is where I'm going wrong? Or is it simply just early days? (It sure is, thanks for the amazing lib btw!)

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I don't know what `ts-node-esm` is doing, but I would wait to use this package just yet.  The package is in alpha state and the next version will have a banner saying so: https://github.com/rome/tools/blob/main/npm/js-api/README.md#rome-javascript-bindings

But there's already some package out there that is using the APIs, so I would assume that `ts-node-esm` is doing something.

**Comment by Gregoor** [comment]
Fair! I did see the banner  but thought I’d risk asking anyway. I’ll close it for now then.
