### ISSUE TITLE
📎 Eslint rule compataibility/equivalency google sheet

### ISSUE THREAD

**Issue by jpike88** [rome/tools#3892]
### Description

To keep track of the sheer amount of types, I think it's a smart idea to fire up a google sheet that shows all rules that have been considered or already implemented in Rome, including:

- Rule name
- whether eslint core, @typescript-eslint, or via 3rd party eslint plugin (including GitHub repo address)
- Equivalent Rome rule name
- Status (in progress, done - with PR showing it was done at that time, rejected)
- Reason for rejection or suggested rule to use instead

There needs to be a clear way to visualise this in a way that's accessible to everyone, until that happens it will be very difficult to map out a path or a point in time where someone could migrate to Rome from eslint.

**Comment by MichaReiser** [comment]
Thank you for bringing this up and we agree. Having an easy way to discover what ESLint rules Rome supports today, will be supported in the near future, and we don't plan to support would help people migrating (and contributing). We plan to create such documentation together with our commitment to bring more ESLint core and React rules to Rome.

**Comment by jpike88** [comment]
This is much preferred.

As you can see I have quite a heavy config file here: https://github.com/rome/tools/discussions/3774

And the only way to try and track them is these issues https://github.com/rome/tools/issues/3966 which obviously are going to just create a world of pain if everyone tries to do the same thing. I ran into that issue by searching for the first rule in my config file!

I think this step needs to be done asap, to prevent spamming of issues and overwhelming everyone

**Comment by jpike88** [comment]
Bonus points if you have a GitHub action that runs on issue creation, and does a lookup of the title in the spreadsheet for easier linkage/reference

**Comment by jpike88** [comment]
We've got our own internal google sheet running which shows the diff between our eslint rules and Rome equivalents, for a model of how to maybe go about things.

https://docs.google.com/spreadsheets/d/16PXNlt7XoQG_ByRC9azLcFqPxZbIyppcb2c92O_lCv4/edit?usp=sharing

Thanks @namhoang1604 for that

**Comment by ematipico** [comment]
I really don't know if we have the workforce to provide such documentation. Of course, we really appreciate if someone wants to contribute and create a page for us!

**Comment by Conaclos** [comment]
I updated the Google sheet several times in the past months.

**Comment by ematipico** [comment]
> I updated the Google sheet several times in the past months.

Should we have a markdown table that we can deploy and update on our website?

Also, there's this project that should help https://github.com/orgs/rome/projects/7?query=is%3Aopen+sort%3Aupdated-desc

**Comment by Conaclos** [comment]
See [Biome planned linter rules](https://github.com/biomejs/biome/discussions/3)
