### ISSUE TITLE
📎 `noRedundantUseStrict`: Support Module and Classes 

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3901]
### Description

Extend the `noRedundantUseStrict` rule to assume `strict` mode in [classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_classes) and [modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules).

**Comment by mzbac** [comment]
I would like to work on this, but I need some pointers/suggestions on how to detect whether the code is a JavaScript module or TypeScript. This is pretty much the reason why I can't implement support for classes and modules in the original PR.
