### ISSUE TITLE
📎 TypeScript 4.9

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3904]
### Description

* [x] Satisfies Operator #3846 
* [ ] #3956

**Comment by nissy-dev** [comment]
I'll try to take Auto Accessors support 🤚

**Comment by MichaReiser** [comment]
> I'll try to take Auto Accessors support 🤚

Awesome. i assigned the task to you. Class modifiers are... interesting, to say the least. I hope you won't need to change much to the infrastructure
