### ISSUE TITLE
🐛 Illegal use of an export declaration outside of a module for .cts files

### ISSUE THREAD

**Issue by IanVS** [rome/tools#3918]
### Environment information

```block
vscode extension
```

### What happened?

I installed the vscode extension into a simple project exploring typescript module resolution.

I got an error from rome on a file:

```ts
// example.cts

export function helper() {
    console.log("hello world!");
}
```

As far as I know, this is valid TypeScript code.  In fact, it's taken from the TypeScript [docs](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#new-file-extensions).  The `.cts` extension indicates that the compilation target should be cjs.  But rome throws an error:

```
Illegal use of an export declaration outside of a module
```

### Expected result

Rome should not error for valid TypeScript code.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I suppose that the TypeScript compiler relaxes its parsing rules because it knows that eventually the code will be compiled into a CJS script. Maybe our parser should do the same assumptions.

**Comment by MichaReiser** [comment]
> I suppose that the TypeScript compiler relaxes its parsing rules because it knows that eventually the code will be compiled into a CJS script. Maybe our parser should do the same assumptions.

It may just be an incorrect mapping in our `SourceType` implementation.
