### ISSUE TITLE
📎 Implement ESLint `no-unsafe-negation`

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#3930]
### Description

This should be a *good-first-issue*.

[no-unsafe-negation](https://eslint.org/docs/latest/rules/no-unsafe-negation)

## Suggested name

`noUnsafeLogicNegation`

**Comment by malobre** [comment]
I'm working on this.

**Comment by malobre** [comment]
This seems to be already implemented https://docs.rome.tools/lint/rules/nounsafenegation
