### ISSUE TITLE
🐛 [js-parser] `extends infer T extends` syntax fails to compile

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#3934]
### Environment information

```block
Rome latest.
```

### What happened?

Rome amits an error for the following snippet of code:

```ts
type B = A extends infer T extends B ? C<T> : never;
```

[Playground](https://docs.rome.tools/playground/?code=dAB5AHAAZQAgAEIAIAA9ACAAQQAgAGUAeAB0AGUAbgBkAHMAIABpAG4AZgBlAHIAIABUACAAZQB4AHQAZQBuAGQAcwAgAEIAIAA%2FACAAQwA8AFQAPgAgADoAIABuAGUAdgBlAHIAOwA%3D)

This is also a ESbuild bug [recently reported](https://github.com/evanw/esbuild/issues/2712).

### Expected result

The code should be parsed without any error.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by nissy-dev** [comment]
I think this issue is fixed by #4018
