### ISSUE TITLE
useHeadingContent

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3943]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/useHeadingContent.md

**Comment by notmd** [comment]
I'm working on this.

**Comment by nissy-dev** [comment]
this issue is assigned to @notmd , but the PR is not submitted for a long time.  Can I take this issue?

**Comment by notmd** [comment]
hi @nissy-dev, sorry for the late response. I was busy, it's also holiday here, feel free to take it.
