### ISSUE TITLE
useHtmlLang

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3944]
https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/useHtmlLang.md

This rule should verify that `lang` is a string or a variable. It doesn't need to check if the attribute is an accepted lang

**Comment by nissy-dev** [comment]
Can I take this issue?

**Comment by mrkldshv** [comment]
Hey! Can I take this one?

**Comment by ematipico** [comment]
@mrkldshv all yours!

**Comment by mrkldshv** [comment]
Thanks! Should we allow trailing spread prop as `<html {...props}></html>` too?

**Comment by ematipico** [comment]
Yes, a case like this should not trigger the rule.

**Comment by mrkldshv** [comment]
Sure, sounds good.

**Comment by mrkldshv** [comment]
I almost finished working on the implementation, and wanted to confirm if we need to check for `""`, `undefined`, `true` and other invalid entries for lang attribute in the scope of this rule? Or we should leave this for `useValidLang` rule?
