### ISSUE TITLE
`noConstantCondition`, no-constant-condition

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3961]
https://eslint.org/docs/latest/rules/no-constant-condition

**Comment by ematipico** [comment]
> Hi @ematipico I would love to take this one.

Sure, no problem. Although we will wait a bit before reviewing. I would like to finish the umbrella issue before, so all the information are ready

**Comment by unvalley** [comment]
I'll take over this one.

**Comment by Conaclos** [comment]
Assigned :)
