### ISSUE TITLE
`noControlCharactersInRegex`, no-control-regex

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3962]
https://eslint.org/docs/latest/rules/no-control-regex

**Comment by mzbac** [comment]
I would like to pick up this. Let me know if you have any concerns.

**Comment by ematipico** [comment]
@mzbac are you still interested at contributing to this rule?

**Comment by mzbac** [comment]
@ematipico Sorry, I thought this was already resolved. If no one would like to pick up this task, I don't mind working on it.

**Comment by unvalley** [comment]
@mzbac Thanks for making the PR before. I will make a PR as a follow up to that.
