### ISSUE TITLE
`noFallthoughSwitchClause`, no-fallthrough

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3973]
https://eslint.org/docs/latest/rules/no-fallthrough

Proposed name: `noFallthoughCase`

**Comment by Conaclos** [comment]
I could suggest another name: `noFallthoughSwitchClause`. I would like to implement this rule. :)

**Comment by ematipico** [comment]
Title updated! All yours

**Comment by Conaclos** [comment]
I am taking some time to explore implementation space. I think about using `ControlFlowGraph` as rule's query and then traversing the graph in order to find every `switch statement`. This should have some cost. Have you an alternative idea for implementing the rule? Have a nice week!

**Comment by ematipico** [comment]
There isn't a need for the control flow graph here. ESLint implementation seems quite straightforward. I wouldn't implement the comment part, though. Rome already requires an explanation to turn off the rule, so we could have that as part of the documentation:

```js
switch (f) {
    case "B":
      // rome-ignore lint/nursery/noFallthoughSwitchClause: fall through intentional
      doSomething();

    case "D":
      doSomething();
      break;
}
```

**Comment by jpike88** [comment]
Just ran into a scenario that could have used this rule. Definitely could use it

**Comment by Conaclos** [comment]
> Just ran into a production bug that could have been prevented by this rule. Definitely looking forward to this one

Do you use TSC? If it is the case you can enable [`noFallthroughCasesInSwitch`](https://www.typescriptlang.org/tsconfig#noFallthroughCasesInSwitch).

**Comment by Conaclos** [comment]
> There isn't a need for the control flow graph here. ESLint implementation seems quite straightforward.

ESLint seems to use a notion of [reachability](https://github.com/eslint/eslint/blob/main/lib/rules/no-fallthrough.js#L160). This is a sign of control flow analysis?

**Comment by jpike88** [comment]
thanks for the heads up, noFallthroughCasesInSwitch works fine.

**Comment by ddanielsantos** [comment]
can I work on this one?

**Comment by Conaclos** [comment]
@ddanielsantos  All yours :)
