### ISSUE TITLE
`noInnerDeclarations`, no-inner-declarations

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3974]
https://eslint.org/docs/latest/rules/no-inner-declarations

**Comment by ematipico** [comment]
This rule has options... by reading the rule, my gut tells me to implement this rule for both `var` and `function`.

**Comment by kaioduarte** [comment]
Please assign this one to me :)

**Comment by kaioduarte** [comment]
@Conaclos I just started it, so no worries. Go for it.
