### ISSUE TITLE
`noSelfAssign`, no-self-assign

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3980]
https://eslint.org/docs/latest/rules/no-self-assign

**Comment by ematipico** [comment]
I put "difficult" only because this might be a lengthy rule because the rule should check various types of assignments. 

It makes sense to split the work into multiple PRs to gradually catch the different types of assignments.

**Comment by Conaclos** [comment]
@ematipico What the status of `noSelfAssign`? Are there some missing parts?

**Comment by ematipico** [comment]
> @ematipico What the status of `noSelfAssign`? Are there some missing parts?

From the PR:

> This implementation doesn't cover:
>
>    parenthesis
>    optional chain
>    string literals inside a computed member expression, e.g. a['b']
