### ISSUE TITLE
`noThisBeforeSuper`, no-this-before-super

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3983]
https://eslint.org/docs/latest/rules/no-this-before-super

**Comment by ematipico** [comment]
This rule requires traversing the code paths of the constructor and checking the range of `super` and `this.`.

**Comment by Conaclos** [comment]
I would like to implement this rule. :)

**Comment by ematipico** [comment]
I believe this rule has been implemented by https://github.com/rome/tools/pull/4017

@leops could you please confirm? And if so, could you please the issue?

**Comment by leops** [comment]
Ah yes that's implemented as part of the control flow analysis in `noUnreachableSuper`
