### ISSUE TITLE
`noExtraSemicolons`, no-extra-semi

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3988]
https://eslint.org/docs/latest/rules/no-extra-semi

**Comment by ematipico** [comment]
We already have the formatter, I would personally not implement it, to promote the usage of both formatter and linter. But since a person can turn off the formatter and use just the linter, maybe we can not recommend it?

**Comment by ktfth** [comment]
I'm currently working on this issue and the PR are in progress here: https://github.com/rome/tools/pull/4061
