### ISSUE TITLE
`useYield`,  require-yield

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3994]
https://eslint.org/docs/latest/rules/require-yield

**Comment by ematipico** [comment]
I am on the fence regarding the difficulty... 

The tricky part is that we have to query a function-like that is a generator and then we have to traverse its tree to find the usage/not-usage of `yield`.

**Comment by kaioduarte** [comment]
Please assign this one to me. It ended up being an easy one after doing the self-compare rule 😁
