### ISSUE TITLE
🐛 `lint/style/noArguments` conditionally misses `arguments` in a `for` loop

### ISSUE THREAD

**Issue by lgarron** [rome/tools#4003]
### Environment information

`npx rome rage` is freakin' out about stuff again

```shell
> npx rome --version
Rome CLI version 11.0.0
```

### What happened?

Rome detects and errors on the second `arguments` in this snippet, but not the first:

```ts
function foo() {
  for (let i = 0; i < arguments.length; i+=2) {
    console.log(arguments[i]);
  }
}

foo("yo", "ho", "yo", "a", "pirate's", "life", "for", "me")
```
[Playground link](https://docs.rome.tools/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKACAAIABmAG8AcgAgACgAbABlAHQAIABpACAAPQAgADAAOwAgAGkAIAA8ACAAYQByAGcAdQBtAGUAbgB0AHMALgBsAGUAbgBnAHQAaAA7ACAAaQArAD0AMgApACAAewAKACAAIAAgACAAYwBvAG4AcwBvAGwAZQAuAGwAbwBnACgAYQByAGcAdQBtAGUAbgB0AHMAWwBpAF0AKQA7AAoAIAAgAH0ACgB9AAoACgBmAG8AbwAoACIAeQBvACIALAAgACIAaABvACIALAAgACIAeQBvACIALAAgACIAYQAiACwAIAAiAHAAaQByAGEAdABlACcAcwAiACwAIAAiAGwAaQBmAGUAIgAsACAAIgBmAG8AcgAiACwAIAAiAG0AZQAiACkA)

However, if you *remove* the `console.log` line then the first `arguments` errors.

### Expected result

The first `arguments` should consistently error.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by xunilrj** [comment]
True. I will look into it.
