### ISSUE TITLE
🐛 `noConstructorReturn` reasoning is wrong

### ISSUE THREAD

**Issue by lgarron** [rome/tools#4005]
### Environment information

```block
Rome 11.0.0
```

### What happened?

https://docs.rome.tools/lint/rules/noconstructorreturn/ states:

> While returning a value from a constructor does not produce an error, the returned value is being ignored.

This is inaccurate:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor
> The constructor method may have a return value. While the base class may return anything from its constructor, the derived class must return an object or undefined, or a [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) will be thrown.

I'm not saying it's a *great* idea to do so, but it's not particularly harmful to the type safety of the program if the returned object is of the same class (that the constructor would already return).

### Expected result

The rule should either avoid erroring on returned objects (at least when the return type matches the constructor's class), or the documentation should be updated.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@Conaclos what do you think? You implemented the rule in the first place, your input would be really valuable!

**Comment by leops** [comment]
We should note though that a linter is not a compiler, what we consider to be errors is not strictly bound to the ECMAScript spec, and we can afford to be more strict if it helps catch potential errors, that's what the `suspicious` group is all about. We may emit diagnostics for code pattern that are perfectly valid but are deemed to be unusual and probably not what the user intended, with the rationale that if the code is actually doing what's intended, then you should put a suppression comment on top of it with a reason explaining why it's valid (this is the motivation behind having rules like `noDangerouslySetInnerHtml`, we don't discourage users from using `dangerouslySetInnerHTML` but we enforce that they add a comment explaining why it's safe)

**Comment by lgarron** [comment]
I think it's totally reasonable for a linter to be rather parental about a "technically could be valid, but usually a bad idea" case like this — I don't feel strongly about the rule, I would just advocate updating the docs if the intention is to warn on "valid" use cases!
