### ISSUE TITLE
🐛 `useConst` does not take into account destructuring of a reassigned var with an unreassigned one.

### ISSUE THREAD

**Issue by lgarron** [rome/tools#4006]
### Environment information

```block
Rome 11.0.0
```

### What happened?

The following results in an error for the line with `let`.
```js
const v = {a: 3, b: 4};
let {a, b} = v;
a++;
console.log(a, b)
```
[Playground link](https://docs.rome.tools/playground/?code=YwBvAG4AcwB0ACAAdgAgAD0AIAB7AGEAOgAgADMALAAgAGIAOgAgADQAfQA7AAoAbABlAHQAIAB7AGEALAAgAGIAfQAgAD0AIAB2ADsACgBhACsAKwA7AAoAYwBvAG4AcwBvAGwAZQAuAGwAbwBnACgAYQAsACAAYgApAA%3D%3D)

Error: `This 'let' declares a variable which is never re-assigned.`

### Expected result

One of the following:

1. No error. The needs of the `let` override the need of the `const`, and splitting up the destructuring into a `let` and a `const` would result in more verbose code (and if there are quite a few destructured fields, it could also get annoying to move some of them back and forth between the `let` and the `const`, e.g. during debugging).

2. A more specific error suggesting not to mix destructuring assignments that should use `let` vs. `const`, ideally also offering a suggested fix to split up the assignments.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by xunilrj** [comment]
Looking into it.

**Comment by ematipico** [comment]
FYI, relevant discussion https://discord.com/channels/678763474494423051/978209399120216076/1050068632773861448

**Comment by lgarron** [comment]
> FYI, relevant discussion https://discord.com/channels/678763474494423051/978209399120216076/1050068632773861448

I don't seem to be able to access to this, could I ask for a summary/excerpt?

**Comment by ematipico** [comment]
> I think we can mute the rule in this case, and not emit a diagnostics. The main reason is DX. I would expect to have this pattern used widely in different projects, and users should not : 
a. suppress the rule every single time
b. change their code to use `let {a} = foo; const {b} = foo;`, which is a pain;
c. eventually turn off the rule completely
