### ISSUE TITLE
🐛 CLI's whitespace formatting is a hindrance

### ISSUE THREAD

**Issue by nstepien** [rome/tools#4010]
### Environment information

```block
n/a
```

### What happened?

1. Run `rome ci .`
2. Notice formatting issues for examples
3. Copy diffed code
4. Paste into text editor or in a search box

### Expected result

I should be able to copy/paste code from the CLI output, but instead all the `·` characters make it invalid.

I can't use it to paste into anything that accepts code as it's invalid syntax.

I can't use it to search for things, which is what occurred to me prior to opening this issue: I tried searching for something so I could take a closer look, instead VSCode couldn't find it and I raised an eyebrow. 🤨

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
The template doesn't contain any examples to reproduce the issue.

**Comment by nstepien** [comment]
Example:

`test.js`:
```js
chrome.runtime.onMessage.addListener(
  (request, sender, sendResponse) => {
  sendResponse(request.type);
});

```

```
> rome ci .

.\src\test.js:2:13 lint/correctness/noUnusedVariables  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ! This parameter is unused.

    1 │ chrome.runtime.onMessage.addListener(
  > 2 │   (request, sender, sendResponse) => {
      │             ^^^^^^
    3 │   sendResponse(request.type);
    4 │ });

  i Unused variables usually are result of incomplete refactoring, typos and other source of bugs.

  i Suggested fix: If this is intentional, prepend sender with an underscore.

    1 1 │   chrome.runtime.onMessage.addListener(
    2   │ - ··(request,·sender,·sendResponse)·=>·{
      2 │ + ··(request,·_sender,·sendResponse)·=>·{
    3 3 │     sendResponse(request.type);
    4 4 │   });


.\src\test.js format ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × File content differs from formatting output

    1   │ - chrome.runtime.onMessage.addListener(
    2   │ - ··(request,·sender,·sendResponse)·=>·{
      1 │ + chrome.runtime.onMessage.addListener((request,·sender,·sendResponse)·=>·{
    3 2 │     sendResponse(request.type);
    4 3 │   });
```

In the suggested diff, whitespaces are replaced with `·`. I don't find them useful, on the contrary.

**Comment by ematipico** [comment]
That's the intended formatting of our diagnostics and it's not a bug.

I share the sentiment about wanting to copy-paste the code, I do that too, but even though we removed the dots, there are also line numbers, pipes, etc.

If you wish for a way to copy the suggested fix, I would suggest opening a discussion with a proposal
