### ISSUE TITLE
useJsxKey - jsx-key

### ISSUE THREAD

**Issue by xunilrj** [rome/tools#4028]
jsx-key - Disallow missing key props in iterators/collection literals
https://github.com/jsx-eslint/eslint-plugin-react/blob/HEAD/docs/rules/jsx-key.md

**Comment by b4s36t4** [comment]
@xunilrj can you help me work on this? as you mentioned this rule needs some improvements in the parent issue can I know what are those things and if I can work on them as well.

**Comment by xunilrj** [comment]
> can I know what are those things and if I can work on them as well.

Sure. There are two possible cases:

1 - From the JsCallExpression:

But the problem is that to match these you would need to query for all call expressions. You would need to test if the call is to a member access to something named map. Then you would need to look into the map arrow function to check if there is any jsx there, and if the JSX creation is correct.

2 - From the JSX

You would do the inverse path. From the JSX you would need to check if the JSX is being created inside an arrow function inside a function named map.

These things are not only complex, but also very slow and error prone.

Ideally our infrastructure would help us already flagging function with JSX and more fast and direct queries to popular things like all Array.map calls.


My suggestion for this rule is to ignore these improvements for now, and base your solution using https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/semantic_analyzers/suspicious/no_array_index_key.rs which does something similar.

**Comment by ematipico** [comment]
Implemented
