### ISSUE TITLE
noDuplicateJsxProps - jsx-no-duplicate-props

### ISSUE THREAD

**Issue by xunilrj** [rome/tools#4029]
jsx-no-duplicate-props - Disallow duplicate properties in JSX
https://github.com/jsx-eslint/eslint-plugin-react/blob/HEAD/docs/rules/jsx-no-duplicate-props.md

Similar rules:
- https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/analyzers/nursery/no_duplicate_object_keys.rs
- https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/semantic_analyzers/suspicious/no_duplicate_parameters.rs

**Comment by iwollmann** [comment]
@xunilrj I would like to try to do this one.

**Comment by xunilrj** [comment]
Done. Any help just shout at me.
