### ISSUE TITLE
noUnusedReact - jsx-uses-react

### ISSUE THREAD

**Issue by xunilrj** [rome/tools#4030]
jsx-uses-react - Disallow React to be incorrectly marked as unused
https://github.com/jsx-eslint/eslint-plugin-react/blob/HEAD/docs/rules/jsx-uses-react.md

We already have some check to not mark `React` as unused. This implements a smarter check.
https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs#L274

Would be interesting to also update this comment pointing to this rule.

**Comment by andrewgremlich** [comment]
Hello! I'm wondering about contributing and working on this one. Is the idea to remove the "React" conditional and put in logic that resembles the eslint rule?

**Comment by ematipico** [comment]
Closing as it's already implemented
