### ISSUE TITLE
📎 Support extensible config via "extends" property

### ISSUE THREAD

**Issue by marcalexiei** [rome/tools#4038]
### Description

Support `extends` key inside configuration file in order to provide the ability to re-use configuration among different repositories.

References:
- https://github.com/rome/tools/issues/1596#issuecomment-1324825243
- #4036

**Comment by ematipico** [comment]
Bumping this. After the `12.1.0` release, I think we could start implementing it.

We have good diagnostics and a great awareness of the configuration file now. Of course, the `extends` will be limited only to physical paths:

Yes ✅ 
```json
{
	"extends": ["./formatter.json"],
}
```

No ❌ 
```json
{
	"extends": ["@somelibrary/hey"],
}
```

cc @rome/core-contributors if you're interested of if there's someone interested

**Comment by Nikola-Milovic** [comment]
> No x
{
	"extends": ["@somelibrary/hey"],
}

@ematipico does this mean we still can't have a shared package with rome config in monorepos and use it to extend? Especially in larger monorepos I'd love to have shared rome config across all projects. I currently use this approach for tsconfigs for example

**Comment by ematipico** [comment]
We're clearly aware of the limitation, but Rome can't resolve dependencies yet.
