### ISSUE TITLE
📎 Formatter should be able to handle Angular @Component decorators

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4049]
### Description

See some example code from one of my Angular components.

<img width="854" alt="Screenshot 2022-12-13 at 12 40 36 am" src="https://user-images.githubusercontent.com/9585787/207115538-68f3a04f-0622-4a77-a019-5675eebaf581.png">
<img width="658" alt="Screenshot 2022-12-13 at 12 45 55 am" src="https://user-images.githubusercontent.com/9585787/207116612-23de36be-781a-4f56-a707-b11f709f6bb5.png">

Specifically, the `template` and `styles` properties in the @Component decorator use HTML and CSS respectively. Rome Formatter should be aware of these specific properties (which are really the only two I know in common usage) and auto-format them accordingly.

Also, I noticed that `selector` and `template` properties don't get auto-indented. It's like Rome ignores everything in the decorator.

Prettier does this, by the way. So using Rome as a formatter will be a major problem for any Angular dev until the above case is handled

**Comment by xunilrj** [comment]
Thanks for the suggestion. We are starting to focus on specific demands of frameworks. We will definitely pay attention more to React, Vue, Svelte and Agular.

Although we don't have a hard deadline to give you about Angular.

**Comment by jpike88** [comment]
I am desperately struggling to use Rome instead of eslint, it's at a point where enabling eslint is vscode is causing crashes to occur:

https://github.com/microsoft/vscode/issues/171691

The only real obstacle right now is that Rome doesn't recognised import statements as used when they're a decorator. As a stop gap, I would highly recommend doing the minimum as a priority, which is to parse decorator names so the import statements are considered 'used' in that file.
