### ISSUE TITLE
🐛 <TITLE> ReferenceError: code is not defined  No prompt with rome

### ISSUE THREAD

**Issue by whiter001** [rome/tools#4110]
### Environment information

```block
>rome --version
Rome CLI version 11.0.0
```

### What happened?

```
const isSuccess = code === 200
                  ^

ReferenceError: code is not defined
```

### Expected result

Prompt error message

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
That's intended, our parser doesn't aim to catch all errors during the parsing phase. Some cases are left to the analyzer infrastructure, but we're not there yet.

This is something we plan to add in the future and we will create a project for that.
