### ISSUE TITLE
🐛 Permission denied (os error 13)

### ISSUE THREAD

**Issue by dougg0k** [rome/tools#4118]
Hi, 

I've been trying out Rome into a back-end project and seems very good replacement to Prettier. But I found something that you might consider a bug or not.

### What happened?

```
> rome format . --write

./mongodb/data/db/diagnostic.data internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Permission denied (os error 13)
  

./mongodb/data/db/journal internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Permission denied (os error 13)
  

Formatted 87 file(s) in 7ms
```

Docker Compose create the mongodb folder with the data. But I have configured rome to ignore the folder, but it doesnt seem to ignore, since the error are there. 

I could probably change permission to resolve the issue.

```
{
	"formatter": {
		"enabled": true,
		"formatWithErrors": false,
		"ignore": [
			"node_modules",
			"dist",
			"build",
			"nginx",
			"mongodb",
			"src/graphql/generated"
		],
		"indentSize": 2,
		"indentStyle": "tab",
		"lineWidth": 80
	},
	"linter": {
		"enabled": false,
		"rules": {}
	}
}
```

### Expected result

But it would be better if it were properly ignored if possible.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I think I know what's the problem here. 

The check whether a file is ignored or not is done at workspace level, while doing the traversal of file system. If a file is ignored, we don't handle it but we don't stop the traversal if it's a folder. I think this is the bug.

**Comment by MichaReiser** [comment]
Isn't the issue that the paths are supposed to be globs: 'node_modules/**' instead of 'node_modules'

Or I guess it may be a bit of both. Can you try the globs with the wildcard to see if it resolved the issue?

**Comment by dougg0k** [comment]
Same issue. It doesnt make sense that would need to contain that, since the root dir should be enough to ignore everything under it.
