### ISSUE TITLE
🐛 Replace with string literal should replace with " " not {" "}

### ISSUE THREAD

**Issue by pegak** [rome/tools#4159]
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 unset

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:              11.0.0-nightly.fab5440
```

### What happened?
1. HTML Element with dynamic string has no dynamic elements, e.g.
```
classNames={`just static classes`}
```
2. It is replaced with `classNames={"just static classes"}` after I call `rome check --apply-suggested`.

### Expected result

It should replace with `classNames="just static classes"`.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
This fix is intended because `""` and `{""}` have two different meanings and are translated to two different nodes.
