### ISSUE TITLE
`useConst` quick fix not working in edge case

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4170]
In below case, the rule is flagged, but no quick fix available
```
let gitHashShort;
gitHashShort = gitHashLong.substr(0, 7);
```

**Comment by Conaclos** [comment]
For now the quick fix is only applied when the variable is both declared and initialized.
Your suggestion could produce a multiline change.
Do you know if _eslint_ handles this case?

**Comment by ematipico** [comment]
I'm not sure we can suggest a fix for this code.

This would mean to join the two statements into one, causing some issues if there are more statements in the middle.

**Comment by jpike88** [comment]
Yeah, I was a little overzealous here, turns out there isn't a quick fix for this from eslint anyway. ill close
