### ISSUE TITLE
📎 `noVar` rule needs quick fix

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4172]
### Description

`noVar` rule complains without intelligently quick fixing to either `let` or `const` depending on the situation.

**Comment by Conaclos** [comment]
`noVar` fixes are unsafe because of `var`-hoisting. The rule suggests a fix when you run `rome check`. You can apply suggestions with `rome check --apply-suggested`.

**Comment by jpike88** [comment]
If people are relying on var hoisting for their code to work properly that means they aren’t writing their code in a proper, modular, scope neutral fashion. They then shouldn’t enable such a rule to begin with. I never have a problem worrying about that kind of issue, and it seems odd to take into account such an edge case because this rule is clearly not for them.

eslint’s equivalent rule has a simple way of determining whether or not let is appropriate, and this rule could benefit for the quick fix trying to take that into consideration. Dumbing down Rome’s quick fixes will turn people off quickly. As an early adopter I’m not impressed with the weird take here.

**Comment by Conaclos** [comment]
> eslint’s equivalent rule has a quick fix which has a simple way of determining whether or not using let is appropriate

Thanks for the remark. I will take a look.

**Comment by jpike88** [comment]
great, appreciate the open minded approach. As you've seen I've raised a bunch of rule requests here https://docs.google.com/spreadsheets/d/16PXNlt7XoQG_ByRC9azLcFqPxZbIyppcb2c92O_lCv4/edit?usp=sharing, the ones marked with importance 1 we consider to be most important, this doesn't just include the rule itself but precisely how the quick fixes work (and that goes for all the rules that use them). Going through this exercise is making me realise how important quick fixes are in our workflow

**Comment by jpike88** [comment]
https://github.com/rome/tools/discussions/3774

In that file I have this set:
```
{
		browser: true,
		es6: true,
	}
```

That same file is used for our nodejs typescript projects without any drama (we use esbuild to transpile them).

Why not target a 'baseline' environment/configuration for the linter, and diversify once you've got parity?

**Comment by jpike88** [comment]
Seems like it comes with its own set of problems, if I'm not wrong.. you're saying that the way a linting rule or quick fix operates can/should change based on the environment? Is the plant to just have some sort of 'safe' version of quick fixes first, then diversify based on environment later? Seems like it might render some/many of the quick fixes not as useful as they could be.

**Comment by ematipico** [comment]
> Seems like it comes with its own set of problems, if I'm not wrong.. you're saying that the way a linting rule or quick fix operates can/should change based on the environment?

Some rules, yes. Once our internal infrastructure will allow us to have more information, I am sure some fixes will become safe.

> Is the plan to just have some sort of 'safe' version of quick fixes first, then diversify based on environment later? Seems like it might render some/many of the quick fixes not as useful as they could be.

Unfortunately, that's because of the nature of JavaScript: a dynamic language.

**Comment by Conaclos** [comment]
@jpike88 Why `--apply-suggested` is not enough in your use case?

The basic idea behind quick fixes is that you can apply them with closed eyes. To make it possible _Rome_ has to be conservative. This is a path taken by mature project such as _esbuild_: _esbuild_ does not transform the code in a way that could break it even if this is edge cases.

Rome provides suggested fixes as a mean to apply unsafe fixes that can break the code in some edge cases. Looks like you are interested in suggested fixes...

**Comment by Conaclos** [comment]
I just noticed that in some cases, no suggestions are provided:

```js
export var y = 5
           ^^^
           Suggest `const`
export var x = 5
           ^^^
           No suggestion
x = 6
```

According to my quick test, any reassigned `var` has no suggestion.
This is something that we can fix.

Could this fix cover your use case?
