### ISSUE TITLE
new rule: `pascalCaseClassNames`

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4175]
### Description

Class names usually adopt the pascal case convention for readability, and standing them out from variables, functions.

This would be invalid:
```
class thisIsAClass { }
```

This would be valid:
```
class ThisIsAClass { }
```

**Comment by unvalley** [comment]
I'll work on this.

**Comment by ematipico** [comment]
Actually, there's an interesting proposal from @Conaclos https://github.com/rome/tools/discussions/4282 I really like. 

@jpike88 when you have an idea, please use GitHub discussions instead. We use issues for bugs, technical tasks and tracking tasks are already planned/discussed. 

@unvalley please hold off on this one, I'd suggest check umbrella issues around ESLint compatibility, accessibility or react

**Comment by jpike88** [comment]
closing in favor of #4282
