### ISSUE TITLE
🐛 ignore option in config file is not consistent

### ISSUE THREAD

**Issue by himaanshu24** [rome/tools#4195]
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...
```

### package.json

```json
"lint:js": "npx rome check cartridges/**/cartridge/client/**/js/",
"lint:js-all": "npx rome check ."
```

### rome.json

```json
"files": {
        "ignore": [
            "cartridges/FOLDER_A/**",
            "cartridges/FOLDER_B/**",
            "cartridges/FOLDER_C/**",
            
            "./cartridges/FOLDER_A/**",
            "./cartridges/FOLDER_B/**",
            "./cartridges/FOLDER_C/**",
        ]
    }
```

To ignore the above folder I have to keep two entries one with `./` and one without. 

- While running the command with `.` 
  - does not ignore files if given only `"cartridges/FOLDER_A/**",`
- While running the command **without** `.` 
  - does not ignore files if given only `"./cartridges/FOLDER_A/**",`

### Expected behavior
Both `./FOLDER/` and `FOLDER/` should work similarly with the respect to where the command is running.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by NexZhu** [comment]
`files.ignore` is completely not working in my case, no matter if there's `./` or not.

**Comment by ematipico** [comment]
FYI the CLI commands **don't support** Unix shell style like patterns . Are you able to replicate the issue in a fresh new repository and share it?

**Comment by ematipico** [comment]
Closing, until there's a repo where we can reproduce the issue.
