### ISSUE TITLE
🐛 EOL (End-Of-Line) | Format behaviour is not consistent

### ISSUE THREAD

**Issue by himaanshu24** [rome/tools#4196]
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...
```

### What happened?

- run `npx rome format . --write` on **mac**, fixing the format.
- run `npx rome format . ` to check if there is any error. Run successfully and does not through any errors.
- Now take pull to windows machine
- run  `npx rome format . `  - errors are reported with eol (**cr**)
- if integrated with githook, fails it
- now it becomes a cycle if fixed and pushed and pulled to the mac machine

![image](https://user-images.githubusercontent.com/8476966/217456840-04edde03-b351-4535-803d-bc2404361fd2.png)

### Expected result

The **eol** should be consistent on running `npx format .` and does not change from mac-windows-mac. This creates an issue every time the code is pushed/pulled to/from mac and windows creating chaos and wasting a lot of time.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
We have had contributors with different operating systems and we used Rome formatter for a while, and we haven't had issues concerning the EOL on different OSs.

Is there any chance you'll be able to create a repo where it's possible to reproduce the issue?

**Comment by himaanshu24** [comment]
> We have had contributors with different operating systems and we used Rome formatter for a while, and we haven't had issues concerning the EOL on different OSs.
> 
> Is there any chance you'll be able to create a repo where it's possible to reproduce the issue?

Hi @ematipico,

I have created the following repo on my mac machine
> https://github.com/himaanshu24/rome-test

- ran `npm install`
- ran the `npm run fix:js`
- then ran the `npm run format:js` // no error shown
<img width="435" alt="Screenshot 2023-02-09 at 12 40 35 PM" src="https://user-images.githubusercontent.com/8476966/217742834-ffe627ff-5ef7-45c7-a884-d0986c2c1d4c.png">

- then cloned it on my windows machine and did `npm install` and
- ran the `npm run format:js` // throw error

**Comment by ematipico** [comment]
I believe this is the expected behaviour and it's not an issue related to Rome.

Have you tried fix the issue using git? https://github.com/rome/tools/blob/main/.gitattributes#L1

**Comment by himaanshu24** [comment]
Actually, I do have `.gitattributes` file at the root of my project. It has the following entry

```txt
# Autodetect text files
* text=auto

# Force all text file types to have unix line endings
*.* text eol=lf

```

Let me try to add the same exact line provided by you in the given test repo above.

**Comment by himaanshu24** [comment]
Hi @ematipico, I tried the exact entry in `.gitattributes`, but the issue still persists.
Can you please check the given repo - https://github.com/himaanshu24/rome-test

Thanks

**Comment by himaanshu24** [comment]
@ematipico, This issue is resolved when using the `.gitattributes` file. But I have to rest using the following command since this is an existing/old project.

```
git rm --cached -r .
git reset --hard
```

Thanks for your help.
