### ISSUE TITLE
🐛 rome format appends an extra newline when formatting from stdin to stdout

### ISSUE THREAD

**Issue by abustany** [rome/tools#4197]
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

```

### What happened?

1. Run `rome format myfile.tsx`
2. Run `rome format --stdin-file-path myfile.tsx < mfile.tsx > foo`
3. Run `diff myfile.tsx foo`

Rome appends a new line after formatting stdin, so `foo` ends up having one extra new line at the end compared to `myfile.tsx`

### Expected result

Rome should not append a new line when formatting files from stdin to stdout.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Conaclos** [comment]
I made several tests. Rome seems adding a blank line in two cases:

1. there is no blank line at the end of the file
2. there is a single blank line at the end of the file.

Rome removes all extra blank lines.

```diff
  class X {}
+ // new line added
```

```diff
  class X {}
  // existing line
+ // new line added
```


```diff
  class X {}
  // existing line
  // existing line
```

```diff
  class X {}
  // existing line
  // existing line
- // existing line
```

@abustany di you complain about the second case?

**Comment by denbezrukov** [comment]
I think that the extra newline added here:
https://github.com/rome/tools/blob/c0556ff3c33091a10cfa8ff39ce9cabd09185082/crates/rome_cli/src/execute.rs#L177
because `console.log` has `writeln` 
https://github.com/rome/tools/blob/c0556ff3c33091a10cfa8ff39ce9cabd09185082/crates/rome_console/src/lib.rs#L135

Maybe we can add condition here?

**Comment by abustany** [comment]
For me the main issue is that the behavior differs between running the tool directly on a file vs. piping the file via stdin… Probably because of `writeln` as @denbezrukov found out. But I’d say that not adding an empty line is the right behavior.

**Comment by ematipico** [comment]
We could add a new `println` method, which will do what `print` does now. And `print` will do the same, expectation that it will call `write!` instead. 

Then, when piping the output to `stdout`, we could call `print` instead.
