### ISSUE TITLE
🐛 Message: internal error: entered unreachable code

### ISSUE THREAD

**Issue by aaaristo** [rome/tools#4202]
### Environment information

```block
Rome encountered an unexpected error

This is a bug in Rome, not an error in your code, and we would appreciate it if you could report it to https://github.com/rome/tools/issues/ along with the following information to help us fixing the issue:

Source Location: crates/rome_js_syntax/src/expr_ext.rs:465:18
Thread Name: rome::worker_1
Message: internal error: entered unreachable code
```

### What happened?

I tryied running rome on our code base  (~1.2M LOC)

npx rome check .

I got a bunch of suggestions and then Rome exited with the above message.

### Expected result

No unexpected errors

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Conaclos** [comment]
Hi [aaaristo](https://github.com/aaaristo).

Thanks for the report!

The error comes from [this line](https://github.com/rome/tools/blob/d9d8211fdbf7ea1efd22bcf842b1771d676a56ce/crates/rome_js_syntax/src/expr_ext.rs#L465). Taking a look at this, I noticed that an assignment operator is missing `/=`.
Could you confirm that your codebase uses this operator? Rome should fail when it encounters this operator.

I will send a fix.

**Comment by aaaristo** [comment]
@Conaclos yes I can confirm.
