### ISSUE TITLE
🐛 Segmentation faults when linting

### ISSUE THREAD

**Issue by theoparis** [rome/tools#4203]
### Environment information

```block
CLI:
  Version:              0.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "tmux-256color"
  JS_RUNTIME_VERSION:   unset
  JS_RUNTIME_NAME:      unset
  NODE_PACKAGE_MANAGER: unset

Rome Configuration:
  Status:               Loaded successfully
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...
```

I built rome from source with debug symbols. I used `mold -run cargo +nightly install -Zsparse-registry --path crates/rome_cli --debug` on a checkout of the latest commit.

Interestingly the version from npm (`yarn dlx rome check .`) does not have the same issue...

Additionally if this helps here is my `~/.cargo/config.toml`:

```
[build]
rustc-wrapper = "ccache"

[profile.release]
strip = true
opt-level = "z"
lto = "thin"
```

### What happened?

```
rome check src
zsh: segmentation fault (core dumped)  rome check src
```

**Stack Trace** (with lldb):

``` rome_$LT$rome_diagnostics..error..Error$u20$as$u20$rome_diagnostics..diagnostic..internal..AsDiagnostic$GT$::as_diagnostic::h76ea47708aa834fa(self=0x00007ffff4bf71a0) at error.rs:126:9
   123      type Diagnostic = dyn Diagnostic;
   124
   125      fn as_diagnostic(&self) -> &Self::Diagnostic {
-> 126          (self.vtable().as_diagnostic)(self.inner())
   127      }
   128
   129      fn as_dyn(&self) -> &dyn Diagnostic {

```

Sometimes `rome format .` will segfault as well...

### Expected result

It should not segfault.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Interesting. I encountered the same error while also using the latest version of Rust. Unfortunately, I can't understand the source of the issue.

**Comment by ematipico** [comment]
This is now fixed
