### ISSUE TITLE
🐛 `rome.json`  takes not effects

### ISSUE THREAD

**Issue by Soltus** [rome/tools#4206]
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 unset

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...

Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:              <=10.0.0
```

### What happened?

```json
{
  "$schema": "./node_modules/rome/configuration_schema.json",
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentSize":2,
    "lineWidth": 120,
    "formatWithErrors": true
  },
  "javascript":{
    "formatter": {
      "quoteStyle": "single"
    }
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "suspicious": {
        "noExplicitAny": "off"
      }
    }
  }
}
```
The above configuration does not work.
I can only comment in the code
// rome-ignore lint/suspicious/noExplicitAny: <explanation>

### Expected result

`rome.json` takes effects

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Soltus** [comment]
![image](https://user-images.githubusercontent.com/83791825/218650567-795926df-850e-429a-81bc-128fe220fa80.png)
According to CI, it seems to be a unique problem with the Windows platform

**Comment by ematipico** [comment]
@Soltus, could you please share more info regarding where/when you have this issue? (CLI, VSCode extension, etc.)

The CI fail doesn't reflect the issue you're having, the CI fails on code that is not currently released, so it should not worry you.

**Comment by Conaclos** [comment]
I noticed the same issue with the latest pre-release (`11.0.0-nightly.97e48b4`). This affects the CLI and the VSCode extension.

This is a regression because I had no problem with the CLI in the previous pre-release (`11.0.0-nightly.fab5440 `).
Note that I did not test the VSCode extension in its previous pre-release.

Next teh output of `rome rage`:

```
CLI:
  Version:              11.0.0-nightly.97e48b4
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"
  JS_RUNTIME_VERSION:   "v18.12.0"
  JS_RUNTIME_NAME:      "node"
  NODE_PACKAGE_MANAGER: "npm/8.19.2"

Rome Configuration:
  Status:               Loaded successfully
  Formatter disabled:   false
  Linter disabled:      false

Workspace:
  Open Documents:       0

Discovering running Rome servers...
```

rome server output (for the VSCode extension):

```
[cli-stdout] data 40
[cli] exit 0
Connecting to "/tmp/rome-socket-11.0.0-nightly.97e48b4" ...
[Info  - 1:02:18 PM] Server initialized with PID: 160684
```

**Comment by Soltus** [comment]
First of all, I run  `pnpm add --save-dev rome`  on the root path of the project
![image](https://user-images.githubusercontent.com/83791825/218733493-289acff2-4ed2-42f9-ac84-9f1870ded11c.png)

Then execute the `pnpm rome init`, and then manually modify` rome.json`

Then I installed the official VSCode extension
![image](https://user-images.githubusercontent.com/83791825/218731509-5ccc5d7e-6f4a-4170-99cf-10b3ab744cf1.png)
@Conaclos  mentioned the VSCode extension preview, I switched to the preview version, I don't know if it has an impact, but I switched back to the official version and also reinstalled

This is the screenshot of Linter:
![image](https://user-images.githubusercontent.com/83791825/218731880-bf5fc6ae-4a14-4d28-8eca-b3e2609a63fc.png)


I tried to uninstall the ROME package, and then VSCODE issued a path warning, but did not affect the VSCode extension . Linter still reported an error as the picture above.
![image](https://user-images.githubusercontent.com/83791825/218733094-b302c97a-25c4-4a45-9069-349b2c3dabe0.png)

**Comment by ematipico** [comment]
Would you be able to reproduce the issue in a fresh new repository and share it here? Or share the one where you're working on? Unfortunately, I can't replicate the issue. It could be an OS issue since I am using macOS while the case is happing on windows.

**Comment by Soltus** [comment]
Wait a minute, I'll ask a friend to help test it out

**Comment by Soltus** [comment]
> ```json
>  "noExplicitAny": "off"
> ```

My friend said that he worked normally on macos
Is it a path problem?

**Comment by Conaclos** [comment]
Strangely I did not get the issue if I used a built version from the source.

**Comment by Soltus** [comment]
The absolute path of my local project contains Chinese characters, will this affect?

**Comment by fanzeyi** [comment]
FYI I figured out in my case, it was because I had the TypeScript project as one of the directories in the workspace but not the top one. Rome doesn't seem to be able to see `rome.json` in the directory if it is not the top directory (first in the list).

Rearranging directories order in my VS Code workspace helped.

**Comment by Soltus** [comment]
yeah, i will confirm it later. thank you

**Comment by Soltus** [comment]
That's right, `rome.json` is put in effect at the root path of the workspace
