### ISSUE TITLE
📎 `noConsoleLog`

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4223]
### Description

https://eslint.org/docs/latest/rules/no-console

forces people to use .error, .info, but not .log as it's for debug purposes and not explicit about the context of the output.

Or maybe it's better to have a more general purpose 'ban', so users can configure more fine-grained things to ban including something like this.

**Comment by jpike88** [comment]
Whoops! Sorry yes. Referring to my eslint file:

https://github.com/rome/tools/discussions/3774

I configured it in such a way that basically everything was allowed BUT the use of console.log. This ensures developers don't accidentally leave hanging console.logs for debug purposes, anything that's not a log would be something deliberate and designed to remain in the code indefinitely.

**Comment by christianalares** [comment]
Any news on this? I really enjoyed the `no-console`-rule in eslint, would be a great feature to have in rome

**Comment by ematipico** [comment]
PRs welcome :)

**Comment by jpike88** [comment]
im open as well to a general `noConsole` rule if that's more in demand
