### ISSUE TITLE
📎 TypeScript 5.0

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#4227]
### Description

Add parsing and formatter support for the syntax introduced by TypeScript 5.0

- [x] `export type *` #4228

  - [TypeScript PR](https://github.com/microsoft/TypeScript/pull/52217)
  - [TypeScript announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#support-for-export-type)

- [ ] `const` type parameters

  - [TypeScript PR](https://github.com/microsoft/TypeScript/pull/51865)
  - [TypeScript announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#const-type-parameters)

**Comment by nissy-dev** [comment]
We should support decorators ? [Typescript announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#decorators)

**Comment by Conaclos** [comment]
> We should support decorators ? [Typescript announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#decorators)

Updated.

**Comment by ematipico** [comment]
Personally, I would move decorators to their issue. Why? Because it's not a TypeScript thing but a JavaScript thing. 

Having decorators here would send the wrong message: it could signal that we aim to support **legacy** decorators, which is not.

**Comment by csvn** [comment]
> Personally, I would move decorators to their issue. Why? Because it's not a TypeScript thing but a JavaScript thing.

I think Typescript has one small difference in TS with decorators compared to the spec in TC39 though, [they allow decorators before `export` or `export default`][ts5]:

```ts
@component('my-foo')
export class Foo {}

@component('my-bar')
export default class Bar {}
```

Officially in JS this has to be written as:

```ts
export @component('my-foo') class Foo {}

export default @component('my-bar') class Bar {}
```

So I think there may at least be a small difference in syntax parsing/AST between JS/TS.

[ts5]: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#whats-new-since-the-beta

**Comment by ematipico** [comment]
@csvn they recently changed the grammar: https://babeljs.io/blog/2023/02/20/7.21.0#decorators-updates

**Comment by Conaclos** [comment]
@csvn The TypeScript team talks about this change on the spec after discussion between them and the spec team in their [TS 5.0 annoucement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/).

**Comment by Conaclos** [comment]
I opened a new issue #4252.

**Comment by csvn** [comment]
@ematipico Oh, cool! I did not find that myself when I looked. Glad it's consistent, since it's (IMO) way more ergonomic to have it before `export` 🙂

**Comment by nissy-dev** [comment]
I'll take const modifier support.
