### ISSUE TITLE
🐛 <parse error>  parse typescript generic type error

### ISSUE THREAD

**Issue by X-Jagger** [rome/tools#4269]
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     aarch64
  OS:                   macos

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      true

Workspace:
  Open Documents:       0
```

### What happened?

https://docs.rome.tools/playground/?code=ZQB4AHAAbwByAHQAIAB0AHkAcABlACAARQB4AHQAcgBhAGMAdABQAHIAbwBwAHMAVAB5AHAAZQBGAHIAbwBtAEYAbwB1AG4AZABhAHQAaQBvAG4APAAKACAAIABGAG8AdQBuAGQAYQB0AGkAbwBuACAAZQB4AHQAZQBuAGQAcwAgAEMAbwBtAHAAbwBuAGUAbgB0AEYAbwB1AG4AZABhAHQAaQBvAG4APABhAG4AeQAsACAAYQBuAHkALAAgAGEAbgB5ACwAIABhAG4AeQA%2BACwACgAgACAAUAByAG8AcABzAE8AcAB0AGkAbwBuAHMAIAA9ACAARgBvAHUAbgBkAGEAdABpAG8AbgAgAGUAeAB0AGUAbgBkAHMAIABDAG8AbQBwAG8AbgBlAG4AdABGAG8AdQBuAGQAYQB0AGkAbwBuADwACgAgACAAIAAgAGkAbgBmAGUAcgAgAFAAIABlAHgAdABlAG4AZABzACAAQwBvAG0AcABvAG4AZQBuAHQAUAByAG8AcABzAE8AcAB0AGkAbwBuAHMALAAKACAAIAAgACAAYQBuAHkALAAKACAAIAAgACAAYQBuAHkALAAKACAAIAAgACAAYQBuAHkACgAgACAAPgAKACAAIAAgACAAPwAgAFAACgAgACAAIAAgADoAIABuAGUAdgBlAHIALAAKACAAIABEAGUAZgBhAHUAbAB0AHMAUAByAG8AcABzACAAPQAgAEUAeAB0AHIAYQBjAHQARABlAGYAYQB1AGwAdABQAHIAbwBwAFQAeQBwAGUAcwA8AFAAcgBvAHAAcwBPAHAAdABpAG8AbgBzAD4ALAAKACAAIABPAHUAdABwAHUAdABQAHIAbwBwAHMAIAA9ACAAUABhAHIAdABpAGEAbAA8AEQAZQBmAGEAdQBsAHQAcwBQAHIAbwBwAHMAPgAgACYACgAgACAAIAAgAE8AbQBpAHQAPABFAHgAdAByAGEAYwB0AFAAcgBvAHAAVAB5AHAAZQBzADwAUAByAG8AcABzAE8AcAB0AGkAbwBuAHMAPgAsACAAawBlAHkAbwBmACAARABlAGYAYQB1AGwAdABzAFAAcgBvAHAAcwA%2BACwACgA%2BACAAPQAgAE8AdQB0AHAAdQB0AFAAcgBvAHAAcwA%3D

![image](https://user-images.githubusercontent.com/23659716/223316610-1f4f22d7-4602-4945-8e82-09778037840b.png)

### Expected result

parse and format correctly 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I am going to close it. The playground doesn't emit any diagnostics and the fix is available in one of our last nightlies.
