### ISSUE TITLE
🐛 `rome check` and `rome ci` do not report unorganized imports

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#4300]
### Environment information

```block
CLI:
  Version:              11.0.0-nightly.846c15e
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   linux

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"
  JS_RUNTIME_VERSION:   "v18.12.0"
  JS_RUNTIME_NAME:      "node"
  NODE_PACKAGE_MANAGER: "npm/8.19.2"

Rome Configuration:
  Status:               Loaded successfully
  Formatter disabled:   true
  Linter disabled:      false

Workspace:
  Open Documents:       0
```

### What happened?

Given the following code:

```js
// index.js
import b, { B } from 'b';
import a, { A } from 'a';
```

and `rome.json`:

```
{
  "organizeImports": {
    "enabled": true
  }
}
```

`rome ci index.js` and `rome check index.js` do not error on the unorganized imports.
I also tested `rome ci --organize-imports-enabled=true index.js`.

Important note: `rome check --apply-unsafe index.js` organizes imports. Thus _Rome_ takes the configuration into account!

### Expected result

Running `rome check` or `rome ci` should error when unorganized imports are found.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Good catch @Conaclos 
This feature needs more architectural work. That was an oversight from by end.
