### ISSUE TITLE
📎 Support `enable` setting in vscode extension

### ISSUE THREAD

**Issue by krzkaczor** [rome/tools#4311]
### Description

It should be possible to turn off rome's vscode extension. It's misbehaving in repositories that don't have `rome.json` (even with `requireConfiguration` turned on). I would like to have it globally disabled and only enable in workspaces that use rome. 

Related: https://github.com/rome/tools/issues/3506

**Comment by ematipico** [comment]
This has been implemented via https://github.com/rome/tools/pull/4023 and available via pre-release.

It will be available once we release the new version.

**Comment by krzkaczor** [comment]
As I mentioned, I already use `requireConfiguration` yet rome still tries to format `.json` files in random workspaces. I would really love to have explicit on/off switch. Many vscode extensions have this.

**Comment by ematipico** [comment]
Feel free to file a bug, that's probably not intentional
