### ISSUE TITLE
🐛 Imports in *.module.ts are always unused (noUnusedVariables)

### ISSUE THREAD

**Issue by DevMark97** [rome/tools#4313]
### Environment information

```block
CLI:
  Version:              11.0.0
  Color support:        true

Platform:
  CPU Architecture:     x86_64
  OS:                   windows

Environment:
  ROME_LOG_DIR:         unset
  NO_COLOR:             unset
  TERM:                 "xterm-256color"

Rome Configuration:
  Status:               loaded
  Formatter disabled:   false
  Linter disabled:      false
```

### What happened?

Open any *.module.ts file in angular project. You can see that every import has error "This variable is unused." but is located in imports below.
![Przechwytywanie](https://user-images.githubusercontent.com/126020086/226565972-364ae634-746e-4906-9dce-f58624d45593.PNG)

### Expected result

Rome should not mark these imports as error

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by denbezrukov** [comment]
Thank you for your issue.
Rome doesn't support decorators now.
https://github.com/rome/tools/issues/4252

**Comment by DevMark97** [comment]
So imports in lines 22-33 rome recognises as decorators?

**Comment by denbezrukov** [comment]
@DevMark97 

Rome can't parse expressions inside the decorator. See the syntax tab in [playground](https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&lintRules=all&code=aQBtAHAAbwByAHQAIAB7AE0AbwBkAHUAbABlAH0AIABmAHIAbwBtACAAJwBtAG8AZAB1AGwAZQAnADsACgAKAEAATgBnAE0AbwBkAHUAbABlACgAewAKACAAIABNAG8AZAB1AGwAZQAKAH0AKQAKAGMAbABhAHMAcwAgAE0AeQBDAGwAYQBzAHMAIAB7AH0A
)

**Comment by jpike88** [comment]
I'm using angular, I have this disabled by Rome for the time being as well.

Although this should be something detected by typescript itself (warning not an error), but should cause your attempt to build angular to error anyway.

**Comment by denbezrukov** [comment]
I've taken decorators in progress, it should be fixed soon:)

**Comment by jpike88** [comment]
looks like this can be closed
