### ISSUE TITLE
🐛 Invalid `useShorthandArrayType` applied fix

### ISSUE THREAD

**Issue by nstepien** [rome/tools#4349]
### Environment information

```block
https://docs.rome.tools/playground/?quoteStyle=single&trailingComma=none&indentWidth=4&lintRules=all&code=dAB5AHAAZQAgAEEAIAA9ACAAUgBlAGEAZABvAG4AbAB5AEEAcgByAGEAeQA8AFIAZQBhAGQAbwBuAGwAeQBBAHIAcgBhAHkAPABuAHUAbQBiAGUAcgA%2BAD4AOwA%3D
Rome v12
```

### What happened?

1. With the code
   ```ts
   type A = ReadonlyArray<ReadonlyArray<number>>;
   ```
2. Run `rome check . --apply-unsafe`
3. The output is not valid syntax
   ```ts
   type A = readonly readonly number[][];
   ```

### Expected result

```ts
type A = readonly (readonly number[])[];
```
Or maybe nested `ReadonlyArray<>` should be allowed 🤔

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by unvalley** [comment]
I'll work on this.

**Comment by jpike88** [comment]
see my comment on PR, I found a deeper issue with this rule, @unvalley pls let me know if you need any more info
