### ISSUE TITLE
🐛 `useLiteralKeys` doesn't ignore valid uses of square bracket notation

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4370]
### Environment information

```block
CLI:
  Version:                      12.0.0-nightly.0133f40
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.14.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.6.3"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    true

Workspace:
  Open Documents:               0
```

### What happened?

This may be as intended, but then it differs in an important way from eslint `dot-notation`.

See below

<img width="1078" alt="wat" src="https://user-images.githubusercontent.com/9585787/231676980-82da5efd-2b22-48fa-9397-ecd42147a3a9.png">

There is no way to specify a literal key while also allowing special characters, the rule must then be ignored to allow this line to happen. Sometimes square bracket notation is unavoidable.

### Expected result

The rule should allow valid uses of square bracket notation

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I assume you're using the nightly version of Rome?

Also, this rule is different from the ESLint rule `dot-notation`.

**Comment by jpike88** [comment]
That's right im on the recently released nightly.

In the meantime I'll just add a bunch of line ignore comments, was just unsure if this is desired outcome or not

**Comment by ematipico** [comment]
Yeah, you did well to report the issue :)
