### ISSUE TITLE
Make every type optional via `Option`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4399]
`bpaf` will mark as optional all the options that have `Option`. In some structs, some of these options don't use it because we rely on the `Default` trait.

Considering that CLI options and `Configration` are two faces of the same coin, we should make all the properties optional via `Option`. For example, `FormatterConfiguration` doesn't use `Option` at all.

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on it. Is it available?

**Comment by ematipico** [comment]
> Hi, I would like to work on it. Is it available?

Sure! Go ahead! If you have any questions, just ask

**Comment by 2022H1030042G** [comment]
@ematipico , Where are the changes required (in which file etc.) and how to implement those changes. I'm new to open source development, so I'd require some help.

**Comment by ematipico** [comment]
Best place to start is here: 

https://github.com/rome/tools/blob/0ce919840c8ebaa02c3329b38fd8864c05b38d6e/crates/rome_service/src/configuration/formatter.rs#L10-L39

And make all properties optional using the `Option` type.

For example:

```rs
  pub enabled: Option<bool>,
```

Once you change that, you'll get some compiler errors coming from here:

https://github.com/rome/tools/blob/0ce919840c8ebaa02c3329b38fd8864c05b38d6e/crates/rome_service/src/configuration/parse/json/formatter.rs#L29-L62

The easy fix will be to remove the `?`, or use the `Some` like `self.property = Some(...)`. The tests should stay like this and the existing tests should pass.

**Comment by 2022H1030042G** [comment]
I made all the properties optional in the file mentioned above and removed the ?, but there is a compilation error

**Comment by 2022H1030042G** [comment]
Refer: #4406

**Comment by ematipico** [comment]
I wanted to get this change faster. I ended up doing it myself because I needed it for the CLI.
