### ISSUE TITLE
🐛 `lint/a11y/useButtonType` misses some issues

### ISSUE THREAD

**Issue by nstepien** [rome/tools#4410]
### Environment information

https://docs.rome.tools/playground/?indentStyle=space&lintRules=all&code=PAA%2BAAoAIAAgAHsALwAqACAAZwBvAG8AZAAgACoALwB9AAoAIAAgADwAYgB1AHQAdABvAG4APgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIAB0AHkAcABlAD0AIgBpAG4AdgBhAGwAaQBkACIAPgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIAB0AHkAcABlAD0AIgBpAG4AdgBhAGwAaQBkACIAIABvAG4AQwBsAGkAYwBrAD0AewBuAHUAbABsAH0APgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgAHsALwAqACAAYgBhAGQALAAgAHQAaABlAHMAZQAgAHMAaABvAHUAbABkACAAYgBlACAAYwBhAHUAZwBoAHQAIABhAHMAIAB3AGUAbABsACAAKgAvAH0ACgAgACAAPABiAHUAdAB0AG8AbgAgAC8APgAKACAAIAA8AGIAdQB0AHQAbwBuACAAbwBuAEMAbABpAGMAawA9AHsAbgB1AGwAbAB9ACAALwA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIABvAG4AQwBsAGkAYwBrAD0AewBuAHUAbABsAH0APgB0AGUAcwB0ADwALwBiAHUAdAB0AG8AbgA%2BAAoAIAAgADwAYgB1AHQAdABvAG4AIAB0AHkAcABlAD0AIgBpAG4AdgBhAGwAaQBkACIAIAAvAD4ACgAgACAAPABiAHUAdAB0AG8AbgAgAHQAeQBwAGUAPQAiAGkAbgB2AGEAbABpAGQAIgAgAG8AbgBDAGwAaQBjAGsAPQB7AG4AdQBsAGwAfQAgAC8APgAKADwALwA%2BADsACgA%3D

### What happened?

1. Open playground link
2. Notice that some buttons should be flagged for missing/invalid `type` prop

### Expected result

Parity with https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/button-has-type.md

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by nissy-dev** [comment]
@Conaclos I couldn't have time yet, so I assign to you 👍
