### ISSUE TITLE
📎 New `rome lint` command

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4452]
### Description

Rome has a command called `rome check`, which does multiple things:
- check formatting
- checks linting
- check imports

And it will contain more in the future. To avoid possible friction in the future, I think Rome should ship a new command called `rome lint`, which only checks the code against lint rules. It will also have `-apply` and `--apply-unsafe` arguments.

**Comment by Conaclos** [comment]
> Rome has a command called rome check, which does multiple things:
>
 > - check formatting

I think that `rome check` does not check formatting, in contrast to `rome ci`.
Do you think that it should? What could be the difference with `rome ci`?

Otherwise, I like the idea.

**Comment by ematipico** [comment]
> > Rome has a command called rome check, which does multiple things:
> >
>  > - check formatting
> 
> I think that `rome check` does not check formatting, in contrast to `rome ci`.

I am about to change that logic (I think it is a bug), but yes it does format. It also checks the imports.

> Do you think that it should? What could be the difference with `rome ci`?
> 

The CI commands wouldn't allow to change any code, it would show the diagnostics on GitHub (check discussions proposal), etc.

> Otherwise, I like the idea.

Nice! If you want, I can guide you :)
