### ISSUE TITLE
🐛 noUndeclaredVariables reports TypeScript utility types

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#4458]
### Environment information

```block
CLI:
  Version:                      12.0.0-nightly.b77547d
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "foot"
  JS_RUNTIME_VERSION:           "v19.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/8.19.2"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

`noUndeclaredVariables` reports TypeScript utility types such as `Partial`, `ReadonlySet`, `ReadonlyMap`, and others as undeclared:
 
```
  ⚠ The Partial variable is undeclared
  
    68 │     useStructFlatUnion = false,
    69 │     useUndefined = false,
  > 70 │ }: Partial<Config>): Config {
       │    ^^^^^^^
    71 │ }
    72 │
```

The bug occurs only when **all** rules are enabled: see [on the playground](https://docs.rome.tools/playground/?lintRules=all&code=ZQB4AHAAbwByAHQAIAB0AHkAcABlACAAQQAgAD0AIABSAGUAYQBkAG8AbgBsAHkA)

A git bisect reveals that the issue comes from commit https://github.com/rome/tools/commit/0133f40fb185cf7610280985b531c12654a5bd96 (PR https://github.com/rome/tools/pull/4368).

### Expected result

No report of TS utility types.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Could you please share a reproduction code?

**Comment by Conaclos** [comment]
```ts
export type A = Partil
export type B = Record
export type C = Required
export type D = ReadonlySet
export type E = ReadonlyMap
```

Other utility types are listed [here](https://www.typescriptlang.org/docs/handbook/utility-types.html).

**Comment by denbezrukov** [comment]
I think that the problem is that we pass  `SourceType::default()` here:

https://github.com/rome/tools/blob/b77547d5b2fac4f06bc4a9b5e10eaab79dac77c1/crates/rome_service/src/file_handlers/javascript.rs#L226-L231
https://github.com/rome/tools/blob/b77547d5b2fac4f06bc4a9b5e10eaab79dac77c1/crates/rome_service/src/file_handlers/javascript.rs#L361-L366
https://github.com/rome/tools/blob/b77547d5b2fac4f06bc4a9b5e10eaab79dac77c1/crates/rome_service/src/file_handlers/javascript.rs#L418-L423
