### ISSUE TITLE
🐛 12.1.0: Single quote style applied to JSX elements

### ISSUE THREAD

**Issue by gkiely** [rome/tools#4469]
### Environment information

```block
Error when running rome rage
```

### What happened?

// rome.json
```json
{
  "javascript": {
    "formatter": {
      "quoteStyle": "single"
    }
  }
}
```
  
  ```tsx
// App.tsx
<div className='myClass'></div>
```

### Expected result

```tsx
// App.tsx
<div className="myClass"></div>
```

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by nissy-dev** [comment]
This is intentional behavior. Rome doesn't treat JSX attributes specially.
ref: #4054 and threads based on https://github.com/rome/tools/discussions/2465#discussioncomment-2592455

**Comment by gkiely** [comment]
@nissy-dev I hope the team reconsiders, it is a popular choice for developers.

**Comment by ematipico** [comment]
> @nissy-dev I hope the team reconsiders, it is a popular choice for developers.

Please refer to the discussion: prettier regrets having some of those options, they create too much bikeshedding and they are difficult to justify.

**Comment by nstepien** [comment]
Is parity with Prettier not a goal anymore?
I'm worried deviating from Prettier would make it harder to adopt Rome's formatting in large codebases.

Maybe a `jsxQuoteStyle` option may be worth it, doesn't seem like a significant maintenance burden, but I could be wrong.

**Comment by ematipico** [comment]
> Is parity with Prettier not a goal anymore? I'm worried deviating from Prettier would make it harder to adopt Rome's formatting in large codebases.
> 
> Maybe a `jsxQuoteStyle` option may be worth it, doesn't seem like a significant maintenance burden, but I could be wrong.

The parity makes sense, but it doesn't make sense to repeat the mistakes that the tool has done; it would be a bit unfortunate to carry over those here.  

We are always open to suggestions! Does it make sense to treat JSX quotes differently from the rest of other quotes? Why? Would that cause more friction in terms of maintainability, bugs, etc.? Would that create bike-shedding or not? If someone feels strongly, they always open a discussion! :)

**Comment by nstepien** [comment]
>it doesn't make sense to repeat the mistakes that a tool did

What may have been a mistake in the past has now become standard. 🤷‍♂️
The [React docs](https://react.dev/learn#displaying-data) themselves use double quotes for jsx props, and single quotes otherwise.
I think the idea may have been that HTML is usually formatted with double quotes, so the habit stuck with JSX.
That's my 2 cents.

**Comment by ematipico** [comment]
Makes sense, we should open an issue

**Comment by nstepien** [comment]
@ematipico I've opened #4486
