### ISSUE TITLE
🐛 noconstructorreturn doesn't make sense in ES6

### ISSUE THREAD

**Issue by GeorgeTailor** [rome/tools#4471]
### Environment information

```block
since `Rome 11.0.0`
```

### What happened?

The default rome lint rule https://docs.rome.tools/lint/rules/noconstructorreturn/
does not make sense in ES6, which is marking creation of OOP-style singletons as incorrect. Blindly copy-pasting rules from eslint, imo, is not a good idea.

Consider the following code:
```
export class NotePositionService {
	static instance: NotePositionService;
	constructor() {
		if (NotePositionService.instance) {
			return NotePositionService.instance;
		}
		NotePositionService.instance = this;
		// some heavy initiazer logic, which should be run only once
	}
}
```

Sadly, https://github.com/rome/tools/issues/4005 turned into a noop.

### Expected result

https://docs.rome.tools/lint/rules/noconstructorreturn/
should not be the default.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@GeorgeTailor, if you suggest making this rule **not** recommended, I think it's best to create a github discussion and give some reasons (like in this issue). 

Instead, you should provide a reproduction code if there's a bug, like a false-positive.

**Comment by GeorgeTailor** [comment]
https://github.com/rome/tools/discussions/4472
created
