### ISSUE TITLE
🐛 Enabling one nursery rule causes all other nursery rules to be enabled

### ISSUE THREAD

**Issue by Vivalldi** [rome/tools#4479]
### Environment information

```block
CLI:
  Version:                      12.1.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/3.3.1"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:                      12.1.0
  Name:                         rome_lsp
  CPU Architecture:             aarch64
  OS:                           macos

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               8
  Client Name:                  Visual Studio Code
  Client Version:               1.78.2

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code
```

### What happened?

1. Enabled `lint/nursery/noAccumulatingSpread`
2. Ran `rome check .`
3. Noticed that `lint/nursery/useExhaustiveDependencies` & `useLiteralKeys` began to be checked as well.

**Diagnostics**
I tried setting `recommended` to false but the same issue was present

### Expected result

Only enabled nursery rules should be checked

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@Vivalldi could please share your configuration?

**Comment by Conaclos** [comment]
As atemporary workaround, you can add `"recommended": false` under `linter.nursery`:

```diff
{
  "$schema": "https://docs.rome.tools/schemas/12.1.0/schema.json",
  "organizeImports": {
    "enabled": false
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "nursery": {
+      "recommended": false,
        "noAccumulatingSpread": "error"
      }
    }
  }
}
```

**Comment by nstepien** [comment]
@Conaclos this does not help, see #4488

**Comment by ematipico** [comment]
I have an idea of the issue! It should be easy to fix

**Comment by ematipico** [comment]
With the code you provided, what's the expected behaviour? Zero diagnostics?

**Comment by Vivalldi** [comment]
Correct, zero diagnostics. Below are two truth tables based on how I expect recommendations to behave. The only case that differs between them is the 4th case.



### Normal groups

All groups respect `linter.rules.recommended` unless there is an explicit group level setting.

| `linter.rules.recommended`  | `linter.rules.[group].recommended` | group recommended rules enabled |
| ---------------------------- | ------------------------------------ | ----------------------------------- |
| `false`                                     | unset                                                     | No                                                       |
| `false`                                     | `false`                                                   | No                                                       |
| `false`                                     | `true`                                                    | Yes                                                       |
| `true`                                      | unset                                                     | Yes                                                       |
| `true`                                      | `false`                                                   | No                                                       |
| `true`                                      | `true`.                                                   | Yes                                                       |

---
### Nursery group

The nursery group **never** respects `linter.rules.recommended`. It should only ever use it's group level setting.

| `linter.rules.recommended`  | `linter.rules.nursery.recommended` | group recommended rules enabled |
| ---------------------------- | ------------------------------------ | ----------------------------------- |
| `false`                                     | unset                                                     | No                                                       |
| `false`                                     | `false`                                                   | No                                                       |
| `false`                                     | `true`                                                    | Yes                                                       |
| `true`                                      | unset                                                     | No                                                       |
| `true`                                      | `false`                                                   | No                                                       |
| `true`                                      | `true`.                                                   | Yes                                                       |

**Comment by ematipico** [comment]
Perfect, I believe I know what's the source of the issue
