### ISSUE TITLE
📎 Implement `noUselessTypeConstraint`, @typescript-eslint/no-unnecessary-type-constraint

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#4480]
### Description

Implement the recommended ESLint rule [no-unnecessary-type-constraint](https://typescript-eslint.io/rules/no-unnecessary-type-constraint/).

I suggest to name the rule `noUselessTypeConstraint`.

In addition to rejecting type constraint `any`, we should also reject type constraint `unknown`.

**Comment by ematipico** [comment]
> we should also reject type constraint unknown.

Could you please provide a reason too?

**Comment by Conaclos** [comment]
> Could you please provide a reason too?

Every type extends `unknown`. TypeScript is transitioning of `any` to `unknown` for safety reason.
