### ISSUE TITLE
🐛 `noInnerDeclarations` incorrectly reports on functions in esm/strict mode

### ISSUE THREAD

**Issue by nstepien** [rome/tools#4492]
### Environment information

```block
https://docs.rome.tools/playground/?quoteStyle=single&code=aQBmACAAKABNAGEAdABoAC4AcgBhAG4AZABvAG0AKAApACAAIQA9AD0AIAAtADEAKQAgAHsACgAgACAAYwBvAG4AcwB0ACAAdgBhAGwAIAA9ACAAMQA7AAoACgAgACAAZgB1AG4AYwB0AGkAbwBuACAAbQB5AEYAbgAoACkAIAB7AAoAIAAgACAAIABjAG8AbgBzAG8AbABlAC4AbABvAGcAKAAnAGMAYQBsAGwAZQBkACAAbQB5AEYAbgAnACwAIAB2AGEAbAApADsACgAgACAAfQAKAH0ACgAKAG0AeQBGAG4AKAApADsACgAKAGUAeABwAG8AcgB0ACAAewB9ADsACgA%3D
```

### What happened?

In the playground example:
1. `myFn` accesses `val` in the block scope, so moving it outside the block would break `myFn`.
2. `myFn` is scoped to the block in esm/strict mode, so there's nothing wrong with keeping it in the block.
  Calling `myFn()` from outside the block would throw an error. Typescript correctly reports it (`Cannot find name 'myFn'.`)

### Expected result

From the ESLint docs for [no-inner-declarations](https://eslint.org/docs/latest/rules/no-inner-declarations):

>The function declaration portion rule will be rendered obsolete when [block-scoped functions](https://bugzilla.mozilla.org/show_bug.cgi?id=585536) land in ES6, but until then, it should be left on to enforce valid constructions.

The rule should only catch functions in blocks when the file is not an ESM or when the block is not in strict mode.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@Conaclos Now that the analyzer can read the `FileSource` (the source type), we should be able to enhance the rule
