### ISSUE TITLE
🐛 missing syntax highlighting on the playground

### ISSUE THREAD

**Issue by Conaclos** [rome/tools#4493]
### Environment information

```block
Playground
```

### What happened?

The syntax highlighting in the [playground](https://docs.rome.tools/playground/?quoteStyle=single&code=ZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABYACAAPQAgADUA) seems no longer working...

### Expected result

Syntax highlighting should work.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by connorjburton** [comment]
![image](https://github.com/rome/tools/assets/10538031/2d665f6e-f7ec-4941-b002-6f8d18ebf0b3)

I tested this locally on the latest commit (`7f72d1575f38073b7625f4cd69157a79f70f7211`) and it seems to work. I did have to fix the local version playground though, upgrading dependencies to fix Windows file system URLs and `wasm-pack` was not listed as a dev dependency.
