### ISSUE TITLE
📎 Add a `noTsComment` linter rule

### ISSUE THREAD

**Issue by MrSimmmons** [rome/tools#4518]
### Description

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-ts-comment.md

**Comment by ematipico** [comment]
Could you please open a GitHub discussion?

**Comment by MrSimmmons** [comment]
Created. https://github.com/rome/tools/discussions/4521

Will close task for now, can be re-opened as a task if the general consensus from the discussion is in favour of creating the rule
