### ISSUE TITLE
📎 Support codeActionsOnSave linting

### ISSUE THREAD

**Issue by gkiely** [rome/tools#4530]
### Description

Allow fixing lint errors on save in VSCode. 
This would save developers from manually typing a command in the CLI or fixing individual issues in VSCode.

Eslint example:
```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
  },
}
```

Prior discusion:
https://github.com/rome/tools/discussions/3856

**Comment by gkiely** [comment]
Supported via: 
`"editor.codeActionsOnSave": { "quickfix.rome": true }`

**Comment by ematipico** [comment]
Documentation https://docs.rome.tools/vscode/#fix-on-save
