### ISSUE TITLE
🐛 `rome.json` json schema not found

### ISSUE THREAD

**Issue by AkaraChen** [rome/tools#4536]
### Environment information

```block
CLI:
  Version:                      12.1.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.14.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.5.1"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              true
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. Init package
2. pnpm rome init
3. Look at `rome.json`

JSON schema not found in 'https://docs.rome.tools/schemas/12.1.2/schema.json', and Visual Studio Code JSON schema LSP show error.

### Expected result

JSON Schema should be found.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
As a temporary workaround you can use https://docs.rome.tools/schemas/12.1.0/schema.json, there's no change in the configuration :)
