### ISSUE TITLE
noUnusedVariables not parsing parameter decorators, injection tokens properly

### ISSUE THREAD

**Issue by jpike88** [rome/tools#4540]
### Environment information

```block
CLI:
  Version:                      12.1.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.14.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.6.3"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Rome servers...
```

### What happened?

<img width="877" alt="Screenshot 2023-05-29 at 7 19 43 pm" src="https://github.com/rome/tools/assets/9585787/1c057a8d-de78-41aa-a514-cfd129e83c79">

### Expected result

There shouldn't be any errors

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Not a bug, but an expected behaviour.

Stage 3 decorators **doesn't support decorators parameters** yet.

**Comment by jpike88** [comment]
According to this, 20% of frontend developers use angular. It's a bug to all of us as it manifests as incomplete or incorrect functionality. So while I appreciate that TC39 says what it may, I would ask you to at least keep this open and reconsider your position from time to time. While this status quo exists, I am unable to use a rule that would be otherwise extremely useful.
https://survey.stackoverflow.co/2022/#section-most-popular-technologies-web-frameworks-and-technologies

**Comment by ematipico** [comment]
FYI, there's a proposal for that: https://github.com/tc39/proposal-class-method-parameter-decorators

So eventually and hopefully, also the new decorators will support that.

**Comment by ematipico** [comment]
> According to this, 20% of frontend developers use angular. It's a bug to all of us as it manifests as incomplete or incorrect functionality. So while I appreciate that TC39 says what it may, I would ask you to at least keep this open and reconsider your position from time to time. While this status quo exists, I am unable to use a rule that would be otherwise extremely useful. [survey.stackoverflow.co/2022/#section-most-popular-technologies-web-frameworks-and-technologies](https://survey.stackoverflow.co/2022/#section-most-popular-technologies-web-frameworks-and-technologies)

As a workaround, in the meantime, you could use the [`globals`](https://docs.rome.tools/configuration/#javascriptglobals) option.

**Comment by jpike88** [comment]
I've tried a few different approaches with globals, none seemed to be. What would the correct entry be?

**Comment by ematipico** [comment]
> I've tried a few different approaches with globals, none seemed to be. What would the correct entry be?

I see, probably noUnusedVariables doesn't take globals into consideration, which is a bug

**Comment by rcoedo** [comment]
> According to this, 20% of frontend developers use angular. It's a bug to all of us as it manifests as incomplete or incorrect functionality. So while I appreciate that TC39 says what it may, I would ask you to at least keep this open and reconsider your position from time to time. While this status quo exists, I am unable to use a rule that would be otherwise extremely useful. https://survey.stackoverflow.co/2022/#section-most-popular-technologies-web-frameworks-and-technologies

Same problem with NestJS.

Rome claims to support TypeScript and, as of today, TypeScript supports method parameter decorators via the `experimentalDecorators` configuration option. Many libraries rely on TypeScript's parameter decorator, and, as a user, I would expect Rome to support them.

`noUnusedVariables` is a must for my team, and we have it turned off for now. If there is no plan to support Angular/NestJS, we will have to migrate back to ESLint.

**Comment by ematipico** [comment]
FYI old decorators **are not part of TypeScript**, but they were part of an old language proposal some years ago. TypeScript, at that time, decided to support it via configuration. That led them to support two versions of the same proposal.

Rome **does support** TypeScript **syntax** extensively. I hope this is a clear distinction.


I **am open** to support parameter decorators, but before charge head down to  the developments, we must first consider what does that mean for us.

**Comment by jpike88** [comment]
That is interesting, didn't know the nuances there. Though I would add that I use TS for many things, thankfully this is the only oddity in the way of things... would be good for us to find a solution that suits the Rome project.

**Comment by rcoedo** [comment]
After re-reading my previous comment I see that it could be interpreted as harsh. I want to point out that It wasn't my intention at all. I'm not threatening with my team migrating, just explaining my situation because other people can be left out the same way.  

I understand your concerns. This is not an official feature yet, so why rush to implement it. However, parameter decorators are a thing in typescript since 2015 and have been widely used for a while. They are being considered by [the official proposal as well](https://github.com/tc39/proposal-decorators/tree/master#could-we-support-decorating-objects-parameters-blocks-functions-etc).

Doing a quick search, I found that:
* AngularJS is the second most used frontend framework
* NestJS is third in popularity rankings for the backend

These are probably unreliable stats but it gives a rough idea about the scope of the frameworks. Both frameworks are built around experimental decorators so it's already a large user base that Rome could potentially miss.

Regarding solutions, would it be possible to support experimental decorators through a configuration option the same way that TypeScript does? How hard would it be to isolate the implementation so it can be turned on/off?

**Comment by ematipico** [comment]
@denbezrukov, what do you think? Should we support the old parameter decorators via options? Considering that we now support decorators, it doesn't affect Rome long term.

We could enable the parsing via option, like this:

```json
{
	"javascript": {
		"parser": {
			"unsafeParameterDecoratorsEnabled": true
		}
	}
}
```

Do you think we have to create new nodes, or can we reuse what we already have?

It's very lengthy, but we should not spare ourselves in wording and explaining that these decorators are not part of the official language specification. Any other suggestion is welcome.

**Comment by denbezrukov** [comment]
Rome can support method decorators. 
I think that we can reuse nodes what we have.

But I'm not sure what the best place to keep a such option.
For example we have `format` function in `rome_js_formatter` which has the option argument.
https://github.com/rome/tools/blob/659412af59a4c47f3cf15605bc7a5a0205c5ca39/crates/rome_js_formatter/src/lib.rs#L519-L524
And we keep these options in the context:
https://github.com/rome/tools/blob/659412af59a4c47f3cf15605bc7a5a0205c5ca39/crates/rome_js_formatter/src/context.rs#L22-L24

We can try to implement the same logic for our js parse.
https://github.com/rome/tools/blob/659412af59a4c47f3cf15605bc7a5a0205c5ca39/crates/rome_js_parser/src/parse.rs#L232-L235

1. Make `source_type` as a field in the option argument.
2. Keep `JsParserOptions` in `JsParser`
https://github.com/rome/tools/blob/659412af59a4c47f3cf15605bc7a5a0205c5ca39/crates/rome_js_parser/src/parser.rs#L33-L38


What do you think?

**Comment by ematipico** [comment]
It's excellent! We use the same patterns thought-out the code base. I will create an issue to track the things to do, so we can split the work among us.
