### ISSUE TITLE
🐛 Incorrect "lint/suspicious/noRedeclare" error

### ISSUE THREAD

**Issue by public** [rome/tools#4545]
### Environment information

```block
Rome Playground
```

### What happened?

[Given this TypeScript code](https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&code=IAAgAGwAZQB0ACAAYQA6ACAAewAgAFsAawBlAHkAOgAgAHMAdAByAGkAbgBnAF0AOgAgAHMAdAByAGkAbgBnACAAfQA7AAoAIAAgAGwAZQB0ACAAYgA6ACAAewAgAFsAawBlAHkAOgAgAHMAdAByAGkAbgBnAF0AOgAgAHMAdAByAGkAbgBnACAAfQA7AA%3D%3D)

```ts
let a: { [key: string]: string };
let b: { [key: string]: string };
```

You get this error

`Shouldn't redeclare 'key'. Consider to delete it or rename it.`

Which suggests it thinks `key` is being redeclared as a variable. But it isn't.

### Expected result

There should be no error reported for this code.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by unvalley** [comment]
I think this closed by #4519
