### ISSUE TITLE
📎 Allow Rome to exit with an error code on lint warnings

### ISSUE THREAD

**Issue by nstepien** [rome/tools#4552]
### Description

For Rome, all the lint rules we've enabled are set to "warn" instead of "error",
the idea is to help devs differentiate between TS type errors (red) and Rome/ESLint lints (yellow) in their code editor.
I've seen junior devs confuse type and lint issues, so I think it's helpful.

Now the issue is that Rome does not exit with an error code, so CI always passes when warnings are found.
We don't want CI to pass on any warnings.

With ESLint we use the `--max-warnings 0` flag, but there is no equivalent feature in Rome.
https://eslint.org/docs/latest/use/command-line-interface#--max-warnings

(The original [discussion](https://github.com/rome/tools/discussions/4328) didn't see much... discussion so I opened this task instead.)

**Comment by ematipico** [comment]
Thank you for creating the issue. I knew I was missing a feature from the list of the next things to build

**Comment by nstepien** [comment]
Thanks!

A setting in the configuration file would be good enough for me.
It's not something we'd ever change or manually use so a CLI flag is less necessary IMO.
Both are fine though.
