### ISSUE TITLE
📎 Typo in diagnostic message

### ISSUE THREAD

**Issue by stef7** [rome/tools#4579]
### Description

There seems to be a typo on [this line](https://github.com/rome/tools/blob/e3d8c8b5a89ea532d95870221c52250f356f7d2e/crates/rome_cli/src/diagnostics.rs#LL202C9-L202C9).

```
  × Fixes applied to the file, but there a still diagnostics to address.
```

It seems to be wanting to say "there **_are_** still diagnostics to address".

**Comment by ematipico** [comment]
Do you want to open a PR @stef7 ? :)

**Comment by stef7** [comment]
Done, not sure if I did it right so please let me know if I missed anything

**Comment by ematipico** [comment]
Thank you @stef7 ! Everything was perfect!
