### ISSUE TITLE
🐛 JSX quote styles are inconsistent between CLI and VS Code extension

### ISSUE THREAD

**Issue by dmt0** [rome/tools#4604]
### Environment information

```block
CLI:
  Version:                      12.1.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              true
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Rome servers...

Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:                      12.1.3-nightly.3de5a1a
```
```


### What happened?

My config file:
```json
{
  "$schema": "https://docs.rome.tools/schemas/12.1.3/schema.json",
  "formatter": {
    "enabled": true,
    "ignore": ["assets/*"],
    "indentStyle": "space",
    "lineWidth": 100
  },
  "organizeImports": {
    "enabled": false
  },
  "linter": {
    "enabled": false
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single"
    }
  }
}
```
When `quoteStyle` is set to `single` and `jsxQuoteStyle` is not specified, running Rome from CLI and from VS Code extenstion (format on save) gives different results.
- From CLI `yarn rome format --write ./src` all quotes - both within JSX and JS code are "single".
- From Format on Save in VS Code, quote style within JSX sets to "double", while in JS still "single".

VS Code version: `Version: 1.80.0-insider (Universal)`
Rome extension: `v0.25.20230614`

Rome configured as default editor in both User settings and in Workspace settings.
Prettier was completely uninstalled (from node_modules and extension in VS Code).

### Easy workaround
~~Set the `"jsxQuoteStyle": "single"`~~ - this option is not available anymore?

### Expected result

Consistent behaviour

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
This option is not available in the version you're using.

The feature is available in the source code but not yet released. We deployed the documentation by mistake.

If you want to use the option, you can use the latest nightly release

**Comment by dmt0** [comment]
Which of the two mentioned options is not available? `quoteStyle` or `jsxQuoteStyle`?

**Comment by ematipico** [comment]
Could you create a repo, so we can investigate?

**Comment by dmt0** [comment]
[Repro](https://docs.rome.tools/playground/?indentStyle=space&quoteStyle=single&jsxQuoteStyle=single&semicolons=as-needed&code=aQBtAHAAbwByAHQAIABEAHIAbwBwAGQAbwB3AG4AIABmAHIAbwBtACAAJwAuAC8ARAByAG8AcABkAG8AdwBuACcAOwAKAAoAYwBvAG4AcwB0ACAAcwB0AHIAaQBuAGcAIAA9ACAAIgBJACcAbQAgAGEAIABzAHQAcgBpAG4AZwAgAG8AdQB0AHMAaQBkAGUAIABKAFMAWAAiAAoACgBjAG8AbgBzAHQAIABBAHIAcgBvAHcAUwBlAGwAZQBjAHQAbwByACAAPQAgACgAcAByAG8AcABzACkAIAA9AD4AIAA8AEQAcgBvAHAAZABvAHcAbgAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgBzAHQAcgBpAG4AZwBJAG4ASgBTAFgAIgAgAC8APgA7AAoACgA%3D&typescript=false)

Or just paste this into your VS Code:

```javascript
import Dropdown from './Dropdown';

const string = "I'm a string outside JSX"

const ArrowSelector = (props) => <Dropdown className="stringInJSX" />;
```

And try formatting it with CLI and then with VS Code extension and see the difference.

**Comment by ematipico** [comment]
I am not able to reproduce the issue. I belive your problem comes from the fact that you're using a version of the extension that is **incompatible** with the CLI. 

Check your `rome rage` command output:

```
Incompatible Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Rome.

Server:
  Version:                      12.1.3-nightly.3de5a1a
```

If you're using the nightly version of the VSCocde extension, you should also use the CLI nightly version. Diverging will cause inconsistencies.

**Comment by dmt0** [comment]
Thanks @ematipico, that resolved it. My source of confusion was the fact that VS Code Insiders uses prerelease versions of extensions by default and the UI to disabled that wasn't super prominent:
<img width="737" alt="image" src="https://github.com/rome/tools/assets/2717746/a7530125-ae93-489a-af99-33965c97af8c">

Switched to Release version and everything is now consistent.
