### ISSUE TITLE
🐛 Some TypeScript utility types detected as undeclared with noUndeclaredVariables enabled

### ISSUE THREAD

**Issue by public** [rome/tools#4643]
### Environment information

```block
Playground and nightly.
```

### What happened?

[Playground Example](https://docs.rome.tools/playground/?lintRules=all&code=YQBzAHkAbgBjACAAZgB1AG4AYwB0AGkAbwBuACAAZgAoACkAIAB7AH0ACgAKAHQAeQBwAGUAIABUACAAPQAgAEEAdwBhAGkAdABlAGQAPAB0AHkAcABlAG8AZgAgAGYAPgA7AA%3D%3D)

Rome doesn't seem to know about all of the utility types that exist in TS.

For example:

```ts
async function f() {}

type T = Awaited<typeof f>;
```

The `noUndeclaredVariables` rule will claim `Awaited` is not defined. This is not true. It is built in. There are probably more of these.

### Expected result

All TypeScript utility types are treated as declared.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by public** [comment]
Previously https://github.com/rome/tools/issues/4458

Do they just need adding in here: https://github.com/rome/tools/blob/bbe819ef9a30e19d757285bb6cfcf50141d59a05/crates/rome_js_analyze/src/globals/typescript.rs#L83?

**Comment by ematipico** [comment]
> Previously https://github.com/rome/tools/issues/4458
> 
> Do they just need adding in here? https://github.com/rome/tools/blob/bbe819ef9a30e19d757285bb6cfcf50141d59a05/crates/rome_js_analyze/src/globals/typescript.rs
> 
> 
> 
> 

Yeah probably they are outdated and need to be updated.
