### ISSUE TITLE
📎 Implement the new resource managment proposal

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4646]
### Description

Context https://github.com/tc39/proposal-explicit-resource-management

Tests for formatter: https://github.com/prettier/prettier/pull/14862/files

Syntax: 

```js
using resource = await instance.lock();
//^^^ new grammar
```

`using` is just a new variable kind, so it will be very straight forward to implement it.

**Comment by nissy-dev** [comment]
I'll take this issue!

**Comment by nissy-dev** [comment]
As I started working on this task, I found that `using` declaration is easy, but `wait using` declaration"is difficult to implement.

I've tried defining it like this for babel (see: https://github.com/babel/babel/pull/15520), but it doesn't seem to work

```
JsForVariableDeclaration =
	kind_token: ('var' | 'let' | 'const' | 'using' | 'await using')
	declarator: JsVariableDeclarator
```
I'm having trouble figuring out how to handle `await using`.

**Comment by ematipico** [comment]
You can develop feature progressively if you prefer.

Here you can check the semantic changes to the language: https://arai-a.github.io/ecma262-compare/?pr=3000 (on the right there's a small widget with arrows, you click them and jump to the next difference).

We start by:
- investigating how babel and TS are doing it, if they are adding new nodes to support the new syntax
- investigating the TC39 changes to the language and what they added/changes
- discuss here the changes, no need to jump coding straightaway

**Comment by arendjr** [comment]
Any progress on this issue? If I have some time left, I might be able to offer some help.

**Comment by ematipico** [comment]
Hi @arendjr , thank you! Feel free to help. There hasn't been any update, so feel free to take it

**Comment by ematipico** [comment]
@arendjr heads up, @nissy-dev opened a PR. If you're still interested, we can all work at helping him to ship the feature and fix regressions as we go

**Comment by arendjr** [comment]
Great! I had made a small start already, but that’s no problem. It should put me in a good position to give a review at least.
