### ISSUE TITLE
🐛 option to disable noVar for typescript types

### ISSUE THREAD

**Issue by gkiely** [rome/tools#4691]
### Environment information

```block
CLI:
  Version:                      12.0.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.2.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.6.6"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true

Workspace:
  Open Documents:               0
```

### What happened?

When declaring a global type with typescript it's required to use var to extend the global object.

See: https://stackoverflow.com/a/69429093/1845423

An error is reported: Use let or const instead of var.

### Expected result

No error is reported as it is a type check and required to extend the global object.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Hey @gkiely , pardon my question: what are you asking?

The title asks for an option to the rule, while the description says that it's a bug and it's a false positive.

Also, could you share a playground link, so we can reproduce the issue?

**Comment by gkiely** [comment]
Found an alternative way to do it, closing.

This was along the lines of the code I was using.
```
declare global {
  var myVariable: number;
}
```
