### ISSUE TITLE
🐛 No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Mauladen** [rome/tools#4774]
### Environment information

```block
CLI:
  Version:                      12.1.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.17.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Rome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

1. `yarn install rome`
2. `yarn rome ci check .`

After these commands I get the error No such file or directory (os error 2)

![gSx23lw](https://github.com/rome/tools/assets/12824589/95dc2924-020a-49c7-bf39-ea326afd6027)

### Expected result

I want this command to work as stated in the documentation, give errors

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Mauladen** [comment]
I tested on macOS and got the same error, I just don't understand how to make rome work, maybe you need to install some libraries past it?

**Comment by Conaclos** [comment]
Did you try the command on another file?

**Comment by Mauladen** [comment]
> Did you try the command on another file?

Yes, I tried in another project and in different files specifically, I ran this command in Windows, in Manjaro Linux on my computer and on Mac Mini M2 where macOS is installed and everywhere I get this error

**Comment by ematipico** [comment]
Could you please share a minimal reproduction repository? This will help us to triage the issue

**Comment by Mauladen** [comment]
> Could you please share a minimal reproduction repository? This will help us to triage the issue 

If I install Rome using yarn or pnpm in an empty project, I will create main.js in which I write console.log, I will get the same error, while formatting works fine and no errors occur, but Rome writes that some errors occurred during the check

**Comment by Mauladen** [comment]
![image1](https://github.com/rome/tools/assets/12824589/f9a0bf56-4f55-42ac-82ac-c1093c3e9573)
![image2](https://github.com/rome/tools/assets/12824589/c55338f3-dc18-47e4-86d6-c974db7e27a8)

**Comment by Mauladen** [comment]
I also want to clarify that the operating system does not matter, this error occurs on Windows, Linux, macOS, you can reproduce it as I wrote above in one file with one line

**Comment by ematipico** [comment]
Thank you @Mauladen for additional information.

Is it possible for you to create a minimal **repository**, so we can replicate the issue? If we can't replicate the issue, we can't help.

This seems to be something related to your system, unfortunately our logs don't provide much information, and that's on us.

**Comment by Mauladen** [comment]
> Thank you @Mauladen for additional information.
> 
> Is it possible for you to create a minimal **repository**, so we can replicate the issue? If we can't replicate the issue, we can't help.
> 
> This seems to be something related to your system, unfortunately our logs don't provide much information, and that's on us.

[Link to the test repository](https://github.com/Mauladen/rome-test)

![](https://github.com/rome/tools/assets/12824589/d1d6c8bb-c293-4cca-96eb-365b4281df9e)
![](https://github.com/rome/tools/assets/12824589/bd045996-25de-4cbd-ae28-4d54f3558a0d)
![](https://github.com/rome/tools/assets/12824589/f3138ff6-c835-4449-8236-79b8974844dd)
![](https://github.com/rome/tools/assets/12824589/4d873f25-b8ab-44eb-b4dc-de834d4627b7)
![](https://github.com/rome/tools/assets/12824589/a0a25252-e4a7-488c-8001-285fc2a881d4)

**Comment by Mauladen** [comment]
@ematipico 

I added information from 3 different computers that are physically independent from each other with different operating systems Windows, macOS, Linux

**Comment by strager** [comment]
The "No such file or directory (os error 2)" error occurs because `rome ci check .` is interpreting `check` as a file name. The correct command is `rome ci .` (or `rome check .`).

The error message could definitely be better...

**Comment by Mauladen** [comment]
@strager

 You really turned out to be right, I added a new file to the Header.tsx repository, the rome check command does not output any errors except formatting, but Rome Playground shows one error

![](https://github.com/rome/tools/assets/12824589/b3279bec-da87-48df-bd74-e15057217d3c)

**Comment by Mauladen** [comment]
At the moment, I have decided to close this appeal because I may have confused some people with my information, I will recreate it with the correct description of the problem

**Comment by Mauladen** [comment]
Closed

**Comment by Conaclos** [comment]
New issue  opened #4784
