### ISSUE TITLE
🐛 `format` and `lint` didn't follow the same rule

### ISSUE THREAD

**Issue by leedalei** [rome/tools#4775]
### Environment information

```block
"rome": "^12.0.0"
```

### What happened?

[demo](https://docs.rome.tools/playground/?semicolons=as-needed&code=ZgB1AG4AYwB0AGkAbwBuACAAaABlAGwAbABvACgAKQAgAHsACgAJADsAKABuAGEAdgBpAGcAYQB0AG8AcgAgAGEAcwAgAGEAbgB5ACkALgBzAGEAeQAoACkACgB9AA%3D%3D)

When setting "semicolons" to "asNeeded", `format` command will add ";" in front of the bracket, and then run `check` command. The following error occurred.
![image](https://github.com/rome/tools/assets/56435405/c32fd806-0ad5-4e34-8c07-20bef896ebf9)

Is the semicolon really necessary in this demo's context? 

### Expected result

Formatter and linter should follow a same rule. 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by Conaclos** [comment]
Hi!

The issue will be fixed in the next release. We removed the linter rule that emits thsi diagnostics.
