### ISSUE TITLE
🐛 Wrong documentation for useExhaustiveDependencies

### ISSUE THREAD

**Issue by jer-sen** [rome/tools#4791]
### Environment information

```block
https://docs.rome.tools/lint/rules/useexhaustivedependencies/
```

### What happened?

Options have nothing to do with hooks considered as stable, it's a list of custom hooks of which the dependencies will be checked.

Stable hooks are defined here https://github.com/rome/tools/blob/392d188a49d70e495f13b1bb08cd7d9c43690f9b/crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs#L180 and are not configurable:

```rust
        let stable_config: HashSet<StableReactHookConfiguration> = HashSet::from_iter([
            StableReactHookConfiguration::new("useState", Some(1)),
            StableReactHookConfiguration::new("useReducer", Some(1)),
            StableReactHookConfiguration::new("useTransition", Some(1)),
            StableReactHookConfiguration::new("useRef", None),
            StableReactHookConfiguration::new("useContext", None),
            StableReactHookConfiguration::new("useId", None),
            StableReactHookConfiguration::new("useSyncExternalStore", None),
        ]);
```

### Expected result

Something like:

> Allows to specify custom hooks - from libraries or internal projects - that will also be checked.

By the way, it would be nice to make stable hooks configurable!

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@jer-sen Rome is NOT maintained anymore

Check the README: https://github.com/rome/tools
