### ISSUE TITLE
☂️ Comprehensive lint documentation for release

### ISSUE THREAD

**Issue by sebmck** [rome/tools#731]
This issue is for tracking the required documentation for our release.

**Comment by MareikeTaeubner** [comment]
@sebmck until when do you need this documentation?

**Comment by sebmck** [comment]
@MareikeTaeubner Before release at the end of the month (specific date TBD). I can't really provide much guidance on what needs to be documented since a lot of it is either embedded in code or my head.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
