### ISSUE TITLE
📎 Add syntax highlighting to patches

### ISSUE THREAD

**Issue by sebmck** [rome/tools#750]

**Comment by VictorHom** [comment]
@sebmck I'm interested in looking more into diagnostic related stuff. (I don't know much on highlighting). If you can direct me a little, that'd be great

**Comment by sebmck** [comment]
@VictorHom Sweet! I’m not sure how this one would be implemented, it’s probably pretty gnarly. I’ll update this issue once I’ve thought of an approach with the relevant changes/files.

I have a list of issues I’m going to create tonight and there’s a handful that are diagnostics related. I’ll cc you on those issues when I create them to see if you’re interested.
