### ISSUE TITLE
📎 Add merge conflict marker detection to parsers

### ISSUE THREAD

**Issue by sebmck** [rome/tools#767]
This could maybe be generic to `parser-core`. We should detect git conflict markers and throw a meaningful error. We could also maybe automatically select the incoming changes to derive the final AST.

Right now other tools throw cryptic errors about the marker sequence. This seems like a common enough scenario to have a dedicated logic and error.

**Comment by ematipico** [comment]
I started works on this one.

@sebmck do you have any suggestions on how to implement this?

I did start by creating specific methods for tokenization and parsing inside `parser-core`.

Later I thought about creating a specific parser and using it inside different other parsers.

I am not sure about both approaches. What's your idea?

**Comment by sebmck** [comment]
@ematipico Best strategy I think is to sanitize the `input`.

We could do a prepass on the `input` passed into `ParserCore`. Probably only when a flag is explicitly set though, we would only want to do it with "source code", ie. markdown, JS, CSS etc, we wouldn't want the overhead for other smaller parsers like semver. Although a `includes("<<<<<<<")` should be pretty fast as a check if we need to do the work.

This would only be viable if `index` was removed from `Position` which I think we could do. It's really only needed in a single place (`buildCodeFrame`), but we can probably figure something else out. We would need to do this as otherwise the positions will be wrong from the source file if we just remove it completely. We can just pad it with newlines instead.
