### ISSUE TITLE
📎 Investigate repository size

### ISSUE THREAD

**Issue by ooflorent** [rome/tools#797]
Currently Rome's repository sits at 52MiB. It does not seem to be a lot but it grows faster than typical projects because `node_modules` and binaries are published. It would be possible to remove the obsolete blobs to reduce the size of the repository.

The main drawback of this is that it would no longer be possible to build old version of Rome since the large files would be gone.

- [Reduce repository size](https://docs.gitlab.com/ee/user/project/repository/reducing_the_repo_size_using_git.html) by GitLab
- [`git gc`](https://git-scm.com/docs/git-gc)

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
