### ISSUE TITLE
📎 Support `/* global */` comments for declaring globals

### ISSUE THREAD

**Issue by sebmck** [rome/tools#966]

**Comment by bitpshr** [comment]
Happy to pick this up. @sebmck can you provide any additional context around implementation on this one? From a high level, it feels like we'd parse comment blocks and add declarations to the global scope accordingly.

**Comment by sebmck** [comment]
I think the best strategy would be to have all comments in a file be declared as global at the root, rather than at a more specific scope-level. You can add it to the `RootScope` constructor in `internal/compiler/scope/Scope.ts` and add it to `this.globals`. A `RootScope` is constructed only once.

I think that's the behaviour of ESLint and other tools. I mostly say we should do that because it's the easiest to do from a performance perspective. Since our scope construction is lazy, and performed every time we traverse, including having to reconstruct when the AST is modified. Parsing every comment would be prohibitively expensive, although we could use a `Set` or `WeakSet` to memoize it.

**Comment by ematipico** [comment]
Closing as it's been implemented
