### ISSUE TITLE
📎 Add fixable tag to lint rule docs

### ISSUE THREAD

**Issue by sebmck** [rome/tools#967]
This should go in the index and in the generated `description`. It could be a frontmatter field.

Generation scripts:

 - https://github.com/romefrontend/rome/blob/main/scripts/generated-files/lint-rules-docs.ts
 - https://github.com/romefrontend/rome/blob/main/scripts/generated-files/lint-rules.ts

**Comment by robintom** [comment]
@sebmck Can i help you on this? And could you please clarify on basically what is to be done? As in i don't understand what you mean by `Add fixable tag `

**Comment by ematipico** [comment]
@robintom We have a set of rules that can be fixable automatically by running the command `rome check --apply`, although some rules cannot be fixed automatically.

Sebastian is suggesting to flag these rules that can be fixed automatically in our docs by adding a frontmatter field. The frontmatter fields are the properties at the top of the file.

If you need more guidance, feel free to ask!
