### ISSUE TITLE
☂️ Future performance optimizations

### ISSUE THREAD

**Issue by sebmck** [rome/tools#970]
This issue is for tracking some known areas that can be optimized:

 - During `check` dependency analysis, don't recurse deep into packages. We will only surface errors.
 - Expensive JS parsing. Lookaheads are expensive and should be minimized. We have parts of the parser that try multiple branches and requires cloning the parser state which is very expensive.

Add the `--profile` flag to any Rome command to produce a CPU profile.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
