### ISSUE TITLE
📎 Additional lint rules from IntelliJ

### ISSUE THREAD

**Issue by sebmck** [rome/tools#976]
I've recently switched to Webstorm and was impressed with a lot of the rules they offer with code inspection. I haven't seen some of these in ESLint.

- ~Unnecessary `continue` as the last statement in a loop~
- Simplify statement or boolean expression
- Expression statement that is not assignment or call
- Single character regex alternations can be a charset
- Unused shadowed bindings

**Comment by aravind1078** [comment]
@sebmck i wanna pick `Unnecessary continue` already started working on it, missing few cases currently will come up with a pr soon.

**Comment by aravind1078** [comment]
do we want to remove the continue statement in `unnecessary continue`  rule or we just tell them that the continue is unnecessary here!

**Comment by ludofischer** [comment]
I am currently trying to write `Expression statement that is not assignment or call`. Down from 12115 false positives to just 329... For the benefit of others attempting a similar task, it helps to know that the AST (Abstract Syntax Tree) format looks similar to [ESTree](https://github.com/estree/estree) and you can paste code into https://astexplorer.net/ to get an idea of how it’s parsed (I think leaving the parser set as acorn gives a good approximation of the Rome AST).

**Comment by ematipico** [comment]
@ludofischer Rome has also a command called `parse` that write to screen the AST:

```
./rome parse ./test.ts
```
