### ISSUE TITLE
📎 Enable `--changed` for `check` by default in `rome ci`

### ISSUE THREAD

**Issue by sebmck** [rome/tools#978]
Would lead to a small performance increase for `rome ci` and should be relatively safe. (`rome test` takes up a **significant** portion of a `rome ci` run)

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
