### ISSUE TITLE
📎 Unquote valid JS identifier property keys and computed members

### ISSUE THREAD

**Issue by sebmck** [rome/tools#982]
Right now if you have:

```
const foo = {
  "bar": true,
};
foo["bar"];
```

We will retain the quotes even though we can drop them. Not sure if this should be implemented in the linter as an autofix or formatter as a basic AST transform.

**Comment by katungi** [comment]
@sebmck I think it should be a lint rule. Would the two options still give the same results which is no quotes??

**Comment by sebmck** [comment]
@katungi Yeah it would. I don't think this makes sense as a lint rule, as it seems purely like formatting, and when we're generating any sort of code, we should still do this.

The changes would need to be made in only the file `internal/formatter/builders/js/objects/JSStaticPropertyKey.ts`. `node.value` can be a `StringLiteral` so you would need to check for that. You would also need to validate that the `name` is a valid JavaScript identifier, which can be done using `isValidIdentifierName` that you can import from `internal/js-ast-utils`.

**Comment by pradel** [comment]
As https://github.com/rome/tools/pull/1235 was merged this one can probably be closed.
