### ISSUE TITLE
☂️ HTML support

### ISSUE THREAD

**Issue by sebmck** [rome/tools#983]
## Parsing

I implemented a pretty awful HTML parser that isn't spec compliant in the slightest. We can expand upon it though and import some spec tests to ensure validity.

## Linting

We might want to make some of the JSX and Accessibility lint rules generic and allow accepting HTML.

**Comment by ematipico** [comment]
Something that I wish to see here is the orchestration of different parsers: when there's a `<style>`, use the CSS parsing, same thing with `<script>`.  

But maybe this is something that can be done way in the future!

**Comment by ematipico** [comment]
This resource could help: https://html.spec.whatwg.org/multipage/parsing.html

**Comment by cassiebeckley** [comment]
Is anybody working on this? I'd be interested if not.

**Comment by ematipico** [comment]
Not at the moment @cassiebeckley , you can pick it up if you wish! 

What's missing (as far as I know):
- `CDATA` parsing
- parsing of self closing tags

And surely there are more cases that I didn't think about.

If possible, it would be great to change the current parser and make it spec compliant. With did that with our current CSS parser and should do the same with our current HTML parser.
